package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Banco generated by hbm2java
 */
@Entity
@Table(name = "BANCO")
public class Banco implements java.io.Serializable {
	
	private static final long serialVersionUID = -1248780920759369878L;
	private int bcoCod;
	private String bcoApe;
	private String bcoNom;
	private String bcoWeb;
//	private Set<Cheque> cheques = new HashSet<Cheque>(0);
//	private Set<CustoFixo> custoFixos = new HashSet<CustoFixo>(0);
//	private Set<ColaboradorConta> colaboradorContas = new HashSet<ColaboradorConta>(0);
	private Set<Agencia> agencias = new HashSet<Agencia>(0);
//	private Set<Bancodocumento> bancodocumentos = new HashSet<Bancodocumento>(0);
//	private Set<Pagar> pagars = new HashSet<Pagar>(0);
//	private Set<Pedido> pedidos = new HashSet<Pedido>(0);
//	private Set<Conta> contas = new HashSet<Conta>(0);
//	private Set<Receber> recebers = new HashSet<Receber>(0);

	@Id
	@Column(name = "BCO_COD", unique = true, nullable = false)
	public int getBcoCod() {
		return this.bcoCod;
	}

	public void setBcoCod(int bcoCod) {
		this.bcoCod = bcoCod;
	}

	@Column(name = "BCO_APE", length = 15)
	public String getBcoApe() {
		return this.bcoApe;
	}

	public void setBcoApe(String bcoApe) {
		this.bcoApe = bcoApe;
	}

	@Column(name = "BCO_NOM", nullable = false, length = 30)
	public String getBcoNom() {
		return this.bcoNom;
	}

	public void setBcoNom(String bcoNom) {
		this.bcoNom = bcoNom;
	}

	@Column(name = "BCO_WEB", length = 50)
	public String getBcoWeb() {
		return this.bcoWeb;
	}

	public void setBcoWeb(String bcoWeb) {
		this.bcoWeb = bcoWeb;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
//	public Set<Cheque> getCheques() {
//		return this.cheques;
//	}
//
//	public void setCheques(Set<Cheque> cheques) {
//		this.cheques = cheques;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
//	public Set<CustoFixo> getCustoFixos() {
//		return this.custoFixos;
//	}
//
//	public void setCustoFixos(Set<CustoFixo> custoFixos) {
//		this.custoFixos = custoFixos;
//	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
//	public Set<ColaboradorConta> getColaboradorcontas() {
//		return this.colaboradorContas;
//	}
//
//	public void setColaboradorcontas(Set<ColaboradorConta> colaboradorContas) {
//		this.colaboradorContas = colaboradorContas;
//	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
	public Set<Agencia> getAgencias() {
		return this.agencias;
	}

	public void setAgencias(Set<Agencia> agencias) {
		this.agencias = agencias;
	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
//	public Set<Bancodocumento> getBancodocumentos() {
//		return this.bancodocumentos;
//	}
//
//	public void setBancodocumentos(Set<Bancodocumento> bancodocumentos) {
//		this.bancodocumentos = bancodocumentos;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
//	public Set<Pagar> getPagars() {
//		return this.pagars;
//	}
//
//	public void setPagars(Set<Pagar> pagars) {
//		this.pagars = pagars;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
//	public Set<Pedido> getPedidos() {
//		return this.pedidos;
//	}
//
//	public void setPedidos(Set<Pedido> pedidos) {
//		this.pedidos = pedidos;
//	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
//	public Set<Conta> getContas() {
//		return this.contas;
//	}
//
//	public void setContas(Set<Conta> contas) {
//		this.contas = contas;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "banco")
//	public Set<Receber> getRecebers() {
//		return this.recebers;
//	}
//
//	public void setRecebers(Set<Receber> recebers) {
//		this.recebers = recebers;
//	}

}
