package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClienteCartaoFidelidadeId generated by hbm2java
 */
@Embeddable
public class ClienteCartaoFidelidadeId implements java.io.Serializable {

	private static final long serialVersionUID = -6116760055868046237L;
	private int ccfEmp;
	private int ccfFil;
	private int ccfCol;
	private int ccfNcf;

	public ClienteCartaoFidelidadeId() {
	}

	public ClienteCartaoFidelidadeId(int ccfEmp, int ccfFil, int ccfCol,
			int ccfNcf) {
		this.ccfEmp = ccfEmp;
		this.ccfFil = ccfFil;
		this.ccfCol = ccfCol;
		this.ccfNcf = ccfNcf;
	}

	@Column(name = "CCF_EMP", nullable = false)
	public int getCcfEmp() {
		return this.ccfEmp;
	}

	public void setCcfEmp(int ccfEmp) {
		this.ccfEmp = ccfEmp;
	}

	@Column(name = "CCF_FIL", nullable = false)
	public int getCcfFil() {
		return this.ccfFil;
	}

	public void setCcfFil(int ccfFil) {
		this.ccfFil = ccfFil;
	}

	@Column(name = "CCF_COL", nullable = false)
	public int getCcfCol() {
		return this.ccfCol;
	}

	public void setCcfCol(int ccfCol) {
		this.ccfCol = ccfCol;
	}

	@Column(name = "CCF_NCF", nullable = false)
	public int getCcfNcf() {
		return this.ccfNcf;
	}

	public void setCcfNcf(int ccfNcf) {
		this.ccfNcf = ccfNcf;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClienteCartaoFidelidadeId))
			return false;
		ClienteCartaoFidelidadeId castOther = (ClienteCartaoFidelidadeId) other;

		return (this.getCcfEmp() == castOther.getCcfEmp())
				&& (this.getCcfFil() == castOther.getCcfFil())
				&& (this.getCcfCol() == castOther.getCcfCol())
				&& (this.getCcfNcf() == castOther.getCcfNcf());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCcfEmp();
		result = 37 * result + this.getCcfFil();
		result = 37 * result + this.getCcfCol();
		result = 37 * result + this.getCcfNcf();
		return result;
	}

}
