package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ColaboradorEmpresaOcorrencia generated by hbm2java
 */
@Entity
@Table(name = "COLABORADOREMPRESAOCORRENCIA")
public class ColaboradorEmpresaOcorrencia implements java.io.Serializable {

	private static final long serialVersionUID = 8138463300084467899L;
	private int ceoCod;
//	private CategoriaFinanceira categoriaFinanceiraByFkCeoCfa;
//	private CategoriaFinanceira categoriaFinanceiraByFkCeoCtf;
//	private ColaboradorEmpresa colaboradorEmpresa;
	private Usuario usuario;
	private int ceoOri;
	private Date ceoDte;
	private Date ceoDti;
	private String ceoOb1;
	private String ceoOb2;
	private String ceoOb3;
	private String ceoOb4;
	private String ceoOb5;
	private char ceoAbv;
	private Integer ceoFil;
	private Integer ceoInt;

	public ColaboradorEmpresaOcorrencia() {
	}

//	public ColaboradorEmpresaOcorrencia(int ceoCod,
//			CategoriaFinanceira categoriaFinanceiraByFkCeoCfa,
//			CategoriaFinanceira categoriaFinanceiraByFkCeoCtf,
//			ColaboradorEmpresa colaboradorEmpresa, Usuario usuario, int ceoOri,
//			Date ceoDte, char ceoAbv) {
//		this.ceoCod = ceoCod;
//		this.categoriaFinanceiraByFkCeoCfa = categoriaFinanceiraByFkCeoCfa;
//		this.categoriaFinanceiraByFkCeoCtf = categoriaFinanceiraByFkCeoCtf;
//		this.colaboradorEmpresa = colaboradorEmpresa;
//		this.usuario = usuario;
//		this.ceoOri = ceoOri;
//		this.ceoDte = ceoDte;
//		this.ceoAbv = ceoAbv;
//	}

	/*public ColaboradorEmpresaOcorrencia(int ceoCod,
			CategoriaFinanceira categoriaFinanceiraByFkCeoCfa,
			CategoriaFinanceira categoriaFinanceiraByFkCeoCtf,
			ColaboradorEmpresa colaboradorEmpresa, Usuario usuario, int ceoOri,
			Date ceoDte, Date ceoDti, String ceoOb1, String ceoOb2,
			String ceoOb3, String ceoOb4, String ceoOb5, char ceoAbv,
			Integer ceoFil, Integer ceoInt) {
		this.ceoCod = ceoCod;
		this.categoriaFinanceiraByFkCeoCfa = categoriaFinanceiraByFkCeoCfa;
		this.categoriaFinanceiraByFkCeoCtf = categoriaFinanceiraByFkCeoCtf;
		this.colaboradorEmpresa = colaboradorEmpresa;
		this.usuario = usuario;
		this.ceoOri = ceoOri;
		this.ceoDte = ceoDte;
		this.ceoDti = ceoDti;
		this.ceoOb1 = ceoOb1;
		this.ceoOb2 = ceoOb2;
		this.ceoOb3 = ceoOb3;
		this.ceoOb4 = ceoOb4;
		this.ceoOb5 = ceoOb5;
		this.ceoAbv = ceoAbv;
		this.ceoFil = ceoFil;
		this.ceoInt = ceoInt;
	}*/

	@Id
	@Column(name = "CEO_COD", unique = true, nullable = false)
	public int getCeoCod() {
		return this.ceoCod;
	}

	public void setCeoCod(int ceoCod) {
		this.ceoCod = ceoCod;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "CEO_EMP", referencedColumnName = "CTF_EMP", nullable = false),
//			@JoinColumn(name = "CEO_CFA", referencedColumnName = "CTF_COD") })
//	public CategoriaFinanceira getCategoriaFinanceiraByFkCeoCfa() {
//		return this.categoriaFinanceiraByFkCeoCfa;
//	}
//
//	public void setCategoriaFinanceiraByFkCeoCfa(
//			CategoriaFinanceira categoriaFinanceiraByFkCeoCfa) {
//		this.categoriaFinanceiraByFkCeoCfa = categoriaFinanceiraByFkCeoCfa;
//	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "CEO_EMP", referencedColumnName = "CTF_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "CEO_CTF", referencedColumnName = "CTF_COD", insertable = false, updatable = false) })
//	public CategoriaFinanceira getCategoriaFinanceiraByFkCeoCtf() {
//		return this.categoriaFinanceiraByFkCeoCtf;
//	}
//
//	public void setCategoriaFinanceiraByFkCeoCtf(
//			CategoriaFinanceira categoriaFinanceiraByFkCeoCtf) {
//		this.categoriaFinanceiraByFkCeoCtf = categoriaFinanceiraByFkCeoCtf;
//	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "CEO_EMP", referencedColumnName = "COE_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "CEO_COL", referencedColumnName = "COE_COL", nullable = false, insertable = false, updatable = false) })
//	public ColaboradorEmpresa getColaboradorEmpresa() {
//		return this.colaboradorEmpresa;
//	}
//
//	public void setColaboradorEmpresa(ColaboradorEmpresa colaboradorEmpresa) {
//		this.colaboradorEmpresa = colaboradorEmpresa;
//	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CEO_USU", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "CEO_ORI", nullable = false)
	public int getCeoOri() {
		return this.ceoOri;
	}

	public void setCeoOri(int ceoOri) {
		this.ceoOri = ceoOri;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CEO_DTE", nullable = false, length = 10)
	public Date getCeoDte() {
		return this.ceoDte;
	}

	public void setCeoDte(Date ceoDte) {
		this.ceoDte = ceoDte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CEO_DTI", length = 10)
	public Date getCeoDti() {
		return this.ceoDti;
	}

	public void setCeoDti(Date ceoDti) {
		this.ceoDti = ceoDti;
	}

	@Column(name = "CEO_OB1", length = 40)
	public String getCeoOb1() {
		return this.ceoOb1;
	}

	public void setCeoOb1(String ceoOb1) {
		this.ceoOb1 = ceoOb1;
	}

	@Column(name = "CEO_OB2", length = 40)
	public String getCeoOb2() {
		return this.ceoOb2;
	}

	public void setCeoOb2(String ceoOb2) {
		this.ceoOb2 = ceoOb2;
	}

	@Column(name = "CEO_OB3", length = 40)
	public String getCeoOb3() {
		return this.ceoOb3;
	}

	public void setCeoOb3(String ceoOb3) {
		this.ceoOb3 = ceoOb3;
	}

	@Column(name = "CEO_OB4", length = 40)
	public String getCeoOb4() {
		return this.ceoOb4;
	}

	public void setCeoOb4(String ceoOb4) {
		this.ceoOb4 = ceoOb4;
	}

	@Column(name = "CEO_OB5", length = 40)
	public String getCeoOb5() {
		return this.ceoOb5;
	}

	public void setCeoOb5(String ceoOb5) {
		this.ceoOb5 = ceoOb5;
	}

	@Column(name = "CEO_ABV", nullable = false, length = 1)
	public char getCeoAbv() {
		return this.ceoAbv;
	}

	public void setCeoAbv(char ceoAbv) {
		this.ceoAbv = ceoAbv;
	}

	@Column(name = "CEO_FIL")
	public Integer getCeoFil() {
		return this.ceoFil;
	}

	public void setCeoFil(Integer ceoFil) {
		this.ceoFil = ceoFil;
	}

	@Column(name = "CEO_INT")
	public Integer getCeoInt() {
		return this.ceoInt;
	}

	public void setCeoInt(Integer ceoInt) {
		this.ceoInt = ceoInt;
	}

}
