package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ColaboradorContatoId generated by hbm2java
 */
@Embeddable
public class ColaboradorContatoId implements java.io.Serializable {
	
	private static final long serialVersionUID = 2149858897814125064L;
	private int cctCol;
	private int cctCod;

	public ColaboradorContatoId() {
	}

	public ColaboradorContatoId(int cctCol, int cctCod) {
		this.cctCol = cctCol;
		this.cctCod = cctCod;
	}

	@Column(name = "CCT_COL", nullable = false)
	public int getCctCol() {
		return this.cctCol;
	}

	public void setCctCol(int cctCol) {
		this.cctCol = cctCol;
	}

	@Column(name = "CCT_COD", nullable = false)
	public int getCctCod() {
		return this.cctCod;
	}

	public void setCctCod(int cctCod) {
		this.cctCod = cctCod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ColaboradorContatoId))
			return false;
		ColaboradorContatoId castOther = (ColaboradorContatoId) other;

		return (this.getCctCol() == castOther.getCctCol())
				&& (this.getCctCod() == castOther.getCctCod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCctCol();
		result = 37 * result + this.getCctCod();
		return result;
	}

}
