package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ColaboradorContaId generated by hbm2java
 */
@Embeddable
public class ColaboradorContaId implements java.io.Serializable {
	
	private static final long serialVersionUID = -4504811676724137850L;
	private int ctcCol;
	private int ctcCod;

	public ColaboradorContaId() {
	}

	public ColaboradorContaId(int ctcCol, int ctcCod) {
		this.ctcCol = ctcCol;
		this.ctcCod = ctcCod;
	}

	@Column(name = "CTC_COL", nullable = false)
	public int getCtcCol() {
		return this.ctcCol;
	}

	public void setCtcCol(int ctcCol) {
		this.ctcCol = ctcCol;
	}

	@Column(name = "CTC_COD", nullable = false)
	public int getCtcCod() {
		return this.ctcCod;
	}

	public void setCtcCod(int ctcCod) {
		this.ctcCod = ctcCod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ColaboradorContaId))
			return false;
		ColaboradorContaId castOther = (ColaboradorContaId) other;

		return (this.getCtcCol() == castOther.getCtcCol())
				&& (this.getCtcCod() == castOther.getCtcCod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCtcCol();
		result = 37 * result + this.getCtcCod();
		return result;
	}

}
