package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Colecao generated by hbm2java
 */
@Entity
@Table(name = "COLECAO")
public class Colecao implements java.io.Serializable {

	private static final long serialVersionUID = -2060184556959395872L;
	private Integer cloCod;
	private String cloNom;
	private Set<Modelo> modelos = new HashSet<Modelo>(0);
	//private Set<Estoqueminimo> estoqueminimos = new HashSet<Estoqueminimo>(0);
	private Set<Produto> produtos = new HashSet<Produto>(0);

	public Colecao() {
	}

	public Colecao(Integer cloCod, String cloNom) {
		this.cloCod = cloCod;
		this.cloNom = cloNom;
	}

	/*public Colecao(Integer cloCod, String cloNom, Set<Modelo> modelos,
			Set<Estoqueminimo> estoqueminimos, Set<Produto> produtos) {
		this.cloCod = cloCod;
		this.cloNom = cloNom;
		this.modelos = modelos;
		this.estoqueminimos = estoqueminimos;
		this.produtos = produtos;
	}*/

	@Id
	@Column(name = "CLO_COD", unique = true, nullable = false)
	public Integer getCloCod() {
		return this.cloCod;
	}

	public void setCloCod(Integer cloCod) {
		this.cloCod = cloCod;
	}

	@Column(name = "CLO_NOM", nullable = false, length = 30)
	public String getCloNom() {
		return this.cloNom;
	}

	public void setCloNom(String cloNom) {
		this.cloNom = cloNom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "colecao")
	public Set<Modelo> getModelos() {
		return this.modelos;
	}

	public void setModelos(Set<Modelo> modelos) {
		this.modelos = modelos;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "colecao")
	public Set<Estoqueminimo> getEstoqueminimos() {
		return this.estoqueminimos;
	}

	public void setEstoqueminimos(Set<Estoqueminimo> estoqueminimos) {
		this.estoqueminimos = estoqueminimos;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "colecao")
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

}
