package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Conta generated by hbm2java
 */
@Entity
@Table(name = "CONTA")
public class Conta implements java.io.Serializable {

	private static final long serialVersionUID = -5512188576253141545L;
	
	private int ctaCod;
	private Agencia agencia;
	private Banco banco;
	private TipoConta tipoConta;
	private String ctaNom;
	private String ctaApe;
	private String ctaNro;
	private String ctaDig;
	private Date ctaDta;
	private Date ctaDtf;
	private BigDecimal ctaLim;
	private Date ctaDti;
	private BigDecimal ctaSli;
	private String ctaOb1;
	private String ctaOb2;
	private String ctaOb3;
	private Character ctaRem;
	private Character ctaRus;
	private int ctaTip;
	private BigDecimal ctaSlb;
	private char ctaAfc;
	/*private Set<Movimentacaoconta> movimentacaocontasForMocCta = new HashSet<Movimentacaoconta>(0);
	private Set<Movimentacaoconta> movimentacaocontasForMocCtd = new HashSet<Movimentacaoconta>(0);
	private Set<Conveniocobranca> conveniocobrancas = new HashSet<Conveniocobranca>(0);*/
	private Set<Filial> filials = new HashSet<Filial>(0);
	/*private Set<Contratocartao> contratocartaos = new HashSet<Contratocartao>(0);
	private Set<Chequebaixaacerto> chequebaixaacertos = new HashSet<Chequebaixaacerto>(0);*/
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	/*private Set<Borderodesconto> borderodescontos = new HashSet<Borderodesconto>(0);
	private Set<Pagarbaixa> pagarbaixas = new HashSet<Pagarbaixa>(0);
	private Set<Chequebaixa> chequebaixas = new HashSet<Chequebaixa>(0);
	private Set<Caixa> caixas = new HashSet<Caixa>(0);
	private Set<Contasaldo> contasaldos = new HashSet<Contasaldo>(0);
	private Set<Receberbaixa> receberbaixas = new HashSet<Receberbaixa>(0);*/

	public Conta() {
	}

	public Conta(int ctaCod, TipoConta tipoConta, String ctaNom, String ctaApe,
			BigDecimal ctaLim, Date ctaDti, BigDecimal ctaSli, int ctaTip,
			BigDecimal ctaSlb, char ctaAfc) {
		this.ctaCod = ctaCod;
		this.tipoConta = tipoConta;
		this.ctaNom = ctaNom;
		this.ctaApe = ctaApe;
		this.ctaLim = ctaLim;
		this.ctaDti = ctaDti;
		this.ctaSli = ctaSli;
		this.ctaTip = ctaTip;
		this.ctaSlb = ctaSlb;
		this.ctaAfc = ctaAfc;
	}

	/*public Conta(int ctaCod, Agencia agencia, Banco banco, Tipoconta tipoconta,
			String ctaNom, String ctaApe, String ctaNro, String ctaDig,
			Date ctaDta, Date ctaDtf, BigDecimal ctaLim, Date ctaDti,
			BigDecimal ctaSli, String ctaOb1, String ctaOb2, String ctaOb3,
			Character ctaRem, Character ctaRus, int ctaTip, BigDecimal ctaSlb,
			char ctaAfc, Set<Movimentacaoconta> movimentacaocontasForMocCta,
			Set<Movimentacaoconta> movimentacaocontasForMocCtd,
			Set<Conveniocobranca> conveniocobrancas, Set<Filial> filials,
			Set<Contratocartao> contratocartaos,
			Set<Chequebaixaacerto> chequebaixaacertos, Set<Usuario> usuarios,
			Set<Borderodesconto> borderodescontos, Set<Pagarbaixa> pagarbaixas,
			Set<Chequebaixa> chequebaixas, Set<Caixa> caixas,
			Set<Contasaldo> contasaldos, Set<Receberbaixa> receberbaixas) {
		this.ctaCod = ctaCod;
		this.agencia = agencia;
		this.banco = banco;
		this.tipoconta = tipoconta;
		this.ctaNom = ctaNom;
		this.ctaApe = ctaApe;
		this.ctaNro = ctaNro;
		this.ctaDig = ctaDig;
		this.ctaDta = ctaDta;
		this.ctaDtf = ctaDtf;
		this.ctaLim = ctaLim;
		this.ctaDti = ctaDti;
		this.ctaSli = ctaSli;
		this.ctaOb1 = ctaOb1;
		this.ctaOb2 = ctaOb2;
		this.ctaOb3 = ctaOb3;
		this.ctaRem = ctaRem;
		this.ctaRus = ctaRus;
		this.ctaTip = ctaTip;
		this.ctaSlb = ctaSlb;
		this.ctaAfc = ctaAfc;
		this.movimentacaocontasForMocCta = movimentacaocontasForMocCta;
		this.movimentacaocontasForMocCtd = movimentacaocontasForMocCtd;
		this.conveniocobrancas = conveniocobrancas;
		this.filials = filials;
		this.contratocartaos = contratocartaos;
		this.chequebaixaacertos = chequebaixaacertos;
		this.usuarios = usuarios;
		this.borderodescontos = borderodescontos;
		this.pagarbaixas = pagarbaixas;
		this.chequebaixas = chequebaixas;
		this.caixas = caixas;
		this.contasaldos = contasaldos;
		this.receberbaixas = receberbaixas;
	}
*/
	@Id
	@Column(name = "CTA_COD", unique = true, nullable = false)
	public int getCtaCod() {
		return this.ctaCod;
	}

	public void setCtaCod(int ctaCod) {
		this.ctaCod = ctaCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CTA_BCO", referencedColumnName = "AGE_BCO"),
			@JoinColumn(name = "CTA_AGE", referencedColumnName = "AGE_COD") })
	public Agencia getAgencia() {
		return this.agencia;
	}

	public void setAgencia(Agencia agencia) {
		this.agencia = agencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTA_BCO", insertable = false, updatable = false)
	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTA_TCO", nullable = false)
	public TipoConta getTipoConta() {
		return this.tipoConta;
	}

	public void setTipoConta(TipoConta tipoConta) {
		this.tipoConta = tipoConta;
	}

	@Column(name = "CTA_NOM", nullable = false, length = 40)
	public String getCtaNom() {
		return this.ctaNom;
	}

	public void setCtaNom(String ctaNom) {
		this.ctaNom = ctaNom;
	}

	@Column(name = "CTA_APE", nullable = false, length = 15)
	public String getCtaApe() {
		return this.ctaApe;
	}

	public void setCtaApe(String ctaApe) {
		this.ctaApe = ctaApe;
	}

	@Column(name = "CTA_NRO", length = 10)
	public String getCtaNro() {
		return this.ctaNro;
	}

	public void setCtaNro(String ctaNro) {
		this.ctaNro = ctaNro;
	}

	@Column(name = "CTA_DIG", length = 2)
	public String getCtaDig() {
		return this.ctaDig;
	}

	public void setCtaDig(String ctaDig) {
		this.ctaDig = ctaDig;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CTA_DTA", length = 10)
	public Date getCtaDta() {
		return this.ctaDta;
	}

	public void setCtaDta(Date ctaDta) {
		this.ctaDta = ctaDta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CTA_DTF", length = 10)
	public Date getCtaDtf() {
		return this.ctaDtf;
	}

	public void setCtaDtf(Date ctaDtf) {
		this.ctaDtf = ctaDtf;
	}

	@Column(name = "CTA_LIM", nullable = false, precision = 15)
	public BigDecimal getCtaLim() {
		return this.ctaLim;
	}

	public void setCtaLim(BigDecimal ctaLim) {
		this.ctaLim = ctaLim;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CTA_DTI", nullable = false, length = 10)
	public Date getCtaDti() {
		return this.ctaDti;
	}

	public void setCtaDti(Date ctaDti) {
		this.ctaDti = ctaDti;
	}

	@Column(name = "CTA_SLI", nullable = false, precision = 15)
	public BigDecimal getCtaSli() {
		return this.ctaSli;
	}

	public void setCtaSli(BigDecimal ctaSli) {
		this.ctaSli = ctaSli;
	}

	@Column(name = "CTA_OB1", length = 40)
	public String getCtaOb1() {
		return this.ctaOb1;
	}

	public void setCtaOb1(String ctaOb1) {
		this.ctaOb1 = ctaOb1;
	}

	@Column(name = "CTA_OB2", length = 40)
	public String getCtaOb2() {
		return this.ctaOb2;
	}

	public void setCtaOb2(String ctaOb2) {
		this.ctaOb2 = ctaOb2;
	}

	@Column(name = "CTA_OB3", length = 40)
	public String getCtaOb3() {
		return this.ctaOb3;
	}

	public void setCtaOb3(String ctaOb3) {
		this.ctaOb3 = ctaOb3;
	}

	@Column(name = "CTA_REM", length = 1)
	public Character getCtaRem() {
		return this.ctaRem;
	}

	public void setCtaRem(Character ctaRem) {
		this.ctaRem = ctaRem;
	}

	@Column(name = "CTA_RUS", length = 1)
	public Character getCtaRus() {
		return this.ctaRus;
	}

	public void setCtaRus(Character ctaRus) {
		this.ctaRus = ctaRus;
	}

	@Column(name = "CTA_TIP", nullable = false)
	public int getCtaTip() {
		return this.ctaTip;
	}

	public void setCtaTip(int ctaTip) {
		this.ctaTip = ctaTip;
	}

	@Column(name = "CTA_SLB", nullable = false, precision = 15)
	public BigDecimal getCtaSlb() {
		return this.ctaSlb;
	}

	public void setCtaSlb(BigDecimal ctaSlb) {
		this.ctaSlb = ctaSlb;
	}

	@Column(name = "CTA_AFC", nullable = false, length = 1)
	public char getCtaAfc() {
		return this.ctaAfc;
	}

	public void setCtaAfc(char ctaAfc) {
		this.ctaAfc = ctaAfc;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contaByMocCta")
	public Set<Movimentacaoconta> getMovimentacaocontasForMocCta() {
		return this.movimentacaocontasForMocCta;
	}

	public void setMovimentacaocontasForMocCta(
			Set<Movimentacaoconta> movimentacaocontasForMocCta) {
		this.movimentacaocontasForMocCta = movimentacaocontasForMocCta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contaByMocCtd")
	public Set<Movimentacaoconta> getMovimentacaocontasForMocCtd() {
		return this.movimentacaocontasForMocCtd;
	}

	public void setMovimentacaocontasForMocCtd(
			Set<Movimentacaoconta> movimentacaocontasForMocCtd) {
		this.movimentacaocontasForMocCtd = movimentacaocontasForMocCtd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conta")
	public Set<Conveniocobranca> getConveniocobrancas() {
		return this.conveniocobrancas;
	}

	public void setConveniocobrancas(Set<Conveniocobranca> conveniocobrancas) {
		this.conveniocobrancas = conveniocobrancas;
	}*/

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "CONTAEMPRESA", joinColumns = { @JoinColumn(name = "CTE_CTA", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "CTE_EMP", nullable = false, updatable = false) })
	public Set<Filial> getFilials() {
		return this.filials;
	}

	public void setFilials(Set<Filial> filials) {
		this.filials = filials;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conta")
	public Set<Contratocartao> getContratocartaos() {
		return this.contratocartaos;
	}

	public void setContratocartaos(Set<Contratocartao> contratocartaos) {
		this.contratocartaos = contratocartaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conta")
	public Set<Chequebaixaacerto> getChequebaixaacertos() {
		return this.chequebaixaacertos;
	}

	public void setChequebaixaacertos(Set<Chequebaixaacerto> chequebaixaacertos) {
		this.chequebaixaacertos = chequebaixaacertos;
	}*/

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "CONTAUSUARIO", joinColumns = { @JoinColumn(name = "CTU_CTA", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "CTU_USU", nullable = false, updatable = false) })
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conta")
	public Set<Borderodesconto> getBorderodescontos() {
		return this.borderodescontos;
	}

	public void setBorderodescontos(Set<Borderodesconto> borderodescontos) {
		this.borderodescontos = borderodescontos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conta")
	public Set<Pagarbaixa> getPagarbaixas() {
		return this.pagarbaixas;
	}

	public void setPagarbaixas(Set<Pagarbaixa> pagarbaixas) {
		this.pagarbaixas = pagarbaixas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conta")
	public Set<Chequebaixa> getChequebaixas() {
		return this.chequebaixas;
	}

	public void setChequebaixas(Set<Chequebaixa> chequebaixas) {
		this.chequebaixas = chequebaixas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conta")
	public Set<Caixa> getCaixas() {
		return this.caixas;
	}

	public void setCaixas(Set<Caixa> caixas) {
		this.caixas = caixas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conta")
	public Set<Contasaldo> getContasaldos() {
		return this.contasaldos;
	}

	public void setContasaldos(Set<Contasaldo> contasaldos) {
		this.contasaldos = contasaldos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conta")
	public Set<Receberbaixa> getReceberbaixas() {
		return this.receberbaixas;
	}

	public void setReceberbaixas(Set<Receberbaixa> receberbaixas) {
		this.receberbaixas = receberbaixas;
	}*/

}
