package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cor generated by hbm2java
 */
@Entity
@Table(name = "COR")
public class Cor implements java.io.Serializable {

	private static final long serialVersionUID = 7585503539139786308L;
	private Integer corCod;
	private String corNom;
	private String corDpr;
	private Integer corTom;
	private String corSit;
	private String corSig;
	//private Set<Estoqueminimo> estoqueminimos = new HashSet<Estoqueminimo>(0);
	private Set<Produto> produtos = new HashSet<Produto>(0);

	public Cor() {
	}

	public Cor(Integer corCod, String corNom, String corDpr, Integer corTom, String corSit) {
		this.corCod = corCod;
		this.corNom = corNom;
		this.corDpr = corDpr;
		this.corTom = corTom;
		this.corSit = corSit;
	}

	/*public Cor(Integer corCod, String corNom, String corDpr, Integer corTom, String corSit,
			String corSig, Set<Estoqueminimo> estoqueminimos,
			Set<Produto> produtos) {
		this.corCod = corCod;
		this.corNom = corNom;
		this.corDpr = corDpr;
		this.corTom = corTom;
		this.corSit = corSit;
		this.corSig = corSig;
		this.estoqueminimos = estoqueminimos;
		this.produtos = produtos;
	}*/

	@Id
	@Column(name = "COR_COD", unique = true, nullable = false)
	public Integer getCorCod() {
		return this.corCod;
	}

	public void setCorCod(Integer corCod) {
		this.corCod = corCod;
	}

	@Column(name = "COR_NOM", nullable = false, length = 30)
	public String getCorNom() {
		return this.corNom;
	}

	public void setCorNom(String corNom) {
		this.corNom = corNom;
	}

	@Column(name = "COR_DPR", nullable = false, length = 1)
	public String getCorDpr() {
		return this.corDpr;
	}

	public void setCorDpr(String corDpr) {
		this.corDpr = corDpr;
	}

	@Column(name = "COR_TOM", nullable = false)
	public Integer getCorTom() {
		return this.corTom;
	}

	public void setCorTom(Integer corTom) {
		this.corTom = corTom;
	}

	@Column(name = "COR_SIT", nullable = false, length = 1)
	public String getCorSit() {
		return this.corSit;
	}

	public void setCorSit(String corSit) {
		this.corSit = corSit;
	}

	@Column(name = "COR_SIG", length = 4)
	public String getCorSig() {
		return this.corSig;
	}

	public void setCorSig(String corSig) {
		this.corSig = corSig;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cor")
	public Set<Estoqueminimo> getEstoqueminimos() {
		return this.estoqueminimos;
	}

	public void setEstoqueminimos(Set<Estoqueminimo> estoqueminimos) {
		this.estoqueminimos = estoqueminimos;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cor")
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

}
