package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmpresaPautaCondicao generated by hbm2java
 */
@Entity
@Table(name = "EMPRESAPAUTACONDICAO")
public class EmpresaPautaCondicao implements java.io.Serializable {

	private static final long serialVersionUID = 1884265537612522215L;
	private Integer epcCod;
	private CondicaoPagto condicaoPagto;
	private EmpresaPauta empresaPauta;
	private FormaPagto formaPagto;
	private BigDecimal epcAcr;
	private Character epcTac;
	private BigDecimal epcDes;
	private Integer epcCol;
	private String epcPal;
	private BigDecimal epcLib;
	private Integer epcLdv;
	private String epcTpv;

	public EmpresaPautaCondicao() {
	}

	public EmpresaPautaCondicao(Integer epcCod, CondicaoPagto condicaoPagto,
			EmpresaPauta empresaPauta, BigDecimal epcAcr, BigDecimal epcDes,
			Integer epcCol, String epcPal, BigDecimal epcLib, Integer epcLdv, String epcTpv) {
		this.epcCod = epcCod;
		this.condicaoPagto = condicaoPagto;
		this.empresaPauta = empresaPauta;
		this.epcAcr = epcAcr;
		this.epcDes = epcDes;
		this.epcCol = epcCol;
		this.epcPal = epcPal;
		this.epcLib = epcLib;
		this.epcLdv = epcLdv;
		this.epcTpv = epcTpv;
	}

	public EmpresaPautaCondicao(Integer epcCod, CondicaoPagto condicaoPagto,
			EmpresaPauta empresaPauta, FormaPagto formaPagto,
			BigDecimal epcAcr, Character epcTac, BigDecimal epcDes, Integer epcCol,
			String epcPal, BigDecimal epcLib, Integer epcLdv, String epcTpv) {
		this.epcCod = epcCod;
		this.condicaoPagto = condicaoPagto;
		this.empresaPauta = empresaPauta;
		this.formaPagto = formaPagto;
		this.epcAcr = epcAcr;
		this.epcTac = epcTac;
		this.epcDes = epcDes;
		this.epcCol = epcCol;
		this.epcPal = epcPal;
		this.epcLib = epcLib;
		this.epcLdv = epcLdv;
		this.epcTpv = epcTpv;
	}

	@Id
	@Column(name = "EPC_COD", unique = true, nullable = false)
	public Integer getEpcCod() {
		return this.epcCod;
	}

	public void setEpcCod(Integer epcCod) {
		this.epcCod = epcCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPC_CDP", nullable = false)
	public CondicaoPagto getCondicaoPagto() {
		return this.condicaoPagto;
	}

	public void setCondicaoPagto(CondicaoPagto condicaoPagto) {
		this.condicaoPagto = condicaoPagto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "EPC_EMP", referencedColumnName = "EPT_EMP", nullable = false),
			@JoinColumn(name = "EPC_PAT", referencedColumnName = "EPT_PAT", nullable = false) })
	public EmpresaPauta getEmpresaPauta() {
		return this.empresaPauta;
	}

	public void setEmpresaPauta(EmpresaPauta empresaPauta) {
		this.empresaPauta = empresaPauta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPC_FPA")
	public FormaPagto getFormaPagto() {
		return this.formaPagto;
	}

	public void setFormaPagto(FormaPagto formaPagto) {
		this.formaPagto = formaPagto;
	}

	@Column(name = "EPC_ACR", nullable = false, precision = 6)
	public BigDecimal getEpcAcr() {
		return this.epcAcr;
	}

	public void setEpcAcr(BigDecimal epcAcr) {
		this.epcAcr = epcAcr;
	}

	@Column(name = "EPC_TAC", length = 1)
	public Character getEpcTac() {
		return this.epcTac;
	}

	public void setEpcTac(Character epcTac) {
		this.epcTac = epcTac;
	}

	@Column(name = "EPC_DES", nullable = false, precision = 6)
	public BigDecimal getEpcDes() {
		return this.epcDes;
	}

	public void setEpcDes(BigDecimal epcDes) {
		this.epcDes = epcDes;
	}

	@Column(name = "EPC_COL", nullable = false)
	public Integer getEpcCol() {
		return this.epcCol;
	}

	public void setEpcCol(Integer epcCol) {
		this.epcCol = epcCol;
	}

	@Column(name = "EPC_PAL", nullable = false, length = 1)
	public String getEpcPal() {
		return this.epcPal;
	}

	public void setEpcPal(String epcPal) {
		this.epcPal = epcPal;
	}

	@Column(name = "EPC_LIB", nullable = false, precision = 15)
	public BigDecimal getEpcLib() {
		return this.epcLib;
	}

	public void setEpcLib(BigDecimal epcLib) {
		this.epcLib = epcLib;
	}

	@Column(name = "EPC_LDV", nullable = false)
	public Integer getEpcLdv() {
		return this.epcLdv;
	}

	public void setEpcLdv(Integer epcLdv) {
		this.epcLdv = epcLdv;
	}

	@Column(name = "EPC_TPV", nullable = false, length = 1)
	public String getEpcTpv() {
		return this.epcTpv;
	}

	public void setEpcTpv(String epcTpv) {
		this.epcTpv = epcTpv;
	}

}
