package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpresaPauta generated by hbm2java
 */
@Entity
@Table(name = "EMPRESAPAUTA")
public class EmpresaPauta implements java.io.Serializable {

	private static final long serialVersionUID = -1109022472376572736L;
	private EmpresaPautaId id;
	private Empresa empresa;
	private String eptNom;
	private Date eptDte;
	private Date eptDtv;
	private BigDecimal eptPde;
	private char eptEvp;
	private String eptOb1;
	private String eptOb2;
	private String eptOb3;
	private String eptOb4;
	private String eptOb5;
	private char eptGnf;
	private char eptSit;
	private Integer eptPmr;
	private BigDecimal eptPvr;
	private int eptPva;
//	private Set<EmpresaPautaproduto> empresaPautaprodutos = new HashSet<EmpresaPautaproduto>(0);
//	private Set<Movimento> movimentos = new HashSet<Movimento>(0);
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);
//	private Set<RepresentanteempresaPauta> representanteempresaPautas = new HashSet<RepresentanteempresaPauta>(0);
	private Set<EmpresaPautaCondicao> empresaPautaCondicaos = new HashSet<EmpresaPautaCondicao>(0);
//	private Set<ClienteRepresentante> clienteRepresentantes = new HashSet<ClienteRepresentante>(0);
	private Set<Filial> filials = new HashSet<Filial>(0);
//	private Set<EmpresaPautamodeloartigo> empresaPautamodeloartigos = new HashSet<EmpresaPautamodeloartigo>(0);

	public EmpresaPauta() {
	}

	public EmpresaPauta(EmpresaPautaId id, Empresa empresa, String eptNom,
			Date eptDte, BigDecimal eptPde, char eptEvp, char eptGnf,
			char eptSit, BigDecimal eptPvr, int eptPva) {
		this.id = id;
		this.empresa = empresa;
		this.eptNom = eptNom;
		this.eptDte = eptDte;
		this.eptPde = eptPde;
		this.eptEvp = eptEvp;
		this.eptGnf = eptGnf;
		this.eptSit = eptSit;
		this.eptPvr = eptPvr;
		this.eptPva = eptPva;
	}

	/*public EmpresaPauta(EmpresaPautaId id, Empresa empresa, String eptNom,
			Date eptDte, Date eptDtv, BigDecimal eptPde, char eptEvp,
			String eptOb1, String eptOb2, String eptOb3, String eptOb4,
			String eptOb5, char eptGnf, char eptSit, Integer eptPmr,
			BigDecimal eptPvr, int eptPva,
			Set<EmpresaPautaproduto> empresaPautaprodutos,
			Set<Movimento> movimentos, Set<Pedido> pedidos,
			Set<RepresentanteempresaPauta> representanteempresaPautas,
			Set<EmpresaPautacondicao> empresaPautacondicaos,
			Set<ClienteRepresentante> clienteRepresentantes,
			Set<Filial> filials,
			Set<EmpresaPautamodeloartigo> empresaPautamodeloartigos) {
		this.id = id;
		this.empresa = empresa;
		this.eptNom = eptNom;
		this.eptDte = eptDte;
		this.eptDtv = eptDtv;
		this.eptPde = eptPde;
		this.eptEvp = eptEvp;
		this.eptOb1 = eptOb1;
		this.eptOb2 = eptOb2;
		this.eptOb3 = eptOb3;
		this.eptOb4 = eptOb4;
		this.eptOb5 = eptOb5;
		this.eptGnf = eptGnf;
		this.eptSit = eptSit;
		this.eptPmr = eptPmr;
		this.eptPvr = eptPvr;
		this.eptPva = eptPva;
		this.empresaPautaprodutos = empresaPautaprodutos;
		this.movimentos = movimentos;
		this.pedidos = pedidos;
		this.representanteempresaPautas = representanteempresaPautas;
		this.empresaPautacondicaos = empresaPautacondicaos;
		this.clienteRepresentantes = clienteRepresentantes;
		this.filials = filials;
		this.empresaPautamodeloartigos = empresaPautamodeloartigos;
	}*/

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "eptEmp", column = @Column(name = "EPT_EMP", nullable = false)),
			@AttributeOverride(name = "eptPat", column = @Column(name = "EPT_PAT", nullable = false)) })
	public EmpresaPautaId getId() {
		return this.id;
	}

	public void setId(EmpresaPautaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPT_EMP", nullable = false, insertable = false, updatable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "EPT_NOM", nullable = false, length = 40)
	public String getEptNom() {
		return this.eptNom;
	}

	public void setEptNom(String eptNom) {
		this.eptNom = eptNom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EPT_DTE", nullable = false, length = 10)
	public Date getEptDte() {
		return this.eptDte;
	}

	public void setEptDte(Date eptDte) {
		this.eptDte = eptDte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EPT_DTV", length = 10)
	public Date getEptDtv() {
		return this.eptDtv;
	}

	public void setEptDtv(Date eptDtv) {
		this.eptDtv = eptDtv;
	}

	@Column(name = "EPT_PDE", nullable = false, precision = 6)
	public BigDecimal getEptPde() {
		return this.eptPde;
	}

	public void setEptPde(BigDecimal eptPde) {
		this.eptPde = eptPde;
	}

	@Column(name = "EPT_EVP", nullable = false, length = 1)
	public char getEptEvp() {
		return this.eptEvp;
	}

	public void setEptEvp(char eptEvp) {
		this.eptEvp = eptEvp;
	}

	@Column(name = "EPT_OB1", length = 40)
	public String getEptOb1() {
		return this.eptOb1;
	}

	public void setEptOb1(String eptOb1) {
		this.eptOb1 = eptOb1;
	}

	@Column(name = "EPT_OB2", length = 40)
	public String getEptOb2() {
		return this.eptOb2;
	}

	public void setEptOb2(String eptOb2) {
		this.eptOb2 = eptOb2;
	}

	@Column(name = "EPT_OB3", length = 40)
	public String getEptOb3() {
		return this.eptOb3;
	}

	public void setEptOb3(String eptOb3) {
		this.eptOb3 = eptOb3;
	}

	@Column(name = "EPT_OB4", length = 40)
	public String getEptOb4() {
		return this.eptOb4;
	}

	public void setEptOb4(String eptOb4) {
		this.eptOb4 = eptOb4;
	}

	@Column(name = "EPT_OB5", length = 40)
	public String getEptOb5() {
		return this.eptOb5;
	}

	public void setEptOb5(String eptOb5) {
		this.eptOb5 = eptOb5;
	}

	@Column(name = "EPT_GNF", nullable = false, length = 1)
	public char getEptGnf() {
		return this.eptGnf;
	}

	public void setEptGnf(char eptGnf) {
		this.eptGnf = eptGnf;
	}

	@Column(name = "EPT_SIT", nullable = false, length = 1)
	public char getEptSit() {
		return this.eptSit;
	}

	public void setEptSit(char eptSit) {
		this.eptSit = eptSit;
	}

	@Column(name = "EPT_PMR")
	public Integer getEptPmr() {
		return this.eptPmr;
	}

	public void setEptPmr(Integer eptPmr) {
		this.eptPmr = eptPmr;
	}

	@Column(name = "EPT_PVR", nullable = false, precision = 6)
	public BigDecimal getEptPvr() {
		return this.eptPvr;
	}

	public void setEptPvr(BigDecimal eptPvr) {
		this.eptPvr = eptPvr;
	}

	@Column(name = "EPT_PVA", nullable = false)
	public int getEptPva() {
		return this.eptPva;
	}

	public void setEptPva(int eptPva) {
		this.eptPva = eptPva;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresaPauta")
	public Set<EmpresaPautaproduto> getEmpresaPautaprodutos() {
		return this.empresaPautaprodutos;
	}

	public void setEmpresaPautaprodutos(
			Set<EmpresaPautaproduto> empresaPautaprodutos) {
		this.empresaPautaprodutos = empresaPautaprodutos;
	}
*/
/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresaPauta")
	public Set<Movimento> getMovimentos() {
		return this.movimentos;
	}

	public void setMovimentos(Set<Movimento> movimentos) {
		this.movimentos = movimentos;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresaPauta")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresaPauta")
	public Set<RepresentanteempresaPauta> getRepresentanteempresaPautas() {
		return this.representanteempresaPautas;
	}

	public void setRepresentanteempresaPautas(
			Set<RepresentanteempresaPauta> representanteempresaPautas) {
		this.representanteempresaPautas = representanteempresaPautas;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresaPauta")
	public Set<EmpresaPautaCondicao> getEmpresaPautaCondicaos() {
		return this.empresaPautaCondicaos;
	}

	public void setEmpresaPautaCondicaos(
			Set<EmpresaPautaCondicao> empresaPautaCondicaos) {
		this.empresaPautaCondicaos = empresaPautaCondicaos;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresaPauta")
	public Set<ClienteRepresentante> getClienteRepresentantes() {
		return this.clienteRepresentantes;
	}

	public void setClienteRepresentantes(
			Set<ClienteRepresentante> clienteRepresentantes) {
		this.clienteRepresentantes = clienteRepresentantes;
	}
*/
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresaPauta")
	public Set<Filial> getFilials() {
		return this.filials;
	}

	public void setFilials(Set<Filial> filials) {
		this.filials = filials;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empresaPauta")
	public Set<EmpresaPautamodeloartigo> getEmpresaPautamodeloartigos() {
		return this.empresaPautamodeloartigos;
	}

	public void setEmpresaPautamodeloartigos(
			Set<EmpresaPautamodeloartigo> empresaPautamodeloartigos) {
		this.empresaPautamodeloartigos = empresaPautamodeloartigos;
	}*/

}
