package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Filial generated by hbm2java
 */
@Entity
@Table(name = "FILIAL")
public class Filial implements java.io.Serializable {
	
	private static final long serialVersionUID = -4123673999050164584L;
	private FilialId id;
	private Cliente clienteByFkFilCcs;
	private Cliente clienteByFkFilCli;
	private Empresa empresa;
	private EmpresaPauta empresaPauta;
	private Municipio municipio;
//	private Operacaocomercial operacaocomercialByFkFilOte;
//	private Operacaocomercial operacaocomercialByFkFilOpe;
//	private Operacaocomercial operacaocomercialByFkFilOoe;
//	private Operacaocomercial operacaocomercialByFkFilOts;
//	private Operacaocomercial operacaocomercialByFkFilOeb;
//	private Operacaocomercial operacaocomercialByFkFilOps;
//	private Operacaocomercial operacaocomercialByFkFilOos;
//	private Operacaocomercial operacaocomercialByFkFilOde;
//	private Operacaocomercial operacaocomercialByFkFilOpv;
//	private Operacaocomercial operacaocomercialByFkFilOsb;
	private String filApe;
	private String filRaz;
	private String filNmf;
	private String filEnd;
	private Integer filNro;
	private String filCpl;
	private String filBai;
	private String filCep;
	private String filDdd;
	private String filFon;
	private String filDdf;
	private String filFax;
	private String filDdc;
	private String filCel;
	private String filTip;
	private String filInf;
	private String filIne;
	private String filInm;
	private Date filDti;
	private Date filDtf;
	private String filEma;
	private String filWeb;
	private Integer filRef;
	private String filRes;
	private String filPrs;
	private Integer filRpm;
	private Integer filRpj;
	private Integer filRpd;
	private Integer filPpm;
	private Integer filPpj;
	private Integer filPpd;
	private Integer filCpd;
	private String filSen;
	private int filCde;
	private Date filDtb;
	private char filUpv;
	private BigDecimal filDpv;
	private char filUpa;
	private BigDecimal filDpa;
	private char filUcr;
	private char filUcs;
	private char filUdf;
	private Integer filTec;
	private String filNec;
	private int filClr;
	private char filPeg;
	private char filPer;
	private char filPcp;
	private short filDvl;
	private char filIdf;
	private BigDecimal filDap;
	private char filPpv;
	private char filCem;
	private char filCat;
	private char filVqe;
	private char filCcc;
	private short filDpm;
	private char filFcc;
	private char filNfs;
	private char filBlc;
	private char filSsp;
	private char filGui;
	private long filNsu;
	private char filSit;
	private char filTpp;
	private BigDecimal filDva;
	private Integer filPta;
	private BigDecimal filAda;
	private char filBev;
	private char filEnf;
	private Integer filCrd;
	private char filDtnf;
	private int filMpdv;
	private char filDpvv;
	private char filOsf;
	private BigDecimal filSfi;
	private char filAtv;
	private char filLvd;
	private int filUap;
	private int filUti;
	private char filDsv;
	private char filUcf;
	private char filPavc;
	private char filBfcp;
	private char filCecl;
	private String filIsf;
	private BigDecimal filPmd;
	private char filCfa;
	private char filPsoa;
	private char filFstp;
	private char filEpc;
	private char filMnf;
	private BigDecimal filLdmp;
	private char filUpt;
	private Integer filPtt;
	private char filBfcd;
	private char filBdpv;
	private int filLdpd;
	private int filRcuc;
	private char filEcol;
	private Character filUcc;
	private Character filCmv;
	private Character filUmc;
	private char filIsb;
	private char filUec;
	private Integer filOpr;
	private Integer filOdr;
	private char filVqemt;
	private char filTppl;
	private char filPdvd;
	private char filBec;
	private char filBpvf;
	private char filOicp;
	private char filDcv;
	private char filTch;
	private char filOcv;
	private BigDecimal filMv1;
	private BigDecimal filMv2;
	private BigDecimal filMv3;
	private BigDecimal filMv4;
	private BigDecimal filMv5;
	private BigDecimal filMv6;
	private BigDecimal filMv7;
	private char filPcf;
	private BigDecimal filLsc;
	private char filCfc;
	private char filLcpc;
	private int filParc;
	private char filPgop;
	private char filUrst;
	private String filRdst;
	private char filIsvv;
	private char filIsbc;
	private char filCdpp;
	private char filNfcr;
	private char filAdac;
	private char filErv;
	private int filPmv;
	private char filEcf;
	private int filUarz;
	private char filCfnf;
	private BigDecimal filDmpr;
	private char filIpll;
	private String filGsge;
	private String filOvc;
	private char filPacr;
	private char filIca;
	private char filPdmc;
	private char filLrac;
	private char filBcr;
	private char filVcag;
	private char filBdev;
	private char filPapv;
	private char filUlcf;
	private char filBcl;
	private char filRfid;
	private long filUaec;
	private char filUtie;
	private String filBclc;
	private String filOrc;
	private String filObvc;
	private char filPgct;
	private BigDecimal filLpd;
	private char filOsst;
//	private Set<Abatimentosaldo> abatimentosaldos = new HashSet<Abatimentosaldo>(0);
//	private Set<Caixa> caixas = new HashSet<Caixa>(0);
//	private Set<Fretebaixa> fretebaixas = new HashSet<Fretebaixa>(0);
//	private Set<Contratocartao> contratocartaos = new HashSet<Contratocartao>(0);
//	private Set<Pagar> pagars = new HashSet<Pagar>(0);
//	private Set<Frete> fretes = new HashSet<Frete>(0);
//	private Set<Movimentocolaboradorbaixa> movimentocolaboradorbaixas = new HashSet<Movimentocolaboradorbaixa>(0);
//	private Set<Cheque> cheques = new HashSet<Cheque>(0);
//	private Set<Movimentacaoconta> movimentacaocontas = new HashSet<Movimentacaoconta>(0);
//	private Set<Balanco> balancos = new HashSet<Balanco>(0);
//	private Set<Movimentocobranca> movimentocobrancas = new HashSet<Movimentocobranca>(0);
//	private Set<Abatimento> abatimentos = new HashSet<Abatimento>(0);

//	private Set<Chequebaixa> chequebaixas = new HashSet<Chequebaixa>(0);
//	private Set<Localdeposito> localdepositos = new HashSet<Localdeposito>(0);
//	private Set<Minuta> minutas = new HashSet<Minuta>(0);
//	private Set<Receberbaixa> receberbaixas = new HashSet<Receberbaixa>(0);
//	private Set<ClienteCartaoFidelidade> clienteCartaoFidelidades = new HashSet<ClienteCartaoFidelidade>(0);
//	private Set<Colaboradorsaldo> colaboradorsaldos = new HashSet<Colaboradorsaldo>(0);
//	private Set<Enviocolaboradorfilial> enviocolaboradorfilials = new HashSet<Enviocolaboradorfilial>(0);
//	private Set<Conserto> consertos = new HashSet<Conserto>(0);
//	private Set<Produtofilial> produtofilials = new HashSet<Produtofilial>(0);
//	private Set<Conta> contas = new HashSet<Conta>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);
	//private Set<Pedido> pedidosForFkPedFis = new HashSet<Pedido>(0);
	private Set<Pedido> pedidosForFkPedFil = new HashSet<Pedido>(0);
//	private Set<Receber> recebers = new HashSet<Receber>(0);
//	private Set<Operacaocomercial> operacaocomercials = new HashSet<Operacaocomercial>(0);
//	private Set<Carga> cargas = new HashSet<Carga>(0);
//	private Set<Conveniocobranca> conveniocobrancas = new HashSet<Conveniocobranca>(0);
//	private Set<CustoFixo> custoFixos = new HashSet<CustoFixo>(0);
	private Set<Representante> representantes = new HashSet<Representante>(0);
//	private Set<Chequebaixaacerto> chequebaixaacertos = new HashSet<Chequebaixaacerto>(0);
//	private Set<Pagarbaixa> pagarbaixas = new HashSet<Pagarbaixa>(0);
//	private Set<Prevenda> prevendas = new HashSet<Prevenda>(0);
//	private Set<Contratoservico> contratoservicos = new HashSet<Contratoservico>(0);
//	private Set<Fci> fcis = new HashSet<Fci>(0);
//	private Set<Pedidocompra> pedidocompras = new HashSet<Pedidocompra>(0);
	private Set<Movimento> movimentos = new HashSet<Movimento>(0);
//	private Set<Movimentocartao> movimentocartaos = new HashSet<Movimentocartao>(0);

	public Filial() {
	}

	public Filial(FilialId id, Cliente clienteByFkFilCcs,
			Cliente clienteByFkFilCli, Empresa empresa,
			Municipio municipio, 
			/*Empresapauta empresapauta, 
			Operacaocomercial operacaocomercialByFkFilOte,
			Operacaocomercial operacaocomercialByFkFilOpe,
			Operacaocomercial operacaocomercialByFkFilOoe,
			Operacaocomercial operacaocomercialByFkFilOts,
			Operacaocomercial operacaocomercialByFkFilOeb,
			Operacaocomercial operacaocomercialByFkFilOps,
			Operacaocomercial operacaocomercialByFkFilOos,
			Operacaocomercial operacaocomercialByFkFilOde,
			Operacaocomercial operacaocomercialByFkFilOpv,
			Operacaocomercial operacaocomercialByFkFilOsb,*/ 
			String filApe,
			String filRaz, String filEnd, String filCep, String filTip,
			String filInf, int filCde, char filUpv, BigDecimal filDpv,
			char filUpa, BigDecimal filDpa, char filUcr, char filUcs,
			char filUdf, int filClr, char filPeg, char filPer, char filPcp,
			short filDvl, char filIdf, BigDecimal filDap, char filPpv,
			char filCem, char filCat, char filVqe, char filCcc, short filDpm,
			char filFcc, char filNfs, char filBlc, char filSsp, char filGui,
			long filNsu, char filSit, char filTpp, BigDecimal filDva,
			BigDecimal filAda, char filBev, char filEnf, char filDtnf,
			int filMpdv, char filDpvv, char filOsf, BigDecimal filSfi,
			char filAtv, char filLvd, int filUap, int filUti, char filDsv,
			char filUcf, char filPavc, char filBfcp, char filCecl,
			BigDecimal filPmd, char filCfa, char filPsoa, char filFstp,
			char filEpc, char filMnf, BigDecimal filLdmp, char filUpt,
			char filBfcd, char filBdpv, int filLdpd, int filRcuc, char filEcol,
			char filIsb, char filUec, char filVqemt, char filTppl,
			char filPdvd, char filBec, char filBpvf, char filOicp, char filDcv,
			char filTch, char filOcv, char filPcf, BigDecimal filLsc,
			char filCfc, char filLcpc, int filParc, char filPgop, char filUrst,
			char filIsvv, char filIsbc, char filCdpp, char filNfcr,
			char filAdac, char filErv, int filPmv, char filEcf, int filUarz,
			char filCfnf, BigDecimal filDmpr, char filIpll, char filPacr,
			char filIca, char filPdmc, char filLrac, char filBcr, char filVcag,
			char filBdev, char filPapv, char filUlcf, char filBcl,
			char filRfid, long filUaec, char filUtie, char filPgct,
			BigDecimal filLpd, char filOsst) {
		this.id = id;
		this.clienteByFkFilCcs = clienteByFkFilCcs;
		this.clienteByFkFilCli = clienteByFkFilCli;
		this.empresa = empresa;
		//this.empresapauta = empresapauta;
		/*this.municipio = municipio;
		this.operacaocomercialByFkFilOte = operacaocomercialByFkFilOte;
		this.operacaocomercialByFkFilOpe = operacaocomercialByFkFilOpe;
		this.operacaocomercialByFkFilOoe = operacaocomercialByFkFilOoe;
		this.operacaocomercialByFkFilOts = operacaocomercialByFkFilOts;
		this.operacaocomercialByFkFilOeb = operacaocomercialByFkFilOeb;
		this.operacaocomercialByFkFilOps = operacaocomercialByFkFilOps;
		this.operacaocomercialByFkFilOos = operacaocomercialByFkFilOos;
		this.operacaocomercialByFkFilOde = operacaocomercialByFkFilOde;
		this.operacaocomercialByFkFilOpv = operacaocomercialByFkFilOpv;
		this.operacaocomercialByFkFilOsb = operacaocomercialByFkFilOsb;*/
		this.filApe = filApe;
		this.filRaz = filRaz;
		this.filEnd = filEnd;
		this.filCep = filCep;
		this.filTip = filTip;
		this.filInf = filInf;
		this.filCde = filCde;
		this.filUpv = filUpv;
		this.filDpv = filDpv;
		this.filUpa = filUpa;
		this.filDpa = filDpa;
		this.filUcr = filUcr;
		this.filUcs = filUcs;
		this.filUdf = filUdf;
		this.filClr = filClr;
		this.filPeg = filPeg;
		this.filPer = filPer;
		this.filPcp = filPcp;
		this.filDvl = filDvl;
		this.filIdf = filIdf;
		this.filDap = filDap;
		this.filPpv = filPpv;
		this.filCem = filCem;
		this.filCat = filCat;
		this.filVqe = filVqe;
		this.filCcc = filCcc;
		this.filDpm = filDpm;
		this.filFcc = filFcc;
		this.filNfs = filNfs;
		this.filBlc = filBlc;
		this.filSsp = filSsp;
		this.filGui = filGui;
		this.filNsu = filNsu;
		this.filSit = filSit;
		this.filTpp = filTpp;
		this.filDva = filDva;
		this.filAda = filAda;
		this.filBev = filBev;
		this.filEnf = filEnf;
		this.filDtnf = filDtnf;
		this.filMpdv = filMpdv;
		this.filDpvv = filDpvv;
		this.filOsf = filOsf;
		this.filSfi = filSfi;
		this.filAtv = filAtv;
		this.filLvd = filLvd;
		this.filUap = filUap;
		this.filUti = filUti;
		this.filDsv = filDsv;
		this.filUcf = filUcf;
		this.filPavc = filPavc;
		this.filBfcp = filBfcp;
		this.filCecl = filCecl;
		this.filPmd = filPmd;
		this.filCfa = filCfa;
		this.filPsoa = filPsoa;
		this.filFstp = filFstp;
		this.filEpc = filEpc;
		this.filMnf = filMnf;
		this.filLdmp = filLdmp;
		this.filUpt = filUpt;
		this.filBfcd = filBfcd;
		this.filBdpv = filBdpv;
		this.filLdpd = filLdpd;
		this.filRcuc = filRcuc;
		this.filEcol = filEcol;
		this.filIsb = filIsb;
		this.filUec = filUec;
		this.filVqemt = filVqemt;
		this.filTppl = filTppl;
		this.filPdvd = filPdvd;
		this.filBec = filBec;
		this.filBpvf = filBpvf;
		this.filOicp = filOicp;
		this.filDcv = filDcv;
		this.filTch = filTch;
		this.filOcv = filOcv;
		this.filPcf = filPcf;
		this.filLsc = filLsc;
		this.filCfc = filCfc;
		this.filLcpc = filLcpc;
		this.filParc = filParc;
		this.filPgop = filPgop;
		this.filUrst = filUrst;
		this.filIsvv = filIsvv;
		this.filIsbc = filIsbc;
		this.filCdpp = filCdpp;
		this.filNfcr = filNfcr;
		this.filAdac = filAdac;
		this.filErv = filErv;
		this.filPmv = filPmv;
		this.filEcf = filEcf;
		this.filUarz = filUarz;
		this.filCfnf = filCfnf;
		this.filDmpr = filDmpr;
		this.filIpll = filIpll;
		this.filPacr = filPacr;
		this.filIca = filIca;
		this.filPdmc = filPdmc;
		this.filLrac = filLrac;
		this.filBcr = filBcr;
		this.filVcag = filVcag;
		this.filBdev = filBdev;
		this.filPapv = filPapv;
		this.filUlcf = filUlcf;
		this.filBcl = filBcl;
		this.filRfid = filRfid;
		this.filUaec = filUaec;
		this.filUtie = filUtie;
		this.filPgct = filPgct;
		this.filLpd = filLpd;
		this.filOsst = filOsst;
	}

	public Filial(FilialId id, Cliente clienteByFkFilCcs,
			Cliente clienteByFkFilCli, Empresa empresa,
			Municipio municipio,
			/*Empresapauta empresapauta,
			Operacaocomercial operacaocomercialByFkFilOte,
			Operacaocomercial operacaocomercialByFkFilOpe,
			Operacaocomercial operacaocomercialByFkFilOoe,
			Operacaocomercial operacaocomercialByFkFilOts,
			Operacaocomercial operacaocomercialByFkFilOeb,
			Operacaocomercial operacaocomercialByFkFilOps,
			Operacaocomercial operacaocomercialByFkFilOos,
			Operacaocomercial operacaocomercialByFkFilOde,
			Operacaocomercial operacaocomercialByFkFilOpv,
			Operacaocomercial operacaocomercialByFkFilOsb,*/ 
			String filApe,
			String filRaz, String filNmf, String filEnd, Integer filNro,
			String filCpl, String filBai, String filCep, String filDdd,
			String filFon, String filDdf, String filFax, String filDdc,
			String filCel, String filTip, String filInf, String filIne,
			String filInm, Date filDti, Date filDtf, String filEma,
			String filWeb, Integer filRef, String filRes, String filPrs,
			Integer filRpm, Integer filRpj, Integer filRpd, Integer filPpm,
			Integer filPpj, Integer filPpd, Integer filCpd, String filSen,
			int filCde, Date filDtb, char filUpv, BigDecimal filDpv,
			char filUpa, BigDecimal filDpa, char filUcr, char filUcs,
			char filUdf, Integer filTec, String filNec, int filClr,
			char filPeg, char filPer, char filPcp, short filDvl, char filIdf,
			BigDecimal filDap, char filPpv, char filCem, char filCat,
			char filVqe, char filCcc, short filDpm, char filFcc, char filNfs,
			char filBlc, char filSsp, char filGui, long filNsu, char filSit,
			char filTpp, BigDecimal filDva, Integer filPta, BigDecimal filAda,
			char filBev, char filEnf, Integer filCrd, char filDtnf,
			int filMpdv, char filDpvv, char filOsf, BigDecimal filSfi,
			char filAtv, char filLvd, int filUap, int filUti, char filDsv,
			char filUcf, char filPavc, char filBfcp, char filCecl,
			String filIsf, BigDecimal filPmd, char filCfa, char filPsoa,
			char filFstp, char filEpc, char filMnf, BigDecimal filLdmp,
			char filUpt, Integer filPtt, char filBfcd, char filBdpv,
			int filLdpd, int filRcuc, char filEcol, Character filUcc,
			Character filCmv, Character filUmc, char filIsb, char filUec,
			Integer filOpr, Integer filOdr, char filVqemt, char filTppl,
			char filPdvd, char filBec, char filBpvf, char filOicp, char filDcv,
			char filTch, char filOcv, BigDecimal filMv1, BigDecimal filMv2,
			BigDecimal filMv3, BigDecimal filMv4, BigDecimal filMv5,
			BigDecimal filMv6, BigDecimal filMv7, char filPcf,
			BigDecimal filLsc, char filCfc, char filLcpc, int filParc,
			char filPgop, char filUrst, String filRdst, char filIsvv,
			char filIsbc, char filCdpp, char filNfcr, char filAdac,
			char filErv, int filPmv, char filEcf, int filUarz, char filCfnf,
			BigDecimal filDmpr, char filIpll, String filGsge, String filOvc,
			char filPacr, char filIca, char filPdmc, char filLrac, char filBcr,
			char filVcag, char filBdev, char filPapv, char filUlcf,
			char filBcl, char filRfid, long filUaec, char filUtie,
			String filBclc, String filOrc, String filObvc, char filPgct,
			BigDecimal filLpd, char filOsst,
			Set<Pedido> pedidosForFkPedFil,
			Set<Conta> contas, 
			Set<Usuario> usuarios,
			Set<Pedido> pedidosForFkPedFis,
			Set<Representante> representantes,
			Set<Movimento> movimentos
			
			/*Set<Abatimentosaldo> abatimentosaldos, 
			Set<Caixa> caixas,
			Set<Fretebaixa> fretebaixas, 
			Set<Contratocartao> contratocartaos,
			Set<Pagar> pagars, 
			Set<Frete> fretes,
			Set<Movimentocolaboradorbaixa> movimentocolaboradorbaixas,
			Set<Cheque> cheques, 
			Set<Movimentacaoconta> movimentacaocontas,
			Set<Balanco> balancos, 
			Set<Movimentocobranca> movimentocobrancas,
			Set<Abatimento> abatimentos, 
			Set<Chequebaixa> chequebaixas, 
			Set<Localdeposito> localdepositos,
			Set<Minuta> minutas,
			Set<Receberbaixa> receberbaixas,
			Set<Clientecartaofidelidade> clientecartaofidelidades,
			Set<Colaboradorsaldo> colaboradorsaldos,
			Set<Enviocolaboradorfilial> enviocolaboradorfilials,
			Set<Conserto> consertos,
			Set<Produtofilial> produtofilials,
			Set<Receber> recebers,
			Set<Operacaocomercial> operacaocomercials, 
			Set<Carga> cargas,
			Set<Conveniocobranca> conveniocobrancas, 
			Set<Custofixo> custofixos,
			Set<Chequebaixaacerto> chequebaixaacertos,
			Set<Pagarbaixa> pagarbaixas, 
			Set<Prevenda> prevendas,
			Set<Contratoservico> contratoservicos, 
			Set<Fci> fcis,
			Set<Pedidocompra> pedidocompras, 
			Set<Movimentocartao> movimentocartaos*/
			
			) {
		this.id = id;
		this.clienteByFkFilCcs = clienteByFkFilCcs;
		this.clienteByFkFilCli = clienteByFkFilCli;
		this.empresa = empresa;
		this.municipio = municipio;
		
		/*this.empresapauta = empresapauta;
		this.operacaocomercialByFkFilOte = operacaocomercialByFkFilOte;
		this.operacaocomercialByFkFilOpe = operacaocomercialByFkFilOpe;
		this.operacaocomercialByFkFilOoe = operacaocomercialByFkFilOoe;
		this.operacaocomercialByFkFilOts = operacaocomercialByFkFilOts;
		this.operacaocomercialByFkFilOeb = operacaocomercialByFkFilOeb;
		this.operacaocomercialByFkFilOps = operacaocomercialByFkFilOps;
		this.operacaocomercialByFkFilOos = operacaocomercialByFkFilOos;
		this.operacaocomercialByFkFilOde = operacaocomercialByFkFilOde;
		this.operacaocomercialByFkFilOpv = operacaocomercialByFkFilOpv;
		this.operacaocomercialByFkFilOsb = operacaocomercialByFkFilOsb;*/
		
		this.filApe = filApe;
		this.filRaz = filRaz;
		this.filNmf = filNmf;
		this.filEnd = filEnd;
		this.filNro = filNro;
		this.filCpl = filCpl;
		this.filBai = filBai;
		this.filCep = filCep;
		this.filDdd = filDdd;
		this.filFon = filFon;
		this.filDdf = filDdf;
		this.filFax = filFax;
		this.filDdc = filDdc;
		this.filCel = filCel;
		this.filTip = filTip;
		this.filInf = filInf;
		this.filIne = filIne;
		this.filInm = filInm;
		this.filDti = filDti;
		this.filDtf = filDtf;
		this.filEma = filEma;
		this.filWeb = filWeb;
		this.filRef = filRef;
		this.filRes = filRes;
		this.filPrs = filPrs;
		this.filRpm = filRpm;
		this.filRpj = filRpj;
		this.filRpd = filRpd;
		this.filPpm = filPpm;
		this.filPpj = filPpj;
		this.filPpd = filPpd;
		this.filCpd = filCpd;
		this.filSen = filSen;
		this.filCde = filCde;
		this.filDtb = filDtb;
		this.filUpv = filUpv;
		this.filDpv = filDpv;
		this.filUpa = filUpa;
		this.filDpa = filDpa;
		this.filUcr = filUcr;
		this.filUcs = filUcs;
		this.filUdf = filUdf;
		this.filTec = filTec;
		this.filNec = filNec;
		this.filClr = filClr;
		this.filPeg = filPeg;
		this.filPer = filPer;
		this.filPcp = filPcp;
		this.filDvl = filDvl;
		this.filIdf = filIdf;
		this.filDap = filDap;
		this.filPpv = filPpv;
		this.filCem = filCem;
		this.filCat = filCat;
		this.filVqe = filVqe;
		this.filCcc = filCcc;
		this.filDpm = filDpm;
		this.filFcc = filFcc;
		this.filNfs = filNfs;
		this.filBlc = filBlc;
		this.filSsp = filSsp;
		this.filGui = filGui;
		this.filNsu = filNsu;
		this.filSit = filSit;
		this.filTpp = filTpp;
		this.filDva = filDva;
		this.filPta = filPta;
		this.filAda = filAda;
		this.filBev = filBev;
		this.filEnf = filEnf;
		this.filCrd = filCrd;
		this.filDtnf = filDtnf;
		this.filMpdv = filMpdv;
		this.filDpvv = filDpvv;
		this.filOsf = filOsf;
		this.filSfi = filSfi;
		this.filAtv = filAtv;
		this.filLvd = filLvd;
		this.filUap = filUap;
		this.filUti = filUti;
		this.filDsv = filDsv;
		this.filUcf = filUcf;
		this.filPavc = filPavc;
		this.filBfcp = filBfcp;
		this.filCecl = filCecl;
		this.filIsf = filIsf;
		this.filPmd = filPmd;
		this.filCfa = filCfa;
		this.filPsoa = filPsoa;
		this.filFstp = filFstp;
		this.filEpc = filEpc;
		this.filMnf = filMnf;
		this.filLdmp = filLdmp;
		this.filUpt = filUpt;
		this.filPtt = filPtt;
		this.filBfcd = filBfcd;
		this.filBdpv = filBdpv;
		this.filLdpd = filLdpd;
		this.filRcuc = filRcuc;
		this.filEcol = filEcol;
		this.filUcc = filUcc;
		this.filCmv = filCmv;
		this.filUmc = filUmc;
		this.filIsb = filIsb;
		this.filUec = filUec;
		this.filOpr = filOpr;
		this.filOdr = filOdr;
		this.filVqemt = filVqemt;
		this.filTppl = filTppl;
		this.filPdvd = filPdvd;
		this.filBec = filBec;
		this.filBpvf = filBpvf;
		this.filOicp = filOicp;
		this.filDcv = filDcv;
		this.filTch = filTch;
		this.filOcv = filOcv;
		this.filMv1 = filMv1;
		this.filMv2 = filMv2;
		this.filMv3 = filMv3;
		this.filMv4 = filMv4;
		this.filMv5 = filMv5;
		this.filMv6 = filMv6;
		this.filMv7 = filMv7;
		this.filPcf = filPcf;
		this.filLsc = filLsc;
		this.filCfc = filCfc;
		this.filLcpc = filLcpc;
		this.filParc = filParc;
		this.filPgop = filPgop;
		this.filUrst = filUrst;
		this.filRdst = filRdst;
		this.filIsvv = filIsvv;
		this.filIsbc = filIsbc;
		this.filCdpp = filCdpp;
		this.filNfcr = filNfcr;
		this.filAdac = filAdac;
		this.filErv = filErv;
		this.filPmv = filPmv;
		this.filEcf = filEcf;
		this.filUarz = filUarz;
		this.filCfnf = filCfnf;
		this.filDmpr = filDmpr;
		this.filIpll = filIpll;
		this.filGsge = filGsge;
		this.filOvc = filOvc;
		this.filPacr = filPacr;
		this.filIca = filIca;
		this.filPdmc = filPdmc;
		this.filLrac = filLrac;
		this.filBcr = filBcr;
		this.filVcag = filVcag;
		this.filBdev = filBdev;
		this.filPapv = filPapv;
		this.filUlcf = filUlcf;
		this.filBcl = filBcl;
		this.filRfid = filRfid;
		this.filUaec = filUaec;
		this.filUtie = filUtie;
		this.filBclc = filBclc;
		this.filOrc = filOrc;
		this.filObvc = filObvc;
		this.filPgct = filPgct;
		this.filLpd = filLpd;
		this.filOsst = filOsst;
		this.pedidosForFkPedFil = pedidosForFkPedFil;
		this.usuarios = usuarios;
		this.representantes = representantes;
		this.movimentos = movimentos;
		
		/*this.abatimentosaldos = abatimentosaldos;
		this.caixas = caixas;
		this.fretebaixas = fretebaixas;
		this.contratocartaos = contratocartaos;
		this.pagars = pagars;
		this.fretes = fretes;
		this.movimentocolaboradorbaixas = movimentocolaboradorbaixas;
		this.cheques = cheques;
		this.movimentacaocontas = movimentacaocontas;
		this.balancos = balancos;
		this.movimentocobrancas = movimentocobrancas;
		this.abatimentos = abatimentos;
		this.chequebaixas = chequebaixas;
		this.localdepositos = localdepositos;
		this.minutas = minutas;
		this.receberbaixas = receberbaixas;
		this.clientecartaofidelidades = clientecartaofidelidades;
		this.colaboradorsaldos = colaboradorsaldos;
		this.enviocolaboradorfilials = enviocolaboradorfilials;
		this.consertos = consertos;
		this.produtofilials = produtofilials;
		this.contas = contas;
		this.pedidosForFkPedFis = pedidosForFkPedFis;
		this.recebers = recebers;
		this.operacaocomercials = operacaocomercials;
		this.cargas = cargas;
		this.conveniocobrancas = conveniocobrancas;
		this.custofixos = custofixos;
		this.chequebaixaacertos = chequebaixaacertos;
		this.pagarbaixas = pagarbaixas;
		this.prevendas = prevendas;
		this.contratoservicos = contratoservicos;
		this.fcis = fcis;
		this.pedidocompras = pedidocompras;
		this.movimentocartaos = movimentocartaos;*/
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "filEmp", column = @Column(name = "FIL_EMP", nullable = false )),
			@AttributeOverride(name = "filCod", column = @Column(name = "FIL_COD", nullable = false)) })
	public FilialId getId() {
		return this.id;
	}

	public void setId(FilialId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "FIL_EMP", referencedColumnName = "CLI_EMP", insertable = false, updatable = false),
			@JoinColumn(name = "FIL_CCS", referencedColumnName = "CLI_COL", insertable = false, updatable = false) })
	public Cliente getClienteByFkFilCcs() {
		return this.clienteByFkFilCcs;
	}

	public void setClienteByFkFilCcs(Cliente clienteByFkFilCcs) {
		this.clienteByFkFilCcs = clienteByFkFilCcs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "FIL_EMP", referencedColumnName = "CLI_EMP", insertable = false, updatable = false),
			@JoinColumn(name = "FIL_CLI", referencedColumnName = "CLI_COL", insertable = false, updatable = false) })
	public Cliente getClienteByFkFilCli() {
		return this.clienteByFkFilCli;
	}

	public void setClienteByFkFilCli(Cliente clienteByFkFilCli) {
		this.clienteByFkFilCli = clienteByFkFilCli;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIL_EMP", nullable = false, insertable = false, updatable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "FIL_EMP", referencedColumnName = "EPT_EMP", insertable = false, updatable = false),
			@JoinColumn(name = "FIL_PAT", referencedColumnName = "EPT_PAT", insertable = false, updatable = false) })
	public EmpresaPauta getEmpresaPauta() {
		return this.empresaPauta;
	}

	public void setEmpresaPauta(EmpresaPauta empresaPauta) {
		this.empresaPauta = empresaPauta;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FIL_MUN", nullable = false)
	public Municipio getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(Municipio municipio) {
		this.municipio = municipio;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "FIL_EMP", referencedColumnName = "OPC_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_COD", referencedColumnName = "OPC_FIL", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_OTE", referencedColumnName = "OPC_COD", insertable = false, updatable = false) })
//	public Operacaocomercial getOperacaocomercialByFkFilOte() {
//		return this.operacaocomercialByFkFilOte;
//	}
//
//	public void setOperacaocomercialByFkFilOte(
//			Operacaocomercial operacaocomercialByFkFilOte) {
//		this.operacaocomercialByFkFilOte = operacaocomercialByFkFilOte;
//	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "FIL_EMP", referencedColumnName = "OPC_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_COD", referencedColumnName = "OPC_FIL", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_OPE", referencedColumnName = "OPC_COD", insertable = false, updatable = false) })
//	public Operacaocomercial getOperacaocomercialByFkFilOpe() {
//		return this.operacaocomercialByFkFilOpe;
//	}
//
//	public void setOperacaocomercialByFkFilOpe(
//			Operacaocomercial operacaocomercialByFkFilOpe) {
//		this.operacaocomercialByFkFilOpe = operacaocomercialByFkFilOpe;
//	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "FIL_EMP", referencedColumnName = "OPC_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_COD", referencedColumnName = "OPC_FIL", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_OOE", referencedColumnName = "OPC_COD", insertable = false, updatable = false) })
//	public Operacaocomercial getOperacaocomercialByFkFilOoe() {
//		return this.operacaocomercialByFkFilOoe;
//	}
//
//	public void setOperacaocomercialByFkFilOoe(
//			Operacaocomercial operacaocomercialByFkFilOoe) {
//		this.operacaocomercialByFkFilOoe = operacaocomercialByFkFilOoe;
//	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "FIL_EMP", referencedColumnName = "OPC_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_COD", referencedColumnName = "OPC_FIL", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_OTS", referencedColumnName = "OPC_COD", insertable = false, updatable = false) })
//	public Operacaocomercial getOperacaocomercialByFkFilOts() {
//		return this.operacaocomercialByFkFilOts;
//	}
//
//	public void setOperacaocomercialByFkFilOts(
//			Operacaocomercial operacaocomercialByFkFilOts) {
//		this.operacaocomercialByFkFilOts = operacaocomercialByFkFilOts;
//	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "FIL_EMP", referencedColumnName = "OPC_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_COD", referencedColumnName = "OPC_FIL", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_OEB", referencedColumnName = "OPC_COD", insertable = false, updatable = false) })
//	public Operacaocomercial getOperacaocomercialByFkFilOeb() {
//		return this.operacaocomercialByFkFilOeb;
//	}
//
//	public void setOperacaocomercialByFkFilOeb(
//			Operacaocomercial operacaocomercialByFkFilOeb) {
//		this.operacaocomercialByFkFilOeb = operacaocomercialByFkFilOeb;
//	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "FIL_EMP", referencedColumnName = "OPC_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_COD", referencedColumnName = "OPC_FIL", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_OPS", referencedColumnName = "OPC_COD", insertable = false, updatable = false) })
//	public Operacaocomercial getOperacaocomercialByFkFilOps() {
//		return this.operacaocomercialByFkFilOps;
//	}
//
//	public void setOperacaocomercialByFkFilOps(
//			Operacaocomercial operacaocomercialByFkFilOps) {
//		this.operacaocomercialByFkFilOps = operacaocomercialByFkFilOps;
//	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "FIL_EMP", referencedColumnName = "OPC_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_COD", referencedColumnName = "OPC_FIL", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_OOS", referencedColumnName = "OPC_COD", insertable = false, updatable = false) })
//	public Operacaocomercial getOperacaocomercialByFkFilOos() {
//		return this.operacaocomercialByFkFilOos;
//	}
//
//	public void setOperacaocomercialByFkFilOos(
//			Operacaocomercial operacaocomercialByFkFilOos) {
//		this.operacaocomercialByFkFilOos = operacaocomercialByFkFilOos;
//	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "FIL_EMP", referencedColumnName = "OPC_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_COD", referencedColumnName = "OPC_FIL", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_ODE", referencedColumnName = "OPC_COD", insertable = false, updatable = false) })
//	public Operacaocomercial getOperacaocomercialByFkFilOde() {
//		return this.operacaocomercialByFkFilOde;
//	}
//
//	public void setOperacaocomercialByFkFilOde(
//			Operacaocomercial operacaocomercialByFkFilOde) {
//		this.operacaocomercialByFkFilOde = operacaocomercialByFkFilOde;
//	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "FIL_EMP", referencedColumnName = "OPC_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_COD", referencedColumnName = "OPC_FIL", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_OPV", referencedColumnName = "OPC_COD", insertable = false, updatable = false) })
//	public Operacaocomercial getOperacaocomercialByFkFilOpv() {
//		return this.operacaocomercialByFkFilOpv;
//	}
//
//	public void setOperacaocomercialByFkFilOpv(
//			Operacaocomercial operacaocomercialByFkFilOpv) {
//		this.operacaocomercialByFkFilOpv = operacaocomercialByFkFilOpv;
//	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "FIL_EMP", referencedColumnName = "OPC_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_COD", referencedColumnName = "OPC_FIL", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "FIL_OSB", referencedColumnName = "OPC_COD", insertable = false, updatable = false) })
//	public Operacaocomercial getOperacaocomercialByFkFilOsb() {
//		return this.operacaocomercialByFkFilOsb;
//	}
//
//	public void setOperacaocomercialByFkFilOsb(
//			Operacaocomercial operacaocomercialByFkFilOsb) {
//		this.operacaocomercialByFkFilOsb = operacaocomercialByFkFilOsb;
//	}

	@Column(name = "FIL_APE", nullable = false, length = 15)
	public String getFilApe() {
		return this.filApe;
	}

	public void setFilApe(String filApe) {
		this.filApe = filApe;
	}

	@Column(name = "FIL_RAZ", nullable = false, length = 50)
	public String getFilRaz() {
		return this.filRaz;
	}

	public void setFilRaz(String filRaz) {
		this.filRaz = filRaz;
	}

	@Column(name = "FIL_NMF", length = 50)
	public String getFilNmf() {
		return this.filNmf;
	}

	public void setFilNmf(String filNmf) {
		this.filNmf = filNmf;
	}

	@Column(name = "FIL_END", nullable = false, length = 40)
	public String getFilEnd() {
		return this.filEnd;
	}

	public void setFilEnd(String filEnd) {
		this.filEnd = filEnd;
	}

	@Column(name = "FIL_NRO")
	public Integer getFilNro() {
		return this.filNro;
	}

	public void setFilNro(Integer filNro) {
		this.filNro = filNro;
	}

	@Column(name = "FIL_CPL", length = 20)
	public String getFilCpl() {
		return this.filCpl;
	}

	public void setFilCpl(String filCpl) {
		this.filCpl = filCpl;
	}

	@Column(name = "FIL_BAI", length = 20)
	public String getFilBai() {
		return this.filBai;
	}

	public void setFilBai(String filBai) {
		this.filBai = filBai;
	}

	@Column(name = "FIL_CEP", nullable = false, length = 8)
	public String getFilCep() {
		return this.filCep;
	}

	public void setFilCep(String filCep) {
		this.filCep = filCep;
	}

	@Column(name = "FIL_DDD", length = 2)
	public String getFilDdd() {
		return this.filDdd;
	}

	public void setFilDdd(String filDdd) {
		this.filDdd = filDdd;
	}

	@Column(name = "FIL_FON", length = 8)
	public String getFilFon() {
		return this.filFon;
	}

	public void setFilFon(String filFon) {
		this.filFon = filFon;
	}

	@Column(name = "FIL_DDF", length = 2)
	public String getFilDdf() {
		return this.filDdf;
	}

	public void setFilDdf(String filDdf) {
		this.filDdf = filDdf;
	}

	@Column(name = "FIL_FAX", length = 8)
	public String getFilFax() {
		return this.filFax;
	}

	public void setFilFax(String filFax) {
		this.filFax = filFax;
	}

	@Column(name = "FIL_DDC", length = 2)
	public String getFilDdc() {
		return this.filDdc;
	}

	public void setFilDdc(String filDdc) {
		this.filDdc = filDdc;
	}

	@Column(name = "FIL_CEL", length = 9)
	public String getFilCel() {
		return this.filCel;
	}

	public void setFilCel(String filCel) {
		this.filCel = filCel;
	}

	@Column(name = "FIL_TIP", nullable = false, length = 4)
	public String getFilTip() {
		return this.filTip;
	}

	public void setFilTip(String filTip) {
		this.filTip = filTip;
	}

	@Column(name = "FIL_INF", nullable = false, length = 14)
	public String getFilInf() {
		return this.filInf;
	}

	public void setFilInf(String filInf) {
		this.filInf = filInf;
	}

	@Column(name = "FIL_INE", length = 20)
	public String getFilIne() {
		return this.filIne;
	}

	public void setFilIne(String filIne) {
		this.filIne = filIne;
	}

	@Column(name = "FIL_INM", length = 20)
	public String getFilInm() {
		return this.filInm;
	}

	public void setFilInm(String filInm) {
		this.filInm = filInm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FIL_DTI", length = 10)
	public Date getFilDti() {
		return this.filDti;
	}

	public void setFilDti(Date filDti) {
		this.filDti = filDti;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FIL_DTF", length = 10)
	public Date getFilDtf() {
		return this.filDtf;
	}

	public void setFilDtf(Date filDtf) {
		this.filDtf = filDtf;
	}

	@Column(name = "FIL_EMA", length = 50)
	public String getFilEma() {
		return this.filEma;
	}

	public void setFilEma(String filEma) {
		this.filEma = filEma;
	}

	@Column(name = "FIL_WEB", length = 50)
	public String getFilWeb() {
		return this.filWeb;
	}

	public void setFilWeb(String filWeb) {
		this.filWeb = filWeb;
	}

	@Column(name = "FIL_REF")
	public Integer getFilRef() {
		return this.filRef;
	}

	public void setFilRef(Integer filRef) {
		this.filRef = filRef;
	}

	@Column(name = "FIL_RES", length = 13)
	public String getFilRes() {
		return this.filRes;
	}

	public void setFilRes(String filRes) {
		this.filRes = filRes;
	}

	@Column(name = "FIL_PRS", length = 14)
	public String getFilPrs() {
		return this.filPrs;
	}

	public void setFilPrs(String filPrs) {
		this.filPrs = filPrs;
	}

	@Column(name = "FIL_RPM")
	public Integer getFilRpm() {
		return this.filRpm;
	}

	public void setFilRpm(Integer filRpm) {
		this.filRpm = filRpm;
	}

	@Column(name = "FIL_RPJ")
	public Integer getFilRpj() {
		return this.filRpj;
	}

	public void setFilRpj(Integer filRpj) {
		this.filRpj = filRpj;
	}

	@Column(name = "FIL_RPD")
	public Integer getFilRpd() {
		return this.filRpd;
	}

	public void setFilRpd(Integer filRpd) {
		this.filRpd = filRpd;
	}

	@Column(name = "FIL_PPM")
	public Integer getFilPpm() {
		return this.filPpm;
	}

	public void setFilPpm(Integer filPpm) {
		this.filPpm = filPpm;
	}

	@Column(name = "FIL_PPJ")
	public Integer getFilPpj() {
		return this.filPpj;
	}

	public void setFilPpj(Integer filPpj) {
		this.filPpj = filPpj;
	}

	@Column(name = "FIL_PPD")
	public Integer getFilPpd() {
		return this.filPpd;
	}

	public void setFilPpd(Integer filPpd) {
		this.filPpd = filPpd;
	}

	@Column(name = "FIL_CPD")
	public Integer getFilCpd() {
		return this.filCpd;
	}

	public void setFilCpd(Integer filCpd) {
		this.filCpd = filCpd;
	}

	@Column(name = "FIL_SEN", length = 15)
	public String getFilSen() {
		return this.filSen;
	}

	public void setFilSen(String filSen) {
		this.filSen = filSen;
	}

	@Column(name = "FIL_CDE", nullable = false)
	public int getFilCde() {
		return this.filCde;
	}

	public void setFilCde(int filCde) {
		this.filCde = filCde;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FIL_DTB", length = 10)
	public Date getFilDtb() {
		return this.filDtb;
	}

	public void setFilDtb(Date filDtb) {
		this.filDtb = filDtb;
	}

	@Column(name = "FIL_UPV", nullable = false, length = 1)
	public char getFilUpv() {
		return this.filUpv;
	}

	public void setFilUpv(char filUpv) {
		this.filUpv = filUpv;
	}

	@Column(name = "FIL_DPV", nullable = false, precision = 14)
	public BigDecimal getFilDpv() {
		return this.filDpv;
	}

	public void setFilDpv(BigDecimal filDpv) {
		this.filDpv = filDpv;
	}

	@Column(name = "FIL_UPA", nullable = false, length = 1)
	public char getFilUpa() {
		return this.filUpa;
	}

	public void setFilUpa(char filUpa) {
		this.filUpa = filUpa;
	}

	@Column(name = "FIL_DPA", nullable = false, precision = 14)
	public BigDecimal getFilDpa() {
		return this.filDpa;
	}

	public void setFilDpa(BigDecimal filDpa) {
		this.filDpa = filDpa;
	}

	@Column(name = "FIL_UCR", nullable = false, length = 1)
	public char getFilUcr() {
		return this.filUcr;
	}

	public void setFilUcr(char filUcr) {
		this.filUcr = filUcr;
	}

	@Column(name = "FIL_UCS", nullable = false, length = 1)
	public char getFilUcs() {
		return this.filUcs;
	}

	public void setFilUcs(char filUcs) {
		this.filUcs = filUcs;
	}

	@Column(name = "FIL_UDF", nullable = false, length = 1)
	public char getFilUdf() {
		return this.filUdf;
	}

	public void setFilUdf(char filUdf) {
		this.filUdf = filUdf;
	}

	@Column(name = "FIL_TEC")
	public Integer getFilTec() {
		return this.filTec;
	}

	public void setFilTec(Integer filTec) {
		this.filTec = filTec;
	}

	@Column(name = "FIL_NEC", length = 15)
	public String getFilNec() {
		return this.filNec;
	}

	public void setFilNec(String filNec) {
		this.filNec = filNec;
	}

	@Column(name = "FIL_CLR", nullable = false)
	public int getFilClr() {
		return this.filClr;
	}

	public void setFilClr(int filClr) {
		this.filClr = filClr;
	}

	@Column(name = "FIL_PEG", nullable = false, length = 1)
	public char getFilPeg() {
		return this.filPeg;
	}

	public void setFilPeg(char filPeg) {
		this.filPeg = filPeg;
	}

	@Column(name = "FIL_PER", nullable = false, length = 1)
	public char getFilPer() {
		return this.filPer;
	}

	public void setFilPer(char filPer) {
		this.filPer = filPer;
	}

	@Column(name = "FIL_PCP", nullable = false, length = 1)
	public char getFilPcp() {
		return this.filPcp;
	}

	public void setFilPcp(char filPcp) {
		this.filPcp = filPcp;
	}

	@Column(name = "FIL_DVL", nullable = false)
	public short getFilDvl() {
		return this.filDvl;
	}

	public void setFilDvl(short filDvl) {
		this.filDvl = filDvl;
	}

	@Column(name = "FIL_IDF", nullable = false, length = 1)
	public char getFilIdf() {
		return this.filIdf;
	}

	public void setFilIdf(char filIdf) {
		this.filIdf = filIdf;
	}

	@Column(name = "FIL_DAP", nullable = false, precision = 6)
	public BigDecimal getFilDap() {
		return this.filDap;
	}

	public void setFilDap(BigDecimal filDap) {
		this.filDap = filDap;
	}

	@Column(name = "FIL_PPV", nullable = false, length = 1)
	public char getFilPpv() {
		return this.filPpv;
	}

	public void setFilPpv(char filPpv) {
		this.filPpv = filPpv;
	}

	@Column(name = "FIL_CEM", nullable = false, length = 1)
	public char getFilCem() {
		return this.filCem;
	}

	public void setFilCem(char filCem) {
		this.filCem = filCem;
	}

	@Column(name = "FIL_CAT", nullable = false, length = 1)
	public char getFilCat() {
		return this.filCat;
	}

	public void setFilCat(char filCat) {
		this.filCat = filCat;
	}

	@Column(name = "FIL_VQE", nullable = false, length = 1)
	public char getFilVqe() {
		return this.filVqe;
	}

	public void setFilVqe(char filVqe) {
		this.filVqe = filVqe;
	}

	@Column(name = "FIL_CCC", nullable = false, length = 1)
	public char getFilCcc() {
		return this.filCcc;
	}

	public void setFilCcc(char filCcc) {
		this.filCcc = filCcc;
	}

	@Column(name = "FIL_DPM", nullable = false)
	public short getFilDpm() {
		return this.filDpm;
	}

	public void setFilDpm(short filDpm) {
		this.filDpm = filDpm;
	}

	@Column(name = "FIL_FCC", nullable = false, length = 1)
	public char getFilFcc() {
		return this.filFcc;
	}

	public void setFilFcc(char filFcc) {
		this.filFcc = filFcc;
	}

	@Column(name = "FIL_NFS", nullable = false, length = 1)
	public char getFilNfs() {
		return this.filNfs;
	}

	public void setFilNfs(char filNfs) {
		this.filNfs = filNfs;
	}

	@Column(name = "FIL_BLC", nullable = false, length = 1)
	public char getFilBlc() {
		return this.filBlc;
	}

	public void setFilBlc(char filBlc) {
		this.filBlc = filBlc;
	}

	@Column(name = "FIL_SSP", nullable = false, length = 1)
	public char getFilSsp() {
		return this.filSsp;
	}

	public void setFilSsp(char filSsp) {
		this.filSsp = filSsp;
	}

	@Column(name = "FIL_GUI", nullable = false, length = 1)
	public char getFilGui() {
		return this.filGui;
	}

	public void setFilGui(char filGui) {
		this.filGui = filGui;
	}

	@Column(name = "FIL_NSU", nullable = false)
	public long getFilNsu() {
		return this.filNsu;
	}

	public void setFilNsu(long filNsu) {
		this.filNsu = filNsu;
	}

	@Column(name = "FIL_SIT", nullable = false, length = 1)
	public char getFilSit() {
		return this.filSit;
	}

	public void setFilSit(char filSit) {
		this.filSit = filSit;
	}

	@Column(name = "FIL_TPP", nullable = false, length = 1)
	public char getFilTpp() {
		return this.filTpp;
	}

	public void setFilTpp(char filTpp) {
		this.filTpp = filTpp;
	}

	@Column(name = "FIL_DVA", nullable = false, precision = 6)
	public BigDecimal getFilDva() {
		return this.filDva;
	}

	public void setFilDva(BigDecimal filDva) {
		this.filDva = filDva;
	}

	@Column(name = "FIL_PTA")
	public Integer getFilPta() {
		return this.filPta;
	}

	public void setFilPta(Integer filPta) {
		this.filPta = filPta;
	}

	@Column(name = "FIL_ADA", nullable = false, precision = 14)
	public BigDecimal getFilAda() {
		return this.filAda;
	}

	public void setFilAda(BigDecimal filAda) {
		this.filAda = filAda;
	}

	@Column(name = "FIL_BEV", nullable = false, length = 1)
	public char getFilBev() {
		return this.filBev;
	}

	public void setFilBev(char filBev) {
		this.filBev = filBev;
	}

	@Column(name = "FIL_ENF", nullable = false, length = 1)
	public char getFilEnf() {
		return this.filEnf;
	}

	public void setFilEnf(char filEnf) {
		this.filEnf = filEnf;
	}

	@Column(name = "FIL_CRD")
	public Integer getFilCrd() {
		return this.filCrd;
	}

	public void setFilCrd(Integer filCrd) {
		this.filCrd = filCrd;
	}

	@Column(name = "FIL_DTNF", nullable = false, length = 1)
	public char getFilDtnf() {
		return this.filDtnf;
	}

	public void setFilDtnf(char filDtnf) {
		this.filDtnf = filDtnf;
	}

	@Column(name = "FIL_MPDV", nullable = false)
	public int getFilMpdv() {
		return this.filMpdv;
	}

	public void setFilMpdv(int filMpdv) {
		this.filMpdv = filMpdv;
	}

	@Column(name = "FIL_DPVV", nullable = false, length = 1)
	public char getFilDpvv() {
		return this.filDpvv;
	}

	public void setFilDpvv(char filDpvv) {
		this.filDpvv = filDpvv;
	}

	@Column(name = "FIL_OSF", nullable = false, length = 1)
	public char getFilOsf() {
		return this.filOsf;
	}

	public void setFilOsf(char filOsf) {
		this.filOsf = filOsf;
	}

	@Column(name = "FIL_SFI", nullable = false, precision = 6)
	public BigDecimal getFilSfi() {
		return this.filSfi;
	}

	public void setFilSfi(BigDecimal filSfi) {
		this.filSfi = filSfi;
	}

	@Column(name = "FIL_ATV", nullable = false, length = 1)
	public char getFilAtv() {
		return this.filAtv;
	}

	public void setFilAtv(char filAtv) {
		this.filAtv = filAtv;
	}

	@Column(name = "FIL_LVD", nullable = false, length = 1)
	public char getFilLvd() {
		return this.filLvd;
	}

	public void setFilLvd(char filLvd) {
		this.filLvd = filLvd;
	}

	@Column(name = "FIL_UAP", nullable = false)
	public int getFilUap() {
		return this.filUap;
	}

	public void setFilUap(int filUap) {
		this.filUap = filUap;
	}

	@Column(name = "FIL_UTI", nullable = false)
	public int getFilUti() {
		return this.filUti;
	}

	public void setFilUti(int filUti) {
		this.filUti = filUti;
	}

	@Column(name = "FIL_DSV", nullable = false, length = 1)
	public char getFilDsv() {
		return this.filDsv;
	}

	public void setFilDsv(char filDsv) {
		this.filDsv = filDsv;
	}

	@Column(name = "FIL_UCF", nullable = false, length = 1)
	public char getFilUcf() {
		return this.filUcf;
	}

	public void setFilUcf(char filUcf) {
		this.filUcf = filUcf;
	}

	@Column(name = "FIL_PAVC", nullable = false, length = 1)
	public char getFilPavc() {
		return this.filPavc;
	}

	public void setFilPavc(char filPavc) {
		this.filPavc = filPavc;
	}

	@Column(name = "FIL_BFCP", nullable = false, length = 1)
	public char getFilBfcp() {
		return this.filBfcp;
	}

	public void setFilBfcp(char filBfcp) {
		this.filBfcp = filBfcp;
	}

	@Column(name = "FIL_CECL", nullable = false, length = 1)
	public char getFilCecl() {
		return this.filCecl;
	}

	public void setFilCecl(char filCecl) {
		this.filCecl = filCecl;
	}

	@Column(name = "FIL_ISF", length = 9)
	public String getFilIsf() {
		return this.filIsf;
	}

	public void setFilIsf(String filIsf) {
		this.filIsf = filIsf;
	}

	@Column(name = "FIL_PMD", nullable = false, precision = 6)
	public BigDecimal getFilPmd() {
		return this.filPmd;
	}

	public void setFilPmd(BigDecimal filPmd) {
		this.filPmd = filPmd;
	}

	@Column(name = "FIL_CFA", nullable = false, length = 1)
	public char getFilCfa() {
		return this.filCfa;
	}

	public void setFilCfa(char filCfa) {
		this.filCfa = filCfa;
	}

	@Column(name = "FIL_PSOA", nullable = false, length = 1)
	public char getFilPsoa() {
		return this.filPsoa;
	}

	public void setFilPsoa(char filPsoa) {
		this.filPsoa = filPsoa;
	}

	@Column(name = "FIL_FSTP", nullable = false, length = 1)
	public char getFilFstp() {
		return this.filFstp;
	}

	public void setFilFstp(char filFstp) {
		this.filFstp = filFstp;
	}

	@Column(name = "FIL_EPC", nullable = false, length = 1)
	public char getFilEpc() {
		return this.filEpc;
	}

	public void setFilEpc(char filEpc) {
		this.filEpc = filEpc;
	}

	@Column(name = "FIL_MNF", nullable = false, length = 1)
	public char getFilMnf() {
		return this.filMnf;
	}

	public void setFilMnf(char filMnf) {
		this.filMnf = filMnf;
	}

	@Column(name = "FIL_LDMP", nullable = false, precision = 5)
	public BigDecimal getFilLdmp() {
		return this.filLdmp;
	}

	public void setFilLdmp(BigDecimal filLdmp) {
		this.filLdmp = filLdmp;
	}

	@Column(name = "FIL_UPT", nullable = false, length = 1)
	public char getFilUpt() {
		return this.filUpt;
	}

	public void setFilUpt(char filUpt) {
		this.filUpt = filUpt;
	}

	@Column(name = "FIL_PTT")
	public Integer getFilPtt() {
		return this.filPtt;
	}

	public void setFilPtt(Integer filPtt) {
		this.filPtt = filPtt;
	}

	@Column(name = "FIL_BFCD", nullable = false, length = 1)
	public char getFilBfcd() {
		return this.filBfcd;
	}

	public void setFilBfcd(char filBfcd) {
		this.filBfcd = filBfcd;
	}

	@Column(name = "FIL_BDPV", nullable = false, length = 1)
	public char getFilBdpv() {
		return this.filBdpv;
	}

	public void setFilBdpv(char filBdpv) {
		this.filBdpv = filBdpv;
	}

	@Column(name = "FIL_LDPD", nullable = false)
	public int getFilLdpd() {
		return this.filLdpd;
	}

	public void setFilLdpd(int filLdpd) {
		this.filLdpd = filLdpd;
	}

	@Column(name = "FIL_RCUC", nullable = false)
	public int getFilRcuc() {
		return this.filRcuc;
	}

	public void setFilRcuc(int filRcuc) {
		this.filRcuc = filRcuc;
	}

	@Column(name = "FIL_ECOL", nullable = false, length = 1)
	public char getFilEcol() {
		return this.filEcol;
	}

	public void setFilEcol(char filEcol) {
		this.filEcol = filEcol;
	}

	@Column(name = "FIL_UCC", length = 1)
	public Character getFilUcc() {
		return this.filUcc;
	}

	public void setFilUcc(Character filUcc) {
		this.filUcc = filUcc;
	}

	@Column(name = "FIL_CMV", length = 1)
	public Character getFilCmv() {
		return this.filCmv;
	}

	public void setFilCmv(Character filCmv) {
		this.filCmv = filCmv;
	}

	@Column(name = "FIL_UMC", length = 1)
	public Character getFilUmc() {
		return this.filUmc;
	}

	public void setFilUmc(Character filUmc) {
		this.filUmc = filUmc;
	}

	@Column(name = "FIL_ISB", nullable = false, length = 1)
	public char getFilIsb() {
		return this.filIsb;
	}

	public void setFilIsb(char filIsb) {
		this.filIsb = filIsb;
	}

	@Column(name = "FIL_UEC", nullable = false, length = 1)
	public char getFilUec() {
		return this.filUec;
	}

	public void setFilUec(char filUec) {
		this.filUec = filUec;
	}

	@Column(name = "FIL_OPR")
	public Integer getFilOpr() {
		return this.filOpr;
	}

	public void setFilOpr(Integer filOpr) {
		this.filOpr = filOpr;
	}

	@Column(name = "FIL_ODR")
	public Integer getFilOdr() {
		return this.filOdr;
	}

	public void setFilOdr(Integer filOdr) {
		this.filOdr = filOdr;
	}

	@Column(name = "FIL_VQEMT", nullable = false, length = 1)
	public char getFilVqemt() {
		return this.filVqemt;
	}

	public void setFilVqemt(char filVqemt) {
		this.filVqemt = filVqemt;
	}

	@Column(name = "FIL_TPPL", nullable = false, length = 1)
	public char getFilTppl() {
		return this.filTppl;
	}

	public void setFilTppl(char filTppl) {
		this.filTppl = filTppl;
	}

	@Column(name = "FIL_PDVD", nullable = false, length = 1)
	public char getFilPdvd() {
		return this.filPdvd;
	}

	public void setFilPdvd(char filPdvd) {
		this.filPdvd = filPdvd;
	}

	@Column(name = "FIL_BEC", nullable = false, length = 1)
	public char getFilBec() {
		return this.filBec;
	}

	public void setFilBec(char filBec) {
		this.filBec = filBec;
	}

	@Column(name = "FIL_BPVF", nullable = false, length = 1)
	public char getFilBpvf() {
		return this.filBpvf;
	}

	public void setFilBpvf(char filBpvf) {
		this.filBpvf = filBpvf;
	}

	@Column(name = "FIL_OICP", nullable = false, length = 1)
	public char getFilOicp() {
		return this.filOicp;
	}

	public void setFilOicp(char filOicp) {
		this.filOicp = filOicp;
	}

	@Column(name = "FIL_DCV", nullable = false, length = 1)
	public char getFilDcv() {
		return this.filDcv;
	}

	public void setFilDcv(char filDcv) {
		this.filDcv = filDcv;
	}

	@Column(name = "FIL_TCH", nullable = false, length = 1)
	public char getFilTch() {
		return this.filTch;
	}

	public void setFilTch(char filTch) {
		this.filTch = filTch;
	}

	@Column(name = "FIL_OCV", nullable = false, length = 1)
	public char getFilOcv() {
		return this.filOcv;
	}

	public void setFilOcv(char filOcv) {
		this.filOcv = filOcv;
	}

	@Column(name = "FIL_MV1", precision = 6)
	public BigDecimal getFilMv1() {
		return this.filMv1;
	}

	public void setFilMv1(BigDecimal filMv1) {
		this.filMv1 = filMv1;
	}

	@Column(name = "FIL_MV2", precision = 6)
	public BigDecimal getFilMv2() {
		return this.filMv2;
	}

	public void setFilMv2(BigDecimal filMv2) {
		this.filMv2 = filMv2;
	}

	@Column(name = "FIL_MV3", precision = 6)
	public BigDecimal getFilMv3() {
		return this.filMv3;
	}

	public void setFilMv3(BigDecimal filMv3) {
		this.filMv3 = filMv3;
	}

	@Column(name = "FIL_MV4", precision = 6)
	public BigDecimal getFilMv4() {
		return this.filMv4;
	}

	public void setFilMv4(BigDecimal filMv4) {
		this.filMv4 = filMv4;
	}

	@Column(name = "FIL_MV5", precision = 6)
	public BigDecimal getFilMv5() {
		return this.filMv5;
	}

	public void setFilMv5(BigDecimal filMv5) {
		this.filMv5 = filMv5;
	}

	@Column(name = "FIL_MV6", precision = 6)
	public BigDecimal getFilMv6() {
		return this.filMv6;
	}

	public void setFilMv6(BigDecimal filMv6) {
		this.filMv6 = filMv6;
	}

	@Column(name = "FIL_MV7", precision = 6)
	public BigDecimal getFilMv7() {
		return this.filMv7;
	}

	public void setFilMv7(BigDecimal filMv7) {
		this.filMv7 = filMv7;
	}

	@Column(name = "FIL_PCF", nullable = false, length = 1)
	public char getFilPcf() {
		return this.filPcf;
	}

	public void setFilPcf(char filPcf) {
		this.filPcf = filPcf;
	}

	@Column(name = "FIL_LSC", nullable = false, precision = 15)
	public BigDecimal getFilLsc() {
		return this.filLsc;
	}

	public void setFilLsc(BigDecimal filLsc) {
		this.filLsc = filLsc;
	}

	@Column(name = "FIL_CFC", nullable = false, length = 1)
	public char getFilCfc() {
		return this.filCfc;
	}

	public void setFilCfc(char filCfc) {
		this.filCfc = filCfc;
	}

	@Column(name = "FIL_LCPC", nullable = false, length = 1)
	public char getFilLcpc() {
		return this.filLcpc;
	}

	public void setFilLcpc(char filLcpc) {
		this.filLcpc = filLcpc;
	}

	@Column(name = "FIL_PARC", nullable = false)
	public int getFilParc() {
		return this.filParc;
	}

	public void setFilParc(int filParc) {
		this.filParc = filParc;
	}

	@Column(name = "FIL_PGOP", nullable = false, length = 1)
	public char getFilPgop() {
		return this.filPgop;
	}

	public void setFilPgop(char filPgop) {
		this.filPgop = filPgop;
	}

	@Column(name = "FIL_URST", nullable = false, length = 1)
	public char getFilUrst() {
		return this.filUrst;
	}

	public void setFilUrst(char filUrst) {
		this.filUrst = filUrst;
	}

	@Column(name = "FIL_RDST", length = 100)
	public String getFilRdst() {
		return this.filRdst;
	}

	public void setFilRdst(String filRdst) {
		this.filRdst = filRdst;
	}

	@Column(name = "FIL_ISVV", nullable = false, length = 1)
	public char getFilIsvv() {
		return this.filIsvv;
	}

	public void setFilIsvv(char filIsvv) {
		this.filIsvv = filIsvv;
	}

	@Column(name = "FIL_ISBC", nullable = false, length = 1)
	public char getFilIsbc() {
		return this.filIsbc;
	}

	public void setFilIsbc(char filIsbc) {
		this.filIsbc = filIsbc;
	}

	@Column(name = "FIL_CDPP", nullable = false, length = 1)
	public char getFilCdpp() {
		return this.filCdpp;
	}

	public void setFilCdpp(char filCdpp) {
		this.filCdpp = filCdpp;
	}

	@Column(name = "FIL_NFCR", nullable = false, length = 1)
	public char getFilNfcr() {
		return this.filNfcr;
	}

	public void setFilNfcr(char filNfcr) {
		this.filNfcr = filNfcr;
	}

	@Column(name = "FIL_ADAC", nullable = false, length = 1)
	public char getFilAdac() {
		return this.filAdac;
	}

	public void setFilAdac(char filAdac) {
		this.filAdac = filAdac;
	}

	@Column(name = "FIL_ERV", nullable = false, length = 1)
	public char getFilErv() {
		return this.filErv;
	}

	public void setFilErv(char filErv) {
		this.filErv = filErv;
	}

	@Column(name = "FIL_PMV", nullable = false)
	public int getFilPmv() {
		return this.filPmv;
	}

	public void setFilPmv(int filPmv) {
		this.filPmv = filPmv;
	}

	@Column(name = "FIL_ECF", nullable = false, length = 1)
	public char getFilEcf() {
		return this.filEcf;
	}

	public void setFilEcf(char filEcf) {
		this.filEcf = filEcf;
	}

	@Column(name = "FIL_UARZ", nullable = false)
	public int getFilUarz() {
		return this.filUarz;
	}

	public void setFilUarz(int filUarz) {
		this.filUarz = filUarz;
	}

	@Column(name = "FIL_CFNF", nullable = false, length = 1)
	public char getFilCfnf() {
		return this.filCfnf;
	}

	public void setFilCfnf(char filCfnf) {
		this.filCfnf = filCfnf;
	}

	@Column(name = "FIL_DMPR", nullable = false, precision = 5)
	public BigDecimal getFilDmpr() {
		return this.filDmpr;
	}

	public void setFilDmpr(BigDecimal filDmpr) {
		this.filDmpr = filDmpr;
	}

	@Column(name = "FIL_IPLL", nullable = false, length = 1)
	public char getFilIpll() {
		return this.filIpll;
	}

	public void setFilIpll(char filIpll) {
		this.filIpll = filIpll;
	}

	@Column(name = "FIL_GSGE", length = 8)
	public String getFilGsge() {
		return this.filGsge;
	}

	public void setFilGsge(String filGsge) {
		this.filGsge = filGsge;
	}

	@Column(name = "FIL_OVC", length = 80)
	public String getFilOvc() {
		return this.filOvc;
	}

	public void setFilOvc(String filOvc) {
		this.filOvc = filOvc;
	}

	@Column(name = "FIL_PACR", nullable = false, length = 1)
	public char getFilPacr() {
		return this.filPacr;
	}

	public void setFilPacr(char filPacr) {
		this.filPacr = filPacr;
	}

	@Column(name = "FIL_ICA", nullable = false, length = 1)
	public char getFilIca() {
		return this.filIca;
	}

	public void setFilIca(char filIca) {
		this.filIca = filIca;
	}

	@Column(name = "FIL_PDMC", nullable = false, length = 1)
	public char getFilPdmc() {
		return this.filPdmc;
	}

	public void setFilPdmc(char filPdmc) {
		this.filPdmc = filPdmc;
	}

	@Column(name = "FIL_LRAC", nullable = false, length = 1)
	public char getFilLrac() {
		return this.filLrac;
	}

	public void setFilLrac(char filLrac) {
		this.filLrac = filLrac;
	}

	@Column(name = "FIL_BCR", nullable = false, length = 1)
	public char getFilBcr() {
		return this.filBcr;
	}

	public void setFilBcr(char filBcr) {
		this.filBcr = filBcr;
	}

	@Column(name = "FIL_VCAG", nullable = false, length = 1)
	public char getFilVcag() {
		return this.filVcag;
	}

	public void setFilVcag(char filVcag) {
		this.filVcag = filVcag;
	}

	@Column(name = "FIL_BDEV", nullable = false, length = 1)
	public char getFilBdev() {
		return this.filBdev;
	}

	public void setFilBdev(char filBdev) {
		this.filBdev = filBdev;
	}

	@Column(name = "FIL_PAPV", nullable = false, length = 1)
	public char getFilPapv() {
		return this.filPapv;
	}

	public void setFilPapv(char filPapv) {
		this.filPapv = filPapv;
	}

	@Column(name = "FIL_ULCF", nullable = false, length = 1)
	public char getFilUlcf() {
		return this.filUlcf;
	}

	public void setFilUlcf(char filUlcf) {
		this.filUlcf = filUlcf;
	}

	@Column(name = "FIL_BCL", nullable = false, length = 1)
	public char getFilBcl() {
		return this.filBcl;
	}

	public void setFilBcl(char filBcl) {
		this.filBcl = filBcl;
	}

	@Column(name = "FIL_RFID", nullable = false, length = 1)
	public char getFilRfid() {
		return this.filRfid;
	}

	public void setFilRfid(char filRfid) {
		this.filRfid = filRfid;
	}

	@Column(name = "FIL_UAEC", nullable = false)
	public long getFilUaec() {
		return this.filUaec;
	}

	public void setFilUaec(long filUaec) {
		this.filUaec = filUaec;
	}

	@Column(name = "FIL_UTIE", nullable = false, length = 1)
	public char getFilUtie() {
		return this.filUtie;
	}

	public void setFilUtie(char filUtie) {
		this.filUtie = filUtie;
	}

	@Column(name = "FIL_BCLC", length = 0)
	public String getFilBclc() {
		return this.filBclc;
	}

	public void setFilBclc(String filBclc) {
		this.filBclc = filBclc;
	}

	@Column(name = "FIL_ORC", length = 80)
	public String getFilOrc() {
		return this.filOrc;
	}

	public void setFilOrc(String filOrc) {
		this.filOrc = filOrc;
	}

	@Column(name = "FIL_OBVC", length = 80)
	public String getFilObvc() {
		return this.filObvc;
	}

	public void setFilObvc(String filObvc) {
		this.filObvc = filObvc;
	}

	@Column(name = "FIL_PGCT", nullable = false, length = 1)
	public char getFilPgct() {
		return this.filPgct;
	}

	public void setFilPgct(char filPgct) {
		this.filPgct = filPgct;
	}

	@Column(name = "FIL_LPD", nullable = false, precision = 15)
	public BigDecimal getFilLpd() {
		return this.filLpd;
	}

	public void setFilLpd(BigDecimal filLpd) {
		this.filLpd = filLpd;
	}

	@Column(name = "FIL_OSST", nullable = false, length = 1)
	public char getFilOsst() {
		return this.filOsst;
	}

	public void setFilOsst(char filOsst) {
		this.filOsst = filOsst;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Abatimentosaldo> getAbatimentosaldos() {
//		return this.abatimentosaldos;
//	}
//
//	public void setAbatimentosaldos(Set<Abatimentosaldo> abatimentosaldos) {
//		this.abatimentosaldos = abatimentosaldos;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Caixa> getCaixas() {
//		return this.caixas;
//	}
//
//	public void setCaixas(Set<Caixa> caixas) {
//		this.caixas = caixas;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Fretebaixa> getFretebaixas() {
//		return this.fretebaixas;
//	}
//
//	public void setFretebaixas(Set<Fretebaixa> fretebaixas) {
//		this.fretebaixas = fretebaixas;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Contratocartao> getContratocartaos() {
//		return this.contratocartaos;
//	}
//
//	public void setContratocartaos(Set<Contratocartao> contratocartaos) {
//		this.contratocartaos = contratocartaos;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Pagar> getPagars() {
//		return this.pagars;
//	}
//
//	public void setPagars(Set<Pagar> pagars) {
//		this.pagars = pagars;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Frete> getFretes() {
//		return this.fretes;
//	}
//
//	public void setFretes(Set<Frete> fretes) {
//		this.fretes = fretes;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Movimentocolaboradorbaixa> getMovimentocolaboradorbaixas() {
//		return this.movimentocolaboradorbaixas;
//	}
//
//	public void setMovimentocolaboradorbaixas(
//			Set<Movimentocolaboradorbaixa> movimentocolaboradorbaixas) {
//		this.movimentocolaboradorbaixas = movimentocolaboradorbaixas;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Cheque> getCheques() {
//		return this.cheques;
//	}
//
//	public void setCheques(Set<Cheque> cheques) {
//		this.cheques = cheques;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Movimentacaoconta> getMovimentacaocontas() {
//		return this.movimentacaocontas;
//	}
//
//	public void setMovimentacaocontas(Set<Movimentacaoconta> movimentacaocontas) {
//		this.movimentacaocontas = movimentacaocontas;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Balanco> getBalancos() {
//		return this.balancos;
//	}
//
//	public void setBalancos(Set<Balanco> balancos) {
//		this.balancos = balancos;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Movimentocobranca> getMovimentocobrancas() {
//		return this.movimentocobrancas;
//	}
//
//	public void setMovimentocobrancas(Set<Movimentocobranca> movimentocobrancas) {
//		this.movimentocobrancas = movimentocobrancas;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Abatimento> getAbatimentos() {
//		return this.abatimentos;
//	}
//
//	public void setAbatimentos(Set<Abatimento> abatimentos) {
//		this.abatimentos = abatimentos;
//	}
//
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filialByFkPedFil")
	public Set<Pedido> getPedidosForFkPedFil() {
		return this.pedidosForFkPedFil;
	}

	public void setPedidosForFkPedFil(Set<Pedido> pedidosForFkPedFil) {
		this.pedidosForFkPedFil = pedidosForFkPedFil;
	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Chequebaixa> getChequebaixas() {
//		return this.chequebaixas;
//	}
//
//	public void setChequebaixas(Set<Chequebaixa> chequebaixas) {
//		this.chequebaixas = chequebaixas;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Localdeposito> getLocaldepositos() {
//		return this.localdepositos;
//	}
//
//	public void setLocaldepositos(Set<Localdeposito> localdepositos) {
//		this.localdepositos = localdepositos;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Minuta> getMinutas() {
//		return this.minutas;
//	}
//
//	public void setMinutas(Set<Minuta> minutas) {
//		this.minutas = minutas;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Receberbaixa> getReceberbaixas() {
//		return this.receberbaixas;
//	}
//
//	public void setReceberbaixas(Set<Receberbaixa> receberbaixas) {
//		this.receberbaixas = receberbaixas;
//	}
//
/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
	public Set<ClienteCartaoFidelidade> getClienteCartaoFidelidades() {
		return this.clienteCartaoFidelidades;
	}

	public void setClienteCartaoFidelidades(
			Set<ClienteCartaoFidelidade> clienteCartaoFidelidades) {
		this.clienteCartaoFidelidades = clienteCartaoFidelidades;
	}*/
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Colaboradorsaldo> getColaboradorsaldos() {
//		return this.colaboradorsaldos;
//	}
//
//	public void setColaboradorsaldos(Set<Colaboradorsaldo> colaboradorsaldos) {
//		this.colaboradorsaldos = colaboradorsaldos;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Enviocolaboradorfilial> getEnviocolaboradorfilials() {
//		return this.enviocolaboradorfilials;
//	}
//
//	public void setEnviocolaboradorfilials(
//			Set<Enviocolaboradorfilial> enviocolaboradorfilials) {
//		this.enviocolaboradorfilials = enviocolaboradorfilials;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Conserto> getConsertos() {
//		return this.consertos;
//	}
//
//	public void setConsertos(Set<Conserto> consertos) {
//		this.consertos = consertos;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Produtofilial> getProdutofilials() {
//		return this.produtofilials;
//	}
//
//	public void setProdutofilials(Set<Produtofilial> produtofilials) {
//		this.produtofilials = produtofilials;
//	}
//
	/*@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "CONTAEMPRESA", joinColumns = {
			@JoinColumn(name = "CTE_EMP", nullable = false, updatable = false),
			@JoinColumn(name = "CTE_FIL", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "CTE_CTA", nullable = false, updatable = false) })
	public Set<Conta> getContas() {
		return this.contas;
	}

	public void setContas(Set<Conta> contas) {
		this.contas = contas;
	}*/

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "USUARIOEMPRESA", joinColumns = {
			@JoinColumn(name = "UEM_EMP", nullable = false, updatable = false),
			@JoinColumn(name = "UEM_FIL", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "UEM_USU", nullable = false, updatable = false) })
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filialByFkPedFis")
	public Set<Pedido> getPedidosForFkPedFis() {
		return this.pedidosForFkPedFis;
	}

	public void setPedidosForFkPedFis(Set<Pedido> pedidosForFkPedFis) {
		this.pedidosForFkPedFis = pedidosForFkPedFis;
	}*/
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Receber> getRecebers() {
//		return this.recebers;
//	}
//
//	public void setRecebers(Set<Receber> recebers) {
//		this.recebers = recebers;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Operacaocomercial> getOperacaocomercials() {
//		return this.operacaocomercials;
//	}
//
//	public void setOperacaocomercials(Set<Operacaocomercial> operacaocomercials) {
//		this.operacaocomercials = operacaocomercials;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Carga> getCargas() {
//		return this.cargas;
//	}
//
//	public void setCargas(Set<Carga> cargas) {
//		this.cargas = cargas;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Conveniocobranca> getConveniocobrancas() {
//		return this.conveniocobrancas;
//	}
//
//	public void setConveniocobrancas(Set<Conveniocobranca> conveniocobrancas) {
//		this.conveniocobrancas = conveniocobrancas;
//	}
//
/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
	public Set<CustoFixo> getCustoFixos() {
		return this.custoFixos;
	}

	public void setCustoFixos(Set<CustoFixo> custoFixos) {
		this.custoFixos = custoFixos;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
	public Set<Representante> getRepresentantes() {
		return this.representantes;
	}

	public void setRepresentantes(Set<Representante> representantes) {
		this.representantes = representantes;
	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Chequebaixaacerto> getChequebaixaacertos() {
//		return this.chequebaixaacertos;
//	}
//
//	public void setChequebaixaacertos(Set<Chequebaixaacerto> chequebaixaacertos) {
//		this.chequebaixaacertos = chequebaixaacertos;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Pagarbaixa> getPagarbaixas() {
//		return this.pagarbaixas;
//	}
//
//	public void setPagarbaixas(Set<Pagarbaixa> pagarbaixas) {
//		this.pagarbaixas = pagarbaixas;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Prevenda> getPrevendas() {
//		return this.prevendas;
//	}
//
//	public void setPrevendas(Set<Prevenda> prevendas) {
//		this.prevendas = prevendas;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Contratoservico> getContratoservicos() {
//		return this.contratoservicos;
//	}
//
//	public void setContratoservicos(Set<Contratoservico> contratoservicos) {
//		this.contratoservicos = contratoservicos;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Fci> getFcis() {
//		return this.fcis;
//	}
//
//	public void setFcis(Set<Fci> fcis) {
//		this.fcis = fcis;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Pedidocompra> getPedidocompras() {
//		return this.pedidocompras;
//	}
//
//	public void setPedidocompras(Set<Pedidocompra> pedidocompras) {
//		this.pedidocompras = pedidocompras;
//	}
//
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
	public Set<Movimento> getMovimentos() {
		return this.movimentos;
	}

	public void setMovimentos(Set<Movimento> movimentos) {
		this.movimentos = movimentos;
	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filial")
//	public Set<Movimentocartao> getMovimentocartaos() {
//		return this.movimentocartaos;
//	}
//
//	public void setMovimentocartaos(Set<Movimentocartao> movimentocartaos) {
//		this.movimentocartaos = movimentocartaos;
//	}

	/*@Override
	public String toString() {
		return filApe;
	}
*/
}
