package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name = "GRADE")
public class Grade implements java.io.Serializable {

	private static final long serialVersionUID = 7659392694931159998L;
	private Integer grdCod;
	private String grdNom;
	private String grdG01;
	private String grdG02;
	private String grdG03;
	private String grdG04;
	private String grdG05;
	private String grdG06;
	private String grdG07;
	private String grdG08;
	private String grdG09;
	private String grdG10;
	private String grdG11;
	private String grdG12;
	private String grdG13;
	private String grdG14;
	private String grdSit;
	private Set<Modelo> modelos = new HashSet<Modelo>(0);
	//private Set<Pedidoproducaoitens> pedidoproducaoitenses = new HashSet<Pedidoproducaoitens>(0);
	//private Set<Pedidoreserva> pedidoreservas = new HashSet<Pedidoreserva>(0);
	//private Set<Ordemproducao> ordemproducaos = new HashSet<Ordemproducao>(0);
	//private Set<Estoqueminimo> estoqueminimos = new HashSet<Estoqueminimo>(0);
	//private Set<Pcpordemproducao> pcpordemproducaos = new HashSet<Pcpordemproducao>(0);
	//private Set<Pedidocompraitens> pedidocompraitenses = new HashSet<Pedidocompraitens>();
	private Set<Produto> produtos = new HashSet<Produto>(0);
	//private Set<Medidalavacao> medidalavacaos = new HashSet<Medidalavacao>(0);
	//private Set<Remessaproducaosimulacaoitens> remessaproducaosimulacaoitenses = new HashSet<Remessaproducaosimulacaoitens>(0);

	public Grade() {
	}

	public Grade(Integer grdCod, String grdNom, String grdSit) {
		this.grdCod = grdCod;
		this.grdNom = grdNom;
		this.grdSit = grdSit;
	}

	/*public Grade(Integer grdCod, String grdNom, String grdG01, String grdG02,
			String grdG03, String grdG04, String grdG05, String grdG06,
			String grdG07, String grdG08, String grdG09, String grdG10,
			String grdG11, String grdG12, String grdG13, String grdG14,
			String grdSit, Set<Modelo> modelos,
			Set<Pedidoproducaoitens> pedidoproducaoitenses,
			Set<Pedidoreserva> pedidoreservas,
			Set<Ordemproducao> ordemproducaos,
			Set<Estoqueminimo> estoqueminimos,
			Set<Pcpordemproducao> pcpordemproducaos,
			Set<Pedidocompraitens> pedidocompraitenses, Set<Produto> produtos,
			Set<Medidalavacao> medidalavacaos,
			Set<Remessaproducaosimulacaoitens> remessaproducaosimulacaoitenses) {
		this.grdCod = grdCod;
		this.grdNom = grdNom;
		this.grdG01 = grdG01;
		this.grdG02 = grdG02;
		this.grdG03 = grdG03;
		this.grdG04 = grdG04;
		this.grdG05 = grdG05;
		this.grdG06 = grdG06;
		this.grdG07 = grdG07;
		this.grdG08 = grdG08;
		this.grdG09 = grdG09;
		this.grdG10 = grdG10;
		this.grdG11 = grdG11;
		this.grdG12 = grdG12;
		this.grdG13 = grdG13;
		this.grdG14 = grdG14;
		this.grdSit = grdSit;
		this.modelos = modelos;
		this.pedidoproducaoitenses = pedidoproducaoitenses;
		this.pedidoreservas = pedidoreservas;
		this.ordemproducaos = ordemproducaos;
		this.estoqueminimos = estoqueminimos;
		this.pcpordemproducaos = pcpordemproducaos;
		this.pedidocompraitenses = pedidocompraitenses;
		this.produtos = produtos;
		this.medidalavacaos = medidalavacaos;
		this.remessaproducaosimulacaoitenses = remessaproducaosimulacaoitenses;
	}*/

	@Id
	@Column(name = "GRD_COD", unique = true, nullable = false)
	public Integer getGrdCod() {
		return this.grdCod;
	}

	public void setGrdCod(Integer grdCod) {
		this.grdCod = grdCod;
	}

	@Column(name = "GRD_NOM", nullable = false, length = 30)
	public String getGrdNom() {
		return this.grdNom;
	}

	public void setGrdNom(String grdNom) {
		this.grdNom = grdNom;
	}

	@Column(name = "GRD_G01", length = 3)
	public String getGrdG01() {
		return this.grdG01;
	}

	public void setGrdG01(String grdG01) {
		this.grdG01 = grdG01;
	}

	@Column(name = "GRD_G02", length = 3)
	public String getGrdG02() {
		return this.grdG02;
	}

	public void setGrdG02(String grdG02) {
		this.grdG02 = grdG02;
	}

	@Column(name = "GRD_G03", length = 3)
	public String getGrdG03() {
		return this.grdG03;
	}

	public void setGrdG03(String grdG03) {
		this.grdG03 = grdG03;
	}

	@Column(name = "GRD_G04", length = 3)
	public String getGrdG04() {
		return this.grdG04;
	}

	public void setGrdG04(String grdG04) {
		this.grdG04 = grdG04;
	}

	@Column(name = "GRD_G05", length = 3)
	public String getGrdG05() {
		return this.grdG05;
	}

	public void setGrdG05(String grdG05) {
		this.grdG05 = grdG05;
	}

	@Column(name = "GRD_G06", length = 3)
	public String getGrdG06() {
		return this.grdG06;
	}

	public void setGrdG06(String grdG06) {
		this.grdG06 = grdG06;
	}

	@Column(name = "GRD_G07", length = 3)
	public String getGrdG07() {
		return this.grdG07;
	}

	public void setGrdG07(String grdG07) {
		this.grdG07 = grdG07;
	}

	@Column(name = "GRD_G08", length = 3)
	public String getGrdG08() {
		return this.grdG08;
	}

	public void setGrdG08(String grdG08) {
		this.grdG08 = grdG08;
	}

	@Column(name = "GRD_G09", length = 3)
	public String getGrdG09() {
		return this.grdG09;
	}

	public void setGrdG09(String grdG09) {
		this.grdG09 = grdG09;
	}

	@Column(name = "GRD_G10", length = 3)
	public String getGrdG10() {
		return this.grdG10;
	}

	public void setGrdG10(String grdG10) {
		this.grdG10 = grdG10;
	}

	@Column(name = "GRD_G11", length = 3)
	public String getGrdG11() {
		return this.grdG11;
	}

	public void setGrdG11(String grdG11) {
		this.grdG11 = grdG11;
	}

	@Column(name = "GRD_G12", length = 3)
	public String getGrdG12() {
		return this.grdG12;
	}

	public void setGrdG12(String grdG12) {
		this.grdG12 = grdG12;
	}

	@Column(name = "GRD_G13", length = 3)
	public String getGrdG13() {
		return this.grdG13;
	}

	public void setGrdG13(String grdG13) {
		this.grdG13 = grdG13;
	}

	@Column(name = "GRD_G14", length = 3)
	public String getGrdG14() {
		return this.grdG14;
	}

	public void setGrdG14(String grdG14) {
		this.grdG14 = grdG14;
	}

	@Column(name = "GRD_SIT", nullable = false, length = 1)
	public String getGrdSit() {
		return this.grdSit;
	}

	public void setGrdSit(String grdSit) {
		this.grdSit = grdSit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<Modelo> getModelos() {
		return this.modelos;
	}

	public void setModelos(Set<Modelo> modelos) {
		this.modelos = modelos;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<Pedidoproducaoitens> getPedidoproducaoitenses() {
		return this.pedidoproducaoitenses;
	}

	public void setPedidoproducaoitenses(
			Set<Pedidoproducaoitens> pedidoproducaoitenses) {
		this.pedidoproducaoitenses = pedidoproducaoitenses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<Pedidoreserva> getPedidoreservas() {
		return this.pedidoreservas;
	}

	public void setPedidoreservas(Set<Pedidoreserva> pedidoreservas) {
		this.pedidoreservas = pedidoreservas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<Ordemproducao> getOrdemproducaos() {
		return this.ordemproducaos;
	}

	public void setOrdemproducaos(Set<Ordemproducao> ordemproducaos) {
		this.ordemproducaos = ordemproducaos;
	}*/

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<Estoqueminimo> getEstoqueminimos() {
		return this.estoqueminimos;
	}

	public void setEstoqueminimos(Set<Estoqueminimo> estoqueminimos) {
		this.estoqueminimos = estoqueminimos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<Pcpordemproducao> getPcpordemproducaos() {
		return this.pcpordemproducaos;
	}

	public void setPcpordemproducaos(Set<Pcpordemproducao> pcpordemproducaos) {
		this.pcpordemproducaos = pcpordemproducaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<Pedidocompraitens> getPedidocompraitenses() {
		return this.pedidocompraitenses;
	}

	public void setPedidocompraitenses(
			Set<Pedidocompraitens> pedidocompraitenses) {
		this.pedidocompraitenses = pedidocompraitenses;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<Medidalavacao> getMedidalavacaos() {
		return this.medidalavacaos;
	}

	public void setMedidalavacaos(Set<Medidalavacao> medidalavacaos) {
		this.medidalavacaos = medidalavacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grade")
	public Set<Remessaproducaosimulacaoitens> getRemessaproducaosimulacaoitenses() {
		return this.remessaproducaosimulacaoitenses;
	}

	public void setRemessaproducaosimulacaoitenses(
			Set<Remessaproducaosimulacaoitens> remessaproducaosimulacaoitenses) {
		this.remessaproducaosimulacaoitenses = remessaproducaosimulacaoitenses;
	}*/

}
