package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Guia generated by hbm2java
 */
@Entity
@Table(name = "GUIA")
public class Guia implements java.io.Serializable {

	private static final long serialVersionUID = 7258590664972494714L;
	private GuiaId id;
	private Municipio municipio;
	private String guiApe;
	private String guiRaz;
	private String guiNmf;
	private String guiTip;
	private String guiInf;
	private String guiIne;
	private String guiInm;
	private Date guiDti;
	private String guiEnd;
	private Integer guiNro;
	private String guiCpl;
	private String guiBai;
	private String guiCep;
	private String guiDdd;
	private String guiFon;
	private String guiDdf;
	private String guiFax;
	private String guiDdc;
	private String guiCel;
	private String guiEma;
	private String guiWeb;
	private String guiCon;
	private String guiCxp;
	private Integer guiRam;
	private char guiIcm;
	private String guiOb1;
	private String guiOb2;
	private String guiOb3;
	private Date guiDte;
	private Date guiDtf;

	public Guia() {
	}

	public Guia(GuiaId id, Municipio municipio, String guiRaz, String guiTip,
			String guiEnd, String guiCep, char guiIcm) {
		this.id = id;
		this.municipio = municipio;
		this.guiRaz = guiRaz;
		this.guiTip = guiTip;
		this.guiEnd = guiEnd;
		this.guiCep = guiCep;
		this.guiIcm = guiIcm;
	}

	public Guia(GuiaId id, Municipio municipio, String guiApe, String guiRaz,
			String guiNmf, String guiTip, String guiInf, String guiIne,
			String guiInm, Date guiDti, String guiEnd, Integer guiNro,
			String guiCpl, String guiBai, String guiCep, String guiDdd,
			String guiFon, String guiDdf, String guiFax, String guiDdc,
			String guiCel, String guiEma, String guiWeb, String guiCon,
			String guiCxp, Integer guiRam, char guiIcm, String guiOb1,
			String guiOb2, String guiOb3, Date guiDte, Date guiDtf) {
		this.id = id;
		this.municipio = municipio;
		this.guiApe = guiApe;
		this.guiRaz = guiRaz;
		this.guiNmf = guiNmf;
		this.guiTip = guiTip;
		this.guiInf = guiInf;
		this.guiIne = guiIne;
		this.guiInm = guiInm;
		this.guiDti = guiDti;
		this.guiEnd = guiEnd;
		this.guiNro = guiNro;
		this.guiCpl = guiCpl;
		this.guiBai = guiBai;
		this.guiCep = guiCep;
		this.guiDdd = guiDdd;
		this.guiFon = guiFon;
		this.guiDdf = guiDdf;
		this.guiFax = guiFax;
		this.guiDdc = guiDdc;
		this.guiCel = guiCel;
		this.guiEma = guiEma;
		this.guiWeb = guiWeb;
		this.guiCon = guiCon;
		this.guiCxp = guiCxp;
		this.guiRam = guiRam;
		this.guiIcm = guiIcm;
		this.guiOb1 = guiOb1;
		this.guiOb2 = guiOb2;
		this.guiOb3 = guiOb3;
		this.guiDte = guiDte;
		this.guiDtf = guiDtf;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "guiEmp", column = @Column(name = "GUI_EMP", nullable = false)),
			@AttributeOverride(name = "guiFil", column = @Column(name = "GUI_FIL", nullable = false)),
			@AttributeOverride(name = "guiCod", column = @Column(name = "GUI_COD", nullable = false)) })
	public GuiaId getId() {
		return this.id;
	}

	public void setId(GuiaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GUI_MUN", nullable = false)
	public Municipio getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(Municipio municipio) {
		this.municipio = municipio;
	}

	@Column(name = "GUI_APE", length = 15)
	public String getGuiApe() {
		return this.guiApe;
	}

	public void setGuiApe(String guiApe) {
		this.guiApe = guiApe;
	}

	@Column(name = "GUI_RAZ", nullable = false, length = 50)
	public String getGuiRaz() {
		return this.guiRaz;
	}

	public void setGuiRaz(String guiRaz) {
		this.guiRaz = guiRaz;
	}

	@Column(name = "GUI_NMF", length = 50)
	public String getGuiNmf() {
		return this.guiNmf;
	}

	public void setGuiNmf(String guiNmf) {
		this.guiNmf = guiNmf;
	}

	@Column(name = "GUI_TIP", nullable = false, length = 4)
	public String getGuiTip() {
		return this.guiTip;
	}

	public void setGuiTip(String guiTip) {
		this.guiTip = guiTip;
	}

	@Column(name = "GUI_INF", length = 14)
	public String getGuiInf() {
		return this.guiInf;
	}

	public void setGuiInf(String guiInf) {
		this.guiInf = guiInf;
	}

	@Column(name = "GUI_INE", length = 20)
	public String getGuiIne() {
		return this.guiIne;
	}

	public void setGuiIne(String guiIne) {
		this.guiIne = guiIne;
	}

	@Column(name = "GUI_INM", length = 20)
	public String getGuiInm() {
		return this.guiInm;
	}

	public void setGuiInm(String guiInm) {
		this.guiInm = guiInm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GUI_DTI", length = 10)
	public Date getGuiDti() {
		return this.guiDti;
	}

	public void setGuiDti(Date guiDti) {
		this.guiDti = guiDti;
	}

	@Column(name = "GUI_END", nullable = false, length = 40)
	public String getGuiEnd() {
		return this.guiEnd;
	}

	public void setGuiEnd(String guiEnd) {
		this.guiEnd = guiEnd;
	}

	@Column(name = "GUI_NRO")
	public Integer getGuiNro() {
		return this.guiNro;
	}

	public void setGuiNro(Integer guiNro) {
		this.guiNro = guiNro;
	}

	@Column(name = "GUI_CPL", length = 20)
	public String getGuiCpl() {
		return this.guiCpl;
	}

	public void setGuiCpl(String guiCpl) {
		this.guiCpl = guiCpl;
	}

	@Column(name = "GUI_BAI", length = 20)
	public String getGuiBai() {
		return this.guiBai;
	}

	public void setGuiBai(String guiBai) {
		this.guiBai = guiBai;
	}

	@Column(name = "GUI_CEP", nullable = false, length = 8)
	public String getGuiCep() {
		return this.guiCep;
	}

	public void setGuiCep(String guiCep) {
		this.guiCep = guiCep;
	}

	@Column(name = "GUI_DDD", length = 2)
	public String getGuiDdd() {
		return this.guiDdd;
	}

	public void setGuiDdd(String guiDdd) {
		this.guiDdd = guiDdd;
	}

	@Column(name = "GUI_FON", length = 8)
	public String getGuiFon() {
		return this.guiFon;
	}

	public void setGuiFon(String guiFon) {
		this.guiFon = guiFon;
	}

	@Column(name = "GUI_DDF", length = 2)
	public String getGuiDdf() {
		return this.guiDdf;
	}

	public void setGuiDdf(String guiDdf) {
		this.guiDdf = guiDdf;
	}

	@Column(name = "GUI_FAX", length = 8)
	public String getGuiFax() {
		return this.guiFax;
	}

	public void setGuiFax(String guiFax) {
		this.guiFax = guiFax;
	}

	@Column(name = "GUI_DDC", length = 2)
	public String getGuiDdc() {
		return this.guiDdc;
	}

	public void setGuiDdc(String guiDdc) {
		this.guiDdc = guiDdc;
	}

	@Column(name = "GUI_CEL", length = 9)
	public String getGuiCel() {
		return this.guiCel;
	}

	public void setGuiCel(String guiCel) {
		this.guiCel = guiCel;
	}

	@Column(name = "GUI_EMA", length = 50)
	public String getGuiEma() {
		return this.guiEma;
	}

	public void setGuiEma(String guiEma) {
		this.guiEma = guiEma;
	}

	@Column(name = "GUI_WEB", length = 50)
	public String getGuiWeb() {
		return this.guiWeb;
	}

	public void setGuiWeb(String guiWeb) {
		this.guiWeb = guiWeb;
	}

	@Column(name = "GUI_CON", length = 50)
	public String getGuiCon() {
		return this.guiCon;
	}

	public void setGuiCon(String guiCon) {
		this.guiCon = guiCon;
	}

	@Column(name = "GUI_CXP", length = 15)
	public String getGuiCxp() {
		return this.guiCxp;
	}

	public void setGuiCxp(String guiCxp) {
		this.guiCxp = guiCxp;
	}

	@Column(name = "GUI_RAM")
	public Integer getGuiRam() {
		return this.guiRam;
	}

	public void setGuiRam(Integer guiRam) {
		this.guiRam = guiRam;
	}

	@Column(name = "GUI_ICM", nullable = false, length = 1)
	public char getGuiIcm() {
		return this.guiIcm;
	}

	public void setGuiIcm(char guiIcm) {
		this.guiIcm = guiIcm;
	}

	@Column(name = "GUI_OB1", length = 40)
	public String getGuiOb1() {
		return this.guiOb1;
	}

	public void setGuiOb1(String guiOb1) {
		this.guiOb1 = guiOb1;
	}

	@Column(name = "GUI_OB2", length = 40)
	public String getGuiOb2() {
		return this.guiOb2;
	}

	public void setGuiOb2(String guiOb2) {
		this.guiOb2 = guiOb2;
	}

	@Column(name = "GUI_OB3", length = 40)
	public String getGuiOb3() {
		return this.guiOb3;
	}

	public void setGuiOb3(String guiOb3) {
		this.guiOb3 = guiOb3;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GUI_DTE", length = 10)
	public Date getGuiDte() {
		return this.guiDte;
	}

	public void setGuiDte(Date guiDte) {
		this.guiDte = guiDte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GUI_DTF", length = 10)
	public Date getGuiDtf() {
		return this.guiDtf;
	}

	public void setGuiDtf(Date guiDtf) {
		this.guiDtf = guiDtf;
	}

}
