package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name = "MARCA")
public class Marca implements java.io.Serializable {

	private static final long serialVersionUID = 6754821133323690649L;
	private Integer marCod;
	private String marNom;
	private String marCom;
	private String marTcm;
	private BigDecimal marPer;
	private String marDcm;
	private BigDecimal marIcm;
	private BigDecimal marIpc;
	private BigDecimal marFre;
	private BigDecimal marOut;
	private BigDecimal marSpn;
	private BigDecimal marCmv;
	private BigDecimal marCmg;
	private BigDecimal marMgl;
	private BigDecimal marDpf;
	//private Set<Estoqueminimo> estoqueminimos = new HashSet<Estoqueminimo>(0);
	private Set<Produto> produtos = new HashSet<Produto>(0);
	private Set<Modelo> modelos = new HashSet<Modelo>(0);

	public Marca() {
	}

	public Marca(Integer marCod, String marNom, String marCom, String marTcm,
			BigDecimal marPer, String marDcm, BigDecimal marIcm,
			BigDecimal marIpc, BigDecimal marFre, BigDecimal marOut,
			BigDecimal marSpn, BigDecimal marCmv, BigDecimal marCmg,
			BigDecimal marMgl, BigDecimal marDpf) {
		this.marCod = marCod;
		this.marNom = marNom;
		this.marCom = marCom;
		this.marTcm = marTcm;
		this.marPer = marPer;
		this.marDcm = marDcm;
		this.marIcm = marIcm;
		this.marIpc = marIpc;
		this.marFre = marFre;
		this.marOut = marOut;
		this.marSpn = marSpn;
		this.marCmv = marCmv;
		this.marCmg = marCmg;
		this.marMgl = marMgl;
		this.marDpf = marDpf;
	}

	/* public Marca(Integer marCod, String marNom, String marCom, String marTcm,
			BigDecimal marPer, String marDcm, BigDecimal marIcm,
			BigDecimal marIpc, BigDecimal marFre, BigDecimal marOut,
			BigDecimal marSpn, BigDecimal marCmv, BigDecimal marCmg,
			BigDecimal marMgl, BigDecimal marDpf,
			Set<Estoqueminimo> estoqueminimos, Set<Produto> produtos,
			Set<Modelo> modelos) {
		this.marCod = marCod;
		this.marNom = marNom;
		this.marCom = marCom;
		this.marTcm = marTcm;
		this.marPer = marPer;
		this.marDcm = marDcm;
		this.marIcm = marIcm;
		this.marIpc = marIpc;
		this.marFre = marFre;
		this.marOut = marOut;
		this.marSpn = marSpn;
		this.marCmv = marCmv;
		this.marCmg = marCmg;
		this.marMgl = marMgl;
		this.marDpf = marDpf;
		this.estoqueminimos = estoqueminimos;
		this.produtos = produtos;
		this.modelos = modelos;
	} */

	@Id
	@Column(name = "MAR_COD", unique = true, nullable = false)
	public Integer getMarCod() {
		return this.marCod;
	}

	public void setMarCod(Integer marCod) {
		this.marCod = marCod;
	}

	@Column(name = "MAR_NOM", nullable = false, length = 30)
	public String getMarNom() {
		return this.marNom;
	}

	public void setMarNom(String marNom) {
		this.marNom = marNom;
	}

	@Column(name = "MAR_COM", nullable = false, length = 1)
	public String getMarCom() {
		return this.marCom;
	}

	public void setMarCom(String marCom) {
		this.marCom = marCom;
	}

	@Column(name = "MAR_TCM", nullable = false, length = 1)
	public String getMarTcm() {
		return this.marTcm;
	}

	public void setMarTcm(String marTcm) {
		this.marTcm = marTcm;
	}

	@Column(name = "MAR_PER", nullable = false, precision = 6)
	public BigDecimal getMarPer() {
		return this.marPer;
	}

	public void setMarPer(BigDecimal marPer) {
		this.marPer = marPer;
	}

	@Column(name = "MAR_DCM", nullable = false, length = 1)
	public String getMarDcm() {
		return this.marDcm;
	}

	public void setMarDcm(String marDcm) {
		this.marDcm = marDcm;
	}

	@Column(name = "MAR_ICM", nullable = false, precision = 6)
	public BigDecimal getMarIcm() {
		return this.marIcm;
	}

	public void setMarIcm(BigDecimal marIcm) {
		this.marIcm = marIcm;
	}

	@Column(name = "MAR_IPC", nullable = false, precision = 6)
	public BigDecimal getMarIpc() {
		return this.marIpc;
	}

	public void setMarIpc(BigDecimal marIpc) {
		this.marIpc = marIpc;
	}

	@Column(name = "MAR_FRE", nullable = false, precision = 6)
	public BigDecimal getMarFre() {
		return this.marFre;
	}

	public void setMarFre(BigDecimal marFre) {
		this.marFre = marFre;
	}

	@Column(name = "MAR_OUT", nullable = false, precision = 6)
	public BigDecimal getMarOut() {
		return this.marOut;
	}

	public void setMarOut(BigDecimal marOut) {
		this.marOut = marOut;
	}

	@Column(name = "MAR_SPN", nullable = false, precision = 6)
	public BigDecimal getMarSpn() {
		return this.marSpn;
	}

	public void setMarSpn(BigDecimal marSpn) {
		this.marSpn = marSpn;
	}

	@Column(name = "MAR_CMV", nullable = false, precision = 6)
	public BigDecimal getMarCmv() {
		return this.marCmv;
	}

	public void setMarCmv(BigDecimal marCmv) {
		this.marCmv = marCmv;
	}

	@Column(name = "MAR_CMG", nullable = false, precision = 6)
	public BigDecimal getMarCmg() {
		return this.marCmg;
	}

	public void setMarCmg(BigDecimal marCmg) {
		this.marCmg = marCmg;
	}

	@Column(name = "MAR_MGL", nullable = false, precision = 6)
	public BigDecimal getMarMgl() {
		return this.marMgl;
	}

	public void setMarMgl(BigDecimal marMgl) {
		this.marMgl = marMgl;
	}

	@Column(name = "MAR_DPF", nullable = false, precision = 6)
	public BigDecimal getMarDpf() {
		return this.marDpf;
	}

	public void setMarDpf(BigDecimal marDpf) {
		this.marDpf = marDpf;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public Set<Estoqueminimo> getEstoqueminimos() {
		return this.estoqueminimos;
	}

	public void setEstoqueminimos(Set<Estoqueminimo> estoqueminimos) {
		this.estoqueminimos = estoqueminimos;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public Set<Modelo> getModelos() {
		return this.modelos;
	}

	public void setModelos(Set<Modelo> modelos) {
		this.modelos = modelos;
	}

}
