package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ModeloId generated by hbm2java
 */
@Embeddable
public class ModeloId implements java.io.Serializable {

	private static final long serialVersionUID = 218502203935861822L;
	private Integer mdlEmp;
	private Integer mdlCod;

	public ModeloId() {
	}

	public ModeloId(Integer mdlEmp, Integer mdlCod) {
		this.mdlEmp = mdlEmp;
		this.mdlCod = mdlCod;
	}

	@Column(name = "MDL_EMP", nullable = false)
	public Integer getMdlEmp() {
		return this.mdlEmp;
	}

	public void setMdlEmp(Integer mdlEmp) {
		this.mdlEmp = mdlEmp;
	}

	@Column(name = "MDL_COD", nullable = false)
	public Integer getMdlCod() {
		return this.mdlCod;
	}

	public void setMdlCod(Integer mdlCod) {
		this.mdlCod = mdlCod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ModeloId))
			return false;
		ModeloId castOther = (ModeloId) other;

		return (this.getMdlEmp() == castOther.getMdlEmp())
				&& (this.getMdlCod() == castOther.getMdlCod());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getMdlEmp();
		result = 37 * result + this.getMdlCod();
		return result;
	}

}
