package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Motorista generated by hbm2java
 */
@Entity
@Table(name = "MOTORISTA")
public class Motorista implements java.io.Serializable {
	
	private static final long serialVersionUID = -3242376795323711078L;
	private int mtrCol;
//	private Colaborador colaborador;
	private Date mtrDti;
	private Date mtrDtf;
	private String mtrOb1;
	private String mtrOb2;
	private String mtrOb3;
	private Set<Veiculo> veiculos = new HashSet<Veiculo>(0);

	public Motorista() {
	}

	/*public Motorista(Colaborador colaborador) {
		this.colaborador = colaborador;
	}

	public Motorista(Colaborador colaborador, Date mtrDti, Date mtrDtf,
			String mtrOb1, String mtrOb2, String mtrOb3, Set<Veiculo> veiculos) {
		this.colaborador = colaborador;
		this.mtrDti = mtrDti;
		this.mtrDtf = mtrDtf;
		this.mtrOb1 = mtrOb1;
		this.mtrOb2 = mtrOb2;
		this.mtrOb3 = mtrOb3;
		this.veiculos = veiculos;
	}*/

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "colaborador"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "MTR_COL", unique = true, nullable = false)
	public int getMtrCol() {
		return this.mtrCol;
	}

	public void setMtrCol(int mtrCol) {
		this.mtrCol = mtrCol;
	}

	/*@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Colaborador getColaborador() {
		return this.colaborador;
	}

	public void setColaborador(Colaborador colaborador) {
		this.colaborador = colaborador;
	}*/

	@Temporal(TemporalType.DATE)
	@Column(name = "MTR_DTI", length = 10)
	public Date getMtrDti() {
		return this.mtrDti;
	}

	public void setMtrDti(Date mtrDti) {
		this.mtrDti = mtrDti;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MTR_DTF", length = 10)
	public Date getMtrDtf() {
		return this.mtrDtf;
	}

	public void setMtrDtf(Date mtrDtf) {
		this.mtrDtf = mtrDtf;
	}

	@Column(name = "MTR_OB1", length = 40)
	public String getMtrOb1() {
		return this.mtrOb1;
	}

	public void setMtrOb1(String mtrOb1) {
		this.mtrOb1 = mtrOb1;
	}

	@Column(name = "MTR_OB2", length = 40)
	public String getMtrOb2() {
		return this.mtrOb2;
	}

	public void setMtrOb2(String mtrOb2) {
		this.mtrOb2 = mtrOb2;
	}

	@Column(name = "MTR_OB3", length = 40)
	public String getMtrOb3() {
		return this.mtrOb3;
	}

	public void setMtrOb3(String mtrOb3) {
		this.mtrOb3 = mtrOb3;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motorista")
	public Set<Veiculo> getVeiculos() {
		return this.veiculos;
	}

	public void setVeiculos(Set<Veiculo> veiculos) {
		this.veiculos = veiculos;
	}

}
