package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MovimentoTipo generated by hbm2java
 */
@Entity
@Table(name = "MOVIMENTOTIPO")
public class MovimentoTipo implements java.io.Serializable {
	
	private static final long serialVersionUID = -5935318228638443275L;
	private int motCod;
	private String motNom;
	private char motSit;
	private Set<Movimento> movimentos = new HashSet<Movimento>(0);
//	private Set<Operacaocomercial> operacaocomercials = new HashSet<Operacaocomercial>(0);

	@Id
	@Column(name = "MOT_COD", unique = true, nullable = false)
	public int getMotCod() {
		return this.motCod;
	}

	public void setMotCod(int motCod) {
		this.motCod = motCod;
	}

	@Column(name = "MOT_NOM", nullable = false, length = 40)
	public String getMotNom() {
		return this.motNom;
	}

	public void setMotNom(String motNom) {
		this.motNom = motNom;
	}

	@Column(name = "MOT_SIT", nullable = false, length = 1)
	public char getMotSit() {
		return this.motSit;
	}

	public void setMotSit(char motSit) {
		this.motSit = motSit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimentoTipo")
	public Set<Movimento> getMovimentos() {
		return this.movimentos;
	}

	public void setMovimentos(Set<Movimento> movimentos) {
		this.movimentos = movimentos;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimentotipo")
//	public Set<Operacaocomercial> getOperacaocomercials() {
//		return this.operacaocomercials;
//	}
//
//	public void setOperacaocomercials(Set<Operacaocomercial> operacaocomercials) {
//		this.operacaocomercials = operacaocomercials;
//	}

}
