package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "PAIS")
public class Pais implements java.io.Serializable {

	private static final long serialVersionUID = 9059266958207082394L;
	private Integer paiCod;
	private String paiNom;
	private Integer paiIbg;
	private Integer paiSis;
	private String paiSgi;

	public Pais() {
	}

	public Pais(Integer paiCod, String paiNom) {
		this.paiCod = paiCod;
		this.paiNom = paiNom;
	}

	public Pais(Integer paiCod, String paiNom, Integer paiIbg, Integer paiSis,
			String paiSgi) {
		this.paiCod = paiCod;
		this.paiNom = paiNom;
		this.paiIbg = paiIbg;
		this.paiSis = paiSis;
		this.paiSgi = paiSgi;
	}

	@Id
	@Column(name = "PAI_COD", unique = true, nullable = false)
	public Integer getPaiCod() {
		return this.paiCod;
	}

	public void setPaiCod(Integer paiCod) {
		this.paiCod = paiCod;
	}

	@Column(name = "PAI_NOM", nullable = false, length = 40)
	public String getPaiNom() {
		return this.paiNom;
	}

	public void setPaiNom(String paiNom) {
		this.paiNom = paiNom;
	}

	@Column(name = "PAI_IBG")
	public Integer getPaiIbg() {
		return this.paiIbg;
	}

	public void setPaiIbg(Integer paiIbg) {
		this.paiIbg = paiIbg;
	}

	@Column(name = "PAI_SIS")
	public Integer getPaiSis() {
		return this.paiSis;
	}

	public void setPaiSis(Integer paiSis) {
		this.paiSis = paiSis;
	}

	@Column(name = "PAI_SGI", length = 2)
	public String getPaiSgi() {
		return this.paiSgi;
	}

	public void setPaiSgi(String paiSgi) {
		this.paiSgi = paiSgi;
	}

}
