package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
 
 

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "PEDIDO", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PED_EMP", "PED_SEQ" }))
public class Pedido implements java.io.Serializable {

	private static final long serialVersionUID = -9014026749239413344L;
	
	private Integer pedCod;
	//private Banco banco;
	private CategoriaFiscal categoriaFiscal;
	private ColaboradorEmpresa colaboradorEmpresa;
	private CondicaoPagto condicaoPagtoByPedCpa;
	private CondicaoPagto condicaoPagtoByPedCdp;
	private EmpresaPauta empresaPauta;
	private Filial filialByFkPedFil;
	
	private Integer pedCol;
	private Integer pedRep; 
	private Integer pedEpt; 
	private String pedCgf; 
	
	//private Filial filialByFkPedFis;
	private FormaPagto formaPagtoByPedFpa;
	private FormaPagto formaPagtoByPedFpc;
	private Representante representante;
//	private Transportador transportador;
	private Usuario usuario;
	private Integer pedSeq;
	private Integer pedTpe;
	private Integer pedOri;
	private Integer pedInt;
	private Integer pedTco;
	private BigDecimal pedPcr;
	private Date pedDte;
	private BigDecimal pedQtd;
	private BigDecimal pedQtp;
	private BigDecimal pedQtr;
	private BigDecimal pedQtc;
	private BigDecimal pedQte;
	private Date pedDtp;
	private String pedDoc;
	private BigDecimal pedTop;
	private BigDecimal pedTot;
	private BigDecimal pedTod;
	private BigDecimal pedPac;
	private BigDecimal pedAcr;
	private BigDecimal pedPou;
	private BigDecimal pedOut;
	private BigDecimal pedPde;
	private BigDecimal pedDes;
	private BigDecimal pedPda;
	private BigDecimal pedDad;
	private BigDecimal pedPds;
	private BigDecimal pedDsp;
	private String pedDpr;
	private String pedSfr;
	private BigDecimal pedPoa;
	private String pedNfi;
	private String pedCba;
	private String pedOb1;
	private String pedOb2;
	private String pedOb3;
	private String pedOp1;
	private String pedOf1;
	private String pedMca;
	private Date pedUdi;
	private String pedSts;
	private String pedOst;
	private Integer pedCvc;
	private Integer pedCtc;
	private Integer pedBan;
	private Set<PedidoItens> pedidoItenses = new HashSet<PedidoItens>(0);
//	private Set<Empacotamento> empacotamentos = new HashSet<Empacotamento>(0);
//	private Set<PedidoCancela> pedidoCancelas = new HashSet<PedidoCancela>(0);

	public Pedido() {
	}
 
	public Pedido(Integer pedCod, CategoriaFiscal categoriaFiscal,
			ColaboradorEmpresa colaboradorEmpresa, EmpresaPauta empresaPauta,
			Filial filialByFkPedFil, Filial filialByFkPedFis,
			Representante representante, 
			//Transportador transportador,
			Usuario usuario, Integer pedSeq, Integer pedTpe, Integer pedOri,
			BigDecimal pedPcr, Date pedDte, BigDecimal pedQtd,
			BigDecimal pedQtp, BigDecimal pedQtr, BigDecimal pedQtc,
			BigDecimal pedQte, BigDecimal pedTop, BigDecimal pedTot,
			BigDecimal pedTod, BigDecimal pedPac, BigDecimal pedAcr,
			BigDecimal pedPou, BigDecimal pedOut, BigDecimal pedPde,
			BigDecimal pedDes, BigDecimal pedPda, BigDecimal pedDad,
			BigDecimal pedPds, BigDecimal pedDsp, String pedDpr, String pedSfr,
			BigDecimal pedPoa, String pedNfi, String pedCba, Date pedUdi,
			String pedSts) {
		this.pedCod = pedCod;
		this.categoriaFiscal = categoriaFiscal;
		this.colaboradorEmpresa = colaboradorEmpresa;
		this.empresaPauta = empresaPauta;
		this.filialByFkPedFil = filialByFkPedFil;
	//	this.filialByFkPedFis = filialByFkPedFis;
		this.representante = representante;
		//this.transportador = transportador;
		this.usuario = usuario;
		this.pedSeq = pedSeq;
		this.pedTpe = pedTpe;
		this.pedOri = pedOri;
		this.pedPcr = pedPcr;
		this.pedDte = pedDte;
		this.pedQtd = pedQtd;
		this.pedQtp = pedQtp;
		this.pedQtr = pedQtr;
		this.pedQtc = pedQtc;
		this.pedQte = pedQte;
		this.pedTop = pedTop;
		this.pedTot = pedTot;
		this.pedTod = pedTod;
		this.pedPac = pedPac;
		this.pedAcr = pedAcr;
		this.pedPou = pedPou;
		this.pedOut = pedOut;
		this.pedPde = pedPde;
		this.pedDes = pedDes;
		this.pedPda = pedPda;
		this.pedDad = pedDad;
		this.pedPds = pedPds;
		this.pedDsp = pedDsp;
		this.pedDpr = pedDpr;
		this.pedSfr = pedSfr;
		this.pedPoa = pedPoa;
		this.pedNfi = pedNfi;
		this.pedCba = pedCba;
		this.pedUdi = pedUdi;
		this.pedSts = pedSts;
	}

	public Pedido(Integer pedCod, Banco banco, CategoriaFiscal categoriaFiscal,
			ColaboradorEmpresa colaboradorEmpresa,
			CondicaoPagto condicaoPagtoByPedCpa,
			CondicaoPagto condicaoPagtoByPedCdp, EmpresaPauta empresaPauta,
			Filial filialByFkPedFil, Filial filialByFkPedFis,
			FormaPagto formaPagtoByPedFpa, FormaPagto formaPagtoByPedFpc,
			Representante representante, 
			//Transportador transportador,
			Usuario usuario, Integer pedSeq, Integer pedTpe, Integer pedOri,
			Integer pedInt, Integer pedTco, BigDecimal pedPcr, Date pedDte,
			BigDecimal pedQtd, BigDecimal pedQtp, BigDecimal pedQtr,
			BigDecimal pedQtc, BigDecimal pedQte, Date pedDtp, String pedDoc,
			BigDecimal pedTop, BigDecimal pedTot, BigDecimal pedTod,
			BigDecimal pedPac, BigDecimal pedAcr, BigDecimal pedPou,
			BigDecimal pedOut, BigDecimal pedPde, BigDecimal pedDes,
			BigDecimal pedPda, BigDecimal pedDad, BigDecimal pedPds,
			BigDecimal pedDsp, String pedDpr, String pedSfr, BigDecimal pedPoa,
			String pedNfi, String pedCba, String pedOb1, String pedOb2,
			String pedOb3, String pedOp1, String pedOf1, String pedMca,
			Date pedUdi, String pedSts, String pedOst, Integer pedCvc,
			Integer pedCtc, Integer pedBan,
			Set<PedidoItens> pedidoItenses
			//Set<Empacotamento> empacotamentos, 
			//Set<PedidoCancela> pedidoCancelas
			) {
		this.pedCod = pedCod;
		//this.banco = banco;
		this.categoriaFiscal = categoriaFiscal;
		this.colaboradorEmpresa = colaboradorEmpresa;
		this.condicaoPagtoByPedCpa = condicaoPagtoByPedCpa;
		this.condicaoPagtoByPedCdp = condicaoPagtoByPedCdp;
		this.empresaPauta = empresaPauta;
		this.filialByFkPedFil = filialByFkPedFil;
		//this.filialByFkPedFis = filialByFkPedFis;
		this.formaPagtoByPedFpa = formaPagtoByPedFpa;
		this.formaPagtoByPedFpc = formaPagtoByPedFpc;
		this.representante = representante;
		//this.transportador = transportador;
		this.usuario = usuario;
		this.pedSeq = pedSeq;
		this.pedTpe = pedTpe;
		this.pedOri = pedOri;
		this.pedInt = pedInt;
		this.pedTco = pedTco;
		this.pedPcr = pedPcr;
		this.pedDte = pedDte;
		this.pedQtd = pedQtd;
		this.pedQtp = pedQtp;
		this.pedQtr = pedQtr;
		this.pedQtc = pedQtc;
		this.pedQte = pedQte;
		this.pedDtp = pedDtp;
		this.pedDoc = pedDoc;
		this.pedTop = pedTop;
		this.pedTot = pedTot;
		this.pedTod = pedTod;
		this.pedPac = pedPac;
		this.pedAcr = pedAcr;
		this.pedPou = pedPou;
		this.pedOut = pedOut;
		this.pedPde = pedPde;
		this.pedDes = pedDes;
		this.pedPda = pedPda;
		this.pedDad = pedDad;
		this.pedPds = pedPds;
		this.pedDsp = pedDsp;
		this.pedDpr = pedDpr;
		this.pedSfr = pedSfr;
		this.pedPoa = pedPoa;
		this.pedNfi = pedNfi;
		this.pedCba = pedCba;
		this.pedOb1 = pedOb1;
		this.pedOb2 = pedOb2;
		this.pedOb3 = pedOb3;
		this.pedOp1 = pedOp1;
		this.pedOf1 = pedOf1;
		this.pedMca = pedMca;
		this.pedUdi = pedUdi;
		this.pedSts = pedSts;
		this.pedOst = pedOst;
		this.pedCvc = pedCvc;
		this.pedCtc = pedCtc;
		this.pedBan = pedBan;
		this.pedidoItenses = pedidoItenses;
		//this.empacotamentos = empacotamentos;
		//this.pedidoCancelas = pedidoCancelas;
	} 

	@Id
	@Column(name = "PED_COD", unique = true, nullable = false)
	public Integer getPedCod() {
		return this.pedCod;
	}

	public void setPedCod(Integer pedCod) {
		this.pedCod = pedCod;
	}

/*	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PED_BCO")
	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}*/

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PED_EMP", referencedColumnName = "CGF_EMP" ,nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PED_CGF", referencedColumnName = "CGF_COD" ,nullable = false, insertable = false, updatable = false) })
	public CategoriaFiscal getCategoriaFiscal() {
		return this.categoriaFiscal;
	}

	public void setCategoriaFiscal(CategoriaFiscal categoriaFiscal) {
		this.categoriaFiscal = categoriaFiscal;
	}


  	@ManyToOne(fetch = FetchType.LAZY)
  	@JoinColumns({
		    @JoinColumn(name = "PED_EMP", referencedColumnName = "COE_EMP",   nullable = false , insertable = false, updatable = false),
			@JoinColumn(name = "PED_COL", referencedColumnName = "COE_COL",   nullable = false , insertable = false, updatable = false ) })
	public ColaboradorEmpresa getColaboradorEmpresa() {
		return this.colaboradorEmpresa;
	}

	public void setColaboradorEmpresa(ColaboradorEmpresa colaboradorEmpresa) {
		this.colaboradorEmpresa = colaboradorEmpresa;
	} 

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PED_CPA")
	public CondicaoPagto getCondicaoPagtoByPedCpa() {
		return this.condicaoPagtoByPedCpa;
	}

	public void setCondicaoPagtoByPedCpa(CondicaoPagto condicaoPagtoByPedCpa) {
		this.condicaoPagtoByPedCpa = condicaoPagtoByPedCpa;
	} 

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PED_CDP")
	public CondicaoPagto getCondicaoPagtoByPedCdp() {
		return this.condicaoPagtoByPedCdp;
	}

	public void setCondicaoPagtoByPedCdp(CondicaoPagto condicaoPagtoByPedCdp) {
		this.condicaoPagtoByPedCdp = condicaoPagtoByPedCdp;
	} 

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PED_EMP", referencedColumnName = "EPT_EMP", nullable = false,  insertable = false, updatable = false),
			@JoinColumn(name = "PED_EPT", referencedColumnName = "EPT_PAT", nullable = false,  insertable = false, updatable = false) })
	public EmpresaPauta getEmpresaPauta() {
		return this.empresaPauta;
	}

	public void setEmpresaPauta(EmpresaPauta empresaPauta) {
		this.empresaPauta = empresaPauta;
	}

	@ManyToOne(fetch = FetchType.LAZY ) 
	@JoinColumns({
			@JoinColumn(name = "PED_EMP", referencedColumnName = "FIL_EMP" ),
			@JoinColumn(name = "PED_FIL", referencedColumnName = "FIL_COD" ) })

	public Filial getFilialByFkPedFil() {
		return this.filialByFkPedFil;
	}
	public void setFilialByFkPedFil(Filial filialByFkPedFil) {
		this.filialByFkPedFil = filialByFkPedFil;
	}
	
/*	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PED_EMP", referencedColumnName = "FIL_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PED_FIS", referencedColumnName = "FIL_COD",   insertable = false, updatable = false) })
	public Filial getFilialByFkPedFis() {
		return this.filialByFkPedFis;
	}

	public void setFilialByFkPedFis(Filial filialByFkPedFis) {
		this.filialByFkPedFis = filialByFkPedFis;
	}*/

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PED_FPA")
	public FormaPagto getFormaPagtoByPedFpa() {
		return this.formaPagtoByPedFpa;
	}

	public void setFormaPagtoByPedFpa(FormaPagto formaPagtoByPedFpa) {
		this.formaPagtoByPedFpa = formaPagtoByPedFpa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PED_FPC")
	public FormaPagto getFormaPagtoByPedFpc() {
		return this.formaPagtoByPedFpc;
	}

	public void setFormaPagtoByPedFpc(FormaPagto formaPagtoByPedFpc) {
		this.formaPagtoByPedFpc = formaPagtoByPedFpc;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PED_EMP", referencedColumnName = "REP_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PED_REP", referencedColumnName = "REP_COL", nullable = false, insertable = false, updatable = false) }) 
	public Representante getRepresentante() {
		return this.representante;
	}
	
	public void setRepresentante(Representante representante) {
		this.representante = representante;
	}

/*	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PED_EMP", referencedColumnName = "TRA_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PED_TRA", referencedColumnName = "TRA_COL", insertable = false, updatable = false) })
	public Transportador getTransportador() {
		return this.transportador;
	}

	public void setTransportador(Transportador transportador) {
		this.transportador = transportador;
	}*/

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PED_USU", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "PED_SEQ", nullable = false)
	public Integer getPedSeq() {
		return this.pedSeq;
	}

	public void setPedSeq(Integer pedSeq) {
		this.pedSeq = pedSeq;
	}

	@Column(name = "PED_TPE", nullable = false)
	public Integer getPedTpe() {
		return this.pedTpe;
	}

	public void setPedTpe(Integer pedTpe) {
		this.pedTpe = pedTpe;
	}

	@Column(name = "PED_ORI", nullable = false)
	public Integer getPedOri() {
		return this.pedOri;
	}

	public void setPedOri(Integer pedOri) {
		this.pedOri = pedOri;
	}

	@Column(name = "PED_INT")
	public Integer getPedInt() {
		return this.pedInt;
	}

	public void setPedInt(Integer pedInt) {
		this.pedInt = pedInt;
	}

	@Column(name = "PED_TCO")
	public Integer getPedTco() {
		return this.pedTco;
	}

	public void setPedTco(Integer pedTco) {
		this.pedTco = pedTco;
	}

	@Column(name = "PED_PCR", nullable = false, precision = 6)
	public BigDecimal getPedPcr() {
		return this.pedPcr;
	}

	public void setPedPcr(BigDecimal pedPcr) {
		this.pedPcr = pedPcr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PED_DTE", nullable = false, length = 10)
	public Date getPedDte() {
		return this.pedDte;
	}

	public void setPedDte(Date pedDte) {
		this.pedDte = pedDte;
	}

	@Column(name = "PED_QTD", nullable = false, precision = 18, scale = 5)
	public BigDecimal getPedQtd() {
		return this.pedQtd;
	}

	public void setPedQtd(BigDecimal pedQtd) {
		this.pedQtd = pedQtd;
	}

	@Column(name = "PED_QTP", nullable = false, precision = 18, scale = 5)
	public BigDecimal getPedQtp() {
		return this.pedQtp;
	}

	public void setPedQtp(BigDecimal pedQtp) {
		this.pedQtp = pedQtp;
	}

	@Column(name = "PED_QTR", nullable = false, precision = 18, scale = 5)
	public BigDecimal getPedQtr() {
		return this.pedQtr;
	}

	public void setPedQtr(BigDecimal pedQtr) {
		this.pedQtr = pedQtr;
	}

	@Column(name = "PED_QTC", nullable = false, precision = 18, scale = 5)
	public BigDecimal getPedQtc() {
		return this.pedQtc;
	}

	public void setPedQtc(BigDecimal pedQtc) {
		this.pedQtc = pedQtc;
	}

	@Column(name = "PED_QTE", nullable = false, precision = 18, scale = 5)
	public BigDecimal getPedQte() {
		return this.pedQte;
	}

	public void setPedQte(BigDecimal pedQte) {
		this.pedQte = pedQte;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PED_DTP", length = 10)
	public Date getPedDtp() {
		return this.pedDtp;
	}

	public void setPedDtp(Date pedDtp) {
		this.pedDtp = pedDtp;
	}

	@Column(name = "PED_DOC", length = 10)
	public String getPedDoc() {
		return this.pedDoc;
	}

	public void setPedDoc(String pedDoc) {
		this.pedDoc = pedDoc;
	}

	@Column(name = "PED_TOP", nullable = false, precision = 14)
	public BigDecimal getPedTop() {
		return this.pedTop;
	}

	public void setPedTop(BigDecimal pedTop) {
		this.pedTop = pedTop;
	}

	@Column(name = "PED_TOT", nullable = false, precision = 14)
	public BigDecimal getPedTot() {
		return this.pedTot;
	}

	public void setPedTot(BigDecimal pedTot) {
		this.pedTot = pedTot;
	}

	@Column(name = "PED_TOD", nullable = false, precision = 14)
	public BigDecimal getPedTod() {
		return this.pedTod;
	}

	public void setPedTod(BigDecimal pedTod) {
		this.pedTod = pedTod;
	}

	@Column(name = "PED_PAC", nullable = false, precision = 8, scale = 4)
	public BigDecimal getPedPac() {
		return this.pedPac;
	}

	public void setPedPac(BigDecimal pedPac) {
		this.pedPac = pedPac;
	}

	@Column(name = "PED_ACR", nullable = false, precision = 14)
	public BigDecimal getPedAcr() {
		return this.pedAcr;
	}

	public void setPedAcr(BigDecimal pedAcr) {
		this.pedAcr = pedAcr;
	}

	@Column(name = "PED_POU", nullable = false, precision = 8, scale = 4)
	public BigDecimal getPedPou() {
		return this.pedPou;
	}

	public void setPedPou(BigDecimal pedPou) {
		this.pedPou = pedPou;
	}

	@Column(name = "PED_OUT", nullable = false, precision = 14)
	public BigDecimal getPedOut() {
		return this.pedOut;
	}

	public void setPedOut(BigDecimal pedOut) {
		this.pedOut = pedOut;
	}

	@Column(name = "PED_PDE", nullable = false, precision = 8, scale = 4)
	public BigDecimal getPedPde() {
		return this.pedPde;
	}

	public void setPedPde(BigDecimal pedPde) {
		this.pedPde = pedPde;
	}

	@Column(name = "PED_DES", nullable = false, precision = 14)
	public BigDecimal getPedDes() {
		return this.pedDes;
	}

	public void setPedDes(BigDecimal pedDes) {
		this.pedDes = pedDes;
	}

	@Column(name = "PED_PDA", nullable = false, precision = 8, scale = 4)
	public BigDecimal getPedPda() {
		return this.pedPda;
	}

	public void setPedPda(BigDecimal pedPda) {
		this.pedPda = pedPda;
	}

	@Column(name = "PED_DAD", nullable = false, precision = 14)
	public BigDecimal getPedDad() {
		return this.pedDad;
	}

	public void setPedDad(BigDecimal pedDad) {
		this.pedDad = pedDad;
	}

	@Column(name = "PED_PDS", nullable = false, precision = 8, scale = 4)
	public BigDecimal getPedPds() {
		return this.pedPds;
	}

	public void setPedPds(BigDecimal pedPds) {
		this.pedPds = pedPds;
	}

	@Column(name = "PED_DSP", nullable = false, precision = 14)
	public BigDecimal getPedDsp() {
		return this.pedDsp;
	}

	public void setPedDsp(BigDecimal pedDsp) {
		this.pedDsp = pedDsp;
	}

	@Column(name = "PED_DPR", nullable = false, length = 1)
	public String getPedDpr() {
		return this.pedDpr;
	}

	public void setPedDpr(String pedDpr) {
		this.pedDpr = pedDpr;
	}

	@Column(name = "PED_SFR", nullable = false, length = 1)
	public String getPedSfr() {
		return this.pedSfr;
	}

	public void setPedSfr(String pedSfr) {
		this.pedSfr = pedSfr;
	}

	@Column(name = "PED_POA", nullable = false, precision = 6)
	public BigDecimal getPedPoa() {
		return this.pedPoa;
	}

	public void setPedPoa(BigDecimal pedPoa) {
		this.pedPoa = pedPoa;
	}

	@Column(name = "PED_NFI", nullable = false, length = 1)
	public String getPedNfi() {
		return this.pedNfi;
	}

	public void setPedNfi(String pedNfi) {
		this.pedNfi = pedNfi;
	}

	@Column(name = "PED_CBA", nullable = false, length = 1)
	public String getPedCba() {
		return this.pedCba;
	}

	public void setPedCba(String pedCba) {
		this.pedCba = pedCba;
	}

	@Column(name = "PED_OB1", length = 40)
	public String getPedOb1() {
		return this.pedOb1;
	}

	public void setPedOb1(String pedOb1) {
		this.pedOb1 = pedOb1;
	}

	@Column(name = "PED_OB2", length = 40)
	public String getPedOb2() {
		return this.pedOb2;
	}

	public void setPedOb2(String pedOb2) {
		this.pedOb2 = pedOb2;
	}

	@Column(name = "PED_OB3", length = 40)
	public String getPedOb3() {
		return this.pedOb3;
	}

	public void setPedOb3(String pedOb3) {
		this.pedOb3 = pedOb3;
	}

	@Column(name = "PED_OP1", length = 60)
	public String getPedOp1() {
		return this.pedOp1;
	}

	public void setPedOp1(String pedOp1) {
		this.pedOp1 = pedOp1;
	}

	@Column(name = "PED_OF1", length = 60)
	public String getPedOf1() {
		return this.pedOf1;
	}

	public void setPedOf1(String pedOf1) {
		this.pedOf1 = pedOf1;
	}

	@Column(name = "PED_MCA", length = 15)
	public String getPedMca() {
		return this.pedMca;
	}

	public void setPedMca(String pedMca) {
		this.pedMca = pedMca;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PED_UDI", nullable = false, length = 19)
	public Date getPedUdi() {
		return this.pedUdi;
	}

	public void setPedUdi(Date pedUdi) {
		this.pedUdi = pedUdi;
	}

	@Column(name = "PED_STS", nullable = false, length = 1)
	public String getPedSts() {
		return this.pedSts;
	}

	public void setPedSts(String pedSts) {
		this.pedSts = pedSts;
	}

	@Column(name = "PED_OST", length = 60)
	public String getPedOst() {
		return this.pedOst;
	}

	public void setPedOst(String pedOst) {
		this.pedOst = pedOst;
	}

	@Column(name = "PED_CVC")
	public Integer getPedCvc() {
		return this.pedCvc;
	}

	public void setPedCvc(Integer pedCvc) {
		this.pedCvc = pedCvc;
	}

	@Column(name = "PED_CTC")
	public Integer getPedCtc() {
		return this.pedCtc;
	}

	public void setPedCtc(Integer pedCtc) {
		this.pedCtc = pedCtc;
	}

	@Column(name = "PED_BAN")
	public Integer getPedBan() {
		return this.pedBan;
	}

	public void setPedBan(Integer pedBan) {
		this.pedBan = pedBan;
	}

	

 	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<PedidoItens> getPedidoItenses() {
		return this.pedidoItenses;
	}

	public void setPedidoItenses(Set<PedidoItens> pedidoItenses) {
		this.pedidoItenses = pedidoItenses;
	}

	@Column(name = "PED_COL", nullable = false)
	public Integer getPedCol() {
		return pedCol;
	}

	public void setPedCol(Integer pedCol) {
		this.pedCol = pedCol;
	}
	
	@Column(name = "PED_REP", nullable = false)
	public Integer getPedRep() {
		return pedRep;
	}

	public void setPedRep(Integer pedRep) {
		this.pedRep = pedRep;
	}

	@Column(name = "PED_EPT", nullable = false)
	public Integer getPedEpt() {
		return pedEpt;
	}

	public void setPedEpt(Integer pedEpt) {
		this.pedEpt = pedEpt;
	}

	@Column(name = "PED_CGF", nullable = false)
	public String getPedCgf() {
		return pedCgf;
	}

	public void setPedCgf(String pedCgf) {
		this.pedCgf = pedCgf;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<Empacotamento> getEmpacotamentos() {
		return this.empacotamentos;
	}

	public void setEmpacotamentos(Set<Empacotamento> empacotamentos) {
		this.empacotamentos = empacotamentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<PedidoCancela> getPedidoCancelas() {
		return this.pedidoCancelas;
	}

	public void setPedidoCancelas(Set<PedidoCancela> pedidoCancelas) {
		this.pedidoCancelas = pedidoCancelas;
	}*/

	

	
	
}

