package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PlanoDeContasId generated by hbm2java
 */
@Embeddable
public class PlanoDeContasId implements java.io.Serializable {

	
	private static final long serialVersionUID = 795566802343216303L;
	private int plaEmp;
	private int plaCod;

	public PlanoDeContasId() {
	}

	public PlanoDeContasId(int plaEmp, int plaCod) {
		this.plaEmp = plaEmp;
		this.plaCod = plaCod;
	}

	@Column(name = "PLA_EMP", nullable = false)
	public int getPlaEmp() {
		return this.plaEmp;
	}

	public void setPlaEmp(int plaEmp) {
		this.plaEmp = plaEmp;
	}

	@Column(name = "PLA_COD", nullable = false)
	public int getPlaCod() {
		return this.plaCod;
	}

	public void setPlaCod(int plaCod) {
		this.plaCod = plaCod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlanoDeContasId))
			return false;
		PlanoDeContasId castOther = (PlanoDeContasId) other;

		return (this.getPlaEmp() == castOther.getPlaEmp())
				&& (this.getPlaCod() == castOther.getPlaCod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPlaEmp();
		result = 37 * result + this.getPlaCod();
		return result;
	}

}
