package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdutoLocal generated by hbm2java
 */
@Entity
@Table(name = "PRODUTOLOCAL")
public class ProdutoLocal implements java.io.Serializable {

	private static final long serialVersionUID = -6998527667851334061L;
	private ProdutoLocalId id;
	private LocalDeposito localDeposito;
	private Produto produto;
	private Integer prlGrd;
	private Integer prlQ01;
	private Integer prlQ02;
	private Integer prlQ03;
	private Integer prlQ04;
	private Integer prlQ05;
	private Integer prlQ06;
	private Integer prlQ07;
	private Integer prlQ08;
	private Integer prlQ09;
	private Integer prlQ10;
	private Integer prlQ11;
	private Integer prlQ12;
	private Integer prlQ13;
	private Integer prlQ14;
	private BigDecimal prlQtp;
	private BigDecimal prlQtt;
	private Integer prlSld;
	private Integer prlR01;
	private Integer prlR02;
	private Integer prlR03;
	private Integer prlR04;
	private Integer prlR05;
	private Integer prlR06;
	private Integer prlR07;
	private Integer prlR08;
	private Integer prlR09;
	private Integer prlR10;
	private Integer prlR11;
	private Integer prlR12;
	private Integer prlR13;
	private Integer prlR14;
	private BigDecimal prlQtr;
	//private Set<Ordemproducao> ordemproducaos = new HashSet<Ordemproducao>(0);
	//private Set<Pedidoreserva> pedidoreservas = new HashSet<Pedidoreserva>(0);
	private Set<MovimentoItens> movimentoItenses = new HashSet<MovimentoItens>(0);

	public ProdutoLocal() {
	}

	public ProdutoLocal(ProdutoLocalId id, LocalDeposito localDeposito,
			Produto produto, Integer prlQ01, Integer prlQ02, Integer prlQ03, Integer prlQ04,
			Integer prlQ05, Integer prlQ06, Integer prlQ07, Integer prlQ08, Integer prlQ09,
			Integer prlQ10, Integer prlQ11, Integer prlQ12, Integer prlQ13, Integer prlQ14,
			BigDecimal prlQtp, BigDecimal prlQtt, Integer prlR01, Integer prlR02,
			Integer prlR03, Integer prlR04, Integer prlR05, Integer prlR06, Integer prlR07,
			Integer prlR08, Integer prlR09, Integer prlR10, Integer prlR11, Integer prlR12,
			Integer prlR13, Integer prlR14, BigDecimal prlQtr) {
		this.id = id;
		this.localDeposito = localDeposito;
		this.produto = produto;
		this.prlQ01 = prlQ01;
		this.prlQ02 = prlQ02;
		this.prlQ03 = prlQ03;
		this.prlQ04 = prlQ04;
		this.prlQ05 = prlQ05;
		this.prlQ06 = prlQ06;
		this.prlQ07 = prlQ07;
		this.prlQ08 = prlQ08;
		this.prlQ09 = prlQ09;
		this.prlQ10 = prlQ10;
		this.prlQ11 = prlQ11;
		this.prlQ12 = prlQ12;
		this.prlQ13 = prlQ13;
		this.prlQ14 = prlQ14;
		this.prlQtp = prlQtp;
		this.prlQtt = prlQtt;
		this.prlR01 = prlR01;
		this.prlR02 = prlR02;
		this.prlR03 = prlR03;
		this.prlR04 = prlR04;
		this.prlR05 = prlR05;
		this.prlR06 = prlR06;
		this.prlR07 = prlR07;
		this.prlR08 = prlR08;
		this.prlR09 = prlR09;
		this.prlR10 = prlR10;
		this.prlR11 = prlR11;
		this.prlR12 = prlR12;
		this.prlR13 = prlR13;
		this.prlR14 = prlR14;
		this.prlQtr = prlQtr;
	}

	/* public ProdutoLocal(ProdutoLocalId id, LocalDeposito localDeposito,
			Produto produto, Integer prlGrd, Integer prlQ01, Integer prlQ02,
			Integer prlQ03, Integer prlQ04, Integer prlQ05, Integer prlQ06, Integer prlQ07,
			Integer prlQ08, Integer prlQ09, Integer prlQ10, Integer prlQ11, Integer prlQ12,
			Integer prlQ13, Integer prlQ14, BigDecimal prlQtp, BigDecimal prlQtt,
			BigDecimal prlSld, Integer prlR01, Integer prlR02, Integer prlR03, Integer prlR04,
			Integer prlR05, Integer prlR06, Integer prlR07, Integer prlR08, Integer prlR09,
			Integer prlR10, Integer prlR11, Integer prlR12, Integer prlR13, Integer prlR14,
			BigDecimal prlQtr, Set<Ordemproducao> ordemproducaos,
			Set<Pedidoreserva> pedidoreservas,
			Set<MovimentoItens> movimentoItenses) {
		this.id = id;
		this.localDeposito = localDeposito;
		this.produto = produto;
		this.prlGrd = prlGrd;
		this.prlQ01 = prlQ01;
		this.prlQ02 = prlQ02;
		this.prlQ03 = prlQ03;
		this.prlQ04 = prlQ04;
		this.prlQ05 = prlQ05;
		this.prlQ06 = prlQ06;
		this.prlQ07 = prlQ07;
		this.prlQ08 = prlQ08;
		this.prlQ09 = prlQ09;
		this.prlQ10 = prlQ10;
		this.prlQ11 = prlQ11;
		this.prlQ12 = prlQ12;
		this.prlQ13 = prlQ13;
		this.prlQ14 = prlQ14;
		this.prlQtp = prlQtp;
		this.prlQtt = prlQtt;
		this.prlSld = prlSld;
		this.prlR01 = prlR01;
		this.prlR02 = prlR02;
		this.prlR03 = prlR03;
		this.prlR04 = prlR04;
		this.prlR05 = prlR05;
		this.prlR06 = prlR06;
		this.prlR07 = prlR07;
		this.prlR08 = prlR08;
		this.prlR09 = prlR09;
		this.prlR10 = prlR10;
		this.prlR11 = prlR11;
		this.prlR12 = prlR12;
		this.prlR13 = prlR13;
		this.prlR14 = prlR14;
		this.prlQtr = prlQtr;
		this.ordemproducaos = ordemproducaos;
		this.pedidoreservas = pedidoreservas;
		this.movimentoItenses = movimentoItenses;
	} */

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "prlEmp", column = @Column(name = "PRL_EMP", nullable = false)),
			@AttributeOverride(name = "prlPro", column = @Column(name = "PRL_PRO", nullable = false)),
			@AttributeOverride(name = "prlFil", column = @Column(name = "PRL_FIL", nullable = false)),
			@AttributeOverride(name = "prlLcd", column = @Column(name = "PRL_LCD", nullable = false)) })
	public ProdutoLocalId getId() {
		return this.id;
	}

	public void setId(ProdutoLocalId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PRL_EMP", referencedColumnName = "LCD_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PRL_FIL", referencedColumnName = "LCD_FIL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PRL_LCD", referencedColumnName = "LCD_COD", nullable = false, insertable = false, updatable = false) })
	public LocalDeposito getLocalDeposito() {
		return this.localDeposito;
	}

	public void setLocalDeposito(LocalDeposito localDeposito) {
		this.localDeposito = localDeposito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PRL_EMP", referencedColumnName = "PRO_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PRL_PRO", referencedColumnName = "PRO_COD", nullable = false, insertable = false, updatable = false) })
	public Produto getProduto() {
		return this.produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	@Column(name = "PRL_GRD")
	public Integer getPrlGrd() {
		return this.prlGrd;
	}

	public void setPrlGrd(Integer prlGrd) {
		this.prlGrd = prlGrd;
	}

	@Column(name = "PRL_Q01", nullable = false)
	public Integer getPrlQ01() {
		return this.prlQ01;
	}

	public void setPrlQ01(Integer prlQ01) {
		this.prlQ01 = prlQ01;
	}

	@Column(name = "PRL_Q02", nullable = false)
	public Integer getPrlQ02() {
		return this.prlQ02;
	}

	public void setPrlQ02(Integer prlQ02) {
		this.prlQ02 = prlQ02;
	}

	@Column(name = "PRL_Q03", nullable = false)
	public Integer getPrlQ03() {
		return this.prlQ03;
	}

	public void setPrlQ03(Integer prlQ03) {
		this.prlQ03 = prlQ03;
	}

	@Column(name = "PRL_Q04", nullable = false)
	public Integer getPrlQ04() {
		return this.prlQ04;
	}

	public void setPrlQ04(Integer prlQ04) {
		this.prlQ04 = prlQ04;
	}

	@Column(name = "PRL_Q05", nullable = false)
	public Integer getPrlQ05() {
		return this.prlQ05;
	}

	public void setPrlQ05(Integer prlQ05) {
		this.prlQ05 = prlQ05;
	}

	@Column(name = "PRL_Q06", nullable = false)
	public Integer getPrlQ06() {
		return this.prlQ06;
	}

	public void setPrlQ06(Integer prlQ06) {
		this.prlQ06 = prlQ06;
	}

	@Column(name = "PRL_Q07", nullable = false)
	public Integer getPrlQ07() {
		return this.prlQ07;
	}

	public void setPrlQ07(Integer prlQ07) {
		this.prlQ07 = prlQ07;
	}

	@Column(name = "PRL_Q08", nullable = false)
	public Integer getPrlQ08() {
		return this.prlQ08;
	}

	public void setPrlQ08(Integer prlQ08) {
		this.prlQ08 = prlQ08;
	}

	@Column(name = "PRL_Q09", nullable = false)
	public Integer getPrlQ09() {
		return this.prlQ09;
	}

	public void setPrlQ09(Integer prlQ09) {
		this.prlQ09 = prlQ09;
	}

	@Column(name = "PRL_Q10", nullable = false)
	public Integer getPrlQ10() {
		return this.prlQ10;
	}

	public void setPrlQ10(Integer prlQ10) {
		this.prlQ10 = prlQ10;
	}

	@Column(name = "PRL_Q11", nullable = false)
	public Integer getPrlQ11() {
		return this.prlQ11;
	}

	public void setPrlQ11(Integer prlQ11) {
		this.prlQ11 = prlQ11;
	}

	@Column(name = "PRL_Q12", nullable = false)
	public Integer getPrlQ12() {
		return this.prlQ12;
	}

	public void setPrlQ12(Integer prlQ12) {
		this.prlQ12 = prlQ12;
	}

	@Column(name = "PRL_Q13", nullable = false)
	public Integer getPrlQ13() {
		return this.prlQ13;
	}

	public void setPrlQ13(Integer prlQ13) {
		this.prlQ13 = prlQ13;
	}

	@Column(name = "PRL_Q14", nullable = false)
	public Integer getPrlQ14() {
		return this.prlQ14;
	}

	public void setPrlQ14(Integer prlQ14) {
		this.prlQ14 = prlQ14;
	}

	@Column(name = "PRL_QTP", nullable = false, precision = 18, scale = 5)
	public BigDecimal getPrlQtp() {
		return this.prlQtp;
	}

	public void setPrlQtp(BigDecimal prlQtp) {
		this.prlQtp = prlQtp;
	}

	@Column(name = "PRL_QTT", nullable = false, precision = 18, scale = 5)
	public BigDecimal getPrlQtt() {
		return this.prlQtt;
	}

	public void setPrlQtt(BigDecimal prlQtt) {
		this.prlQtt = prlQtt;
	}

	//@Column(name = "PRL_SLD", precision = 0, scale = 5)
	@Column(name = "PRL_SLD")
	public Integer getPrlSld() {
		return this.prlSld;
	}

	public void setPrlSld(Integer prlSld) {
		this.prlSld = prlSld;
	}

	@Column(name = "PRL_R01", nullable = false)
	public Integer getPrlR01() {
		return this.prlR01;
	}

	public void setPrlR01(Integer prlR01) {
		this.prlR01 = prlR01;
	}

	@Column(name = "PRL_R02", nullable = false)
	public Integer getPrlR02() {
		return this.prlR02;
	}

	public void setPrlR02(Integer prlR02) {
		this.prlR02 = prlR02;
	}

	@Column(name = "PRL_R03", nullable = false)
	public Integer getPrlR03() {
		return this.prlR03;
	}

	public void setPrlR03(Integer prlR03) {
		this.prlR03 = prlR03;
	}

	@Column(name = "PRL_R04", nullable = false)
	public Integer getPrlR04() {
		return this.prlR04;
	}

	public void setPrlR04(Integer prlR04) {
		this.prlR04 = prlR04;
	}

	@Column(name = "PRL_R05", nullable = false)
	public Integer getPrlR05() {
		return this.prlR05;
	}

	public void setPrlR05(Integer prlR05) {
		this.prlR05 = prlR05;
	}

	@Column(name = "PRL_R06", nullable = false)
	public Integer getPrlR06() {
		return this.prlR06;
	}

	public void setPrlR06(Integer prlR06) {
		this.prlR06 = prlR06;
	}

	@Column(name = "PRL_R07", nullable = false)
	public Integer getPrlR07() {
		return this.prlR07;
	}

	public void setPrlR07(Integer prlR07) {
		this.prlR07 = prlR07;
	}

	@Column(name = "PRL_R08", nullable = false)
	public Integer getPrlR08() {
		return this.prlR08;
	}

	public void setPrlR08(Integer prlR08) {
		this.prlR08 = prlR08;
	}

	@Column(name = "PRL_R09", nullable = false)
	public Integer getPrlR09() {
		return this.prlR09;
	}

	public void setPrlR09(Integer prlR09) {
		this.prlR09 = prlR09;
	}

	@Column(name = "PRL_R10", nullable = false)
	public Integer getPrlR10() {
		return this.prlR10;
	}

	public void setPrlR10(Integer prlR10) {
		this.prlR10 = prlR10;
	}

	@Column(name = "PRL_R11", nullable = false)
	public Integer getPrlR11() {
		return this.prlR11;
	}

	public void setPrlR11(Integer prlR11) {
		this.prlR11 = prlR11;
	}

	@Column(name = "PRL_R12", nullable = false)
	public Integer getPrlR12() {
		return this.prlR12;
	}

	public void setPrlR12(Integer prlR12) {
		this.prlR12 = prlR12;
	}

	@Column(name = "PRL_R13", nullable = false)
	public Integer getPrlR13() {
		return this.prlR13;
	}

	public void setPrlR13(Integer prlR13) {
		this.prlR13 = prlR13;
	}

	@Column(name = "PRL_R14", nullable = false)
	public Integer getPrlR14() {
		return this.prlR14;
	}

	public void setPrlR14(Integer prlR14) {
		this.prlR14 = prlR14;
	}

	@Column(name = "PRL_QTR", nullable = false, precision = 18, scale = 5)
	public BigDecimal getPrlQtr() {
		return this.prlQtr;
	}

	public void setPrlQtr(BigDecimal prlQtr) {
		this.prlQtr = prlQtr;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "produtoLocal")
	public Set<Ordemproducao> getOrdemproducaos() {
		return this.ordemproducaos;
	}

	public void setOrdemproducaos(Set<Ordemproducao> ordemproducaos) {
		this.ordemproducaos = ordemproducaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produtoLocal")
	public Set<Pedidoreserva> getPedidoreservas() {
		return this.pedidoreservas;
	}

	public void setPedidoreservas(Set<Pedidoreserva> pedidoreservas) {
		this.pedidoreservas = pedidoreservas;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produtoLocal")
	public Set<MovimentoItens> getMovimentoItenses() {
		return this.movimentoItenses;
	}

	public void setMovimentoItenses(Set<MovimentoItens> movimentoItenses) {
		this.movimentoItenses = movimentoItenses;
	}

}
