package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PropSistemaId generated by hbm2java
 */
@Embeddable
public class PropSistemaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7170325539730821565L;
	private String prsGcvp;
	private String prsGcvn;
	private String prsGcse;
	private String prsGcoi;
	private String prsGcli;
	private String prsGmoi;
	private String prsGfoi;
	private String prsGrei;
	private String prsGrpi;
	private String prsGfui;
	private String prsGtri;
	private String prsGpri;
	private String prsGcri;
	private String prsFrco;
	private String prsFrch;
	private String prsFpco;
	private String prsFcco;
	private Integer prsEtnu;
	private String prsEtod;
	private String prsEtdh;
	private String prsEtdu;
	private String prsEqsc;
	private String prsEfsc;
	private String prsEqkk;
	private String prsAfpn;
	private String prsAfpt;
	private String prsAfan;
	private String prsAfat;
	private String prsGlic;
	private String prsEtfu;
	private String prsAcce;
	private String prsAace;
	private String prsGisc;
	private String prsGlbc;
	private Integer prsGvum;
	private String prsAfnp;
	private Integer prsGskn;
	private String prsGicf;
	private Integer prsGccf;
	private String prsGlbr;
	private String prsGftp;
	private String prsGftu;
	private String prsGfts;
	private Integer prsGfdi;
	private Integer prsGfch;
	private Integer prsGfct;
	private Integer prsGfcr;
	private Integer prsGfcs;
	private Integer prsGffl;
	private String prsGicv;
	private String prsGsge;
	private String prsApca;
	private String prsAaca;
	private String prsApvs;
	private String prsApvm;
	private String prsGipf;
	private String prsGops;
	private String prsChqb;
	private String prsChqa;
	private String prsChqc;
	private String prsChqn;
	private String prsGlvc;
	private String prsGidc;
	private String prsAfve;
	private String prsCtb;
	private String prsGacp;
	private Integer prsGmct;
	private String prsAgna;
	private String prsChql;
	private String prsIrmc;
	private String prsImec;
	private String prsIprc;
	private String prsIvec;
	private String prsIpvc;
	private String prsIpv;
	private String prsIchc;
	private String prsFccc;
	private String prsGfpr;
	private String prsAfvn;
	private String prsAdrp;
	private String prsFtpp;
	private Integer prsGncq;
	private String prsDtri;
	private String prsGsde;
	private String prsVfp;
	private String prsFeda;
	private String prsFstp;
	private String prsTvf;
	private Integer prsMdc;
	private String prsIsvv;
	private String prsTclp;
	private String prsMft;
	private String prsInpm;
	private String prsPbmr;
	private Integer prsCdcp;
	private String prsFpct;
	private String prsGccs;
	private Integer prsAdan;
	private Integer prsAfen;
	private Integer prsAamb;
	private String prsApnf;
	private Integer prsItec;
	private String prsArnf;
	private Integer prsQtcd;
	private String prsFacp;
	private String prsCpsp;
	private String prsCcmt;
	private String prsTcct;
	private BigDecimal prsSict;
	private String prsPsvo;
	private String prsPaqr;
	private String prsEssp;
	private String prsCcrm;
	private Integer prsCtam;
	private String prsHism;
	private String prsFglc;
	private String prsFgcj;
	private Integer prsGrd;
	private String prsIpo;
	private Integer prsTioc;
	private Integer prsGccv;
	private Integer prsStce;
	private Integer prsFolf;
	private String prsOccd;
	private String prsRdpv;
	private String prsEsm;
	private String prsEctd;
	private String prsIomc;
	private String prsIcac;
	private String prsFimp;
	private String prsFncs;
	private String prsFips;
	private Integer prsFpts;
	private Integer prsFuas;
	private Integer prsLzt;
	private String prsTcb;
	private String prsEbt;
	private String prsUapc;
	private String prsGpcg;
	private String prsFdsb;
	private String prsCocm;
	private String prsCvb;
	private String prsAmpr;
	private String prsFabd;
	private String prsEcn;
	private String prsBapf;
	private String prsAjpcp;
	private String prsPpdt;
	private String prsDcm;
	private String prsEemt;
	private String prsFdpr;
	private String prsPeca;
	private String prsEeac;
	private Date prsDuec;
	private String prsGcrp;
	private String prsUnd;
	private String prsLvpr;
	private BigDecimal prsDlpn;
	private BigDecimal prsDlpm;
	private String prsLvqp;
	private BigDecimal prsDlqn;
	private BigDecimal prsDlqm;
	private String prsOpsg;
	private String prsPimc;
	private String prsGnfq;
	private String prsOipc;
	private String prsGscl;
	private String prsAgst;
	private String prsVnfe;
	private String prsAmpi;
	private BigDecimal prsVmci;
	private String prsCmpr;

	public PropSistemaId() {
	}

	public PropSistemaId(String prsGcvp, String prsGcvn, String prsGcse,
			String prsGcoi, String prsGcli, String prsGmoi, String prsGfoi,
			String prsGrei, String prsGrpi, String prsGfui, String prsGtri,
			String prsGpri, String prsGcri, String prsFrco, String prsFrch,
			String prsFpco, String prsFcco, Integer prsEtnu, String prsEtod,
			String prsEtdh, String prsEtdu, String prsEqsc, String prsEfsc,
			String prsEqkk, String prsAfpn, String prsAfpt, String prsAfan,
			String prsAfat, String prsEtfu, String prsAcce, String prsAace,
			String prsGisc, String prsGlbc, Integer prsGvum, String prsAfnp,
			Integer prsGskn, String prsGicf, String prsGicv, String prsApca,
			String prsAaca, String prsApvs, String prsApvm, String prsChqb,
			String prsChqa, String prsChqc, String prsChqn, String prsGlvc,
			String prsGidc, String prsAfve, String prsCtb, String prsGacp, Integer prsGmct,
			String prsAgna, String prsChql, String prsIrmc, String prsImec,
			String prsIprc, String prsIvec, String prsIpvc, String prsIpv,
			String prsIchc, String prsFccc, String prsGfpr, String prsAfvn,
			String prsAdrp, String prsFtpp, Integer prsGncq, String prsDtri, String prsVfp,
			String prsFeda, String prsFstp, String prsTvf, Integer prsMdc, String prsIsvv,
			String prsTclp, String prsMft, String prsInpm, String prsPbmr, Integer prsCdcp,
			String prsFpct, String prsGccs, Integer prsAdan, Integer prsAfen,
			Integer prsAamb, String prsApnf, Integer prsItec, String prsArnf, Integer prsQtcd,
			String prsFacp, String prsCpsp, String prsCcmt, String prsTcct,
			BigDecimal prsSict, String prsPsvo, String prsPaqr, String prsEssp,
			String prsCcrm, String prsFglc, String prsFgcj, String prsIpo, Integer prsTioc,
			Integer prsGccv, Integer prsStce, String prsOccd, String prsRdpv, String prsEsm,
			String prsIomc, String prsIcac, String prsFimp, String prsTcb, String prsEbt,
			String prsUapc, String prsGpcg, String prsFdsb, String prsCocm,
			String prsCvb, String prsAmpr, String prsFabd, String prsEcn, String prsBapf,
			String prsAjpcp, String prsPpdt, String prsDcm, String prsEemt,
			String prsFdpr, String prsPeca, String prsEeac, Date prsDuec,
			String prsGcrp, String prsLvpr, BigDecimal prsDlpn, BigDecimal prsDlpm,
			String prsLvqp, BigDecimal prsDlqn, BigDecimal prsDlqm, String prsPimc,
			String prsGnfq, String prsOipc, String prsGscl, String prsAgst,
			String prsVnfe, String prsAmpi, BigDecimal prsVmci, String prsCmpr) {
		this.prsGcvp = prsGcvp;
		this.prsGcvn = prsGcvn;
		this.prsGcse = prsGcse;
		this.prsGcoi = prsGcoi;
		this.prsGcli = prsGcli;
		this.prsGmoi = prsGmoi;
		this.prsGfoi = prsGfoi;
		this.prsGrei = prsGrei;
		this.prsGrpi = prsGrpi;
		this.prsGfui = prsGfui;
		this.prsGtri = prsGtri;
		this.prsGpri = prsGpri;
		this.prsGcri = prsGcri;
		this.prsFrco = prsFrco;
		this.prsFrch = prsFrch;
		this.prsFpco = prsFpco;
		this.prsFcco = prsFcco;
		this.prsEtnu = prsEtnu;
		this.prsEtod = prsEtod;
		this.prsEtdh = prsEtdh;
		this.prsEtdu = prsEtdu;
		this.prsEqsc = prsEqsc;
		this.prsEfsc = prsEfsc;
		this.prsEqkk = prsEqkk;
		this.prsAfpn = prsAfpn;
		this.prsAfpt = prsAfpt;
		this.prsAfan = prsAfan;
		this.prsAfat = prsAfat;
		this.prsEtfu = prsEtfu;
		this.prsAcce = prsAcce;
		this.prsAace = prsAace;
		this.prsGisc = prsGisc;
		this.prsGlbc = prsGlbc;
		this.prsGvum = prsGvum;
		this.prsAfnp = prsAfnp;
		this.prsGskn = prsGskn;
		this.prsGicf = prsGicf;
		this.prsGicv = prsGicv;
		this.prsApca = prsApca;
		this.prsAaca = prsAaca;
		this.prsApvs = prsApvs;
		this.prsApvm = prsApvm;
		this.prsChqb = prsChqb;
		this.prsChqa = prsChqa;
		this.prsChqc = prsChqc;
		this.prsChqn = prsChqn;
		this.prsGlvc = prsGlvc;
		this.prsGidc = prsGidc;
		this.prsAfve = prsAfve;
		this.prsCtb = prsCtb;
		this.prsGacp = prsGacp;
		this.prsGmct = prsGmct;
		this.prsAgna = prsAgna;
		this.prsChql = prsChql;
		this.prsIrmc = prsIrmc;
		this.prsImec = prsImec;
		this.prsIprc = prsIprc;
		this.prsIvec = prsIvec;
		this.prsIpvc = prsIpvc;
		this.prsIpv = prsIpv;
		this.prsIchc = prsIchc;
		this.prsFccc = prsFccc;
		this.prsGfpr = prsGfpr;
		this.prsAfvn = prsAfvn;
		this.prsAdrp = prsAdrp;
		this.prsFtpp = prsFtpp;
		this.prsGncq = prsGncq;
		this.prsDtri = prsDtri;
		this.prsVfp = prsVfp;
		this.prsFeda = prsFeda;
		this.prsFstp = prsFstp;
		this.prsTvf = prsTvf;
		this.prsMdc = prsMdc;
		this.prsIsvv = prsIsvv;
		this.prsTclp = prsTclp;
		this.prsMft = prsMft;
		this.prsInpm = prsInpm;
		this.prsPbmr = prsPbmr;
		this.prsCdcp = prsCdcp;
		this.prsFpct = prsFpct;
		this.prsGccs = prsGccs;
		this.prsAdan = prsAdan;
		this.prsAfen = prsAfen;
		this.prsAamb = prsAamb;
		this.prsApnf = prsApnf;
		this.prsItec = prsItec;
		this.prsArnf = prsArnf;
		this.prsQtcd = prsQtcd;
		this.prsFacp = prsFacp;
		this.prsCpsp = prsCpsp;
		this.prsCcmt = prsCcmt;
		this.prsTcct = prsTcct;
		this.prsSict = prsSict;
		this.prsPsvo = prsPsvo;
		this.prsPaqr = prsPaqr;
		this.prsEssp = prsEssp;
		this.prsCcrm = prsCcrm;
		this.prsFglc = prsFglc;
		this.prsFgcj = prsFgcj;
		this.prsIpo = prsIpo;
		this.prsTioc = prsTioc;
		this.prsGccv = prsGccv;
		this.prsStce = prsStce;
		this.prsOccd = prsOccd;
		this.prsRdpv = prsRdpv;
		this.prsEsm = prsEsm;
		this.prsIomc = prsIomc;
		this.prsIcac = prsIcac;
		this.prsFimp = prsFimp;
		this.prsTcb = prsTcb;
		this.prsEbt = prsEbt;
		this.prsUapc = prsUapc;
		this.prsGpcg = prsGpcg;
		this.prsFdsb = prsFdsb;
		this.prsCocm = prsCocm;
		this.prsCvb = prsCvb;
		this.prsAmpr = prsAmpr;
		this.prsFabd = prsFabd;
		this.prsEcn = prsEcn;
		this.prsBapf = prsBapf;
		this.prsAjpcp = prsAjpcp;
		this.prsPpdt = prsPpdt;
		this.prsDcm = prsDcm;
		this.prsEemt = prsEemt;
		this.prsFdpr = prsFdpr;
		this.prsPeca = prsPeca;
		this.prsEeac = prsEeac;
		this.prsDuec = prsDuec;
		this.prsGcrp = prsGcrp;
		this.prsLvpr = prsLvpr;
		this.prsDlpn = prsDlpn;
		this.prsDlpm = prsDlpm;
		this.prsLvqp = prsLvqp;
		this.prsDlqn = prsDlqn;
		this.prsDlqm = prsDlqm;
		this.prsPimc = prsPimc;
		this.prsGnfq = prsGnfq;
		this.prsOipc = prsOipc;
		this.prsGscl = prsGscl;
		this.prsAgst = prsAgst;
		this.prsVnfe = prsVnfe;
		this.prsAmpi = prsAmpi;
		this.prsVmci = prsVmci;
		this.prsCmpr = prsCmpr;
	}

	public PropSistemaId(String prsGcvp, String prsGcvn, String prsGcse,
			String prsGcoi, String prsGcli, String prsGmoi, String prsGfoi,
			String prsGrei, String prsGrpi, String prsGfui, String prsGtri,
			String prsGpri, String prsGcri, String prsFrco, String prsFrch,
			String prsFpco, String prsFcco, Integer prsEtnu, String prsEtod,
			String prsEtdh, String prsEtdu, String prsEqsc, String prsEfsc,
			String prsEqkk, String prsAfpn, String prsAfpt, String prsAfan,
			String prsAfat, String prsGlic, String prsEtfu, String prsAcce,
			String prsAace, String prsGisc, String prsGlbc, Integer prsGvum,
			String prsAfnp, Integer prsGskn, String prsGicf, Integer prsGccf,
			String prsGlbr, String prsGftp, String prsGftu, String prsGfts,
			Integer prsGfdi, Integer prsGfch, Integer prsGfct, Integer prsGfcr,
			Integer prsGfcs, Integer prsGffl, String prsGicv, String prsGsge,
			String prsApca, String prsAaca, String prsApvs, String prsApvm,
			String prsGipf, String prsGops, String prsChqb, String prsChqa,
			String prsChqc, String prsChqn, String prsGlvc, String prsGidc,
			String prsAfve, String prsCtb, String prsGacp, Integer prsGmct, String prsAgna,
			String prsChql, String prsIrmc, String prsImec, String prsIprc,
			String prsIvec, String prsIpvc, String prsIpv, String prsIchc,
			String prsFccc, String prsGfpr, String prsAfvn, String prsAdrp,
			String prsFtpp, Integer prsGncq, String prsDtri, String prsGsde,
			String prsVfp, String prsFeda, String prsFstp, String prsTvf, Integer prsMdc,
			String prsIsvv, String prsTclp, String prsMft, String prsInpm,
			String prsPbmr, Integer prsCdcp, String prsFpct, String prsGccs,
			Integer prsAdan, Integer prsAfen, Integer prsAamb, String prsApnf, Integer prsItec,
			String prsArnf, Integer prsQtcd, String prsFacp, String prsCpsp,
			String prsCcmt, String prsTcct, BigDecimal prsSict, String prsPsvo,
			String prsPaqr, String prsEssp, String prsCcrm, Integer prsCtam,
			String prsHism, String prsFglc, String prsFgcj, Integer prsGrd,
			String prsIpo, Integer prsTioc, Integer prsGccv, Integer prsStce,
			Integer prsFolf, String prsOccd, String prsRdpv, String prsEsm,
			String prsEctd, String prsIomc, String prsIcac, String prsFimp,
			String prsFncs, String prsFips, Integer prsFpts, Integer prsFuas,
			Integer prsLzt, String prsTcb, String prsEbt, String prsUapc,
			String prsGpcg, String prsFdsb, String prsCocm, String prsCvb,
			String prsAmpr, String prsFabd, String prsEcn, String prsBapf,
			String prsAjpcp, String prsPpdt, String prsDcm, String prsEemt,
			String prsFdpr, String prsPeca, String prsEeac, Date prsDuec,
			String prsGcrp, String prsUnd, String prsLvpr, BigDecimal prsDlpn,
			BigDecimal prsDlpm, String prsLvqp, BigDecimal prsDlqn,
			BigDecimal prsDlqm, String prsOpsg, String prsPimc, String prsGnfq,
			String prsOipc, String prsGscl, String prsAgst, String prsVnfe,
			String prsAmpi, BigDecimal prsVmci, String prsCmpr) {
		this.prsGcvp = prsGcvp;
		this.prsGcvn = prsGcvn;
		this.prsGcse = prsGcse;
		this.prsGcoi = prsGcoi;
		this.prsGcli = prsGcli;
		this.prsGmoi = prsGmoi;
		this.prsGfoi = prsGfoi;
		this.prsGrei = prsGrei;
		this.prsGrpi = prsGrpi;
		this.prsGfui = prsGfui;
		this.prsGtri = prsGtri;
		this.prsGpri = prsGpri;
		this.prsGcri = prsGcri;
		this.prsFrco = prsFrco;
		this.prsFrch = prsFrch;
		this.prsFpco = prsFpco;
		this.prsFcco = prsFcco;
		this.prsEtnu = prsEtnu;
		this.prsEtod = prsEtod;
		this.prsEtdh = prsEtdh;
		this.prsEtdu = prsEtdu;
		this.prsEqsc = prsEqsc;
		this.prsEfsc = prsEfsc;
		this.prsEqkk = prsEqkk;
		this.prsAfpn = prsAfpn;
		this.prsAfpt = prsAfpt;
		this.prsAfan = prsAfan;
		this.prsAfat = prsAfat;
		this.prsGlic = prsGlic;
		this.prsEtfu = prsEtfu;
		this.prsAcce = prsAcce;
		this.prsAace = prsAace;
		this.prsGisc = prsGisc;
		this.prsGlbc = prsGlbc;
		this.prsGvum = prsGvum;
		this.prsAfnp = prsAfnp;
		this.prsGskn = prsGskn;
		this.prsGicf = prsGicf;
		this.prsGccf = prsGccf;
		this.prsGlbr = prsGlbr;
		this.prsGftp = prsGftp;
		this.prsGftu = prsGftu;
		this.prsGfts = prsGfts;
		this.prsGfdi = prsGfdi;
		this.prsGfch = prsGfch;
		this.prsGfct = prsGfct;
		this.prsGfcr = prsGfcr;
		this.prsGfcs = prsGfcs;
		this.prsGffl = prsGffl;
		this.prsGicv = prsGicv;
		this.prsGsge = prsGsge;
		this.prsApca = prsApca;
		this.prsAaca = prsAaca;
		this.prsApvs = prsApvs;
		this.prsApvm = prsApvm;
		this.prsGipf = prsGipf;
		this.prsGops = prsGops;
		this.prsChqb = prsChqb;
		this.prsChqa = prsChqa;
		this.prsChqc = prsChqc;
		this.prsChqn = prsChqn;
		this.prsGlvc = prsGlvc;
		this.prsGidc = prsGidc;
		this.prsAfve = prsAfve;
		this.prsCtb = prsCtb;
		this.prsGacp = prsGacp;
		this.prsGmct = prsGmct;
		this.prsAgna = prsAgna;
		this.prsChql = prsChql;
		this.prsIrmc = prsIrmc;
		this.prsImec = prsImec;
		this.prsIprc = prsIprc;
		this.prsIvec = prsIvec;
		this.prsIpvc = prsIpvc;
		this.prsIpv = prsIpv;
		this.prsIchc = prsIchc;
		this.prsFccc = prsFccc;
		this.prsGfpr = prsGfpr;
		this.prsAfvn = prsAfvn;
		this.prsAdrp = prsAdrp;
		this.prsFtpp = prsFtpp;
		this.prsGncq = prsGncq;
		this.prsDtri = prsDtri;
		this.prsGsde = prsGsde;
		this.prsVfp = prsVfp;
		this.prsFeda = prsFeda;
		this.prsFstp = prsFstp;
		this.prsTvf = prsTvf;
		this.prsMdc = prsMdc;
		this.prsIsvv = prsIsvv;
		this.prsTclp = prsTclp;
		this.prsMft = prsMft;
		this.prsInpm = prsInpm;
		this.prsPbmr = prsPbmr;
		this.prsCdcp = prsCdcp;
		this.prsFpct = prsFpct;
		this.prsGccs = prsGccs;
		this.prsAdan = prsAdan;
		this.prsAfen = prsAfen;
		this.prsAamb = prsAamb;
		this.prsApnf = prsApnf;
		this.prsItec = prsItec;
		this.prsArnf = prsArnf;
		this.prsQtcd = prsQtcd;
		this.prsFacp = prsFacp;
		this.prsCpsp = prsCpsp;
		this.prsCcmt = prsCcmt;
		this.prsTcct = prsTcct;
		this.prsSict = prsSict;
		this.prsPsvo = prsPsvo;
		this.prsPaqr = prsPaqr;
		this.prsEssp = prsEssp;
		this.prsCcrm = prsCcrm;
		this.prsCtam = prsCtam;
		this.prsHism = prsHism;
		this.prsFglc = prsFglc;
		this.prsFgcj = prsFgcj;
		this.prsGrd = prsGrd;
		this.prsIpo = prsIpo;
		this.prsTioc = prsTioc;
		this.prsGccv = prsGccv;
		this.prsStce = prsStce;
		this.prsFolf = prsFolf;
		this.prsOccd = prsOccd;
		this.prsRdpv = prsRdpv;
		this.prsEsm = prsEsm;
		this.prsEctd = prsEctd;
		this.prsIomc = prsIomc;
		this.prsIcac = prsIcac;
		this.prsFimp = prsFimp;
		this.prsFncs = prsFncs;
		this.prsFips = prsFips;
		this.prsFpts = prsFpts;
		this.prsFuas = prsFuas;
		this.prsLzt = prsLzt;
		this.prsTcb = prsTcb;
		this.prsEbt = prsEbt;
		this.prsUapc = prsUapc;
		this.prsGpcg = prsGpcg;
		this.prsFdsb = prsFdsb;
		this.prsCocm = prsCocm;
		this.prsCvb = prsCvb;
		this.prsAmpr = prsAmpr;
		this.prsFabd = prsFabd;
		this.prsEcn = prsEcn;
		this.prsBapf = prsBapf;
		this.prsAjpcp = prsAjpcp;
		this.prsPpdt = prsPpdt;
		this.prsDcm = prsDcm;
		this.prsEemt = prsEemt;
		this.prsFdpr = prsFdpr;
		this.prsPeca = prsPeca;
		this.prsEeac = prsEeac;
		this.prsDuec = prsDuec;
		this.prsGcrp = prsGcrp;
		this.prsUnd = prsUnd;
		this.prsLvpr = prsLvpr;
		this.prsDlpn = prsDlpn;
		this.prsDlpm = prsDlpm;
		this.prsLvqp = prsLvqp;
		this.prsDlqn = prsDlqn;
		this.prsDlqm = prsDlqm;
		this.prsOpsg = prsOpsg;
		this.prsPimc = prsPimc;
		this.prsGnfq = prsGnfq;
		this.prsOipc = prsOipc;
		this.prsGscl = prsGscl;
		this.prsAgst = prsAgst;
		this.prsVnfe = prsVnfe;
		this.prsAmpi = prsAmpi;
		this.prsVmci = prsVmci;
		this.prsCmpr = prsCmpr;
	}

	@Column(name = "PRS_GCVP", nullable = false, length = 20)
	public String getPrsGcvp() {
		return this.prsGcvp;
	}

	public void setPrsGcvp(String prsGcvp) {
		this.prsGcvp = prsGcvp;
	}

	@Column(name = "PRS_GCVN", nullable = false, length = 20)
	public String getPrsGcvn() {
		return this.prsGcvn;
	}

	public void setPrsGcvn(String prsGcvn) {
		this.prsGcvn = prsGcvn;
	}

	@Column(name = "PRS_GCSE", nullable = false, length = 20)
	public String getPrsGcse() {
		return this.prsGcse;
	}

	public void setPrsGcse(String prsGcse) {
		this.prsGcse = prsGcse;
	}

	@Column(name = "PRS_GCOI", nullable = false, length = 1)
	public String getPrsGcoi() {
		return this.prsGcoi;
	}

	public void setPrsGcoi(String prsGcoi) {
		this.prsGcoi = prsGcoi;
	}

	@Column(name = "PRS_GCLI", nullable = false, length = 1)
	public String getPrsGcli() {
		return this.prsGcli;
	}

	public void setPrsGcli(String prsGcli) {
		this.prsGcli = prsGcli;
	}

	@Column(name = "PRS_GMOI", nullable = false, length = 1)
	public String getPrsGmoi() {
		return this.prsGmoi;
	}

	public void setPrsGmoi(String prsGmoi) {
		this.prsGmoi = prsGmoi;
	}

	@Column(name = "PRS_GFOI", nullable = false, length = 1)
	public String getPrsGfoi() {
		return this.prsGfoi;
	}

	public void setPrsGfoi(String prsGfoi) {
		this.prsGfoi = prsGfoi;
	}

	@Column(name = "PRS_GREI", nullable = false, length = 1)
	public String getPrsGrei() {
		return this.prsGrei;
	}

	public void setPrsGrei(String prsGrei) {
		this.prsGrei = prsGrei;
	}

	@Column(name = "PRS_GRPI", nullable = false, length = 1)
	public String getPrsGrpi() {
		return this.prsGrpi;
	}

	public void setPrsGrpi(String prsGrpi) {
		this.prsGrpi = prsGrpi;
	}

	@Column(name = "PRS_GFUI", nullable = false, length = 1)
	public String getPrsGfui() {
		return this.prsGfui;
	}

	public void setPrsGfui(String prsGfui) {
		this.prsGfui = prsGfui;
	}

	@Column(name = "PRS_GTRI", nullable = false, length = 1)
	public String getPrsGtri() {
		return this.prsGtri;
	}

	public void setPrsGtri(String prsGtri) {
		this.prsGtri = prsGtri;
	}

	@Column(name = "PRS_GPRI", nullable = false, length = 1)
	public String getPrsGpri() {
		return this.prsGpri;
	}

	public void setPrsGpri(String prsGpri) {
		this.prsGpri = prsGpri;
	}

	@Column(name = "PRS_GCRI", nullable = false, length = 1)
	public String getPrsGcri() {
		return this.prsGcri;
	}

	public void setPrsGcri(String prsGcri) {
		this.prsGcri = prsGcri;
	}

	@Column(name = "PRS_FRCO", nullable = false, length = 1)
	public String getPrsFrco() {
		return this.prsFrco;
	}

	public void setPrsFrco(String prsFrco) {
		this.prsFrco = prsFrco;
	}

	@Column(name = "PRS_FRCH", nullable = false, length = 1)
	public String getPrsFrch() {
		return this.prsFrch;
	}

	public void setPrsFrch(String prsFrch) {
		this.prsFrch = prsFrch;
	}

	@Column(name = "PRS_FPCO", nullable = false, length = 1)
	public String getPrsFpco() {
		return this.prsFpco;
	}

	public void setPrsFpco(String prsFpco) {
		this.prsFpco = prsFpco;
	}

	@Column(name = "PRS_FCCO", nullable = false, length = 1)
	public String getPrsFcco() {
		return this.prsFcco;
	}

	public void setPrsFcco(String prsFcco) {
		this.prsFcco = prsFcco;
	}

	@Column(name = "PRS_ETNU", nullable = false)
	public Integer getPrsEtnu() {
		return this.prsEtnu;
	}

	public void setPrsEtnu(Integer prsEtnu) {
		this.prsEtnu = prsEtnu;
	}

	@Column(name = "PRS_ETOD", nullable = false, length = 1)
	public String getPrsEtod() {
		return this.prsEtod;
	}

	public void setPrsEtod(String prsEtod) {
		this.prsEtod = prsEtod;
	}

	@Column(name = "PRS_ETDH", nullable = false, length = 1)
	public String getPrsEtdh() {
		return this.prsEtdh;
	}

	public void setPrsEtdh(String prsEtdh) {
		this.prsEtdh = prsEtdh;
	}

	@Column(name = "PRS_ETDU", nullable = false, length = 1)
	public String getPrsEtdu() {
		return this.prsEtdu;
	}

	public void setPrsEtdu(String prsEtdu) {
		this.prsEtdu = prsEtdu;
	}

	@Column(name = "PRS_EQSC", nullable = false, length = 1)
	public String getPrsEqsc() {
		return this.prsEqsc;
	}

	public void setPrsEqsc(String prsEqsc) {
		this.prsEqsc = prsEqsc;
	}

	@Column(name = "PRS_EFSC", nullable = false, length = 1)
	public String getPrsEfsc() {
		return this.prsEfsc;
	}

	public void setPrsEfsc(String prsEfsc) {
		this.prsEfsc = prsEfsc;
	}

	@Column(name = "PRS_EQKK", nullable = false, length = 1)
	public String getPrsEqkk() {
		return this.prsEqkk;
	}

	public void setPrsEqkk(String prsEqkk) {
		this.prsEqkk = prsEqkk;
	}

	@Column(name = "PRS_AFPN", nullable = false, length = 1)
	public String getPrsAfpn() {
		return this.prsAfpn;
	}

	public void setPrsAfpn(String prsAfpn) {
		this.prsAfpn = prsAfpn;
	}

	@Column(name = "PRS_AFPT", nullable = false, length = 1)
	public String getPrsAfpt() {
		return this.prsAfpt;
	}

	public void setPrsAfpt(String prsAfpt) {
		this.prsAfpt = prsAfpt;
	}

	@Column(name = "PRS_AFAN", nullable = false, length = 1)
	public String getPrsAfan() {
		return this.prsAfan;
	}

	public void setPrsAfan(String prsAfan) {
		this.prsAfan = prsAfan;
	}

	@Column(name = "PRS_AFAT", nullable = false, length = 1)
	public String getPrsAfat() {
		return this.prsAfat;
	}

	public void setPrsAfat(String prsAfat) {
		this.prsAfat = prsAfat;
	}

	@Column(name = "PRS_GLIC", length = 200)
	public String getPrsGlic() {
		return this.prsGlic;
	}

	public void setPrsGlic(String prsGlic) {
		this.prsGlic = prsGlic;
	}

	@Column(name = "PRS_ETFU", nullable = false, length = 1)
	public String getPrsEtfu() {
		return this.prsEtfu;
	}

	public void setPrsEtfu(String prsEtfu) {
		this.prsEtfu = prsEtfu;
	}

	@Column(name = "PRS_ACCE", nullable = false, length = 1)
	public String getPrsAcce() {
		return this.prsAcce;
	}

	public void setPrsAcce(String prsAcce) {
		this.prsAcce = prsAcce;
	}

	@Column(name = "PRS_AACE", nullable = false, length = 1)
	public String getPrsAace() {
		return this.prsAace;
	}

	public void setPrsAace(String prsAace) {
		this.prsAace = prsAace;
	}

	@Column(name = "PRS_GISC", nullable = false, length = 1)
	public String getPrsGisc() {
		return this.prsGisc;
	}

	public void setPrsGisc(String prsGisc) {
		this.prsGisc = prsGisc;
	}

	@Column(name = "PRS_GLBC", nullable = false, length = 60)
	public String getPrsGlbc() {
		return this.prsGlbc;
	}

	public void setPrsGlbc(String prsGlbc) {
		this.prsGlbc = prsGlbc;
	}

	@Column(name = "PRS_GVUM", nullable = false)
	public Integer getPrsGvum() {
		return this.prsGvum;
	}

	public void setPrsGvum(Integer prsGvum) {
		this.prsGvum = prsGvum;
	}

	@Column(name = "PRS_AFNP", nullable = false, length = 1)
	public String getPrsAfnp() {
		return this.prsAfnp;
	}

	public void setPrsAfnp(String prsAfnp) {
		this.prsAfnp = prsAfnp;
	}

	@Column(name = "PRS_GSKN", nullable = false)
	public Integer getPrsGskn() {
		return this.prsGskn;
	}

	public void setPrsGskn(Integer prsGskn) {
		this.prsGskn = prsGskn;
	}

	@Column(name = "PRS_GICF", nullable = false, length = 1)
	public String getPrsGicf() {
		return this.prsGicf;
	}

	public void setPrsGicf(String prsGicf) {
		this.prsGicf = prsGicf;
	}

	@Column(name = "PRS_GCCF")
	public Integer getPrsGccf() {
		return this.prsGccf;
	}

	public void setPrsGccf(Integer prsGccf) {
		this.prsGccf = prsGccf;
	}

	@Column(name = "PRS_GLBR", length = 60)
	public String getPrsGlbr() {
		return this.prsGlbr;
	}

	public void setPrsGlbr(String prsGlbr) {
		this.prsGlbr = prsGlbr;
	}

	@Column(name = "PRS_GFTP", length = 80)
	public String getPrsGftp() {
		return this.prsGftp;
	}

	public void setPrsGftp(String prsGftp) {
		this.prsGftp = prsGftp;
	}

	@Column(name = "PRS_GFTU", length = 40)
	public String getPrsGftu() {
		return this.prsGftu;
	}

	public void setPrsGftu(String prsGftu) {
		this.prsGftu = prsGftu;
	}

	@Column(name = "PRS_GFTS", length = 40)
	public String getPrsGfts() {
		return this.prsGfts;
	}

	public void setPrsGfts(String prsGfts) {
		this.prsGfts = prsGfts;
	}

	@Column(name = "PRS_GFDI")
	public Integer getPrsGfdi() {
		return this.prsGfdi;
	}

	public void setPrsGfdi(Integer prsGfdi) {
		this.prsGfdi = prsGfdi;
	}

	@Column(name = "PRS_GFCH")
	public Integer getPrsGfch() {
		return this.prsGfch;
	}

	public void setPrsGfch(Integer prsGfch) {
		this.prsGfch = prsGfch;
	}

	@Column(name = "PRS_GFCT")
	public Integer getPrsGfct() {
		return this.prsGfct;
	}

	public void setPrsGfct(Integer prsGfct) {
		this.prsGfct = prsGfct;
	}

	@Column(name = "PRS_GFCR")
	public Integer getPrsGfcr() {
		return this.prsGfcr;
	}

	public void setPrsGfcr(Integer prsGfcr) {
		this.prsGfcr = prsGfcr;
	}

	@Column(name = "PRS_GFCS")
	public Integer getPrsGfcs() {
		return this.prsGfcs;
	}

	public void setPrsGfcs(Integer prsGfcs) {
		this.prsGfcs = prsGfcs;
	}

	@Column(name = "PRS_GFFL")
	public Integer getPrsGffl() {
		return this.prsGffl;
	}

	public void setPrsGffl(Integer prsGffl) {
		this.prsGffl = prsGffl;
	}

	@Column(name = "PRS_GICV", nullable = false, length = 1)
	public String getPrsGicv() {
		return this.prsGicv;
	}

	public void setPrsGicv(String prsGicv) {
		this.prsGicv = prsGicv;
	}

	@Column(name = "PRS_GSGE", length = 8)
	public String getPrsGsge() {
		return this.prsGsge;
	}

	public void setPrsGsge(String prsGsge) {
		this.prsGsge = prsGsge;
	}

	@Column(name = "PRS_APCA", nullable = false, length = 1)
	public String getPrsApca() {
		return this.prsApca;
	}

	public void setPrsApca(String prsApca) {
		this.prsApca = prsApca;
	}

	@Column(name = "PRS_AACA", nullable = false, length = 1)
	public String getPrsAaca() {
		return this.prsAaca;
	}

	public void setPrsAaca(String prsAaca) {
		this.prsAaca = prsAaca;
	}

	@Column(name = "PRS_APVS", nullable = false, length = 1)
	public String getPrsApvs() {
		return this.prsApvs;
	}

	public void setPrsApvs(String prsApvs) {
		this.prsApvs = prsApvs;
	}

	@Column(name = "PRS_APVM", nullable = false, length = 1)
	public String getPrsApvm() {
		return this.prsApvm;
	}

	public void setPrsApvm(String prsApvm) {
		this.prsApvm = prsApvm;
	}

	@Column(name = "PRS_GIPF", length = 60)
	public String getPrsGipf() {
		return this.prsGipf;
	}

	public void setPrsGipf(String prsGipf) {
		this.prsGipf = prsGipf;
	}

	@Column(name = "PRS_GOPS", length = 0)
	public String getPrsGops() {
		return this.prsGops;
	}

	public void setPrsGops(String prsGops) {
		this.prsGops = prsGops;
	}

	@Column(name = "PRS_CHQB", nullable = false, length = 1)
	public String getPrsChqb() {
		return this.prsChqb;
	}

	public void setPrsChqb(String prsChqb) {
		this.prsChqb = prsChqb;
	}

	@Column(name = "PRS_CHQA", nullable = false, length = 1)
	public String getPrsChqa() {
		return this.prsChqa;
	}

	public void setPrsChqa(String prsChqa) {
		this.prsChqa = prsChqa;
	}

	@Column(name = "PRS_CHQC", nullable = false, length = 1)
	public String getPrsChqc() {
		return this.prsChqc;
	}

	public void setPrsChqc(String prsChqc) {
		this.prsChqc = prsChqc;
	}

	@Column(name = "PRS_CHQN", nullable = false, length = 1)
	public String getPrsChqn() {
		return this.prsChqn;
	}

	public void setPrsChqn(String prsChqn) {
		this.prsChqn = prsChqn;
	}

	@Column(name = "PRS_GLVC", nullable = false, length = 1)
	public String getPrsGlvc() {
		return this.prsGlvc;
	}

	public void setPrsGlvc(String prsGlvc) {
		this.prsGlvc = prsGlvc;
	}

	@Column(name = "PRS_GIDC", nullable = false, length = 1)
	public String getPrsGidc() {
		return this.prsGidc;
	}

	public void setPrsGidc(String prsGidc) {
		this.prsGidc = prsGidc;
	}

	@Column(name = "PRS_AFVE", nullable = false, length = 1)
	public String getPrsAfve() {
		return this.prsAfve;
	}

	public void setPrsAfve(String prsAfve) {
		this.prsAfve = prsAfve;
	}

	@Column(name = "PRS_CTB", nullable = false, length = 1)
	public String getPrsCtb() {
		return this.prsCtb;
	}

	public void setPrsCtb(String prsCtb) {
		this.prsCtb = prsCtb;
	}

	@Column(name = "PRS_GACP", nullable = false, length = 1)
	public String getPrsGacp() {
		return this.prsGacp;
	}

	public void setPrsGacp(String prsGacp) {
		this.prsGacp = prsGacp;
	}

	@Column(name = "PRS_GMCT", nullable = false)
	public Integer getPrsGmct() {
		return this.prsGmct;
	}

	public void setPrsGmct(Integer prsGmct) {
		this.prsGmct = prsGmct;
	}

	@Column(name = "PRS_AGNA", nullable = false, length = 1)
	public String getPrsAgna() {
		return this.prsAgna;
	}

	public void setPrsAgna(String prsAgna) {
		this.prsAgna = prsAgna;
	}

	@Column(name = "PRS_CHQL", nullable = false, length = 1)
	public String getPrsChql() {
		return this.prsChql;
	}

	public void setPrsChql(String prsChql) {
		this.prsChql = prsChql;
	}

	@Column(name = "PRS_IRMC", nullable = false, length = 1)
	public String getPrsIrmc() {
		return this.prsIrmc;
	}

	public void setPrsIrmc(String prsIrmc) {
		this.prsIrmc = prsIrmc;
	}

	@Column(name = "PRS_IMEC", nullable = false, length = 1)
	public String getPrsImec() {
		return this.prsImec;
	}

	public void setPrsImec(String prsImec) {
		this.prsImec = prsImec;
	}

	@Column(name = "PRS_IPRC", nullable = false, length = 1)
	public String getPrsIprc() {
		return this.prsIprc;
	}

	public void setPrsIprc(String prsIprc) {
		this.prsIprc = prsIprc;
	}

	@Column(name = "PRS_IVEC", nullable = false, length = 1)
	public String getPrsIvec() {
		return this.prsIvec;
	}

	public void setPrsIvec(String prsIvec) {
		this.prsIvec = prsIvec;
	}

	@Column(name = "PRS_IPVC", nullable = false, length = 1)
	public String getPrsIpvc() {
		return this.prsIpvc;
	}

	public void setPrsIpvc(String prsIpvc) {
		this.prsIpvc = prsIpvc;
	}

	@Column(name = "PRS_IPV", nullable = false, length = 1)
	public String getPrsIpv() {
		return this.prsIpv;
	}

	public void setPrsIpv(String prsIpv) {
		this.prsIpv = prsIpv;
	}

	@Column(name = "PRS_ICHC", nullable = false, length = 1)
	public String getPrsIchc() {
		return this.prsIchc;
	}

	public void setPrsIchc(String prsIchc) {
		this.prsIchc = prsIchc;
	}

	@Column(name = "PRS_FCCC", nullable = false, length = 1)
	public String getPrsFccc() {
		return this.prsFccc;
	}

	public void setPrsFccc(String prsFccc) {
		this.prsFccc = prsFccc;
	}

	@Column(name = "PRS_GFPR", nullable = false, length = 1)
	public String getPrsGfpr() {
		return this.prsGfpr;
	}

	public void setPrsGfpr(String prsGfpr) {
		this.prsGfpr = prsGfpr;
	}

	@Column(name = "PRS_AFVN", nullable = false, length = 1)
	public String getPrsAfvn() {
		return this.prsAfvn;
	}

	public void setPrsAfvn(String prsAfvn) {
		this.prsAfvn = prsAfvn;
	}

	@Column(name = "PRS_ADRP", nullable = false, length = 1)
	public String getPrsAdrp() {
		return this.prsAdrp;
	}

	public void setPrsAdrp(String prsAdrp) {
		this.prsAdrp = prsAdrp;
	}

	@Column(name = "PRS_FTPP", nullable = false, length = 1)
	public String getPrsFtpp() {
		return this.prsFtpp;
	}

	public void setPrsFtpp(String prsFtpp) {
		this.prsFtpp = prsFtpp;
	}

	@Column(name = "PRS_GNCQ", nullable = false)
	public Integer getPrsGncq() {
		return this.prsGncq;
	}

	public void setPrsGncq(Integer prsGncq) {
		this.prsGncq = prsGncq;
	}

	@Column(name = "PRS_DTRI", nullable = false, length = 1)
	public String getPrsDtri() {
		return this.prsDtri;
	}

	public void setPrsDtri(String prsDtri) {
		this.prsDtri = prsDtri;
	}

	@Column(name = "PRS_GSDE", length = 8)
	public String getPrsGsde() {
		return this.prsGsde;
	}

	public void setPrsGsde(String prsGsde) {
		this.prsGsde = prsGsde;
	}

	@Column(name = "PRS_VFP", nullable = false, length = 1)
	public String getPrsVfp() {
		return this.prsVfp;
	}

	public void setPrsVfp(String prsVfp) {
		this.prsVfp = prsVfp;
	}

	@Column(name = "PRS_FEDA", nullable = false, length = 1)
	public String getPrsFeda() {
		return this.prsFeda;
	}

	public void setPrsFeda(String prsFeda) {
		this.prsFeda = prsFeda;
	}

	@Column(name = "PRS_FSTP", nullable = false, length = 1)
	public String getPrsFstp() {
		return this.prsFstp;
	}

	public void setPrsFstp(String prsFstp) {
		this.prsFstp = prsFstp;
	}

	@Column(name = "PRS_TVF", nullable = false, length = 1)
	public String getPrsTvf() {
		return this.prsTvf;
	}

	public void setPrsTvf(String prsTvf) {
		this.prsTvf = prsTvf;
	}

	@Column(name = "PRS_MDC", nullable = false)
	public Integer getPrsMdc() {
		return this.prsMdc;
	}

	public void setPrsMdc(Integer prsMdc) {
		this.prsMdc = prsMdc;
	}

	@Column(name = "PRS_ISVV", nullable = false, length = 1)
	public String getPrsIsvv() {
		return this.prsIsvv;
	}

	public void setPrsIsvv(String prsIsvv) {
		this.prsIsvv = prsIsvv;
	}

	@Column(name = "PRS_TCLP", nullable = false, length = 1)
	public String getPrsTclp() {
		return this.prsTclp;
	}

	public void setPrsTclp(String prsTclp) {
		this.prsTclp = prsTclp;
	}

	@Column(name = "PRS_MFT", nullable = false, length = 1)
	public String getPrsMft() {
		return this.prsMft;
	}

	public void setPrsMft(String prsMft) {
		this.prsMft = prsMft;
	}

	@Column(name = "PRS_INPM", nullable = false, length = 1)
	public String getPrsInpm() {
		return this.prsInpm;
	}

	public void setPrsInpm(String prsInpm) {
		this.prsInpm = prsInpm;
	}

	@Column(name = "PRS_PBMR", nullable = false, length = 1)
	public String getPrsPbmr() {
		return this.prsPbmr;
	}

	public void setPrsPbmr(String prsPbmr) {
		this.prsPbmr = prsPbmr;
	}

	@Column(name = "PRS_CDCP", nullable = false)
	public Integer getPrsCdcp() {
		return this.prsCdcp;
	}

	public void setPrsCdcp(Integer prsCdcp) {
		this.prsCdcp = prsCdcp;
	}

	@Column(name = "PRS_FPCT", nullable = false, length = 1)
	public String getPrsFpct() {
		return this.prsFpct;
	}

	public void setPrsFpct(String prsFpct) {
		this.prsFpct = prsFpct;
	}

	@Column(name = "PRS_GCCS", nullable = false, length = 20)
	public String getPrsGccs() {
		return this.prsGccs;
	}

	public void setPrsGccs(String prsGccs) {
		this.prsGccs = prsGccs;
	}

	@Column(name = "PRS_ADAN", nullable = false)
	public Integer getPrsAdan() {
		return this.prsAdan;
	}

	public void setPrsAdan(Integer prsAdan) {
		this.prsAdan = prsAdan;
	}

	@Column(name = "PRS_AFEN", nullable = false)
	public Integer getPrsAfen() {
		return this.prsAfen;
	}

	public void setPrsAfen(Integer prsAfen) {
		this.prsAfen = prsAfen;
	}

	@Column(name = "PRS_AAMB", nullable = false)
	public Integer getPrsAamb() {
		return this.prsAamb;
	}

	public void setPrsAamb(Integer prsAamb) {
		this.prsAamb = prsAamb;
	}

	@Column(name = "PRS_APNF", nullable = false, length = 1)
	public String getPrsApnf() {
		return this.prsApnf;
	}

	public void setPrsApnf(String prsApnf) {
		this.prsApnf = prsApnf;
	}

	@Column(name = "PRS_ITEC", nullable = false)
	public Integer getPrsItec() {
		return this.prsItec;
	}

	public void setPrsItec(Integer prsItec) {
		this.prsItec = prsItec;
	}

	@Column(name = "PRS_ARNF", nullable = false, length = 1)
	public String getPrsArnf() {
		return this.prsArnf;
	}

	public void setPrsArnf(String prsArnf) {
		this.prsArnf = prsArnf;
	}

	@Column(name = "PRS_QTCD", nullable = false)
	public Integer getPrsQtcd() {
		return this.prsQtcd;
	}

	public void setPrsQtcd(Integer prsQtcd) {
		this.prsQtcd = prsQtcd;
	}

	@Column(name = "PRS_FACP", nullable = false, length = 1)
	public String getPrsFacp() {
		return this.prsFacp;
	}

	public void setPrsFacp(String prsFacp) {
		this.prsFacp = prsFacp;
	}

	@Column(name = "PRS_CPSP", nullable = false, length = 1)
	public String getPrsCpsp() {
		return this.prsCpsp;
	}

	public void setPrsCpsp(String prsCpsp) {
		this.prsCpsp = prsCpsp;
	}

	@Column(name = "PRS_CCMT", nullable = false, length = 1)
	public String getPrsCcmt() {
		return this.prsCcmt;
	}

	public void setPrsCcmt(String prsCcmt) {
		this.prsCcmt = prsCcmt;
	}

	@Column(name = "PRS_TCCT", nullable = false, length = 1)
	public String getPrsTcct() {
		return this.prsTcct;
	}

	public void setPrsTcct(String prsTcct) {
		this.prsTcct = prsTcct;
	}

	@Column(name = "PRS_SICT", nullable = false, precision = 5)
	public BigDecimal getPrsSict() {
		return this.prsSict;
	}

	public void setPrsSict(BigDecimal prsSict) {
		this.prsSict = prsSict;
	}

	@Column(name = "PRS_PSVO", nullable = false, length = 1)
	public String getPrsPsvo() {
		return this.prsPsvo;
	}

	public void setPrsPsvo(String prsPsvo) {
		this.prsPsvo = prsPsvo;
	}

	@Column(name = "PRS_PAQR", nullable = false, length = 1)
	public String getPrsPaqr() {
		return this.prsPaqr;
	}

	public void setPrsPaqr(String prsPaqr) {
		this.prsPaqr = prsPaqr;
	}

	@Column(name = "PRS_ESSP", nullable = false, length = 1)
	public String getPrsEssp() {
		return this.prsEssp;
	}

	public void setPrsEssp(String prsEssp) {
		this.prsEssp = prsEssp;
	}

	@Column(name = "PRS_CCRM", nullable = false, length = 1)
	public String getPrsCcrm() {
		return this.prsCcrm;
	}

	public void setPrsCcrm(String prsCcrm) {
		this.prsCcrm = prsCcrm;
	}

	@Column(name = "PRS_CTAM")
	public Integer getPrsCtam() {
		return this.prsCtam;
	}

	public void setPrsCtam(Integer prsCtam) {
		this.prsCtam = prsCtam;
	}

	@Column(name = "PRS_HISM", length = 40)
	public String getPrsHism() {
		return this.prsHism;
	}

	public void setPrsHism(String prsHism) {
		this.prsHism = prsHism;
	}

	@Column(name = "PRS_FGLC", nullable = false, length = 1)
	public String getPrsFglc() {
		return this.prsFglc;
	}

	public void setPrsFglc(String prsFglc) {
		this.prsFglc = prsFglc;
	}

	@Column(name = "PRS_FGCJ", nullable = false, length = 1)
	public String getPrsFgcj() {
		return this.prsFgcj;
	}

	public void setPrsFgcj(String prsFgcj) {
		this.prsFgcj = prsFgcj;
	}

	@Column(name = "PRS_GRD")
	public Integer getPrsGrd() {
		return this.prsGrd;
	}

	public void setPrsGrd(Integer prsGrd) {
		this.prsGrd = prsGrd;
	}

	@Column(name = "PRS_IPO", nullable = false, length = 1)
	public String getPrsIpo() {
		return this.prsIpo;
	}

	public void setPrsIpo(String prsIpo) {
		this.prsIpo = prsIpo;
	}

	@Column(name = "PRS_TIOC", nullable = false)
	public Integer getPrsTioc() {
		return this.prsTioc;
	}

	public void setPrsTioc(Integer prsTioc) {
		this.prsTioc = prsTioc;
	}

	@Column(name = "PRS_GCCV", nullable = false)
	public Integer getPrsGccv() {
		return this.prsGccv;
	}

	public void setPrsGccv(Integer prsGccv) {
		this.prsGccv = prsGccv;
	}

	@Column(name = "PRS_STCE", nullable = false)
	public Integer getPrsStce() {
		return this.prsStce;
	}

	public void setPrsStce(Integer prsStce) {
		this.prsStce = prsStce;
	}

	@Column(name = "PRS_FOLF")
	public Integer getPrsFolf() {
		return this.prsFolf;
	}

	public void setPrsFolf(Integer prsFolf) {
		this.prsFolf = prsFolf;
	}

	@Column(name = "PRS_OCCD", nullable = false, length = 1)
	public String getPrsOccd() {
		return this.prsOccd;
	}

	public void setPrsOccd(String prsOccd) {
		this.prsOccd = prsOccd;
	}

	@Column(name = "PRS_RDPV", nullable = false, length = 1)
	public String getPrsRdpv() {
		return this.prsRdpv;
	}

	public void setPrsRdpv(String prsRdpv) {
		this.prsRdpv = prsRdpv;
	}

	@Column(name = "PRS_ESM", nullable = false, length = 1)
	public String getPrsEsm() {
		return this.prsEsm;
	}

	public void setPrsEsm(String prsEsm) {
		this.prsEsm = prsEsm;
	}

	@Column(name = "PRS_ECTD", length = 100)
	public String getPrsEctd() {
		return this.prsEctd;
	}

	public void setPrsEctd(String prsEctd) {
		this.prsEctd = prsEctd;
	}

	@Column(name = "PRS_IOMC", nullable = false, length = 1)
	public String getPrsIomc() {
		return this.prsIomc;
	}

	public void setPrsIomc(String prsIomc) {
		this.prsIomc = prsIomc;
	}

	@Column(name = "PRS_ICAC", nullable = false, length = 1)
	public String getPrsIcac() {
		return this.prsIcac;
	}

	public void setPrsIcac(String prsIcac) {
		this.prsIcac = prsIcac;
	}

	@Column(name = "PRS_FIMP", nullable = false, length = 1)
	public String getPrsFimp() {
		return this.prsFimp;
	}

	public void setPrsFimp(String prsFimp) {
		this.prsFimp = prsFimp;
	}

	@Column(name = "PRS_FNCS", length = 8)
	public String getPrsFncs() {
		return this.prsFncs;
	}

	public void setPrsFncs(String prsFncs) {
		this.prsFncs = prsFncs;
	}

	@Column(name = "PRS_FIPS", length = 20)
	public String getPrsFips() {
		return this.prsFips;
	}

	public void setPrsFips(String prsFips) {
		this.prsFips = prsFips;
	}

	@Column(name = "PRS_FPTS")
	public Integer getPrsFpts() {
		return this.prsFpts;
	}

	public void setPrsFpts(Integer prsFpts) {
		this.prsFpts = prsFpts;
	}

	@Column(name = "PRS_FUAS")
	public Integer getPrsFuas() {
		return this.prsFuas;
	}

	public void setPrsFuas(Integer prsFuas) {
		this.prsFuas = prsFuas;
	}

	@Column(name = "PRS_LZT")
	public Integer getPrsLzt() {
		return this.prsLzt;
	}

	public void setPrsLzt(Integer prsLzt) {
		this.prsLzt = prsLzt;
	}

	@Column(name = "PRS_TCB", nullable = false, length = 1)
	public String getPrsTcb() {
		return this.prsTcb;
	}

	public void setPrsTcb(String prsTcb) {
		this.prsTcb = prsTcb;
	}

	@Column(name = "PRS_EBT", nullable = false, length = 1)
	public String getPrsEbt() {
		return this.prsEbt;
	}

	public void setPrsEbt(String prsEbt) {
		this.prsEbt = prsEbt;
	}

	@Column(name = "PRS_UAPC", nullable = false, length = 1)
	public String getPrsUapc() {
		return this.prsUapc;
	}

	public void setPrsUapc(String prsUapc) {
		this.prsUapc = prsUapc;
	}

	@Column(name = "PRS_GPCG", nullable = false, length = 1)
	public String getPrsGpcg() {
		return this.prsGpcg;
	}

	public void setPrsGpcg(String prsGpcg) {
		this.prsGpcg = prsGpcg;
	}

	@Column(name = "PRS_FDSB", nullable = false, length = 1)
	public String getPrsFdsb() {
		return this.prsFdsb;
	}

	public void setPrsFdsb(String prsFdsb) {
		this.prsFdsb = prsFdsb;
	}

	@Column(name = "PRS_COCM", nullable = false, length = 1)
	public String getPrsCocm() {
		return this.prsCocm;
	}

	public void setPrsCocm(String prsCocm) {
		this.prsCocm = prsCocm;
	}

	@Column(name = "PRS_CVB", nullable = false, length = 1)
	public String getPrsCvb() {
		return this.prsCvb;
	}

	public void setPrsCvb(String prsCvb) {
		this.prsCvb = prsCvb;
	}

	@Column(name = "PRS_AMPR", nullable = false, length = 1)
	public String getPrsAmpr() {
		return this.prsAmpr;
	}

	public void setPrsAmpr(String prsAmpr) {
		this.prsAmpr = prsAmpr;
	}

	@Column(name = "PRS_FABD", nullable = false, length = 1)
	public String getPrsFabd() {
		return this.prsFabd;
	}

	public void setPrsFabd(String prsFabd) {
		this.prsFabd = prsFabd;
	}

	@Column(name = "PRS_ECN", nullable = false, length = 1)
	public String getPrsEcn() {
		return this.prsEcn;
	}

	public void setPrsEcn(String prsEcn) {
		this.prsEcn = prsEcn;
	}

	@Column(name = "PRS_BAPF", nullable = false, length = 1)
	public String getPrsBapf() {
		return this.prsBapf;
	}

	public void setPrsBapf(String prsBapf) {
		this.prsBapf = prsBapf;
	}

	@Column(name = "PRS_AJPCP", nullable = false, length = 1)
	public String getPrsAjpcp() {
		return this.prsAjpcp;
	}

	public void setPrsAjpcp(String prsAjpcp) {
		this.prsAjpcp = prsAjpcp;
	}

	@Column(name = "PRS_PPDT", nullable = false, length = 1)
	public String getPrsPpdt() {
		return this.prsPpdt;
	}

	public void setPrsPpdt(String prsPpdt) {
		this.prsPpdt = prsPpdt;
	}

	@Column(name = "PRS_DCM", nullable = false, length = 1)
	public String getPrsDcm() {
		return this.prsDcm;
	}

	public void setPrsDcm(String prsDcm) {
		this.prsDcm = prsDcm;
	}

	@Column(name = "PRS_EEMT", nullable = false, length = 1)
	public String getPrsEemt() {
		return this.prsEemt;
	}

	public void setPrsEemt(String prsEemt) {
		this.prsEemt = prsEemt;
	}

	@Column(name = "PRS_FDPR", nullable = false, length = 1)
	public String getPrsFdpr() {
		return this.prsFdpr;
	}

	public void setPrsFdpr(String prsFdpr) {
		this.prsFdpr = prsFdpr;
	}

	@Column(name = "PRS_PECA", nullable = false, length = 1)
	public String getPrsPeca() {
		return this.prsPeca;
	}

	public void setPrsPeca(String prsPeca) {
		this.prsPeca = prsPeca;
	}

	@Column(name = "PRS_EEAC", nullable = false, length = 1)
	public String getPrsEeac() {
		return this.prsEeac;
	}

	public void setPrsEeac(String prsEeac) {
		this.prsEeac = prsEeac;
	}

	@Column(name = "PRS_DUEC", nullable = false, length = 10)
	public Date getPrsDuec() {
		return this.prsDuec;
	}

	public void setPrsDuec(Date prsDuec) {
		this.prsDuec = prsDuec;
	}

	@Column(name = "PRS_GCRP", nullable = false, length = 1)
	public String getPrsGcrp() {
		return this.prsGcrp;
	}

	public void setPrsGcrp(String prsGcrp) {
		this.prsGcrp = prsGcrp;
	}

	@Column(name = "PRS_UND", length = 3)
	public String getPrsUnd() {
		return this.prsUnd;
	}

	public void setPrsUnd(String prsUnd) {
		this.prsUnd = prsUnd;
	}

	@Column(name = "PRS_LVPR", nullable = false, length = 1)
	public String getPrsLvpr() {
		return this.prsLvpr;
	}

	public void setPrsLvpr(String prsLvpr) {
		this.prsLvpr = prsLvpr;
	}

	@Column(name = "PRS_DLPN", nullable = false, precision = 14)
	public BigDecimal getPrsDlpn() {
		return this.prsDlpn;
	}

	public void setPrsDlpn(BigDecimal prsDlpn) {
		this.prsDlpn = prsDlpn;
	}

	@Column(name = "PRS_DLPM", nullable = false, precision = 14)
	public BigDecimal getPrsDlpm() {
		return this.prsDlpm;
	}

	public void setPrsDlpm(BigDecimal prsDlpm) {
		this.prsDlpm = prsDlpm;
	}

	@Column(name = "PRS_LVQP", nullable = false, length = 1)
	public String getPrsLvqp() {
		return this.prsLvqp;
	}

	public void setPrsLvqp(String prsLvqp) {
		this.prsLvqp = prsLvqp;
	}

	@Column(name = "PRS_DLQN", nullable = false, precision = 14)
	public BigDecimal getPrsDlqn() {
		return this.prsDlqn;
	}

	public void setPrsDlqn(BigDecimal prsDlqn) {
		this.prsDlqn = prsDlqn;
	}

	@Column(name = "PRS_DLQM", nullable = false, precision = 14)
	public BigDecimal getPrsDlqm() {
		return this.prsDlqm;
	}

	public void setPrsDlqm(BigDecimal prsDlqm) {
		this.prsDlqm = prsDlqm;
	}

	@Column(name = "PRS_OPSG", length = 0)
	public String getPrsOpsg() {
		return this.prsOpsg;
	}

	public void setPrsOpsg(String prsOpsg) {
		this.prsOpsg = prsOpsg;
	}

	@Column(name = "PRS_PIMC", nullable = false, length = 1)
	public String getPrsPimc() {
		return this.prsPimc;
	}

	public void setPrsPimc(String prsPimc) {
		this.prsPimc = prsPimc;
	}

	@Column(name = "PRS_GNFQ", nullable = false, length = 1)
	public String getPrsGnfq() {
		return this.prsGnfq;
	}

	public void setPrsGnfq(String prsGnfq) {
		this.prsGnfq = prsGnfq;
	}

	@Column(name = "PRS_OIPC", nullable = false, length = 1)
	public String getPrsOipc() {
		return this.prsOipc;
	}

	public void setPrsOipc(String prsOipc) {
		this.prsOipc = prsOipc;
	}

	@Column(name = "PRS_GSCL", nullable = false, length = 1)
	public String getPrsGscl() {
		return this.prsGscl;
	}

	public void setPrsGscl(String prsGscl) {
		this.prsGscl = prsGscl;
	}

	@Column(name = "PRS_AGST", nullable = false, length = 1)
	public String getPrsAgst() {
		return this.prsAgst;
	}

	public void setPrsAgst(String prsAgst) {
		this.prsAgst = prsAgst;
	}

	@Column(name = "PRS_VNFE", nullable = false, length = 1)
	public String getPrsVnfe() {
		return this.prsVnfe;
	}

	public void setPrsVnfe(String prsVnfe) {
		this.prsVnfe = prsVnfe;
	}

	@Column(name = "PRS_AMPI", nullable = false, length = 1)
	public String getPrsAmpi() {
		return this.prsAmpi;
	}

	public void setPrsAmpi(String prsAmpi) {
		this.prsAmpi = prsAmpi;
	}

	@Column(name = "PRS_VMCI", nullable = false, precision = 15)
	public BigDecimal getPrsVmci() {
		return this.prsVmci;
	}

	public void setPrsVmci(BigDecimal prsVmci) {
		this.prsVmci = prsVmci;
	}

	@Column(name = "PRS_CMPR", nullable = false, length = 1)
	public String getPrsCmpr() {
		return this.prsCmpr;
	}

	public void setPrsCmpr(String prsCmpr) {
		this.prsCmpr = prsCmpr;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((prsAaca == null) ? 0 : prsAaca.hashCode());
		result = prime * result + ((prsAace == null) ? 0 : prsAace.hashCode());
		result = prime * result + ((prsAamb == null) ? 0 : prsAamb.hashCode());
		result = prime * result + ((prsAcce == null) ? 0 : prsAcce.hashCode());
		result = prime * result + ((prsAdan == null) ? 0 : prsAdan.hashCode());
		result = prime * result + ((prsAdrp == null) ? 0 : prsAdrp.hashCode());
		result = prime * result + ((prsAfan == null) ? 0 : prsAfan.hashCode());
		result = prime * result + ((prsAfat == null) ? 0 : prsAfat.hashCode());
		result = prime * result + ((prsAfen == null) ? 0 : prsAfen.hashCode());
		result = prime * result + ((prsAfnp == null) ? 0 : prsAfnp.hashCode());
		result = prime * result + ((prsAfpn == null) ? 0 : prsAfpn.hashCode());
		result = prime * result + ((prsAfpt == null) ? 0 : prsAfpt.hashCode());
		result = prime * result + ((prsAfve == null) ? 0 : prsAfve.hashCode());
		result = prime * result + ((prsAfvn == null) ? 0 : prsAfvn.hashCode());
		result = prime * result + ((prsAgna == null) ? 0 : prsAgna.hashCode());
		result = prime * result + ((prsAgst == null) ? 0 : prsAgst.hashCode());
		result = prime * result
				+ ((prsAjpcp == null) ? 0 : prsAjpcp.hashCode());
		result = prime * result + ((prsAmpi == null) ? 0 : prsAmpi.hashCode());
		result = prime * result + ((prsAmpr == null) ? 0 : prsAmpr.hashCode());
		result = prime * result + ((prsApca == null) ? 0 : prsApca.hashCode());
		result = prime * result + ((prsApnf == null) ? 0 : prsApnf.hashCode());
		result = prime * result + ((prsApvm == null) ? 0 : prsApvm.hashCode());
		result = prime * result + ((prsApvs == null) ? 0 : prsApvs.hashCode());
		result = prime * result + ((prsArnf == null) ? 0 : prsArnf.hashCode());
		result = prime * result + ((prsBapf == null) ? 0 : prsBapf.hashCode());
		result = prime * result + ((prsCcmt == null) ? 0 : prsCcmt.hashCode());
		result = prime * result + ((prsCcrm == null) ? 0 : prsCcrm.hashCode());
		result = prime * result + ((prsCdcp == null) ? 0 : prsCdcp.hashCode());
		result = prime * result + ((prsChqa == null) ? 0 : prsChqa.hashCode());
		result = prime * result + ((prsChqb == null) ? 0 : prsChqb.hashCode());
		result = prime * result + ((prsChqc == null) ? 0 : prsChqc.hashCode());
		result = prime * result + ((prsChql == null) ? 0 : prsChql.hashCode());
		result = prime * result + ((prsChqn == null) ? 0 : prsChqn.hashCode());
		result = prime * result + ((prsCmpr == null) ? 0 : prsCmpr.hashCode());
		result = prime * result + ((prsCocm == null) ? 0 : prsCocm.hashCode());
		result = prime * result + ((prsCpsp == null) ? 0 : prsCpsp.hashCode());
		result = prime * result + ((prsCtam == null) ? 0 : prsCtam.hashCode());
		result = prime * result + ((prsCtb == null) ? 0 : prsCtb.hashCode());
		result = prime * result + ((prsCvb == null) ? 0 : prsCvb.hashCode());
		result = prime * result + ((prsDcm == null) ? 0 : prsDcm.hashCode());
		result = prime * result + ((prsDlpm == null) ? 0 : prsDlpm.hashCode());
		result = prime * result + ((prsDlpn == null) ? 0 : prsDlpn.hashCode());
		result = prime * result + ((prsDlqm == null) ? 0 : prsDlqm.hashCode());
		result = prime * result + ((prsDlqn == null) ? 0 : prsDlqn.hashCode());
		result = prime * result + ((prsDtri == null) ? 0 : prsDtri.hashCode());
		result = prime * result + ((prsDuec == null) ? 0 : prsDuec.hashCode());
		result = prime * result + ((prsEbt == null) ? 0 : prsEbt.hashCode());
		result = prime * result + ((prsEcn == null) ? 0 : prsEcn.hashCode());
		result = prime * result + ((prsEctd == null) ? 0 : prsEctd.hashCode());
		result = prime * result + ((prsEeac == null) ? 0 : prsEeac.hashCode());
		result = prime * result + ((prsEemt == null) ? 0 : prsEemt.hashCode());
		result = prime * result + ((prsEfsc == null) ? 0 : prsEfsc.hashCode());
		result = prime * result + ((prsEqkk == null) ? 0 : prsEqkk.hashCode());
		result = prime * result + ((prsEqsc == null) ? 0 : prsEqsc.hashCode());
		result = prime * result + ((prsEsm == null) ? 0 : prsEsm.hashCode());
		result = prime * result + ((prsEssp == null) ? 0 : prsEssp.hashCode());
		result = prime * result + ((prsEtdh == null) ? 0 : prsEtdh.hashCode());
		result = prime * result + ((prsEtdu == null) ? 0 : prsEtdu.hashCode());
		result = prime * result + ((prsEtfu == null) ? 0 : prsEtfu.hashCode());
		result = prime * result + ((prsEtnu == null) ? 0 : prsEtnu.hashCode());
		result = prime * result + ((prsEtod == null) ? 0 : prsEtod.hashCode());
		result = prime * result + ((prsFabd == null) ? 0 : prsFabd.hashCode());
		result = prime * result + ((prsFacp == null) ? 0 : prsFacp.hashCode());
		result = prime * result + ((prsFccc == null) ? 0 : prsFccc.hashCode());
		result = prime * result + ((prsFcco == null) ? 0 : prsFcco.hashCode());
		result = prime * result + ((prsFdpr == null) ? 0 : prsFdpr.hashCode());
		result = prime * result + ((prsFdsb == null) ? 0 : prsFdsb.hashCode());
		result = prime * result + ((prsFeda == null) ? 0 : prsFeda.hashCode());
		result = prime * result + ((prsFgcj == null) ? 0 : prsFgcj.hashCode());
		result = prime * result + ((prsFglc == null) ? 0 : prsFglc.hashCode());
		result = prime * result + ((prsFimp == null) ? 0 : prsFimp.hashCode());
		result = prime * result + ((prsFips == null) ? 0 : prsFips.hashCode());
		result = prime * result + ((prsFncs == null) ? 0 : prsFncs.hashCode());
		result = prime * result + ((prsFolf == null) ? 0 : prsFolf.hashCode());
		result = prime * result + ((prsFpco == null) ? 0 : prsFpco.hashCode());
		result = prime * result + ((prsFpct == null) ? 0 : prsFpct.hashCode());
		result = prime * result + ((prsFpts == null) ? 0 : prsFpts.hashCode());
		result = prime * result + ((prsFrch == null) ? 0 : prsFrch.hashCode());
		result = prime * result + ((prsFrco == null) ? 0 : prsFrco.hashCode());
		result = prime * result + ((prsFstp == null) ? 0 : prsFstp.hashCode());
		result = prime * result + ((prsFtpp == null) ? 0 : prsFtpp.hashCode());
		result = prime * result + ((prsFuas == null) ? 0 : prsFuas.hashCode());
		result = prime * result + ((prsGacp == null) ? 0 : prsGacp.hashCode());
		result = prime * result + ((prsGccf == null) ? 0 : prsGccf.hashCode());
		result = prime * result + ((prsGccs == null) ? 0 : prsGccs.hashCode());
		result = prime * result + ((prsGccv == null) ? 0 : prsGccv.hashCode());
		result = prime * result + ((prsGcli == null) ? 0 : prsGcli.hashCode());
		result = prime * result + ((prsGcoi == null) ? 0 : prsGcoi.hashCode());
		result = prime * result + ((prsGcri == null) ? 0 : prsGcri.hashCode());
		result = prime * result + ((prsGcrp == null) ? 0 : prsGcrp.hashCode());
		result = prime * result + ((prsGcse == null) ? 0 : prsGcse.hashCode());
		result = prime * result + ((prsGcvn == null) ? 0 : prsGcvn.hashCode());
		result = prime * result + ((prsGcvp == null) ? 0 : prsGcvp.hashCode());
		result = prime * result + ((prsGfch == null) ? 0 : prsGfch.hashCode());
		result = prime * result + ((prsGfcr == null) ? 0 : prsGfcr.hashCode());
		result = prime * result + ((prsGfcs == null) ? 0 : prsGfcs.hashCode());
		result = prime * result + ((prsGfct == null) ? 0 : prsGfct.hashCode());
		result = prime * result + ((prsGfdi == null) ? 0 : prsGfdi.hashCode());
		result = prime * result + ((prsGffl == null) ? 0 : prsGffl.hashCode());
		result = prime * result + ((prsGfoi == null) ? 0 : prsGfoi.hashCode());
		result = prime * result + ((prsGfpr == null) ? 0 : prsGfpr.hashCode());
		result = prime * result + ((prsGftp == null) ? 0 : prsGftp.hashCode());
		result = prime * result + ((prsGfts == null) ? 0 : prsGfts.hashCode());
		result = prime * result + ((prsGftu == null) ? 0 : prsGftu.hashCode());
		result = prime * result + ((prsGfui == null) ? 0 : prsGfui.hashCode());
		result = prime * result + ((prsGicf == null) ? 0 : prsGicf.hashCode());
		result = prime * result + ((prsGicv == null) ? 0 : prsGicv.hashCode());
		result = prime * result + ((prsGidc == null) ? 0 : prsGidc.hashCode());
		result = prime * result + ((prsGipf == null) ? 0 : prsGipf.hashCode());
		result = prime * result + ((prsGisc == null) ? 0 : prsGisc.hashCode());
		result = prime * result + ((prsGlbc == null) ? 0 : prsGlbc.hashCode());
		result = prime * result + ((prsGlbr == null) ? 0 : prsGlbr.hashCode());
		result = prime * result + ((prsGlic == null) ? 0 : prsGlic.hashCode());
		result = prime * result + ((prsGlvc == null) ? 0 : prsGlvc.hashCode());
		result = prime * result + ((prsGmct == null) ? 0 : prsGmct.hashCode());
		result = prime * result + ((prsGmoi == null) ? 0 : prsGmoi.hashCode());
		result = prime * result + ((prsGncq == null) ? 0 : prsGncq.hashCode());
		result = prime * result + ((prsGnfq == null) ? 0 : prsGnfq.hashCode());
		result = prime * result + ((prsGops == null) ? 0 : prsGops.hashCode());
		result = prime * result + ((prsGpcg == null) ? 0 : prsGpcg.hashCode());
		result = prime * result + ((prsGpri == null) ? 0 : prsGpri.hashCode());
		result = prime * result + ((prsGrd == null) ? 0 : prsGrd.hashCode());
		result = prime * result + ((prsGrei == null) ? 0 : prsGrei.hashCode());
		result = prime * result + ((prsGrpi == null) ? 0 : prsGrpi.hashCode());
		result = prime * result + ((prsGscl == null) ? 0 : prsGscl.hashCode());
		result = prime * result + ((prsGsde == null) ? 0 : prsGsde.hashCode());
		result = prime * result + ((prsGsge == null) ? 0 : prsGsge.hashCode());
		result = prime * result + ((prsGskn == null) ? 0 : prsGskn.hashCode());
		result = prime * result + ((prsGtri == null) ? 0 : prsGtri.hashCode());
		result = prime * result + ((prsGvum == null) ? 0 : prsGvum.hashCode());
		result = prime * result + ((prsHism == null) ? 0 : prsHism.hashCode());
		result = prime * result + ((prsIcac == null) ? 0 : prsIcac.hashCode());
		result = prime * result + ((prsIchc == null) ? 0 : prsIchc.hashCode());
		result = prime * result + ((prsImec == null) ? 0 : prsImec.hashCode());
		result = prime * result + ((prsInpm == null) ? 0 : prsInpm.hashCode());
		result = prime * result + ((prsIomc == null) ? 0 : prsIomc.hashCode());
		result = prime * result + ((prsIpo == null) ? 0 : prsIpo.hashCode());
		result = prime * result + ((prsIprc == null) ? 0 : prsIprc.hashCode());
		result = prime * result + ((prsIpv == null) ? 0 : prsIpv.hashCode());
		result = prime * result + ((prsIpvc == null) ? 0 : prsIpvc.hashCode());
		result = prime * result + ((prsIrmc == null) ? 0 : prsIrmc.hashCode());
		result = prime * result + ((prsIsvv == null) ? 0 : prsIsvv.hashCode());
		result = prime * result + ((prsItec == null) ? 0 : prsItec.hashCode());
		result = prime * result + ((prsIvec == null) ? 0 : prsIvec.hashCode());
		result = prime * result + ((prsLvpr == null) ? 0 : prsLvpr.hashCode());
		result = prime * result + ((prsLvqp == null) ? 0 : prsLvqp.hashCode());
		result = prime * result + ((prsLzt == null) ? 0 : prsLzt.hashCode());
		result = prime * result + ((prsMdc == null) ? 0 : prsMdc.hashCode());
		result = prime * result + ((prsMft == null) ? 0 : prsMft.hashCode());
		result = prime * result + ((prsOccd == null) ? 0 : prsOccd.hashCode());
		result = prime * result + ((prsOipc == null) ? 0 : prsOipc.hashCode());
		result = prime * result + ((prsOpsg == null) ? 0 : prsOpsg.hashCode());
		result = prime * result + ((prsPaqr == null) ? 0 : prsPaqr.hashCode());
		result = prime * result + ((prsPbmr == null) ? 0 : prsPbmr.hashCode());
		result = prime * result + ((prsPeca == null) ? 0 : prsPeca.hashCode());
		result = prime * result + ((prsPimc == null) ? 0 : prsPimc.hashCode());
		result = prime * result + ((prsPpdt == null) ? 0 : prsPpdt.hashCode());
		result = prime * result + ((prsPsvo == null) ? 0 : prsPsvo.hashCode());
		result = prime * result + ((prsQtcd == null) ? 0 : prsQtcd.hashCode());
		result = prime * result + ((prsRdpv == null) ? 0 : prsRdpv.hashCode());
		result = prime * result + ((prsSict == null) ? 0 : prsSict.hashCode());
		result = prime * result + ((prsStce == null) ? 0 : prsStce.hashCode());
		result = prime * result + ((prsTcb == null) ? 0 : prsTcb.hashCode());
		result = prime * result + ((prsTcct == null) ? 0 : prsTcct.hashCode());
		result = prime * result + ((prsTclp == null) ? 0 : prsTclp.hashCode());
		result = prime * result + ((prsTioc == null) ? 0 : prsTioc.hashCode());
		result = prime * result + ((prsTvf == null) ? 0 : prsTvf.hashCode());
		result = prime * result + ((prsUapc == null) ? 0 : prsUapc.hashCode());
		result = prime * result + ((prsUnd == null) ? 0 : prsUnd.hashCode());
		result = prime * result + ((prsVfp == null) ? 0 : prsVfp.hashCode());
		result = prime * result + ((prsVmci == null) ? 0 : prsVmci.hashCode());
		result = prime * result + ((prsVnfe == null) ? 0 : prsVnfe.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof PropSistemaId)) {
			return false;
		}
		PropSistemaId other = (PropSistemaId) obj;
		if (prsAaca == null) {
			if (other.prsAaca != null) {
				return false;
			}
		} else if (!prsAaca.equals(other.prsAaca)) {
			return false;
		}
		if (prsAace == null) {
			if (other.prsAace != null) {
				return false;
			}
		} else if (!prsAace.equals(other.prsAace)) {
			return false;
		}
		if (prsAamb == null) {
			if (other.prsAamb != null) {
				return false;
			}
		} else if (!prsAamb.equals(other.prsAamb)) {
			return false;
		}
		if (prsAcce == null) {
			if (other.prsAcce != null) {
				return false;
			}
		} else if (!prsAcce.equals(other.prsAcce)) {
			return false;
		}
		if (prsAdan == null) {
			if (other.prsAdan != null) {
				return false;
			}
		} else if (!prsAdan.equals(other.prsAdan)) {
			return false;
		}
		if (prsAdrp == null) {
			if (other.prsAdrp != null) {
				return false;
			}
		} else if (!prsAdrp.equals(other.prsAdrp)) {
			return false;
		}
		if (prsAfan == null) {
			if (other.prsAfan != null) {
				return false;
			}
		} else if (!prsAfan.equals(other.prsAfan)) {
			return false;
		}
		if (prsAfat == null) {
			if (other.prsAfat != null) {
				return false;
			}
		} else if (!prsAfat.equals(other.prsAfat)) {
			return false;
		}
		if (prsAfen == null) {
			if (other.prsAfen != null) {
				return false;
			}
		} else if (!prsAfen.equals(other.prsAfen)) {
			return false;
		}
		if (prsAfnp == null) {
			if (other.prsAfnp != null) {
				return false;
			}
		} else if (!prsAfnp.equals(other.prsAfnp)) {
			return false;
		}
		if (prsAfpn == null) {
			if (other.prsAfpn != null) {
				return false;
			}
		} else if (!prsAfpn.equals(other.prsAfpn)) {
			return false;
		}
		if (prsAfpt == null) {
			if (other.prsAfpt != null) {
				return false;
			}
		} else if (!prsAfpt.equals(other.prsAfpt)) {
			return false;
		}
		if (prsAfve == null) {
			if (other.prsAfve != null) {
				return false;
			}
		} else if (!prsAfve.equals(other.prsAfve)) {
			return false;
		}
		if (prsAfvn == null) {
			if (other.prsAfvn != null) {
				return false;
			}
		} else if (!prsAfvn.equals(other.prsAfvn)) {
			return false;
		}
		if (prsAgna == null) {
			if (other.prsAgna != null) {
				return false;
			}
		} else if (!prsAgna.equals(other.prsAgna)) {
			return false;
		}
		if (prsAgst == null) {
			if (other.prsAgst != null) {
				return false;
			}
		} else if (!prsAgst.equals(other.prsAgst)) {
			return false;
		}
		if (prsAjpcp == null) {
			if (other.prsAjpcp != null) {
				return false;
			}
		} else if (!prsAjpcp.equals(other.prsAjpcp)) {
			return false;
		}
		if (prsAmpi == null) {
			if (other.prsAmpi != null) {
				return false;
			}
		} else if (!prsAmpi.equals(other.prsAmpi)) {
			return false;
		}
		if (prsAmpr == null) {
			if (other.prsAmpr != null) {
				return false;
			}
		} else if (!prsAmpr.equals(other.prsAmpr)) {
			return false;
		}
		if (prsApca == null) {
			if (other.prsApca != null) {
				return false;
			}
		} else if (!prsApca.equals(other.prsApca)) {
			return false;
		}
		if (prsApnf == null) {
			if (other.prsApnf != null) {
				return false;
			}
		} else if (!prsApnf.equals(other.prsApnf)) {
			return false;
		}
		if (prsApvm == null) {
			if (other.prsApvm != null) {
				return false;
			}
		} else if (!prsApvm.equals(other.prsApvm)) {
			return false;
		}
		if (prsApvs == null) {
			if (other.prsApvs != null) {
				return false;
			}
		} else if (!prsApvs.equals(other.prsApvs)) {
			return false;
		}
		if (prsArnf == null) {
			if (other.prsArnf != null) {
				return false;
			}
		} else if (!prsArnf.equals(other.prsArnf)) {
			return false;
		}
		if (prsBapf == null) {
			if (other.prsBapf != null) {
				return false;
			}
		} else if (!prsBapf.equals(other.prsBapf)) {
			return false;
		}
		if (prsCcmt == null) {
			if (other.prsCcmt != null) {
				return false;
			}
		} else if (!prsCcmt.equals(other.prsCcmt)) {
			return false;
		}
		if (prsCcrm == null) {
			if (other.prsCcrm != null) {
				return false;
			}
		} else if (!prsCcrm.equals(other.prsCcrm)) {
			return false;
		}
		if (prsCdcp == null) {
			if (other.prsCdcp != null) {
				return false;
			}
		} else if (!prsCdcp.equals(other.prsCdcp)) {
			return false;
		}
		if (prsChqa == null) {
			if (other.prsChqa != null) {
				return false;
			}
		} else if (!prsChqa.equals(other.prsChqa)) {
			return false;
		}
		if (prsChqb == null) {
			if (other.prsChqb != null) {
				return false;
			}
		} else if (!prsChqb.equals(other.prsChqb)) {
			return false;
		}
		if (prsChqc == null) {
			if (other.prsChqc != null) {
				return false;
			}
		} else if (!prsChqc.equals(other.prsChqc)) {
			return false;
		}
		if (prsChql == null) {
			if (other.prsChql != null) {
				return false;
			}
		} else if (!prsChql.equals(other.prsChql)) {
			return false;
		}
		if (prsChqn == null) {
			if (other.prsChqn != null) {
				return false;
			}
		} else if (!prsChqn.equals(other.prsChqn)) {
			return false;
		}
		if (prsCmpr == null) {
			if (other.prsCmpr != null) {
				return false;
			}
		} else if (!prsCmpr.equals(other.prsCmpr)) {
			return false;
		}
		if (prsCocm == null) {
			if (other.prsCocm != null) {
				return false;
			}
		} else if (!prsCocm.equals(other.prsCocm)) {
			return false;
		}
		if (prsCpsp == null) {
			if (other.prsCpsp != null) {
				return false;
			}
		} else if (!prsCpsp.equals(other.prsCpsp)) {
			return false;
		}
		if (prsCtam == null) {
			if (other.prsCtam != null) {
				return false;
			}
		} else if (!prsCtam.equals(other.prsCtam)) {
			return false;
		}
		if (prsCtb == null) {
			if (other.prsCtb != null) {
				return false;
			}
		} else if (!prsCtb.equals(other.prsCtb)) {
			return false;
		}
		if (prsCvb == null) {
			if (other.prsCvb != null) {
				return false;
			}
		} else if (!prsCvb.equals(other.prsCvb)) {
			return false;
		}
		if (prsDcm == null) {
			if (other.prsDcm != null) {
				return false;
			}
		} else if (!prsDcm.equals(other.prsDcm)) {
			return false;
		}
		if (prsDlpm == null) {
			if (other.prsDlpm != null) {
				return false;
			}
		} else if (!prsDlpm.equals(other.prsDlpm)) {
			return false;
		}
		if (prsDlpn == null) {
			if (other.prsDlpn != null) {
				return false;
			}
		} else if (!prsDlpn.equals(other.prsDlpn)) {
			return false;
		}
		if (prsDlqm == null) {
			if (other.prsDlqm != null) {
				return false;
			}
		} else if (!prsDlqm.equals(other.prsDlqm)) {
			return false;
		}
		if (prsDlqn == null) {
			if (other.prsDlqn != null) {
				return false;
			}
		} else if (!prsDlqn.equals(other.prsDlqn)) {
			return false;
		}
		if (prsDtri == null) {
			if (other.prsDtri != null) {
				return false;
			}
		} else if (!prsDtri.equals(other.prsDtri)) {
			return false;
		}
		if (prsDuec == null) {
			if (other.prsDuec != null) {
				return false;
			}
		} else if (!prsDuec.equals(other.prsDuec)) {
			return false;
		}
		if (prsEbt == null) {
			if (other.prsEbt != null) {
				return false;
			}
		} else if (!prsEbt.equals(other.prsEbt)) {
			return false;
		}
		if (prsEcn == null) {
			if (other.prsEcn != null) {
				return false;
			}
		} else if (!prsEcn.equals(other.prsEcn)) {
			return false;
		}
		if (prsEctd == null) {
			if (other.prsEctd != null) {
				return false;
			}
		} else if (!prsEctd.equals(other.prsEctd)) {
			return false;
		}
		if (prsEeac == null) {
			if (other.prsEeac != null) {
				return false;
			}
		} else if (!prsEeac.equals(other.prsEeac)) {
			return false;
		}
		if (prsEemt == null) {
			if (other.prsEemt != null) {
				return false;
			}
		} else if (!prsEemt.equals(other.prsEemt)) {
			return false;
		}
		if (prsEfsc == null) {
			if (other.prsEfsc != null) {
				return false;
			}
		} else if (!prsEfsc.equals(other.prsEfsc)) {
			return false;
		}
		if (prsEqkk == null) {
			if (other.prsEqkk != null) {
				return false;
			}
		} else if (!prsEqkk.equals(other.prsEqkk)) {
			return false;
		}
		if (prsEqsc == null) {
			if (other.prsEqsc != null) {
				return false;
			}
		} else if (!prsEqsc.equals(other.prsEqsc)) {
			return false;
		}
		if (prsEsm == null) {
			if (other.prsEsm != null) {
				return false;
			}
		} else if (!prsEsm.equals(other.prsEsm)) {
			return false;
		}
		if (prsEssp == null) {
			if (other.prsEssp != null) {
				return false;
			}
		} else if (!prsEssp.equals(other.prsEssp)) {
			return false;
		}
		if (prsEtdh == null) {
			if (other.prsEtdh != null) {
				return false;
			}
		} else if (!prsEtdh.equals(other.prsEtdh)) {
			return false;
		}
		if (prsEtdu == null) {
			if (other.prsEtdu != null) {
				return false;
			}
		} else if (!prsEtdu.equals(other.prsEtdu)) {
			return false;
		}
		if (prsEtfu == null) {
			if (other.prsEtfu != null) {
				return false;
			}
		} else if (!prsEtfu.equals(other.prsEtfu)) {
			return false;
		}
		if (prsEtnu == null) {
			if (other.prsEtnu != null) {
				return false;
			}
		} else if (!prsEtnu.equals(other.prsEtnu)) {
			return false;
		}
		if (prsEtod == null) {
			if (other.prsEtod != null) {
				return false;
			}
		} else if (!prsEtod.equals(other.prsEtod)) {
			return false;
		}
		if (prsFabd == null) {
			if (other.prsFabd != null) {
				return false;
			}
		} else if (!prsFabd.equals(other.prsFabd)) {
			return false;
		}
		if (prsFacp == null) {
			if (other.prsFacp != null) {
				return false;
			}
		} else if (!prsFacp.equals(other.prsFacp)) {
			return false;
		}
		if (prsFccc == null) {
			if (other.prsFccc != null) {
				return false;
			}
		} else if (!prsFccc.equals(other.prsFccc)) {
			return false;
		}
		if (prsFcco == null) {
			if (other.prsFcco != null) {
				return false;
			}
		} else if (!prsFcco.equals(other.prsFcco)) {
			return false;
		}
		if (prsFdpr == null) {
			if (other.prsFdpr != null) {
				return false;
			}
		} else if (!prsFdpr.equals(other.prsFdpr)) {
			return false;
		}
		if (prsFdsb == null) {
			if (other.prsFdsb != null) {
				return false;
			}
		} else if (!prsFdsb.equals(other.prsFdsb)) {
			return false;
		}
		if (prsFeda == null) {
			if (other.prsFeda != null) {
				return false;
			}
		} else if (!prsFeda.equals(other.prsFeda)) {
			return false;
		}
		if (prsFgcj == null) {
			if (other.prsFgcj != null) {
				return false;
			}
		} else if (!prsFgcj.equals(other.prsFgcj)) {
			return false;
		}
		if (prsFglc == null) {
			if (other.prsFglc != null) {
				return false;
			}
		} else if (!prsFglc.equals(other.prsFglc)) {
			return false;
		}
		if (prsFimp == null) {
			if (other.prsFimp != null) {
				return false;
			}
		} else if (!prsFimp.equals(other.prsFimp)) {
			return false;
		}
		if (prsFips == null) {
			if (other.prsFips != null) {
				return false;
			}
		} else if (!prsFips.equals(other.prsFips)) {
			return false;
		}
		if (prsFncs == null) {
			if (other.prsFncs != null) {
				return false;
			}
		} else if (!prsFncs.equals(other.prsFncs)) {
			return false;
		}
		if (prsFolf == null) {
			if (other.prsFolf != null) {
				return false;
			}
		} else if (!prsFolf.equals(other.prsFolf)) {
			return false;
		}
		if (prsFpco == null) {
			if (other.prsFpco != null) {
				return false;
			}
		} else if (!prsFpco.equals(other.prsFpco)) {
			return false;
		}
		if (prsFpct == null) {
			if (other.prsFpct != null) {
				return false;
			}
		} else if (!prsFpct.equals(other.prsFpct)) {
			return false;
		}
		if (prsFpts == null) {
			if (other.prsFpts != null) {
				return false;
			}
		} else if (!prsFpts.equals(other.prsFpts)) {
			return false;
		}
		if (prsFrch == null) {
			if (other.prsFrch != null) {
				return false;
			}
		} else if (!prsFrch.equals(other.prsFrch)) {
			return false;
		}
		if (prsFrco == null) {
			if (other.prsFrco != null) {
				return false;
			}
		} else if (!prsFrco.equals(other.prsFrco)) {
			return false;
		}
		if (prsFstp == null) {
			if (other.prsFstp != null) {
				return false;
			}
		} else if (!prsFstp.equals(other.prsFstp)) {
			return false;
		}
		if (prsFtpp == null) {
			if (other.prsFtpp != null) {
				return false;
			}
		} else if (!prsFtpp.equals(other.prsFtpp)) {
			return false;
		}
		if (prsFuas == null) {
			if (other.prsFuas != null) {
				return false;
			}
		} else if (!prsFuas.equals(other.prsFuas)) {
			return false;
		}
		if (prsGacp == null) {
			if (other.prsGacp != null) {
				return false;
			}
		} else if (!prsGacp.equals(other.prsGacp)) {
			return false;
		}
		if (prsGccf == null) {
			if (other.prsGccf != null) {
				return false;
			}
		} else if (!prsGccf.equals(other.prsGccf)) {
			return false;
		}
		if (prsGccs == null) {
			if (other.prsGccs != null) {
				return false;
			}
		} else if (!prsGccs.equals(other.prsGccs)) {
			return false;
		}
		if (prsGccv == null) {
			if (other.prsGccv != null) {
				return false;
			}
		} else if (!prsGccv.equals(other.prsGccv)) {
			return false;
		}
		if (prsGcli == null) {
			if (other.prsGcli != null) {
				return false;
			}
		} else if (!prsGcli.equals(other.prsGcli)) {
			return false;
		}
		if (prsGcoi == null) {
			if (other.prsGcoi != null) {
				return false;
			}
		} else if (!prsGcoi.equals(other.prsGcoi)) {
			return false;
		}
		if (prsGcri == null) {
			if (other.prsGcri != null) {
				return false;
			}
		} else if (!prsGcri.equals(other.prsGcri)) {
			return false;
		}
		if (prsGcrp == null) {
			if (other.prsGcrp != null) {
				return false;
			}
		} else if (!prsGcrp.equals(other.prsGcrp)) {
			return false;
		}
		if (prsGcse == null) {
			if (other.prsGcse != null) {
				return false;
			}
		} else if (!prsGcse.equals(other.prsGcse)) {
			return false;
		}
		if (prsGcvn == null) {
			if (other.prsGcvn != null) {
				return false;
			}
		} else if (!prsGcvn.equals(other.prsGcvn)) {
			return false;
		}
		if (prsGcvp == null) {
			if (other.prsGcvp != null) {
				return false;
			}
		} else if (!prsGcvp.equals(other.prsGcvp)) {
			return false;
		}
		if (prsGfch == null) {
			if (other.prsGfch != null) {
				return false;
			}
		} else if (!prsGfch.equals(other.prsGfch)) {
			return false;
		}
		if (prsGfcr == null) {
			if (other.prsGfcr != null) {
				return false;
			}
		} else if (!prsGfcr.equals(other.prsGfcr)) {
			return false;
		}
		if (prsGfcs == null) {
			if (other.prsGfcs != null) {
				return false;
			}
		} else if (!prsGfcs.equals(other.prsGfcs)) {
			return false;
		}
		if (prsGfct == null) {
			if (other.prsGfct != null) {
				return false;
			}
		} else if (!prsGfct.equals(other.prsGfct)) {
			return false;
		}
		if (prsGfdi == null) {
			if (other.prsGfdi != null) {
				return false;
			}
		} else if (!prsGfdi.equals(other.prsGfdi)) {
			return false;
		}
		if (prsGffl == null) {
			if (other.prsGffl != null) {
				return false;
			}
		} else if (!prsGffl.equals(other.prsGffl)) {
			return false;
		}
		if (prsGfoi == null) {
			if (other.prsGfoi != null) {
				return false;
			}
		} else if (!prsGfoi.equals(other.prsGfoi)) {
			return false;
		}
		if (prsGfpr == null) {
			if (other.prsGfpr != null) {
				return false;
			}
		} else if (!prsGfpr.equals(other.prsGfpr)) {
			return false;
		}
		if (prsGftp == null) {
			if (other.prsGftp != null) {
				return false;
			}
		} else if (!prsGftp.equals(other.prsGftp)) {
			return false;
		}
		if (prsGfts == null) {
			if (other.prsGfts != null) {
				return false;
			}
		} else if (!prsGfts.equals(other.prsGfts)) {
			return false;
		}
		if (prsGftu == null) {
			if (other.prsGftu != null) {
				return false;
			}
		} else if (!prsGftu.equals(other.prsGftu)) {
			return false;
		}
		if (prsGfui == null) {
			if (other.prsGfui != null) {
				return false;
			}
		} else if (!prsGfui.equals(other.prsGfui)) {
			return false;
		}
		if (prsGicf == null) {
			if (other.prsGicf != null) {
				return false;
			}
		} else if (!prsGicf.equals(other.prsGicf)) {
			return false;
		}
		if (prsGicv == null) {
			if (other.prsGicv != null) {
				return false;
			}
		} else if (!prsGicv.equals(other.prsGicv)) {
			return false;
		}
		if (prsGidc == null) {
			if (other.prsGidc != null) {
				return false;
			}
		} else if (!prsGidc.equals(other.prsGidc)) {
			return false;
		}
		if (prsGipf == null) {
			if (other.prsGipf != null) {
				return false;
			}
		} else if (!prsGipf.equals(other.prsGipf)) {
			return false;
		}
		if (prsGisc == null) {
			if (other.prsGisc != null) {
				return false;
			}
		} else if (!prsGisc.equals(other.prsGisc)) {
			return false;
		}
		if (prsGlbc == null) {
			if (other.prsGlbc != null) {
				return false;
			}
		} else if (!prsGlbc.equals(other.prsGlbc)) {
			return false;
		}
		if (prsGlbr == null) {
			if (other.prsGlbr != null) {
				return false;
			}
		} else if (!prsGlbr.equals(other.prsGlbr)) {
			return false;
		}
		if (prsGlic == null) {
			if (other.prsGlic != null) {
				return false;
			}
		} else if (!prsGlic.equals(other.prsGlic)) {
			return false;
		}
		if (prsGlvc == null) {
			if (other.prsGlvc != null) {
				return false;
			}
		} else if (!prsGlvc.equals(other.prsGlvc)) {
			return false;
		}
		if (prsGmct == null) {
			if (other.prsGmct != null) {
				return false;
			}
		} else if (!prsGmct.equals(other.prsGmct)) {
			return false;
		}
		if (prsGmoi == null) {
			if (other.prsGmoi != null) {
				return false;
			}
		} else if (!prsGmoi.equals(other.prsGmoi)) {
			return false;
		}
		if (prsGncq == null) {
			if (other.prsGncq != null) {
				return false;
			}
		} else if (!prsGncq.equals(other.prsGncq)) {
			return false;
		}
		if (prsGnfq == null) {
			if (other.prsGnfq != null) {
				return false;
			}
		} else if (!prsGnfq.equals(other.prsGnfq)) {
			return false;
		}
		if (prsGops == null) {
			if (other.prsGops != null) {
				return false;
			}
		} else if (!prsGops.equals(other.prsGops)) {
			return false;
		}
		if (prsGpcg == null) {
			if (other.prsGpcg != null) {
				return false;
			}
		} else if (!prsGpcg.equals(other.prsGpcg)) {
			return false;
		}
		if (prsGpri == null) {
			if (other.prsGpri != null) {
				return false;
			}
		} else if (!prsGpri.equals(other.prsGpri)) {
			return false;
		}
		if (prsGrd == null) {
			if (other.prsGrd != null) {
				return false;
			}
		} else if (!prsGrd.equals(other.prsGrd)) {
			return false;
		}
		if (prsGrei == null) {
			if (other.prsGrei != null) {
				return false;
			}
		} else if (!prsGrei.equals(other.prsGrei)) {
			return false;
		}
		if (prsGrpi == null) {
			if (other.prsGrpi != null) {
				return false;
			}
		} else if (!prsGrpi.equals(other.prsGrpi)) {
			return false;
		}
		if (prsGscl == null) {
			if (other.prsGscl != null) {
				return false;
			}
		} else if (!prsGscl.equals(other.prsGscl)) {
			return false;
		}
		if (prsGsde == null) {
			if (other.prsGsde != null) {
				return false;
			}
		} else if (!prsGsde.equals(other.prsGsde)) {
			return false;
		}
		if (prsGsge == null) {
			if (other.prsGsge != null) {
				return false;
			}
		} else if (!prsGsge.equals(other.prsGsge)) {
			return false;
		}
		if (prsGskn == null) {
			if (other.prsGskn != null) {
				return false;
			}
		} else if (!prsGskn.equals(other.prsGskn)) {
			return false;
		}
		if (prsGtri == null) {
			if (other.prsGtri != null) {
				return false;
			}
		} else if (!prsGtri.equals(other.prsGtri)) {
			return false;
		}
		if (prsGvum == null) {
			if (other.prsGvum != null) {
				return false;
			}
		} else if (!prsGvum.equals(other.prsGvum)) {
			return false;
		}
		if (prsHism == null) {
			if (other.prsHism != null) {
				return false;
			}
		} else if (!prsHism.equals(other.prsHism)) {
			return false;
		}
		if (prsIcac == null) {
			if (other.prsIcac != null) {
				return false;
			}
		} else if (!prsIcac.equals(other.prsIcac)) {
			return false;
		}
		if (prsIchc == null) {
			if (other.prsIchc != null) {
				return false;
			}
		} else if (!prsIchc.equals(other.prsIchc)) {
			return false;
		}
		if (prsImec == null) {
			if (other.prsImec != null) {
				return false;
			}
		} else if (!prsImec.equals(other.prsImec)) {
			return false;
		}
		if (prsInpm == null) {
			if (other.prsInpm != null) {
				return false;
			}
		} else if (!prsInpm.equals(other.prsInpm)) {
			return false;
		}
		if (prsIomc == null) {
			if (other.prsIomc != null) {
				return false;
			}
		} else if (!prsIomc.equals(other.prsIomc)) {
			return false;
		}
		if (prsIpo == null) {
			if (other.prsIpo != null) {
				return false;
			}
		} else if (!prsIpo.equals(other.prsIpo)) {
			return false;
		}
		if (prsIprc == null) {
			if (other.prsIprc != null) {
				return false;
			}
		} else if (!prsIprc.equals(other.prsIprc)) {
			return false;
		}
		if (prsIpv == null) {
			if (other.prsIpv != null) {
				return false;
			}
		} else if (!prsIpv.equals(other.prsIpv)) {
			return false;
		}
		if (prsIpvc == null) {
			if (other.prsIpvc != null) {
				return false;
			}
		} else if (!prsIpvc.equals(other.prsIpvc)) {
			return false;
		}
		if (prsIrmc == null) {
			if (other.prsIrmc != null) {
				return false;
			}
		} else if (!prsIrmc.equals(other.prsIrmc)) {
			return false;
		}
		if (prsIsvv == null) {
			if (other.prsIsvv != null) {
				return false;
			}
		} else if (!prsIsvv.equals(other.prsIsvv)) {
			return false;
		}
		if (prsItec == null) {
			if (other.prsItec != null) {
				return false;
			}
		} else if (!prsItec.equals(other.prsItec)) {
			return false;
		}
		if (prsIvec == null) {
			if (other.prsIvec != null) {
				return false;
			}
		} else if (!prsIvec.equals(other.prsIvec)) {
			return false;
		}
		if (prsLvpr == null) {
			if (other.prsLvpr != null) {
				return false;
			}
		} else if (!prsLvpr.equals(other.prsLvpr)) {
			return false;
		}
		if (prsLvqp == null) {
			if (other.prsLvqp != null) {
				return false;
			}
		} else if (!prsLvqp.equals(other.prsLvqp)) {
			return false;
		}
		if (prsLzt == null) {
			if (other.prsLzt != null) {
				return false;
			}
		} else if (!prsLzt.equals(other.prsLzt)) {
			return false;
		}
		if (prsMdc == null) {
			if (other.prsMdc != null) {
				return false;
			}
		} else if (!prsMdc.equals(other.prsMdc)) {
			return false;
		}
		if (prsMft == null) {
			if (other.prsMft != null) {
				return false;
			}
		} else if (!prsMft.equals(other.prsMft)) {
			return false;
		}
		if (prsOccd == null) {
			if (other.prsOccd != null) {
				return false;
			}
		} else if (!prsOccd.equals(other.prsOccd)) {
			return false;
		}
		if (prsOipc == null) {
			if (other.prsOipc != null) {
				return false;
			}
		} else if (!prsOipc.equals(other.prsOipc)) {
			return false;
		}
		if (prsOpsg == null) {
			if (other.prsOpsg != null) {
				return false;
			}
		} else if (!prsOpsg.equals(other.prsOpsg)) {
			return false;
		}
		if (prsPaqr == null) {
			if (other.prsPaqr != null) {
				return false;
			}
		} else if (!prsPaqr.equals(other.prsPaqr)) {
			return false;
		}
		if (prsPbmr == null) {
			if (other.prsPbmr != null) {
				return false;
			}
		} else if (!prsPbmr.equals(other.prsPbmr)) {
			return false;
		}
		if (prsPeca == null) {
			if (other.prsPeca != null) {
				return false;
			}
		} else if (!prsPeca.equals(other.prsPeca)) {
			return false;
		}
		if (prsPimc == null) {
			if (other.prsPimc != null) {
				return false;
			}
		} else if (!prsPimc.equals(other.prsPimc)) {
			return false;
		}
		if (prsPpdt == null) {
			if (other.prsPpdt != null) {
				return false;
			}
		} else if (!prsPpdt.equals(other.prsPpdt)) {
			return false;
		}
		if (prsPsvo == null) {
			if (other.prsPsvo != null) {
				return false;
			}
		} else if (!prsPsvo.equals(other.prsPsvo)) {
			return false;
		}
		if (prsQtcd == null) {
			if (other.prsQtcd != null) {
				return false;
			}
		} else if (!prsQtcd.equals(other.prsQtcd)) {
			return false;
		}
		if (prsRdpv == null) {
			if (other.prsRdpv != null) {
				return false;
			}
		} else if (!prsRdpv.equals(other.prsRdpv)) {
			return false;
		}
		if (prsSict == null) {
			if (other.prsSict != null) {
				return false;
			}
		} else if (!prsSict.equals(other.prsSict)) {
			return false;
		}
		if (prsStce == null) {
			if (other.prsStce != null) {
				return false;
			}
		} else if (!prsStce.equals(other.prsStce)) {
			return false;
		}
		if (prsTcb == null) {
			if (other.prsTcb != null) {
				return false;
			}
		} else if (!prsTcb.equals(other.prsTcb)) {
			return false;
		}
		if (prsTcct == null) {
			if (other.prsTcct != null) {
				return false;
			}
		} else if (!prsTcct.equals(other.prsTcct)) {
			return false;
		}
		if (prsTclp == null) {
			if (other.prsTclp != null) {
				return false;
			}
		} else if (!prsTclp.equals(other.prsTclp)) {
			return false;
		}
		if (prsTioc == null) {
			if (other.prsTioc != null) {
				return false;
			}
		} else if (!prsTioc.equals(other.prsTioc)) {
			return false;
		}
		if (prsTvf == null) {
			if (other.prsTvf != null) {
				return false;
			}
		} else if (!prsTvf.equals(other.prsTvf)) {
			return false;
		}
		if (prsUapc == null) {
			if (other.prsUapc != null) {
				return false;
			}
		} else if (!prsUapc.equals(other.prsUapc)) {
			return false;
		}
		if (prsUnd == null) {
			if (other.prsUnd != null) {
				return false;
			}
		} else if (!prsUnd.equals(other.prsUnd)) {
			return false;
		}
		if (prsVfp == null) {
			if (other.prsVfp != null) {
				return false;
			}
		} else if (!prsVfp.equals(other.prsVfp)) {
			return false;
		}
		if (prsVmci == null) {
			if (other.prsVmci != null) {
				return false;
			}
		} else if (!prsVmci.equals(other.prsVmci)) {
			return false;
		}
		if (prsVnfe == null) {
			if (other.prsVnfe != null) {
				return false;
			}
		} else if (!prsVnfe.equals(other.prsVnfe)) {
			return false;
		}
		return true;
	}

	
	

}
