package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Representante generated by hbm2java
 */
@Entity
@Table(name = "REPRESENTANTE")
public class Representante implements java.io.Serializable {


	private static final long serialVersionUID = 2939668333475644266L;
	private RepresentanteId id;
	private ColaboradorEmpresa colaboradorEmpresa;
	private Filial filial;
	private Date repDti;
	private Date repDtf;
	private Character repFpa;
	private Character repFap;
	private String repOb1;
	private String repOb2;
	private String repOb3;
	private BigDecimal repPev;
	private int repFpc;
	private char repCom;
	private char repCoj;
	private char repCoe;
	private char repDac;
	private BigDecimal repPdc;
	private char repTip;
	private String repSen;
	private char repBrv;
	private String repSfl;
	private BigDecimal repPir;
	/*private Set<Cheque> cheques = new HashSet<Cheque>(0);
	private Set<Contratoservico> contratoservicos = new HashSet<Contratoservico>(0);
	private Set<Representanteempresapauta> representanteempresapautas = new HashSet<Representanteempresapauta>(0);
	private Set<Custofixo> custofixos = new HashSet<Custofixo>(0);
	private Set<Representantepreposto> representanteprepostos = new HashSet<Representantepreposto>(0);
	private Set<Notafiscal> notafiscals = new HashSet<Notafiscal>(0);
	private Set<Pagar> pagars = new HashSet<Pagar>(0);
	private Set<Receber> recebers = new HashSet<Receber>(0);*/
	private Set<ClienteRepresentante> clienteRepresentantes = new HashSet<ClienteRepresentante>(0);
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Representante() {
	}

	//	public Representante(ColaboradorEmpresa colaboradorEmpresa, Filial filial,
	//			BigDecimal repPev, int repFpc, char repCom, char repCoj,
	//			char repCoe, char repDac, BigDecimal repPdc, char repTip,
	//			char repBrv, BigDecimal repPir) {
	//		this.colaboradorEmpresa = colaboradorEmpresa;
	//		this.filial = filial;
	//		this.repPev = repPev;
	//		this.repFpc = repFpc;
	//		this.repCom = repCom;
	//		this.repCoj = repCoj;
	//		this.repCoe = repCoe;
	//		this.repDac = repDac;
	//		this.repPdc = repPdc;
	//		this.repTip = repTip;
	//		this.repBrv = repBrv;
	//		this.repPir = repPir;
	//	}

	/*public Representante(ColaboradorEmpresa colaboradorEmpresa, Filial filial,
			Date repDti, Date repDtf, Character repFpa, Character repFap,
			String repOb1, String repOb2, String repOb3, BigDecimal repPev,
			int repFpc, char repCom, char repCoj, char repCoe, char repDac,
			BigDecimal repPdc, char repTip, String repSen, char repBrv,
			String repSfl, BigDecimal repPir, Set<Cheque> cheques,
			Set<Contratoservico> contratoservicos,
			Set<Representanteempresapauta> representanteempresapautas,
			Set<Custofixo> custofixos,
			Set<Representantepreposto> representanteprepostos,
			Set<Notafiscal> notafiscals, Set<Pagar> pagars,
			Set<Clienterepresentante> clienterepresentantes,
			Set<Pedido> pedidos, Set<Receber> recebers) {
		this.colaboradorEmpresa = colaboradorEmpresa;
		this.filial = filial;
		this.repDti = repDti;
		this.repDtf = repDtf;
		this.repFpa = repFpa;
		this.repFap = repFap;
		this.repOb1 = repOb1;
		this.repOb2 = repOb2;
		this.repOb3 = repOb3;
		this.repPev = repPev;
		this.repFpc = repFpc;
		this.repCom = repCom;
		this.repCoj = repCoj;
		this.repCoe = repCoe;
		this.repDac = repDac;
		this.repPdc = repPdc;
		this.repTip = repTip;
		this.repSen = repSen;
		this.repBrv = repBrv;
		this.repSfl = repSfl;
		this.repPir = repPir;
		this.cheques = cheques;
		this.contratoservicos = contratoservicos;
		this.representanteempresapautas = representanteempresapautas;
		this.custofixos = custofixos;
		this.representanteprepostos = representanteprepostos;
		this.notafiscals = notafiscals;
		this.pagars = pagars;
		this.clienterepresentantes = clienterepresentantes;
		this.pedidos = pedidos;
		this.recebers = recebers;
	}*/

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "repEmp", column = @Column(name = "REP_EMP", nullable = false)),
		@AttributeOverride(name = "repCol", column = @Column(name = "REP_COL", nullable = false)) })
	public RepresentanteId getId() {
		return this.id;
	}

	public void setId(RepresentanteId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public ColaboradorEmpresa getColaboradorEmpresa() {
		return this.colaboradorEmpresa;
	}

	public void setColaboradorEmpresa(ColaboradorEmpresa colaboradorEmpresa) {
		this.colaboradorEmpresa = colaboradorEmpresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
		@JoinColumn(name = "REP_EMP", referencedColumnName = "FIL_EMP", insertable = false, updatable = false),
		@JoinColumn(name = "REP_FIL", referencedColumnName = "FIL_COD", insertable = false, updatable = false) })
	public Filial getFilial() {
		return this.filial;
	}

	public void setFilial(Filial filial) {
		this.filial = filial;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REP_DTI", length = 10)
	public Date getRepDti() {
		return this.repDti;
	}

	public void setRepDti(Date repDti) {
		this.repDti = repDti;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REP_DTF", length = 10)
	public Date getRepDtf() {
		return this.repDtf;
	}

	public void setRepDtf(Date repDtf) {
		this.repDtf = repDtf;
	}

	@Column(name = "REP_FPA", length = 1)
	public Character getRepFpa() {
		return this.repFpa;
	}

	public void setRepFpa(Character repFpa) {
		this.repFpa = repFpa;
	}

	@Column(name = "REP_FAP", length = 1)
	public Character getRepFap() {
		return this.repFap;
	}

	public void setRepFap(Character repFap) {
		this.repFap = repFap;
	}

	@Column(name = "REP_OB1", length = 40)
	public String getRepOb1() {
		return this.repOb1;
	}

	public void setRepOb1(String repOb1) {
		this.repOb1 = repOb1;
	}

	@Column(name = "REP_OB2", length = 40)
	public String getRepOb2() {
		return this.repOb2;
	}

	public void setRepOb2(String repOb2) {
		this.repOb2 = repOb2;
	}

	@Column(name = "REP_OB3", length = 40)
	public String getRepOb3() {
		return this.repOb3;
	}

	public void setRepOb3(String repOb3) {
		this.repOb3 = repOb3;
	}

	@Column(name = "REP_PEV", nullable = false, precision = 6)
	public BigDecimal getRepPev() {
		return this.repPev;
	}

	public void setRepPev(BigDecimal repPev) {
		this.repPev = repPev;
	}

	@Column(name = "REP_FPC", nullable = false)
	public int getRepFpc() {
		return this.repFpc;
	}

	public void setRepFpc(int repFpc) {
		this.repFpc = repFpc;
	}

	@Column(name = "REP_COM", nullable = false, length = 1)
	public char getRepCom() {
		return this.repCom;
	}

	public void setRepCom(char repCom) {
		this.repCom = repCom;
	}

	@Column(name = "REP_COJ", nullable = false, length = 1)
	public char getRepCoj() {
		return this.repCoj;
	}

	public void setRepCoj(char repCoj) {
		this.repCoj = repCoj;
	}

	@Column(name = "REP_COE", nullable = false, length = 1)
	public char getRepCoe() {
		return this.repCoe;
	}

	public void setRepCoe(char repCoe) {
		this.repCoe = repCoe;
	}

	@Column(name = "REP_DAC", nullable = false, length = 1)
	public char getRepDac() {
		return this.repDac;
	}

	public void setRepDac(char repDac) {
		this.repDac = repDac;
	}

	@Column(name = "REP_PDC", nullable = false, precision = 6)
	public BigDecimal getRepPdc() {
		return this.repPdc;
	}

	public void setRepPdc(BigDecimal repPdc) {
		this.repPdc = repPdc;
	}

	@Column(name = "REP_TIP", nullable = false, length = 1)
	public char getRepTip() {
		return this.repTip;
	}

	public void setRepTip(char repTip) {
		this.repTip = repTip;
	}

	@Column(name = "REP_SEN", length = 15)
	public String getRepSen() {
		return this.repSen;
	}

	public void setRepSen(String repSen) {
		this.repSen = repSen;
	}

	@Column(name = "REP_BRV", nullable = false, length = 1)
	public char getRepBrv() {
		return this.repBrv;
	}

	public void setRepBrv(char repBrv) {
		this.repBrv = repBrv;
	}

	@Column(name = "REP_SFL", length = 80)
	public String getRepSfl() {
		return this.repSfl;
	}

	public void setRepSfl(String repSfl) {
		this.repSfl = repSfl;
	}

	@Column(name = "REP_PIR", nullable = false, precision = 6)
	public BigDecimal getRepPir() {
		return this.repPir;
	}

	public void setRepPir(BigDecimal repPir) {
		this.repPir = repPir;
	}

	/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "representante")
	public Set<Cheque> getCheques() {
		return this.cheques;
	}

	public void setCheques(Set<Cheque> cheques) {
		this.cheques = cheques;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "representante")
	public Set<Contratoservico> getContratoservicos() {
		return this.contratoservicos;
	}

	public void setContratoservicos(Set<Contratoservico> contratoservicos) {
		this.contratoservicos = contratoservicos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "representante")
	public Set<Representanteempresapauta> getRepresentanteempresapautas() {
		return this.representanteempresapautas;
	}

	public void setRepresentanteempresapautas(
			Set<Representanteempresapauta> representanteempresapautas) {
		this.representanteempresapautas = representanteempresapautas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "representante")
	public Set<Custofixo> getCustofixos() {
		return this.custofixos;
	}

	public void setCustofixos(Set<Custofixo> custofixos) {
		this.custofixos = custofixos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "representante")
	public Set<Representantepreposto> getRepresentanteprepostos() {
		return this.representanteprepostos;
	}

	public void setRepresentanteprepostos(
			Set<Representantepreposto> representanteprepostos) {
		this.representanteprepostos = representanteprepostos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "representante")
	public Set<Notafiscal> getNotafiscals() {
		return this.notafiscals;
	}

	public void setNotafiscals(Set<Notafiscal> notafiscals) {
		this.notafiscals = notafiscals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "representante")
	public Set<Pagar> getPagars() {
		return this.pagars;
	}

	public void setPagars(Set<Pagar> pagars) {
		this.pagars = pagars;
	}



	@OneToMany(fetch = FetchType.LAZY, mappedBy = "representante")
	public Set<Receber> getRecebers() {
		return this.recebers;
	}

	public void setRecebers(Set<Receber> recebers) {
		this.recebers = recebers;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "representante")
	public Set<ClienteRepresentante> getClienteRepresentantes() {
		return this.clienteRepresentantes;
	}

	public void setClienteRepresentantes(Set<ClienteRepresentante> clienteRepresentantes) {
		this.clienteRepresentantes = clienteRepresentantes;
	}



	@OneToMany(fetch = FetchType.LAZY, mappedBy = "representante")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}
}
