package br.ufsc.creche.model;

// Generated 19/03/2015 10:22:22 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TelaWeb generated by hbm2java
 */
@Entity
@Table(name = "TELAWEB")
public class TelaWeb implements java.io.Serializable {

	private static final long serialVersionUID = -2064015171579425477L;
	private TelaWebId id;
	private String tlwDes;
	private Integer tlwPos;
	private String tlwObg;
	private String tlwDef;
	private String tlwDis;
	private Integer tlwFil;
	private Set<TelaWebUsuario> telaWebUsuarios = new HashSet<TelaWebUsuario>(0);

	public TelaWeb() {
	}

	public TelaWeb(TelaWebId id, String tlwDes, Integer tlwPos, String tlwObg,
			String tlwDis,   Integer tlwFil) {
		this.id = id;
		this.tlwDes = tlwDes;
		this.tlwPos = tlwPos;
		this.tlwObg = tlwObg;
		this.tlwDis = tlwDis;
		this.tlwFil = tlwFil;
	}

	public TelaWeb(TelaWebId id, String tlwDes, Integer tlwPos, String tlwObg,
			String tlwDis,   Integer tlwFil,
			Set<TelaWebUsuario> telaWebUsuarios) {
		this.id = id;
		this.tlwDes = tlwDes;
		this.tlwPos = tlwPos;
		this.tlwObg = tlwObg;
		this.tlwDis = tlwDis;
		this.tlwFil = tlwFil;
		this.telaWebUsuarios = telaWebUsuarios;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "tlwFrm", column = @Column(name = "TLW_FRM", nullable = false, length = 40)),
			@AttributeOverride(name = "tlwCpo", column = @Column(name = "TLW_CPO", nullable = false, length = 20)) })
	public TelaWebId getId() {
		return this.id;
	}

	public void setId(TelaWebId id) {
		this.id = id;
	}

	@Column(name = "TLW_DES", nullable = false, length = 30)
	public String getTlwDes() {
		return this.tlwDes;
	}

	public void setTlwDes(String tlwDes) {
		this.tlwDes = tlwDes;
	}

	@Column(name = "TLW_POS", nullable = false)
	public Integer getTlwPos() {
		return this.tlwPos;
	}

	public void setTlwPos(Integer tlwPos) {
		this.tlwPos = tlwPos;
	}

	@Column(name = "TLW_OBG", nullable = false, length = 1)
	public String getTlwObg() {
		return this.tlwObg;
	}

	public void setTlwObg(String tlwObg) {
		this.tlwObg = tlwObg;
	}

	@Column(name = "TLW_DIS", nullable = false, length = 1)
	public String getTlwDis() {
		return this.tlwDis;
	}

	public void setTlwDis(String tlwDis) {
		this.tlwDis = tlwDis;
	}


	@Column(name = "TLW_FIL", nullable = false)
	public Integer getTlwFil() {
		return this.tlwFil;
	}

	public void setTlwFil(Integer tlwFil) {
		this.tlwFil = tlwFil;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "telaWeb")
	public Set<TelaWebUsuario> getTelaWebUsuarios() {
		return this.telaWebUsuarios;
	}

	public void setTelaWebUsuarios(Set<TelaWebUsuario> telaWebUsuarios) {
		this.telaWebUsuarios = telaWebUsuarios;
	}

	@Override
	public String toString() {
		return id.getTlwCpo();
	}

	@Column(name = "TLW_DEF", nullable = false)
	public String getTlwDef() {
		return tlwDef;
	}

	public void setTlwDef(String tlwDef) {
		this.tlwDef = tlwDef;
	}
	
}
