package br.ufsc.creche.model;

// Generated 19/03/2015 10:22:22 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TelaWebUsuario generated by hbm2java
 */
@Entity
@Table(name = "TELAWEBUSUARIO")
public class TelaWebUsuario implements java.io.Serializable {

	private static final long serialVersionUID = 5895166740249875988L;
	private TelaWebUsuarioId id;
	private TelaWeb telaWeb;
	private Usuario usuario;
	private Integer twuPos;
	private Integer twuFil;

	public TelaWebUsuario() {
	}

	public TelaWebUsuario(TelaWebUsuarioId id, TelaWeb telaWeb,
			Usuario usuario, Integer twuPer, Integer twuPos) {
		this.id = id;
		this.telaWeb = telaWeb;
		this.usuario = usuario;
		this.twuPos = twuPos;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "twuUsu", column = @Column(name = "TWU_USU", nullable = false)),
			@AttributeOverride(name = "twuFrm", column = @Column(name = "TWU_FRM", nullable = false, length = 40)),
			@AttributeOverride(name = "twuCpo", column = @Column(name = "TWU_CPO", nullable = false, length = 20)) })
	public TelaWebUsuarioId getId() {
		return this.id;
	}

	public void setId(TelaWebUsuarioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "TWU_FRM", referencedColumnName = "TLW_FRM", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "TWU_CPO", referencedColumnName = "TLW_CPO", nullable = false, insertable = false, updatable = false) })
	public TelaWeb getTelaWeb() {
		return this.telaWeb;
	}

	public void setTelaWeb(TelaWeb telaWeb) {
		this.telaWeb = telaWeb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TWU_USU", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "TWU_POS", nullable = false)
	public Integer getTwuPos() {
		return this.twuPos;
	}

	public void setTwuPos(Integer twuPos) {
		this.twuPos = twuPos;
	}

	@Column(name = "TWU_FIL", nullable = false)
	public Integer getTwuFil() {
		return twuFil;
	}

	public void setTwuFil(Integer twuFil) {
		this.twuFil = twuFil;
	}

	@Override
	public String toString() {
		return  id.getTwuCpo() ;
	}

}
