package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoConta generated by hbm2java
 */
@Entity
@Table(name = "TIPOCONTA")
public class TipoConta implements java.io.Serializable {

	private static final long serialVersionUID = 6632469706223035273L;
	
	private int tcoCod;
	private String tcoNom;
	private String tcoApe;
	private char tcoCau;
	private char tcoLch;
	private char tcoDch;
	private char tcoClcd;
//	private Set<Conta> contas = new HashSet<Conta>(0);

	public TipoConta() {
	}

	public TipoConta(int tcoCod, String tcoNom, char tcoCau, char tcoLch,
			char tcoDch, char tcoClcd) {
		this.tcoCod = tcoCod;
		this.tcoNom = tcoNom;
		this.tcoCau = tcoCau;
		this.tcoLch = tcoLch;
		this.tcoDch = tcoDch;
		this.tcoClcd = tcoClcd;
	}

/*	public TipoConta(int tcoCod, String tcoNom, String tcoApe, char tcoCau,
			char tcoLch, char tcoDch, char tcoClcd, Set<Conta> contas) {
		this.tcoCod = tcoCod;
		this.tcoNom = tcoNom;
		this.tcoApe = tcoApe;
		this.tcoCau = tcoCau;
		this.tcoLch = tcoLch;
		this.tcoDch = tcoDch;
		this.tcoClcd = tcoClcd;
		this.contas = contas;
	}*/

	@Id
	@Column(name = "TCO_COD", unique = true, nullable = false)
	public int getTcoCod() {
		return this.tcoCod;
	}

	public void setTcoCod(int tcoCod) {
		this.tcoCod = tcoCod;
	}

	@Column(name = "TCO_NOM", nullable = false, length = 40)
	public String getTcoNom() {
		return this.tcoNom;
	}

	public void setTcoNom(String tcoNom) {
		this.tcoNom = tcoNom;
	}

	@Column(name = "TCO_APE", length = 15)
	public String getTcoApe() {
		return this.tcoApe;
	}

	public void setTcoApe(String tcoApe) {
		this.tcoApe = tcoApe;
	}

	@Column(name = "TCO_CAU", nullable = false, length = 1)
	public char getTcoCau() {
		return this.tcoCau;
	}

	public void setTcoCau(char tcoCau) {
		this.tcoCau = tcoCau;
	}

	@Column(name = "TCO_LCH", nullable = false, length = 1)
	public char getTcoLch() {
		return this.tcoLch;
	}

	public void setTcoLch(char tcoLch) {
		this.tcoLch = tcoLch;
	}

	@Column(name = "TCO_DCH", nullable = false, length = 1)
	public char getTcoDch() {
		return this.tcoDch;
	}

	public void setTcoDch(char tcoDch) {
		this.tcoDch = tcoDch;
	}

	@Column(name = "TCO_CLCD", nullable = false, length = 1)
	public char getTcoClcd() {
		return this.tcoClcd;
	}

	public void setTcoClcd(char tcoClcd) {
		this.tcoClcd = tcoClcd;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoConta")
	public Set<Conta> getContas() {
		return this.contas;
	}

	public void setContas(Set<Conta> contas) {
		this.contas = contas;
	}*/

}
