package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgenciaId generated by hbm2java
 */
@Embeddable
public class AgenciaId implements java.io.Serializable {
	
	private static final long serialVersionUID = -7927045138908065855L;
	
	private int ageBco;
	private int ageCod;

	public AgenciaId() {
	}

	public AgenciaId(int ageBco, int ageCod) {
		this.ageBco = ageBco;
		this.ageCod = ageCod;
	}

	@Column(name = "AGE_BCO", nullable = false)
	public int getAgeBco() {
		return this.ageBco;
	}

	public void setAgeBco(int ageBco) {
		this.ageBco = ageBco;
	}

	@Column(name = "AGE_COD", nullable = false)
	public int getAgeCod() {
		return this.ageCod;
	}

	public void setAgeCod(int ageCod) {
		this.ageCod = ageCod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgenciaId))
			return false;
		AgenciaId castOther = (AgenciaId) other;

		return (this.getAgeBco() == castOther.getAgeBco())
				&& (this.getAgeCod() == castOther.getAgeCod());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAgeBco();
		result = 37 * result + this.getAgeCod();
		return result;
	}

}
