package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoriaFinanceira generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIAFINANCEIRA")
public class CategoriaFinanceira implements java.io.Serializable {


	private static final long serialVersionUID = 868885027939427437L;
	private CategoriaFinanceiraId id;
	private Empresa empresa;
	private String ctfNom;
	private String ctfApe;
	private char ctfCkl;
	private BigDecimal ctfLim;
	private char ctfCkd;
	private Integer ctfDia;
	private char ctfPad;
	private char ctfBcs;
	//	private Set<ColaboradorEmpresaOcorrencia> colaboradorEmpresaOcorrenciasForFkCeoCfa = new HashSet<ColaboradorEmpresaOcorrencia>(0);
	private Set<Cliente> clientes = new HashSet<Cliente>(0);
	//	private Set<ColaboradorEmpresaOcorrencia> colaboradorEmpresaocorrenciasForFkCeoCtf = new HashSet<ColaboradorEmpresaOcorrencia>(0);

	public CategoriaFinanceira() {
	}

	public CategoriaFinanceira(CategoriaFinanceiraId id, Empresa empresa,
			String ctfNom, char ctfCkl, BigDecimal ctfLim, char ctfCkd,
			Integer ctfDia, char ctfPad, char ctfBcs) {
		this.id = id;
		this.empresa = empresa;
		this.ctfNom = ctfNom;
		this.ctfCkl = ctfCkl;
		this.ctfLim = ctfLim;
		this.ctfCkd = ctfCkd;
		this.ctfDia = ctfDia;
		this.ctfPad = ctfPad;
		this.ctfBcs = ctfBcs;
	}

	/*	public CategoriaFinanceira(
			CategoriaFinanceiraId id,
			Empresa empresa,
			String ctfNom,
			String ctfApe,
			char ctfCkl,
			BigDecimal ctfLim,
			char ctfCkd,
			Integer ctfDia,
			char ctfPad,
			char ctfBcs,
			Set<ColaboradorEmpresaOcorrencia> colaboradorEmpresaOcorrenciasForFkCeoCfa,
			Set<Cliente> clientes,
			Set<ColaboradorEmpresaOcorrencia> colaboradorEmpresaocorrenciasForFkCeoCtf) {
		this.id = id;
		this.empresa = empresa;
		this.ctfNom = ctfNom;
		this.ctfApe = ctfApe;
		this.ctfCkl = ctfCkl;
		this.ctfLim = ctfLim;
		this.ctfCkd = ctfCkd;
		this.ctfDia = ctfDia;
		this.ctfPad = ctfPad;
		this.ctfBcs = ctfBcs;
		this.colaboradorEmpresaOcorrenciasForFkCeoCfa = colaboradorEmpresaOcorrenciasForFkCeoCfa;
		this.clientes = clientes;
		this.colaboradorEmpresaocorrenciasForFkCeoCtf = colaboradorEmpresaocorrenciasForFkCeoCtf;
	}
	 */
	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "ctfEmp", column = @Column(name = "CTF_EMP", nullable = false)),
		@AttributeOverride(name = "ctfCod", column = @Column(name = "CTF_COD", nullable = false)) })
	public CategoriaFinanceiraId getId() {
		return this.id;
	}

	public void setId(CategoriaFinanceiraId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTF_EMP", nullable = false, insertable = false, updatable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "CTF_NOM", nullable = false, length = 40)
	public String getCtfNom() {
		return this.ctfNom;
	}

	public void setCtfNom(String ctfNom) {
		this.ctfNom = ctfNom;
	}

	@Column(name = "CTF_APE", length = 15)
	public String getCtfApe() {
		return this.ctfApe;
	}

	public void setCtfApe(String ctfApe) {
		this.ctfApe = ctfApe;
	}

	@Column(name = "CTF_CKL", nullable = false, length = 1)
	public char getCtfCkl() {
		return this.ctfCkl;
	}

	public void setCtfCkl(char ctfCkl) {
		this.ctfCkl = ctfCkl;
	}

	@Column(name = "CTF_LIM", nullable = false, precision = 14)
	public BigDecimal getCtfLim() {
		return this.ctfLim;
	}

	public void setCtfLim(BigDecimal ctfLim) {
		this.ctfLim = ctfLim;
	}

	@Column(name = "CTF_CKD", nullable = false, length = 1)
	public char getCtfCkd() {
		return this.ctfCkd;
	}

	public void setCtfCkd(char ctfCkd) {
		this.ctfCkd = ctfCkd;
	}

	@Column(name = "CTF_DIA", nullable = false)
	public Integer getCtfDia() {
		return this.ctfDia;
	}

	public void setCtfDia(Integer ctfDia) {
		this.ctfDia = ctfDia;
	}

	@Column(name = "CTF_PAD", nullable = false, length = 1)
	public char getCtfPad() {
		return this.ctfPad;
	}

	public void setCtfPad(char ctfPad) {
		this.ctfPad = ctfPad;
	}

	@Column(name = "CTF_BCS", nullable = false, length = 1)
	public char getCtfBcs() {
		return this.ctfBcs;
	}

	public void setCtfBcs(char ctfBcs) {
		this.ctfBcs = ctfBcs;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriafinanceiraByFkCeoCfa")
	public Set<ColaboradorEmpresaOcorrencia> getColaboradorEmpresaOcorrenciasForFkCeoCfa() {
		return this.colaboradorEmpresaOcorrenciasForFkCeoCfa;
	}

	public void setColaboradorEmpresaOcorrenciasForFkCeoCfa(
			Set<ColaboradorEmpresaOcorrencia> colaboradorEmpresaOcorrenciasForFkCeoCfa) {
		this.colaboradorEmpresaOcorrenciasForFkCeoCfa = colaboradorEmpresaOcorrenciasForFkCeoCfa;
	}
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaFinanceira")
	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

	/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriafinanceiraByFkCeoCtf")
	public Set<ColaboradorEmpresaOcorrencia> getColaboradorEmpresaOcorrenciasForFkCeoCtf() {
		return this.colaboradorEmpresaocorrenciasForFkCeoCtf;
	}

	public void setColaboradorEmpresaOcorrenciasForFkCeoCtf(
			Set<ColaboradorEmpresaOcorrencia> colaboradorEmpresaocorrenciasForFkCeoCtf) {
		this.colaboradorEmpresaocorrenciasForFkCeoCtf = colaboradorEmpresaocorrenciasForFkCeoCtf;
	}*/

}
