package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoriaFiscalId generated by hbm2java
 */
@Embeddable
public class CategoriaFiscalId implements java.io.Serializable {

	private static final long serialVersionUID = -7852430172690562262L;
	private int cgfEmp;
	private String cgfCod;

	public CategoriaFiscalId() {
	}

	public CategoriaFiscalId(int cgfEmp, String cgfCod) {
		this.cgfEmp = cgfEmp;
		this.cgfCod = cgfCod;
	}

	@Column(name = "CGF_EMP", nullable = false)
	public int getCgfEmp() {
		return this.cgfEmp;
	}

	public void setCgfEmp(int cgfEmp) {
		this.cgfEmp = cgfEmp;
	}

	@Column(name = "CGF_COD", nullable = false, length = 1)
	public String getCgfCod() {
		return this.cgfCod;
	}

	public void setCgfCod(String cgfCod) {
		this.cgfCod = cgfCod;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cgfCod == null) ? 0 : cgfCod.hashCode());
		result = prime * result + cgfEmp;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof CategoriaFiscalId)) {
			return false;
		}
		CategoriaFiscalId other = (CategoriaFiscalId) obj;
		if (cgfCod == null) {
			if (other.cgfCod != null) {
				return false;
			}
		} else if (!cgfCod.equals(other.cgfCod)) {
			return false;
		}
		if (cgfEmp != other.cgfEmp) {
			return false;
		}
		return true;
	}

	 

	 

}
