package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "CLIENTE")
public class Cliente implements java.io.Serializable {

	private static final long serialVersionUID = 511200698828114204L;

	private ClienteId id;
	private CategoriaFinanceira categoriaFinanceira;
	//private ColaboradorEmpresa colaboradorEmpresa;
	private Municipio municipioByCliCmu;
	private Municipio municipioByCliEmu;
	private Date cliDti;
	private Date cliDtf;
	private String cliEen;
	private Integer cliEnu;
	private String cliEcp;
	private String cliEba;
	private String cliEce;
	private String cliCen;
	private Integer cliCnu;
	private String cliCcp;
	private String cliCba;
	private String cliCce;
	private String cliCpp;
	private String cliOb1;
	private String cliOb2;
	private String cliOb3;
	private Integer cliRes;
	private Integer cliCfd;
	private Integer cliCtf;
	private Integer cliCro;
	private String cliLra;
	//	private Set<ClienteCartaoFidelidade> clienteCartaoFidelidades = new HashSet<ClienteCartaoFidelidade>(0);
	private Set<Filial> filialsForFkFilCcs = new HashSet<Filial>(0);
	private Set<ClienteRepresentante> clienteRepresentantes = new HashSet<ClienteRepresentante>(0);
	private Set<Filial> filialsForFkFilCli = new HashSet<Filial>(0);

	private Set<ColaboradorEmpresa> colaboradorEmpresas = new HashSet<ColaboradorEmpresa>(0);

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "cliEmp", column = @Column(name = "CLI_EMP", nullable = false)),
		@AttributeOverride(name = "cliCol", column = @Column(name = "CLI_COL", nullable = false)) })
	public ClienteId getId() {
		return this.id;
	}

	public void setId(ClienteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
		@JoinColumn(name = "CLI_EMP", referencedColumnName = "CTF_EMP", nullable = false, insertable = false, updatable = false),
		@JoinColumn(name = "CLI_CTF", referencedColumnName = "CTF_COD", nullable = false, insertable = false, updatable = false) })
	public CategoriaFinanceira getCategoriaFinanceira() {
		return this.categoriaFinanceira;
	}

	public void setCategoriaFinanceira(CategoriaFinanceira categoriaFinanceira) {
		this.categoriaFinanceira = categoriaFinanceira;
	}

	/*@OneToOne(fetch = FetchType.LAZY  , optional = false)
	@PrimaryKeyJoinColumn
	public ColaboradorEmpresa getColaboradorEmpresa() {
		return this.colaboradorEmpresa;
	}

	public void setColaboradorEmpresa(ColaboradorEmpresa colaboradorEmpresa) {
		this.colaboradorEmpresa = colaboradorEmpresa;
	}*/

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CLI_CMU")
	public Municipio getMunicipioByCliCmu() {
		return this.municipioByCliCmu;
	}

	public void setMunicipioByCliCmu(Municipio municipioByCliCmu) {
		this.municipioByCliCmu = municipioByCliCmu;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CLI_EMU")
	public Municipio getMunicipioByCliEmu() {
		return this.municipioByCliEmu;
	}

	public void setMunicipioByCliEmu(Municipio municipioByCliEmu) {
		this.municipioByCliEmu = municipioByCliEmu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CLI_DTI", length = 10)
	public Date getCliDti() {
		return this.cliDti;
	}

	public void setCliDti(Date cliDti) {
		this.cliDti = cliDti;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CLI_DTF", length = 10)
	public Date getCliDtf() {
		return this.cliDtf;
	}

	public void setCliDtf(Date cliDtf) {
		this.cliDtf = cliDtf;
	}

	@Column(name = "CLI_EEN", length = 40)
	public String getCliEen() {
		return this.cliEen;
	}

	public void setCliEen(String cliEen) {
		this.cliEen = cliEen;
	}

	@Column(name = "CLI_ENU")
	public Integer getCliEnu() {
		return this.cliEnu;
	}

	public void setCliEnu(Integer cliEnu) {
		this.cliEnu = cliEnu;
	}

	@Column(name = "CLI_ECP", length = 20)
	public String getCliEcp() {
		return this.cliEcp;
	}

	public void setCliEcp(String cliEcp) {
		this.cliEcp = cliEcp;
	}

	@Column(name = "CLI_EBA", length = 20)
	public String getCliEba() {
		return this.cliEba;
	}

	public void setCliEba(String cliEba) {
		this.cliEba = cliEba;
	}

	@Column(name = "CLI_ECE", length = 8)
	public String getCliEce() {
		return this.cliEce;
	}

	public void setCliEce(String cliEce) {
		this.cliEce = cliEce;
	}

	@Column(name = "CLI_CEN", length = 40)
	public String getCliCen() {
		return this.cliCen;
	}

	public void setCliCen(String cliCen) {
		this.cliCen = cliCen;
	}

	@Column(name = "CLI_CNU")
	public Integer getCliCnu() {
		return this.cliCnu;
	}

	public void setCliCnu(Integer cliCnu) {
		this.cliCnu = cliCnu;
	}

	@Column(name = "CLI_CCP", length = 20)
	public String getCliCcp() {
		return this.cliCcp;
	}

	public void setCliCcp(String cliCcp) {
		this.cliCcp = cliCcp;
	}

	@Column(name = "CLI_CBA", length = 20)
	public String getCliCba() {
		return this.cliCba;
	}

	public void setCliCba(String cliCba) {
		this.cliCba = cliCba;
	}

	@Column(name = "CLI_CCE", length = 8)
	public String getCliCce() {
		return this.cliCce;
	}

	public void setCliCce(String cliCce) {
		this.cliCce = cliCce;
	}

	@Column(name = "CLI_CPP", length = 40)
	public String getCliCpp() {
		return this.cliCpp;
	}

	public void setCliCpp(String cliCpp) {
		this.cliCpp = cliCpp;
	}

	@Column(name = "CLI_OB1", length = 40)
	public String getCliOb1() {
		return this.cliOb1;
	}

	public void setCliOb1(String cliOb1) {
		this.cliOb1 = cliOb1;
	}

	@Column(name = "CLI_OB2", length = 40)
	public String getCliOb2() {
		return this.cliOb2;
	}

	public void setCliOb2(String cliOb2) {
		this.cliOb2 = cliOb2;
	}

	@Column(name = "CLI_OB3", length = 40)
	public String getCliOb3() {
		return this.cliOb3;
	}

	public void setCliOb3(String cliOb3) {
		this.cliOb3 = cliOb3;
	}

	@Column(name = "CLI_RES", nullable = false)
	public Integer getCliRes() {
		return this.cliRes;
	}

	public void setCliRes(Integer cliRes) {
		this.cliRes = cliRes;
	}

	@Column(name = "CLI_CFD", nullable = false)
	public Integer getCliCfd() {
		return this.cliCfd;
	}

	public void setCliCfd(Integer cliCfd) {
		this.cliCfd = cliCfd;
	}

	@Column(name = "CLI_CTF", nullable = false)
	public Integer getCliCtf() {
		return this.cliCtf;
	}

	public void setCliCtf(Integer cliCtf) {
		this.cliCtf = cliCtf;
	}

	@Column(name = "CLI_CRO")
	public Integer getCliCro() {
		return this.cliCro;
	}

	public void setCliCro(Integer cliCro) {
		this.cliCro = cliCro;
	}

	@Column(name = "CLI_LRA")
	public String getCliLra() {
		return this.cliLra;
	}

	public void setCliLra(String cliLra) {
		this.cliLra = cliLra;
	}
	//
	//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	//	public Set<ClienteCartaoFidelidade> getClienteCartaoFidelidades() {
	//		return this.clienteCartaoFidelidades;
	//	}
	//
	//	public void setClienteCartaoFidelidades(
	//			Set<ClienteCartaoFidelidade> clienteCartaoFidelidades) {
	//		this.clienteCartaoFidelidades = clienteCartaoFidelidades;
	//	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clienteByFkFilCcs")
	public Set<Filial> getFilialsForFkFilCcs() {
		return this.filialsForFkFilCcs;
	}

	public void setFilialsForFkFilCcs(Set<Filial> filialsForFkFilCcs) {
		this.filialsForFkFilCcs = filialsForFkFilCcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<ClienteRepresentante> getClienteRepresentantes() {
		return this.clienteRepresentantes;
	}

	public void setClienteRepresentantes(Set<ClienteRepresentante> clienteRepresentantes) {
		this.clienteRepresentantes = clienteRepresentantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clienteByFkFilCli")
	public Set<Filial> getFilialsForFkFilCli() {
		return this.filialsForFkFilCli;
	}

	public void setFilialsForFkFilCli(Set<Filial> filialsForFkFilCli) {
		this.filialsForFkFilCli = filialsForFkFilCli;
	}



	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cliente")
	public Set<ColaboradorEmpresa> getColaboradorEmpresas() {
		return this.colaboradorEmpresas;
	}

	public void setColaboradorEmpresas(Set<ColaboradorEmpresa> colaboradorEmpresas) {
		this.colaboradorEmpresas = colaboradorEmpresas;
	}


}
