package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ColaboradorConta generated by hbm2java
 */
@Entity
@Table(name = "COLABORADORCONTA")
public class ColaboradorConta implements java.io.Serializable {
	
	private static final long serialVersionUID = -5949244435126333317L;
	private ColaboradorContaId id;
	private Banco banco;
//	private Colaborador colaborador;
	private int ctcAge;
	private Integer ctcDig;
	private String ctcCta;
	private char ctcTip;
	private String ctcObs;
	private Character ctcTer;
	private String ctcEno;
	private String ctcEin;

	public ColaboradorConta() {
	}

	/*public ColaboradorConta(ColaboradorContaId id, Banco banco,
			Colaborador colaborador, int ctcAge, String ctcCta, char ctcTip) {
		this.id = id;
		this.banco = banco;
		this.colaborador = colaborador;
		this.ctcAge = ctcAge;
		this.ctcCta = ctcCta;
		this.ctcTip = ctcTip;
	}

	public ColaboradorConta(ColaboradorContaId id, Banco banco,
			Colaborador colaborador, int ctcAge, Integer ctcDig, String ctcCta,
			char ctcTip, String ctcObs, Character ctcTer, String ctcEno,
			String ctcEin) {
		this.id = id;
		this.banco = banco;
		this.colaborador = colaborador;
		this.ctcAge = ctcAge;
		this.ctcDig = ctcDig;
		this.ctcCta = ctcCta;
		this.ctcTip = ctcTip;
		this.ctcObs = ctcObs;
		this.ctcTer = ctcTer;
		this.ctcEno = ctcEno;
		this.ctcEin = ctcEin;
	}*/

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ctcCol", column = @Column(name = "CTC_COL", nullable = false)),
			@AttributeOverride(name = "ctcCod", column = @Column(name = "CTC_COD", nullable = false)) })
	public ColaboradorContaId getId() {
		return this.id;
	}

	public void setId(ColaboradorContaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTC_BCO", nullable = false)
	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTC_COL", nullable = false, insertable = false, updatable = false)
	public Colaborador getColaborador() {
		return this.colaborador;
	}

	public void setColaborador(Colaborador colaborador) {
		this.colaborador = colaborador;
	}*/

	@Column(name = "CTC_AGE", nullable = false)
	public int getCtcAge() {
		return this.ctcAge;
	}

	public void setCtcAge(int ctcAge) {
		this.ctcAge = ctcAge;
	}

	@Column(name = "CTC_DIG")
	public Integer getCtcDig() {
		return this.ctcDig;
	}

	public void setCtcDig(Integer ctcDig) {
		this.ctcDig = ctcDig;
	}

	@Column(name = "CTC_CTA", nullable = false, length = 15)
	public String getCtcCta() {
		return this.ctcCta;
	}

	public void setCtcCta(String ctcCta) {
		this.ctcCta = ctcCta;
	}

	@Column(name = "CTC_TIP", nullable = false, length = 1)
	public char getCtcTip() {
		return this.ctcTip;
	}

	public void setCtcTip(char ctcTip) {
		this.ctcTip = ctcTip;
	}

	@Column(name = "CTC_OBS", length = 40)
	public String getCtcObs() {
		return this.ctcObs;
	}

	public void setCtcObs(String ctcObs) {
		this.ctcObs = ctcObs;
	}

	@Column(name = "CTC_TER", length = 1)
	public Character getCtcTer() {
		return this.ctcTer;
	}

	public void setCtcTer(Character ctcTer) {
		this.ctcTer = ctcTer;
	}

	@Column(name = "CTC_ENO", length = 50)
	public String getCtcEno() {
		return this.ctcEno;
	}

	public void setCtcEno(String ctcEno) {
		this.ctcEno = ctcEno;
	}

	@Column(name = "CTC_EIN", length = 14)
	public String getCtcEin() {
		return this.ctcEin;
	}

	public void setCtcEin(String ctcEin) {
		this.ctcEin = ctcEin;
	}

}
