package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ColaboradorContato generated by hbm2java
 */
@Entity
@Table(name = "COLABORADORCONTATO")
public class ColaboradorContato implements java.io.Serializable {
	
	private static final long serialVersionUID = -2741573989115963606L;
	private ColaboradorContatoId id;
//	private Colaborador colaborador;
	private int cctTip;
	private String cctNom;
	private String cctCon;

	public ColaboradorContato() {
	}

	/*public ColaboradorContato(ColaboradorContatoId id, Colaborador colaborador,
			int cctTip) {
		this.id = id;
		this.colaborador = colaborador;
		this.cctTip = cctTip;
	}

	public ColaboradorContato(ColaboradorContatoId id, Colaborador colaborador,
			int cctTip, String cctNom, String cctCon) {
		this.id = id;
		this.colaborador = colaborador;
		this.cctTip = cctTip;
		this.cctNom = cctNom;
		this.cctCon = cctCon;
	}*/

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cctCol", column = @Column(name = "CCT_COL", nullable = false)),
			@AttributeOverride(name = "cctCod", column = @Column(name = "CCT_COD", nullable = false)) })
	public ColaboradorContatoId getId() {
		return this.id;
	}

	public void setId(ColaboradorContatoId id) {
		this.id = id;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CCT_COL", nullable = false, insertable = false, updatable = false)
	public Colaborador getColaborador() {
		return this.colaborador;
	}

	public void setColaborador(Colaborador colaborador) {
		this.colaborador = colaborador;
	}*/

	@Column(name = "CCT_TIP", nullable = false)
	public int getCctTip() {
		return this.cctTip;
	}

	public void setCctTip(int cctTip) {
		this.cctTip = cctTip;
	}

	@Column(name = "CCT_NOM", length = 40)
	public String getCctNom() {
		return this.cctNom;
	}

	public void setCctNom(String cctNom) {
		this.cctNom = cctNom;
	}

	@Column(name = "CCT_CON", length = 40)
	public String getCctCon() {
		return this.cctCon;
	}

	public void setCctCon(String cctCon) {
		this.cctCon = cctCon;
	}

}
