package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CondicaoPagto generated by hbm2java
 */
@Entity
@Table(name = "CONDICAOPAGTO")
public class CondicaoPagto implements java.io.Serializable {

	private static final long serialVersionUID = 4294564825526460750L;
	private Integer cdpCod;
	private String cdpNom;
	private String cdpApe;
	private char cdpTip;
	private Integer cdpC01;
	private Integer cdpC02;
	private Integer cdpC03;
	private Integer cdpC04;
	private Integer cdpC05;
	private Integer cdpC06;
	private Integer cdpC07;
	private Integer cdpC08;
	private Integer cdpC09;
	private Integer cdpC10;
	private Integer cdpC11;
	private Integer cdpC12;
	private Integer cdpNrp;
	private char cdpCen;
	
	private Set<Pedido> pedidosForPedCpa = new HashSet<Pedido>(0);
	private Set<Pedido> pedidosForPedCdp = new HashSet<Pedido>(0);
	/*private Set<Empresapautacondicao> empresapautacondicaos = new HashSet<Empresapautacondicao>(0);
	private Set<Pedidocompra> pedidocompras = new HashSet<Pedidocompra>(0);*/
//	private Set<ClienteRepresentante> clienteRepresentantes = new HashSet<ClienteRepresentante>(0);

	 
	/*public CondicaoPagto(Integer cdpCod, String cdpNom, char cdpTip, char cdpCen) {
		this.cdpCod = cdpCod;
		this.cdpNom = cdpNom;
		this.cdpTip = cdpTip;
		this.cdpCen = cdpCen;
	}*/

	/*public CondicaoPagto(Integer cdpCod, String cdpNom, String cdpApe, char cdpTip,
			Integer cdpC01, Integer cdpC02, Integer cdpC03, Integer cdpC04,
			Integer cdpC05, Integer cdpC06, Integer cdpC07, Integer cdpC08,
			Integer cdpC09, Integer cdpC10, Integer cdpC11, Integer cdpC12,
			Integer cdpNrp, char cdpCen,
			Set<Empresapautacondicao> empresapautacondicaos,
			Set<Pedido> pedidosForPedCpa, Set<Pedido> pedidosForPedCdp,
			Set<Pedidocompra> pedidocompras,
			Set<ClienteRepresentante> clienteRepresentantes) {
		this.cdpCod = cdpCod;
		this.cdpNom = cdpNom;
		this.cdpApe = cdpApe;
		this.cdpTip = cdpTip;
		this.cdpC01 = cdpC01;
		this.cdpC02 = cdpC02;
		this.cdpC03 = cdpC03;
		this.cdpC04 = cdpC04;
		this.cdpC05 = cdpC05;
		this.cdpC06 = cdpC06;
		this.cdpC07 = cdpC07;
		this.cdpC08 = cdpC08;
		this.cdpC09 = cdpC09;
		this.cdpC10 = cdpC10;
		this.cdpC11 = cdpC11;
		this.cdpC12 = cdpC12;
		this.cdpNrp = cdpNrp;
		this.cdpCen = cdpCen;
		this.empresapautacondicaos = empresapautacondicaos;
		this.pedidosForPedCpa = pedidosForPedCpa;
		this.pedidosForPedCdp = pedidosForPedCdp;
		this.pedidocompras = pedidocompras;
		this.clienteRepresentantes = clienteRepresentantes;
	}*/

	@Id
	@Column(name = "CDP_COD", unique = true, nullable = false)
	public Integer getCdpCod() {
		return this.cdpCod;
	}

	public void setCdpCod(Integer cdpCod) {
		this.cdpCod = cdpCod;
	}

	@Column(name = "CDP_NOM", nullable = false, length = 40)
	public String getCdpNom() {
		return this.cdpNom;
	}

	public void setCdpNom(String cdpNom) {
		this.cdpNom = cdpNom;
	}

	@Column(name = "CDP_APE", length = 15)
	public String getCdpApe() {
		return this.cdpApe;
	}

	public void setCdpApe(String cdpApe) {
		this.cdpApe = cdpApe;
	}

	@Column(name = "CDP_TIP", nullable = false, length = 1)
	public char getCdpTip() {
		return this.cdpTip;
	}

	public void setCdpTip(char cdpTip) {
		this.cdpTip = cdpTip;
	}

	@Column(name = "CDP_C01")
	public Integer getCdpC01() {
		return this.cdpC01;
	}

	public void setCdpC01(Integer cdpC01) {
		this.cdpC01 = cdpC01;
	}

	@Column(name = "CDP_C02")
	public Integer getCdpC02() {
		return this.cdpC02;
	}

	public void setCdpC02(Integer cdpC02) {
		this.cdpC02 = cdpC02;
	}

	@Column(name = "CDP_C03")
	public Integer getCdpC03() {
		return this.cdpC03;
	}

	public void setCdpC03(Integer cdpC03) {
		this.cdpC03 = cdpC03;
	}

	@Column(name = "CDP_C04")
	public Integer getCdpC04() {
		return this.cdpC04;
	}

	public void setCdpC04(Integer cdpC04) {
		this.cdpC04 = cdpC04;
	}

	@Column(name = "CDP_C05")
	public Integer getCdpC05() {
		return this.cdpC05;
	}

	public void setCdpC05(Integer cdpC05) {
		this.cdpC05 = cdpC05;
	}

	@Column(name = "CDP_C06")
	public Integer getCdpC06() {
		return this.cdpC06;
	}

	public void setCdpC06(Integer cdpC06) {
		this.cdpC06 = cdpC06;
	}

	@Column(name = "CDP_C07")
	public Integer getCdpC07() {
		return this.cdpC07;
	}

	public void setCdpC07(Integer cdpC07) {
		this.cdpC07 = cdpC07;
	}

	@Column(name = "CDP_C08")
	public Integer getCdpC08() {
		return this.cdpC08;
	}

	public void setCdpC08(Integer cdpC08) {
		this.cdpC08 = cdpC08;
	}

	@Column(name = "CDP_C09")
	public Integer getCdpC09() {
		return this.cdpC09;
	}

	public void setCdpC09(Integer cdpC09) {
		this.cdpC09 = cdpC09;
	}

	@Column(name = "CDP_C10")
	public Integer getCdpC10() {
		return this.cdpC10;
	}

	public void setCdpC10(Integer cdpC10) {
		this.cdpC10 = cdpC10;
	}

	@Column(name = "CDP_C11")
	public Integer getCdpC11() {
		return this.cdpC11;
	}

	public void setCdpC11(Integer cdpC11) {
		this.cdpC11 = cdpC11;
	}

	@Column(name = "CDP_C12")
	public Integer getCdpC12() {
		return this.cdpC12;
	}

	public void setCdpC12(Integer cdpC12) {
		this.cdpC12 = cdpC12;
	}

	@Column(name = "CDP_NRP")
	public Integer getCdpNrp() {
		return this.cdpNrp;
	}

	public void setCdpNrp(Integer cdpNrp) {
		this.cdpNrp = cdpNrp;
	}

	@Column(name = "CDP_CEN", nullable = false, length = 1)
	public char getCdpCen() {
		return this.cdpCen;
	}

	public void setCdpCen(char cdpCen) {
		this.cdpCen = cdpCen;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "condicaoPagtoByPedCpa")
	public Set<Pedido> getPedidosForPedCpa() {
		return this.pedidosForPedCpa;
	}

	public void setPedidosForPedCpa(Set<Pedido> pedidosForPedCpa) {
		this.pedidosForPedCpa = pedidosForPedCpa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "condicaoPagtoByPedCdp")
	public Set<Pedido> getPedidosForPedCdp() {
		return this.pedidosForPedCdp;
	}

	public void setPedidosForPedCdp(Set<Pedido> pedidosForPedCdp) {
		this.pedidosForPedCdp = pedidosForPedCdp;
	}
	
/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "condicaoPagto")
	public Set<Empresapautacondicao> getEmpresapautacondicaos() {
		return this.empresapautacondicaos;
	}

	public void setEmpresapautacondicaos(
			Set<Empresapautacondicao> empresapautacondicaos) {
		this.empresapautacondicaos = empresapautacondicaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "condicaoPagto")
	public Set<Pedidocompra> getPedidocompras() {
		return this.pedidocompras;
	}

	public void setPedidocompras(Set<Pedidocompra> pedidocompras) {
		this.pedidocompras = pedidocompras;
	}*/

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "condicaoPagto")
//	public Set<ClienteRepresentante> getClienteRepresentantes() {
//		return this.clienteRepresentantes;
//	}
//
//	public void setClienteRepresentantes(
//			Set<ClienteRepresentante> clienteRepresentantes) {
//		this.clienteRepresentantes = clienteRepresentantes;
//	}

}
