package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CustoFixo generated by hbm2java
 */
@Entity
@Table(name = "CUSTOFIXO")
public class CustoFixo implements java.io.Serializable {

	
	private static final long serialVersionUID = 895770801135296145L;
	private CustoFixoId id;
	private Banco banco;
//	private ColaboradorEmpresa colaboradorEmpresa;
	private Filial filial;
	private FormaPagto formaPagto;
	private PlanoDeContas planoDeContas;
	private Representante representante;
	private Integer cfxOri;
	private Integer cfxInt;
	private Integer cfxDie;
	private int cfxDiv;
	private Integer cfxAge;
	private String cfxNct;
	private BigDecimal cfxMul;
	private BigDecimal cfxJur;
	private int cfxTol;
	private String cfxOb1;
	private String cfxOb2;
	private int cfxTif;
	private char cfxCtb;
	private Integer cfxOpf;
	private char cfxSit;
	private BigDecimal cfxVlr;
	private char cfxM01;
	private char cfxM02;
	private char cfxM03;
	private char cfxM04;
	private char cfxM05;
	private char cfxM06;
	private char cfxM07;
	private char cfxM08;
	private char cfxM09;
	private char cfxM10;
	private char cfxM11;
	private char cfxM12;
	private char cfxTdv;
	private char cfxTcv;
	private String cfxDoc;
	private char cfxTpc;

	public CustoFixo() {
	}

//	public CustoFixo(CustoFixoId id, ColaboradorEmpresa colaboradorEmpresa,
//			Filial filial, PlanoDeContas planoDeContas,
//			Representante representante, int cfxDiv, BigDecimal cfxMul,
//			BigDecimal cfxJur, int cfxTol, int cfxTif, char cfxCtb,
//			char cfxSit, BigDecimal cfxVlr, char cfxM01, char cfxM02,
//			char cfxM03, char cfxM04, char cfxM05, char cfxM06, char cfxM07,
//			char cfxM08, char cfxM09, char cfxM10, char cfxM11, char cfxM12,
//			char cfxTdv, char cfxTcv, char cfxTpc) {
//		this.id = id;
//		this.colaboradorEmpresa = colaboradorEmpresa;
//		this.filial = filial;
//		this.planoDeContas = planoDeContas;
//		this.representante = representante;
//		this.cfxDiv = cfxDiv;
//		this.cfxMul = cfxMul;
//		this.cfxJur = cfxJur;
//		this.cfxTol = cfxTol;
//		this.cfxTif = cfxTif;
//		this.cfxCtb = cfxCtb;
//		this.cfxSit = cfxSit;
//		this.cfxVlr = cfxVlr;
//		this.cfxM01 = cfxM01;
//		this.cfxM02 = cfxM02;
//		this.cfxM03 = cfxM03;
//		this.cfxM04 = cfxM04;
//		this.cfxM05 = cfxM05;
//		this.cfxM06 = cfxM06;
//		this.cfxM07 = cfxM07;
//		this.cfxM08 = cfxM08;
//		this.cfxM09 = cfxM09;
//		this.cfxM10 = cfxM10;
//		this.cfxM11 = cfxM11;
//		this.cfxM12 = cfxM12;
//		this.cfxTdv = cfxTdv;
//		this.cfxTcv = cfxTcv;
//		this.cfxTpc = cfxTpc;
//	}

//	public CustoFixo(CustoFixoId id, Banco banco,
//			ColaboradorEmpresa colaboradorEmpresa, Filial filial,
//			FormaPagto formaPagto, PlanoDeContas planoDeContas,
//			Representante representante, Integer cfxOri, Integer cfxInt,
//			Integer cfxDie, int cfxDiv, Integer cfxAge, String cfxNct,
//			BigDecimal cfxMul, BigDecimal cfxJur, int cfxTol, String cfxOb1,
//			String cfxOb2, int cfxTif, char cfxCtb, Integer cfxOpf,
//			char cfxSit, BigDecimal cfxVlr, char cfxM01, char cfxM02,
//			char cfxM03, char cfxM04, char cfxM05, char cfxM06, char cfxM07,
//			char cfxM08, char cfxM09, char cfxM10, char cfxM11, char cfxM12,
//			char cfxTdv, char cfxTcv, String cfxDoc, char cfxTpc) {
//		this.id = id;
//		this.banco = banco;
//		this.colaboradorEmpresa = colaboradorEmpresa;
//		this.filial = filial;
//		this.formaPagto = formaPagto;
//		this.planoDeContas = planoDeContas;
//		this.representante = representante;
//		this.cfxOri = cfxOri;
//		this.cfxInt = cfxInt;
//		this.cfxDie = cfxDie;
//		this.cfxDiv = cfxDiv;
//		this.cfxAge = cfxAge;
//		this.cfxNct = cfxNct;
//		this.cfxMul = cfxMul;
//		this.cfxJur = cfxJur;
//		this.cfxTol = cfxTol;
//		this.cfxOb1 = cfxOb1;
//		this.cfxOb2 = cfxOb2;
//		this.cfxTif = cfxTif;
//		this.cfxCtb = cfxCtb;
//		this.cfxOpf = cfxOpf;
//		this.cfxSit = cfxSit;
//		this.cfxVlr = cfxVlr;
//		this.cfxM01 = cfxM01;
//		this.cfxM02 = cfxM02;
//		this.cfxM03 = cfxM03;
//		this.cfxM04 = cfxM04;
//		this.cfxM05 = cfxM05;
//		this.cfxM06 = cfxM06;
//		this.cfxM07 = cfxM07;
//		this.cfxM08 = cfxM08;
//		this.cfxM09 = cfxM09;
//		this.cfxM10 = cfxM10;
//		this.cfxM11 = cfxM11;
//		this.cfxM12 = cfxM12;
//		this.cfxTdv = cfxTdv;
//		this.cfxTcv = cfxTcv;
//		this.cfxDoc = cfxDoc;
//		this.cfxTpc = cfxTpc;
//	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cfxEmp", column = @Column(name = "CFX_EMP", nullable = false)),
			@AttributeOverride(name = "cfxCod", column = @Column(name = "CFX_COD", nullable = false)) })
	public CustoFixoId getId() {
		return this.id;
	}

	public void setId(CustoFixoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CFX_BCO")
	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

/*	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CFX_EMP", referencedColumnName = "COE_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CFX_COL", referencedColumnName = "COE_COL", nullable = false, insertable = false, updatable = false) })
	public ColaboradorEmpresa getColaboradorEmpresa() {
		return this.colaboradorEmpresa;
	}

	public void setColaboradorEmpresa(ColaboradorEmpresa colaboradorEmpresa) {
		this.colaboradorEmpresa = colaboradorEmpresa;
	}*/

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CFX_EMP", referencedColumnName = "FIL_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CFX_FIL", referencedColumnName = "FIL_COD", insertable = false, updatable = false) })
	public Filial getFilial() {
		return this.filial;
	}

	public void setFilial(Filial filial) {
		this.filial = filial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CFX_FPA")
	public FormaPagto getFormaPagto() {
		return this.formaPagto;
	}

	public void setFormaPagto(FormaPagto formaPagto) {
		this.formaPagto = formaPagto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CFX_EMP", referencedColumnName = "PLA_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CFX_PLA", referencedColumnName = "PLA_COD", insertable = false, updatable = false) })
	public PlanoDeContas getPlanoDeContas() {
		return this.planoDeContas;
	}

	public void setPlanoDeContas(PlanoDeContas planoDeContas) {
		this.planoDeContas = planoDeContas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "CFX_EMP", referencedColumnName = "REP_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "CFX_REP", referencedColumnName = "REP_COL", insertable = false, updatable = false) })
	public Representante getRepresentante() {
		return this.representante;
	}

	public void setRepresentante(Representante representante) {
		this.representante = representante;
	}

	@Column(name = "CFX_ORI")
	public Integer getCfxOri() {
		return this.cfxOri;
	}

	public void setCfxOri(Integer cfxOri) {
		this.cfxOri = cfxOri;
	}

	@Column(name = "CFX_INT")
	public Integer getCfxInt() {
		return this.cfxInt;
	}

	public void setCfxInt(Integer cfxInt) {
		this.cfxInt = cfxInt;
	}

	@Column(name = "CFX_DIE")
	public Integer getCfxDie() {
		return this.cfxDie;
	}

	public void setCfxDie(Integer cfxDie) {
		this.cfxDie = cfxDie;
	}

	@Column(name = "CFX_DIV", nullable = false)
	public int getCfxDiv() {
		return this.cfxDiv;
	}

	public void setCfxDiv(int cfxDiv) {
		this.cfxDiv = cfxDiv;
	}

	@Column(name = "CFX_AGE")
	public Integer getCfxAge() {
		return this.cfxAge;
	}

	public void setCfxAge(Integer cfxAge) {
		this.cfxAge = cfxAge;
	}

	@Column(name = "CFX_NCT", length = 10)
	public String getCfxNct() {
		return this.cfxNct;
	}

	public void setCfxNct(String cfxNct) {
		this.cfxNct = cfxNct;
	}

	@Column(name = "CFX_MUL", nullable = false, precision = 6)
	public BigDecimal getCfxMul() {
		return this.cfxMul;
	}

	public void setCfxMul(BigDecimal cfxMul) {
		this.cfxMul = cfxMul;
	}

	@Column(name = "CFX_JUR", nullable = false, precision = 6)
	public BigDecimal getCfxJur() {
		return this.cfxJur;
	}

	public void setCfxJur(BigDecimal cfxJur) {
		this.cfxJur = cfxJur;
	}

	@Column(name = "CFX_TOL", nullable = false)
	public int getCfxTol() {
		return this.cfxTol;
	}

	public void setCfxTol(int cfxTol) {
		this.cfxTol = cfxTol;
	}

	@Column(name = "CFX_OB1", length = 40)
	public String getCfxOb1() {
		return this.cfxOb1;
	}

	public void setCfxOb1(String cfxOb1) {
		this.cfxOb1 = cfxOb1;
	}

	@Column(name = "CFX_OB2", length = 40)
	public String getCfxOb2() {
		return this.cfxOb2;
	}

	public void setCfxOb2(String cfxOb2) {
		this.cfxOb2 = cfxOb2;
	}

	@Column(name = "CFX_TIF", nullable = false)
	public int getCfxTif() {
		return this.cfxTif;
	}

	public void setCfxTif(int cfxTif) {
		this.cfxTif = cfxTif;
	}

	@Column(name = "CFX_CTB", nullable = false, length = 1)
	public char getCfxCtb() {
		return this.cfxCtb;
	}

	public void setCfxCtb(char cfxCtb) {
		this.cfxCtb = cfxCtb;
	}

	@Column(name = "CFX_OPF")
	public Integer getCfxOpf() {
		return this.cfxOpf;
	}

	public void setCfxOpf(Integer cfxOpf) {
		this.cfxOpf = cfxOpf;
	}

	@Column(name = "CFX_SIT", nullable = false, length = 1)
	public char getCfxSit() {
		return this.cfxSit;
	}

	public void setCfxSit(char cfxSit) {
		this.cfxSit = cfxSit;
	}

	@Column(name = "CFX_VLR", nullable = false, precision = 14)
	public BigDecimal getCfxVlr() {
		return this.cfxVlr;
	}

	public void setCfxVlr(BigDecimal cfxVlr) {
		this.cfxVlr = cfxVlr;
	}

	@Column(name = "CFX_M01", nullable = false, length = 1)
	public char getCfxM01() {
		return this.cfxM01;
	}

	public void setCfxM01(char cfxM01) {
		this.cfxM01 = cfxM01;
	}

	@Column(name = "CFX_M02", nullable = false, length = 1)
	public char getCfxM02() {
		return this.cfxM02;
	}

	public void setCfxM02(char cfxM02) {
		this.cfxM02 = cfxM02;
	}

	@Column(name = "CFX_M03", nullable = false, length = 1)
	public char getCfxM03() {
		return this.cfxM03;
	}

	public void setCfxM03(char cfxM03) {
		this.cfxM03 = cfxM03;
	}

	@Column(name = "CFX_M04", nullable = false, length = 1)
	public char getCfxM04() {
		return this.cfxM04;
	}

	public void setCfxM04(char cfxM04) {
		this.cfxM04 = cfxM04;
	}

	@Column(name = "CFX_M05", nullable = false, length = 1)
	public char getCfxM05() {
		return this.cfxM05;
	}

	public void setCfxM05(char cfxM05) {
		this.cfxM05 = cfxM05;
	}

	@Column(name = "CFX_M06", nullable = false, length = 1)
	public char getCfxM06() {
		return this.cfxM06;
	}

	public void setCfxM06(char cfxM06) {
		this.cfxM06 = cfxM06;
	}

	@Column(name = "CFX_M07", nullable = false, length = 1)
	public char getCfxM07() {
		return this.cfxM07;
	}

	public void setCfxM07(char cfxM07) {
		this.cfxM07 = cfxM07;
	}

	@Column(name = "CFX_M08", nullable = false, length = 1)
	public char getCfxM08() {
		return this.cfxM08;
	}

	public void setCfxM08(char cfxM08) {
		this.cfxM08 = cfxM08;
	}

	@Column(name = "CFX_M09", nullable = false, length = 1)
	public char getCfxM09() {
		return this.cfxM09;
	}

	public void setCfxM09(char cfxM09) {
		this.cfxM09 = cfxM09;
	}

	@Column(name = "CFX_M10", nullable = false, length = 1)
	public char getCfxM10() {
		return this.cfxM10;
	}

	public void setCfxM10(char cfxM10) {
		this.cfxM10 = cfxM10;
	}

	@Column(name = "CFX_M11", nullable = false, length = 1)
	public char getCfxM11() {
		return this.cfxM11;
	}

	public void setCfxM11(char cfxM11) {
		this.cfxM11 = cfxM11;
	}

	@Column(name = "CFX_M12", nullable = false, length = 1)
	public char getCfxM12() {
		return this.cfxM12;
	}

	public void setCfxM12(char cfxM12) {
		this.cfxM12 = cfxM12;
	}

	@Column(name = "CFX_TDV", nullable = false, length = 1)
	public char getCfxTdv() {
		return this.cfxTdv;
	}

	public void setCfxTdv(char cfxTdv) {
		this.cfxTdv = cfxTdv;
	}

	@Column(name = "CFX_TCV", nullable = false, length = 1)
	public char getCfxTcv() {
		return this.cfxTcv;
	}

	public void setCfxTcv(char cfxTcv) {
		this.cfxTcv = cfxTcv;
	}

	@Column(name = "CFX_DOC", length = 10)
	public String getCfxDoc() {
		return this.cfxDoc;
	}

	public void setCfxDoc(String cfxDoc) {
		this.cfxDoc = cfxDoc;
	}

	@Column(name = "CFX_TPC", nullable = false, length = 1)
	public char getCfxTpc() {
		return this.cfxTpc;
	}

	public void setCfxTpc(char cfxTpc) {
		this.cfxTpc = cfxTpc;
	}

}
