package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmpresaPautaModeloArtigo generated by hbm2java
 */
@Entity
@Table(name = "EMPRESAPAUTAMODELOARTIGO")
public class EmpresaPautaModeloArtigo implements java.io.Serializable {

	private static final long serialVersionUID = -1814189072033180385L;
	private EmpresaPautaModeloArtigoId id;
	private Artigo artigo;
	private EmpresaPauta empresaPauta;
	private Modelo modelo;
	private BigDecimal epmPrv;
	private BigDecimal epmPrp;

	public EmpresaPautaModeloArtigo() {
	}

	public EmpresaPautaModeloArtigo(EmpresaPautaModeloArtigoId id,
			Artigo artigo, EmpresaPauta empresaPauta, Modelo modelo,
			BigDecimal epmPrv, BigDecimal epmPrp) {
		this.id = id;
		this.artigo = artigo;
		this.empresaPauta = empresaPauta;
		this.modelo = modelo;
		this.epmPrv = epmPrv;
		this.epmPrp = epmPrp;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "epmEmp", column = @Column(name = "EPM_EMP", nullable = false)),
			@AttributeOverride(name = "epmPat", column = @Column(name = "EPM_PAT", nullable = false)),
			@AttributeOverride(name = "epmMdl", column = @Column(name = "EPM_MDL", nullable = false)),
			@AttributeOverride(name = "epmAtg", column = @Column(name = "EPM_ATG", nullable = false)) })
	public EmpresaPautaModeloArtigoId getId() {
		return this.id;
	}

	public void setId(EmpresaPautaModeloArtigoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EPM_ATG", nullable = false, insertable = false, updatable = false)
	public Artigo getArtigo() {
		return this.artigo;
	}

	public void setArtigo(Artigo artigo) {
		this.artigo = artigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "EPM_EMP", referencedColumnName = "EPT_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "EPM_PAT", referencedColumnName = "EPT_PAT", nullable = false, insertable = false, updatable = false) })
	public EmpresaPauta getEmpresaPauta() {
		return this.empresaPauta;
	}

	public void setEmpresaPauta(EmpresaPauta empresaPauta) {
		this.empresaPauta = empresaPauta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "EPM_EMP", referencedColumnName = "MDL_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "EPM_MDL", referencedColumnName = "MDL_COD", nullable = false, insertable = false, updatable = false)  
	})
	public Modelo getModelo() {
		return this.modelo;
	}

	public void setModelo(Modelo modelo) {
		this.modelo = modelo;
	}

	@Column(name = "EPM_PRV", nullable = false, precision = 18, scale = 5)
	public BigDecimal getEpmPrv() {
		return this.epmPrv;
	}

	public void setEpmPrv(BigDecimal epmPrv) {
		this.epmPrv = epmPrv;
	}

	@Column(name = "EPM_PRP", nullable = false, precision = 18, scale = 5)
	public BigDecimal getEpmPrp() {
		return this.epmPrp;
	}

	public void setEpmPrp(BigDecimal epmPrp) {
		this.epmPrp = epmPrp;
	}

}
