package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FormaPagto generated by hbm2java
 */
@Entity
@Table(name = "FORMAPAGTO")
public class FormaPagto implements java.io.Serializable {

	
	private static final long serialVersionUID = 748722100883260352L;
	private int fpaCod;
	private String fpaNom;
	private String fpaSig;
	private BigDecimal fpaMul;
	private BigDecimal fpaJur;
	private int fpaTol;
	private char fpaCba;
	private char fpaLre;
	private char fpaBre;
	private char fpaLpg;
	private char fpaBpg;
	private char fpaLmc;
	private char fpaBmc;
	private char fpaPal;
	private int fpaFvd;
	private int fpaFpd;
	private char fpaEqf;
	private char fpaEqn;
	private char fpaEqc;
	private int fpaFcp;
	private int fpaTic;
	private Set<Pedido> pedidosForPedFpa = new HashSet<Pedido>(0);
	private Set<Pedido> pedidosForPedFpc = new HashSet<Pedido>(0);
	/*private Set<Movimentacaoconta> movimentacaocontas = new HashSet<Movimentacaoconta>(0);
	private Set<Pedidocompra> pedidocompras = new HashSet<Pedidocompra>(0);
	private Set<Receber> recebers = new HashSet<Receber>(0);
	private Set<Contratoservico> contratoservicos = new HashSet<Contratoservico>(0);
	private Set<Empresapautacondicao> empresapautacondicaos = new HashSet<Empresapautacondicao>(0);
	private Set<Notafiscalparcelas> notafiscalparcelases = new HashSet<Notafiscalparcelas>(0);
	private Set<Notafiscal> notafiscals = new HashSet<Notafiscal>(0);
	private Set<Clienterepresentante> clienterepresentantesForClrFpa = new HashSet<Clienterepresentante>(0);
	private Set<Pagar> pagars = new HashSet<Pagar>(0);
	private Set<Custofixo> custofixos = new HashSet<Custofixo>(0);
	private Set<Clienterepresentante> clienterepresentantesForClrFpc = new HashSet<Clienterepresentante>(0);
	private Set<Movimentoparcelas> movimentoparcelases = new HashSet<Movimentoparcelas>(0);*/

	public FormaPagto() {
	}

	public FormaPagto(int fpaCod, String fpaNom, BigDecimal fpaMul,
			BigDecimal fpaJur, int fpaTol, char fpaCba, char fpaLre,
			char fpaBre, char fpaLpg, char fpaBpg, char fpaLmc, char fpaBmc,
			char fpaPal, int fpaFvd, int fpaFpd, char fpaEqf, char fpaEqn,
			char fpaEqc, int fpaFcp, int fpaTic) {
		this.fpaCod = fpaCod;
		this.fpaNom = fpaNom;
		this.fpaMul = fpaMul;
		this.fpaJur = fpaJur;
		this.fpaTol = fpaTol;
		this.fpaCba = fpaCba;
		this.fpaLre = fpaLre;
		this.fpaBre = fpaBre;
		this.fpaLpg = fpaLpg;
		this.fpaBpg = fpaBpg;
		this.fpaLmc = fpaLmc;
		this.fpaBmc = fpaBmc;
		this.fpaPal = fpaPal;
		this.fpaFvd = fpaFvd;
		this.fpaFpd = fpaFpd;
		this.fpaEqf = fpaEqf;
		this.fpaEqn = fpaEqn;
		this.fpaEqc = fpaEqc;
		this.fpaFcp = fpaFcp;
		this.fpaTic = fpaTic;
	}

	/*public FormaPagto(int fpaCod, String fpaNom, String fpaSig,
			BigDecimal fpaMul, BigDecimal fpaJur, int fpaTol, char fpaCba,
			char fpaLre, char fpaBre, char fpaLpg, char fpaBpg, char fpaLmc,
			char fpaBmc, char fpaPal, int fpaFvd, int fpaFpd, char fpaEqf,
			char fpaEqn, char fpaEqc, int fpaFcp, int fpaTic,
			Set<Pedido> pedidosForPedFpa,
			Set<Movimentacaoconta> movimentacaocontas,
			Set<Pedido> pedidosForPedFpc, Set<Pedidocompra> pedidocompras,
			Set<Receber> recebers, Set<Contratoservico> contratoservicos,
			Set<Empresapautacondicao> empresapautacondicaos,
			Set<Notafiscalparcelas> notafiscalparcelases,
			Set<Notafiscal> notafiscals,
			Set<Clienterepresentante> clienterepresentantesForClrFpa,
			Set<Pagar> pagars, Set<Custofixo> custofixos,
			Set<Clienterepresentante> clienterepresentantesForClrFpc,
			Set<Movimentoparcelas> movimentoparcelases) {
		this.fpaCod = fpaCod;
		this.fpaNom = fpaNom;
		this.fpaSig = fpaSig;
		this.fpaMul = fpaMul;
		this.fpaJur = fpaJur;
		this.fpaTol = fpaTol;
		this.fpaCba = fpaCba;
		this.fpaLre = fpaLre;
		this.fpaBre = fpaBre;
		this.fpaLpg = fpaLpg;
		this.fpaBpg = fpaBpg;
		this.fpaLmc = fpaLmc;
		this.fpaBmc = fpaBmc;
		this.fpaPal = fpaPal;
		this.fpaFvd = fpaFvd;
		this.fpaFpd = fpaFpd;
		this.fpaEqf = fpaEqf;
		this.fpaEqn = fpaEqn;
		this.fpaEqc = fpaEqc;
		this.fpaFcp = fpaFcp;
		this.fpaTic = fpaTic;
		this.pedidosForPedFpa = pedidosForPedFpa;
		this.movimentacaocontas = movimentacaocontas;
		this.pedidosForPedFpc = pedidosForPedFpc;
		this.pedidocompras = pedidocompras;
		this.recebers = recebers;
		this.contratoservicos = contratoservicos;
		this.empresapautacondicaos = empresapautacondicaos;
		this.notafiscalparcelases = notafiscalparcelases;
		this.notafiscals = notafiscals;
		this.clienterepresentantesForClrFpa = clienterepresentantesForClrFpa;
		this.pagars = pagars;
		this.custofixos = custofixos;
		this.clienterepresentantesForClrFpc = clienterepresentantesForClrFpc;
		this.movimentoparcelases = movimentoparcelases;
	}*/

	@Id
	@Column(name = "FPA_COD", unique = true, nullable = false)
	public int getFpaCod() {
		return this.fpaCod;
	}

	public void setFpaCod(int fpaCod) {
		this.fpaCod = fpaCod;
	}

	@Column(name = "FPA_NOM", nullable = false, length = 30)
	public String getFpaNom() {
		return this.fpaNom;
	}

	public void setFpaNom(String fpaNom) {
		this.fpaNom = fpaNom;
	}

	@Column(name = "FPA_SIG", length = 3)
	public String getFpaSig() {
		return this.fpaSig;
	}

	public void setFpaSig(String fpaSig) {
		this.fpaSig = fpaSig;
	}

	@Column(name = "FPA_MUL", nullable = false, precision = 6)
	public BigDecimal getFpaMul() {
		return this.fpaMul;
	}

	public void setFpaMul(BigDecimal fpaMul) {
		this.fpaMul = fpaMul;
	}

	@Column(name = "FPA_JUR", nullable = false, precision = 6)
	public BigDecimal getFpaJur() {
		return this.fpaJur;
	}

	public void setFpaJur(BigDecimal fpaJur) {
		this.fpaJur = fpaJur;
	}

	@Column(name = "FPA_TOL", nullable = false)
	public int getFpaTol() {
		return this.fpaTol;
	}

	public void setFpaTol(int fpaTol) {
		this.fpaTol = fpaTol;
	}

	@Column(name = "FPA_CBA", nullable = false, length = 1)
	public char getFpaCba() {
		return this.fpaCba;
	}

	public void setFpaCba(char fpaCba) {
		this.fpaCba = fpaCba;
	}

	@Column(name = "FPA_LRE", nullable = false, length = 1)
	public char getFpaLre() {
		return this.fpaLre;
	}

	public void setFpaLre(char fpaLre) {
		this.fpaLre = fpaLre;
	}

	@Column(name = "FPA_BRE", nullable = false, length = 1)
	public char getFpaBre() {
		return this.fpaBre;
	}

	public void setFpaBre(char fpaBre) {
		this.fpaBre = fpaBre;
	}

	@Column(name = "FPA_LPG", nullable = false, length = 1)
	public char getFpaLpg() {
		return this.fpaLpg;
	}

	public void setFpaLpg(char fpaLpg) {
		this.fpaLpg = fpaLpg;
	}

	@Column(name = "FPA_BPG", nullable = false, length = 1)
	public char getFpaBpg() {
		return this.fpaBpg;
	}

	public void setFpaBpg(char fpaBpg) {
		this.fpaBpg = fpaBpg;
	}

	@Column(name = "FPA_LMC", nullable = false, length = 1)
	public char getFpaLmc() {
		return this.fpaLmc;
	}

	public void setFpaLmc(char fpaLmc) {
		this.fpaLmc = fpaLmc;
	}

	@Column(name = "FPA_BMC", nullable = false, length = 1)
	public char getFpaBmc() {
		return this.fpaBmc;
	}

	public void setFpaBmc(char fpaBmc) {
		this.fpaBmc = fpaBmc;
	}

	@Column(name = "FPA_PAL", nullable = false, length = 1)
	public char getFpaPal() {
		return this.fpaPal;
	}

	public void setFpaPal(char fpaPal) {
		this.fpaPal = fpaPal;
	}

	@Column(name = "FPA_FVD", nullable = false)
	public int getFpaFvd() {
		return this.fpaFvd;
	}

	public void setFpaFvd(int fpaFvd) {
		this.fpaFvd = fpaFvd;
	}

	@Column(name = "FPA_FPD", nullable = false)
	public int getFpaFpd() {
		return this.fpaFpd;
	}

	public void setFpaFpd(int fpaFpd) {
		this.fpaFpd = fpaFpd;
	}

	@Column(name = "FPA_EQF", nullable = false, length = 1)
	public char getFpaEqf() {
		return this.fpaEqf;
	}

	public void setFpaEqf(char fpaEqf) {
		this.fpaEqf = fpaEqf;
	}

	@Column(name = "FPA_EQN", nullable = false, length = 1)
	public char getFpaEqn() {
		return this.fpaEqn;
	}

	public void setFpaEqn(char fpaEqn) {
		this.fpaEqn = fpaEqn;
	}

	@Column(name = "FPA_EQC", nullable = false, length = 1)
	public char getFpaEqc() {
		return this.fpaEqc;
	}

	public void setFpaEqc(char fpaEqc) {
		this.fpaEqc = fpaEqc;
	}

	@Column(name = "FPA_FCP", nullable = false)
	public int getFpaFcp() {
		return this.fpaFcp;
	}

	public void setFpaFcp(int fpaFcp) {
		this.fpaFcp = fpaFcp;
	}

	@Column(name = "FPA_TIC", nullable = false)
	public int getFpaTic() {
		return this.fpaTic;
	}

	public void setFpaTic(int fpaTic) {
		this.fpaTic = fpaTic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formaPagtoByPedFpa")
	public Set<Pedido> getPedidosForPedFpa() {
		return this.pedidosForPedFpa;
	}

	public void setPedidosForPedFpa(Set<Pedido> pedidosForPedFpa) {
		this.pedidosForPedFpa = pedidosForPedFpa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formaPagtoByPedFpc")
	public Set<Pedido> getPedidosForPedFpc() {
		return this.pedidosForPedFpc;
	}

	public void setPedidosForPedFpc(Set<Pedido> pedidosForPedFpc) {
		this.pedidosForPedFpc = pedidosForPedFpc;
	}
	
	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "formapagto")
	public Set<Movimentacaoconta> getMovimentacaocontas() {
		return this.movimentacaocontas;
	}

	public void setMovimentacaocontas(Set<Movimentacaoconta> movimentacaocontas) {
		this.movimentacaocontas = movimentacaocontas;
	}

	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formapagto")
	public Set<Pedidocompra> getPedidocompras() {
		return this.pedidocompras;
	}

	public void setPedidocompras(Set<Pedidocompra> pedidocompras) {
		this.pedidocompras = pedidocompras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formapagto")
	public Set<Receber> getRecebers() {
		return this.recebers;
	}

	public void setRecebers(Set<Receber> recebers) {
		this.recebers = recebers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formapagto")
	public Set<Contratoservico> getContratoservicos() {
		return this.contratoservicos;
	}

	public void setContratoservicos(Set<Contratoservico> contratoservicos) {
		this.contratoservicos = contratoservicos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formapagto")
	public Set<Empresapautacondicao> getEmpresapautacondicaos() {
		return this.empresapautacondicaos;
	}

	public void setEmpresapautacondicaos(
			Set<Empresapautacondicao> empresapautacondicaos) {
		this.empresapautacondicaos = empresapautacondicaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formapagto")
	public Set<Notafiscalparcelas> getNotafiscalparcelases() {
		return this.notafiscalparcelases;
	}

	public void setNotafiscalparcelases(
			Set<Notafiscalparcelas> notafiscalparcelases) {
		this.notafiscalparcelases = notafiscalparcelases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formapagto")
	public Set<Notafiscal> getNotafiscals() {
		return this.notafiscals;
	}

	public void setNotafiscals(Set<Notafiscal> notafiscals) {
		this.notafiscals = notafiscals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formapagtoByClrFpa")
	public Set<Clienterepresentante> getClienterepresentantesForClrFpa() {
		return this.clienterepresentantesForClrFpa;
	}

	public void setClienterepresentantesForClrFpa(
			Set<Clienterepresentante> clienterepresentantesForClrFpa) {
		this.clienterepresentantesForClrFpa = clienterepresentantesForClrFpa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formapagto")
	public Set<Pagar> getPagars() {
		return this.pagars;
	}

	public void setPagars(Set<Pagar> pagars) {
		this.pagars = pagars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formapagto")
	public Set<Custofixo> getCustofixos() {
		return this.custofixos;
	}

	public void setCustofixos(Set<Custofixo> custofixos) {
		this.custofixos = custofixos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formapagtoByClrFpc")
	public Set<Clienterepresentante> getClienterepresentantesForClrFpc() {
		return this.clienterepresentantesForClrFpc;
	}

	public void setClienterepresentantesForClrFpc(
			Set<Clienterepresentante> clienterepresentantesForClrFpc) {
		this.clienterepresentantesForClrFpc = clienterepresentantesForClrFpc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "formapagto")
	public Set<Movimentoparcelas> getMovimentoparcelases() {
		return this.movimentoparcelases;
	}

	public void setMovimentoparcelases(
			Set<Movimentoparcelas> movimentoparcelases) {
		this.movimentoparcelases = movimentoparcelases;
	}*/

}
