package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name = "FORNECEDOR")
public class Fornecedor implements java.io.Serializable {

	private static final long serialVersionUID = 8024595054762398082L;
	private FornecedorId id;
	private ColaboradorEmpresa colaboradorEmpresa;
	private Date forDti;
	private Date forDtf;
	private String forRno;
	private String forRti;
	private String forRin;
	private String forRrg;
	private String forRen;
	private Integer forRnu;
	private String forRco;
	private String forRba;
	private Integer forRmu;
	private String forRce;
	private String forRdd;
	private String forRfo;
	private String forRdf;
	private String forRfa;
	private String forRdc;
	private String forRcl;
	private String forRem;
	private String forRwe;
	private String forOb1;
	private String forOb2;
	private String forOb3;
	private Set<Modelo> modelos = new HashSet<Modelo>(0);
	//private Set<Produtofornecedor> produtofornecedors = new HashSet<Produtofornecedor>(0);
	private Set<Produto> produtos = new HashSet<Produto>(0);

	public Fornecedor() {
	}

	public Fornecedor(ColaboradorEmpresa colaboradorEmpresa) {
		this.colaboradorEmpresa = colaboradorEmpresa;
	}

	/*public Fornecedor(ColaboradorEmpresa colaboradorEmpresa, Date forDti,
			Date forDtf, String forRno, String forRti, String forRin,
			String forRrg, String forRen, Integer forRnu, String forRco,
			String forRba, Integer forRmu, String forRce, String forRdd,
			String forRfo, String forRdf, String forRfa, String forRdc,
			String forRcl, String forRem, String forRwe, String forOb1,
			String forOb2, String forOb3, Set<Modelo> modelos,
			Set<Produtofornecedor> produtofornecedors, Set<Produto> produtos) {
		this.colaboradorEmpresa = colaboradorEmpresa;
		this.forDti = forDti;
		this.forDtf = forDtf;
		this.forRno = forRno;
		this.forRti = forRti;
		this.forRin = forRin;
		this.forRrg = forRrg;
		this.forRen = forRen;
		this.forRnu = forRnu;
		this.forRco = forRco;
		this.forRba = forRba;
		this.forRmu = forRmu;
		this.forRce = forRce;
		this.forRdd = forRdd;
		this.forRfo = forRfo;
		this.forRdf = forRdf;
		this.forRfa = forRfa;
		this.forRdc = forRdc;
		this.forRcl = forRcl;
		this.forRem = forRem;
		this.forRwe = forRwe;
		this.forOb1 = forOb1;
		this.forOb2 = forOb2;
		this.forOb3 = forOb3;
		this.modelos = modelos;
		this.produtofornecedors = produtofornecedors;
		this.produtos = produtos;
	}*/

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "forEmp", column = @Column(name = "FOR_EMP", nullable = false)),
			@AttributeOverride(name = "forCol", column = @Column(name = "FOR_COL", nullable = false)) })
	public FornecedorId getId() {
		return this.id;
	}

	public void setId(FornecedorId id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public ColaboradorEmpresa getColaboradorEmpresa() {
		return this.colaboradorEmpresa;
	}

	public void setColaboradorEmpresa(ColaboradorEmpresa colaboradorEmpresa) {
		this.colaboradorEmpresa = colaboradorEmpresa;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FOR_DTI", length = 10)
	public Date getForDti() {
		return this.forDti;
	}

	public void setForDti(Date forDti) {
		this.forDti = forDti;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FOR_DTF", length = 10)
	public Date getForDtf() {
		return this.forDtf;
	}

	public void setForDtf(Date forDtf) {
		this.forDtf = forDtf;
	}

	@Column(name = "FOR_RNO", length = 40)
	public String getForRno() {
		return this.forRno;
	}

	public void setForRno(String forRno) {
		this.forRno = forRno;
	}

	@Column(name = "FOR_RTI", length = 4)
	public String getForRti() {
		return this.forRti;
	}

	public void setForRti(String forRti) {
		this.forRti = forRti;
	}

	@Column(name = "FOR_RIN", length = 14)
	public String getForRin() {
		return this.forRin;
	}

	public void setForRin(String forRin) {
		this.forRin = forRin;
	}

	@Column(name = "FOR_RRG", length = 15)
	public String getForRrg() {
		return this.forRrg;
	}

	public void setForRrg(String forRrg) {
		this.forRrg = forRrg;
	}

	@Column(name = "FOR_REN", length = 40)
	public String getForRen() {
		return this.forRen;
	}

	public void setForRen(String forRen) {
		this.forRen = forRen;
	}

	@Column(name = "FOR_RNU")
	public Integer getForRnu() {
		return this.forRnu;
	}

	public void setForRnu(Integer forRnu) {
		this.forRnu = forRnu;
	}

	@Column(name = "FOR_RCO", length = 20)
	public String getForRco() {
		return this.forRco;
	}

	public void setForRco(String forRco) {
		this.forRco = forRco;
	}

	@Column(name = "FOR_RBA", length = 20)
	public String getForRba() {
		return this.forRba;
	}

	public void setForRba(String forRba) {
		this.forRba = forRba;
	}

	@Column(name = "FOR_RMU")
	public Integer getForRmu() {
		return this.forRmu;
	}

	public void setForRmu(Integer forRmu) {
		this.forRmu = forRmu;
	}

	@Column(name = "FOR_RCE", length = 8)
	public String getForRce() {
		return this.forRce;
	}

	public void setForRce(String forRce) {
		this.forRce = forRce;
	}

	@Column(name = "FOR_RDD", length = 2)
	public String getForRdd() {
		return this.forRdd;
	}

	public void setForRdd(String forRdd) {
		this.forRdd = forRdd;
	}

	@Column(name = "FOR_RFO", length = 8)
	public String getForRfo() {
		return this.forRfo;
	}

	public void setForRfo(String forRfo) {
		this.forRfo = forRfo;
	}

	@Column(name = "FOR_RDF", length = 2)
	public String getForRdf() {
		return this.forRdf;
	}

	public void setForRdf(String forRdf) {
		this.forRdf = forRdf;
	}

	@Column(name = "FOR_RFA", length = 8)
	public String getForRfa() {
		return this.forRfa;
	}

	public void setForRfa(String forRfa) {
		this.forRfa = forRfa;
	}

	@Column(name = "FOR_RDC", length = 2)
	public String getForRdc() {
		return this.forRdc;
	}

	public void setForRdc(String forRdc) {
		this.forRdc = forRdc;
	}

	@Column(name = "FOR_RCL", length = 8)
	public String getForRcl() {
		return this.forRcl;
	}

	public void setForRcl(String forRcl) {
		this.forRcl = forRcl;
	}

	@Column(name = "FOR_REM", length = 50)
	public String getForRem() {
		return this.forRem;
	}

	public void setForRem(String forRem) {
		this.forRem = forRem;
	}

	@Column(name = "FOR_RWE", length = 50)
	public String getForRwe() {
		return this.forRwe;
	}

	public void setForRwe(String forRwe) {
		this.forRwe = forRwe;
	}

	@Column(name = "FOR_OB1", length = 40)
	public String getForOb1() {
		return this.forOb1;
	}

	public void setForOb1(String forOb1) {
		this.forOb1 = forOb1;
	}

	@Column(name = "FOR_OB2", length = 40)
	public String getForOb2() {
		return this.forOb2;
	}

	public void setForOb2(String forOb2) {
		this.forOb2 = forOb2;
	}

	@Column(name = "FOR_OB3", length = 40)
	public String getForOb3() {
		return this.forOb3;
	}

	public void setForOb3(String forOb3) {
		this.forOb3 = forOb3;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fornecedor")
	public Set<Modelo> getModelos() {
		return this.modelos;
	}

	public void setModelos(Set<Modelo> modelos) {
		this.modelos = modelos;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "fornecedor")
	public Set<Produtofornecedor> getProdutofornecedors() {
		return this.produtofornecedors;
	}

	public void setProdutofornecedors(Set<Produtofornecedor> produtofornecedors) {
		this.produtofornecedors = produtofornecedors;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fornecedor")
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

}
