package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name = "GRUPO")
public class Grupo implements java.io.Serializable {

	private static final long serialVersionUID = 4006234145947874641L;
	private Integer gruCod;
	private String gruNom;
	private String gruTip;
	private String gruMat;
	private String gruSit;
	private String gruNcm;
	//private Set<Subgrupo> subgrupos = new HashSet<Subgrupo>(0);
	private Set<Modelo> modelos = new HashSet<Modelo>(0);
	//private Set<Estoqueminimo> estoqueminimos = new HashSet<Estoqueminimo>(0);
	private Set<Produto> produtos = new HashSet<Produto>(0);
	//private Set<Grupomateriaprima> grupomateriaprimas = new HashSet<Grupomateriaprima>(0);

	public Grupo() {
	}

	public Grupo(Integer gruCod, String gruNom, String gruTip, String gruMat,
			String gruSit) {
		this.gruCod = gruCod;
		this.gruNom = gruNom;
		this.gruTip = gruTip;
		this.gruMat = gruMat;
		this.gruSit = gruSit;
	}

	/*public Grupo(Integer gruCod, String gruNom, String gruTip, String gruMat,
			String gruSit, String gruNcm, Set<Subgrupo> subgrupos,
			Set<Modelo> modelos, Set<Estoqueminimo> estoqueminimos,
			Set<Produto> produtos, Set<Grupomateriaprima> grupomateriaprimas) {
		this.gruCod = gruCod;
		this.gruNom = gruNom;
		this.gruTip = gruTip;
		this.gruMat = gruMat;
		this.gruSit = gruSit;
		this.gruNcm = gruNcm;
		this.subgrupos = subgrupos;
		this.modelos = modelos;
		this.estoqueminimos = estoqueminimos;
		this.produtos = produtos;
		this.grupomateriaprimas = grupomateriaprimas;
	}*/

	@Id
	@Column(name = "GRU_COD", unique = true, nullable = false)
	public Integer getGruCod() {
		return this.gruCod;
	}

	public void setGruCod(Integer gruCod) {
		this.gruCod = gruCod;
	}

	@Column(name = "GRU_NOM", nullable = false, length = 30)
	public String getGruNom() {
		return this.gruNom;
	}

	public void setGruNom(String gruNom) {
		this.gruNom = gruNom;
	}

	@Column(name = "GRU_TIP", nullable = false, length = 1)
	public String getGruTip() {
		return this.gruTip;
	}

	public void setGruTip(String gruTip) {
		this.gruTip = gruTip;
	}

	@Column(name = "GRU_MAT", nullable = false, length = 1)
	public String getGruMat() {
		return this.gruMat;
	}

	public void setGruMat(String gruMat) {
		this.gruMat = gruMat;
	}

	@Column(name = "GRU_SIT", nullable = false, length = 1)
	public String getGruSit() {
		return this.gruSit;
	}

	public void setGruSit(String gruSit) {
		this.gruSit = gruSit;
	}

	@Column(name = "GRU_NCM", length = 8)
	public String getGruNcm() {
		return this.gruNcm;
	}

	public void setGruNcm(String gruNcm) {
		this.gruNcm = gruNcm;
	}
/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	public Set<Subgrupo> getSubgrupos() {
		return this.subgrupos;
	}

	public void setSubgrupos(Set<Subgrupo> subgrupos) {
		this.subgrupos = subgrupos;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	public Set<Modelo> getModelos() {
		return this.modelos;
	}

	public void setModelos(Set<Modelo> modelos) {
		this.modelos = modelos;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	public Set<Estoqueminimo> getEstoqueminimos() {
		return this.estoqueminimos;
	}

	public void setEstoqueminimos(Set<Estoqueminimo> estoqueminimos) {
		this.estoqueminimos = estoqueminimos;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	public Set<Grupomateriaprima> getGrupomateriaprimas() {
		return this.grupomateriaprimas;
	}

	public void setGrupomateriaprimas(Set<Grupomateriaprima> grupomateriaprimas) {
		this.grupomateriaprimas = grupomateriaprimas;
	}*/

}
