package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LocalDeposito generated by hbm2java
 */
@Entity
@Table(name = "LOCALDEPOSITO")
public class LocalDeposito implements java.io.Serializable {

	private static final long serialVersionUID = 2331816544896894499L;
	private LocalDepositoId id;
	private Filial filial;
	private String lcdNom;
	private Set<Movimento> movimentosForFkMovLcd = new HashSet<Movimento>(0);
	private Set<ProdutoLocal> produtoLocals = new HashSet<ProdutoLocal>(0);
	//private Set<Balanco> balancos = new HashSet<Balanco>(0);
	private Set<Movimento> movimentosForFkMovLdd = new HashSet<Movimento>(0);

	public LocalDeposito() {
	}

	public LocalDeposito(LocalDepositoId id, Filial filial, String lcdNom) {
		this.id = id;
		this.filial = filial;
		this.lcdNom = lcdNom;
	}

	/* public LocalDeposito(LocalDepositoId id, Filial filial, String lcdNom,
			Set<Movimento> movimentosForFkMovLcd,
			Set<ProdutoLocal> produtoLocals, Set<Balanco> balancos,
			Set<Movimento> movimentosForFkMovLdd) {
		this.id = id;
		this.filial = filial;
		this.lcdNom = lcdNom;
		this.movimentosForFkMovLcd = movimentosForFkMovLcd;
		this.produtoLocals = produtoLocals;
		this.balancos = balancos;
		this.movimentosForFkMovLdd = movimentosForFkMovLdd;
	} */

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "lcdEmp", column = @Column(name = "LCD_EMP", nullable = false)),
			@AttributeOverride(name = "lcdFil", column = @Column(name = "LCD_FIL", nullable = false)),
			@AttributeOverride(name = "lcdCod", column = @Column(name = "LCD_COD", nullable = false)) })
	public LocalDepositoId getId() {
		return this.id;
	}

	public void setId(LocalDepositoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "LCD_EMP", referencedColumnName = "FIL_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "LCD_FIL", referencedColumnName = "FIL_COD", nullable = false, insertable = false, updatable = false) })
	public Filial getFilial() {
		return this.filial;
	}

	public void setFilial(Filial filial) {
		this.filial = filial;
	}

	@Column(name = "LCD_NOM", nullable = false, length = 40)
	public String getLcdNom() {
		return this.lcdNom;
	}

	public void setLcdNom(String lcdNom) {
		this.lcdNom = lcdNom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localDepositoByFkMovLcd")
	public Set<Movimento> getMovimentosForFkMovLcd() {
		return this.movimentosForFkMovLcd;
	}

	public void setMovimentosForFkMovLcd(Set<Movimento> movimentosForFkMovLcd) {
		this.movimentosForFkMovLcd = movimentosForFkMovLcd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localDeposito")
	public Set<ProdutoLocal> getProdutoLocals() {
		return this.produtoLocals;
	}

	public void setProdutoLocals(Set<ProdutoLocal> produtoLocals) {
		this.produtoLocals = produtoLocals;
	}

	/* @OneToMany(fetch = FetchType.LAZY, mappedBy = "localDeposito")
	public Set<Balanco> getBalancos() {
		return this.balancos;
	}

	public void setBalancos(Set<Balanco> balancos) {
		this.balancos = balancos;
	} */

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "localDepositoByFkMovLdd")
	public Set<Movimento> getMovimentosForFkMovLdd() {
		return this.movimentosForFkMovLdd;
	}

	public void setMovimentosForFkMovLdd(Set<Movimento> movimentosForFkMovLdd) {
		this.movimentosForFkMovLdd = movimentosForFkMovLdd;
	}

}
