package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocalDepositoId generated by hbm2java
 */
@Embeddable
public class LocalDepositoId implements java.io.Serializable {

	private static final long serialVersionUID = -1834458241644989432L;
	private Integer lcdEmp;
	private Integer lcdFil;
	private Integer lcdCod;

	public LocalDepositoId() {
	}

	public LocalDepositoId(Integer lcdEmp, Integer lcdFil, Integer lcdCod) {
		this.lcdEmp = lcdEmp;
		this.lcdFil = lcdFil;
		this.lcdCod = lcdCod;
	}

	@Column(name = "LCD_EMP", nullable = false)
	public Integer getLcdEmp() {
		return this.lcdEmp;
	}

	public void setLcdEmp(Integer lcdEmp) {
		this.lcdEmp = lcdEmp;
	}

	@Column(name = "LCD_FIL", nullable = false)
	public Integer getLcdFil() {
		return this.lcdFil;
	}

	public void setLcdFil(Integer lcdFil) {
		this.lcdFil = lcdFil;
	}

	@Column(name = "LCD_COD", nullable = false)
	public Integer getLcdCod() {
		return this.lcdCod;
	}

	public void setLcdCod(Integer lcdCod) {
		this.lcdCod = lcdCod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LocalDepositoId))
			return false;
		LocalDepositoId castOther = (LocalDepositoId) other;

		return (this.getLcdEmp() == castOther.getLcdEmp())
				&& (this.getLcdFil() == castOther.getLcdFil())
				&& (this.getLcdCod() == castOther.getLcdCod());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getLcdEmp();
		result = 37 * result + this.getLcdFil();
		result = 37 * result + this.getLcdCod();
		return result;
	}

}
