package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "MODELO", uniqueConstraints = @UniqueConstraint(columnNames = {
		"MDL_EMP", "MDL_CCP" }))
public class Modelo implements java.io.Serializable {

	private static final long serialVersionUID = 8348524082166668333L;
	private ModeloId id;
	private Colecao colecao;
	private Empresa empresa;
	private Fornecedor fornecedor;
	private Grade grade;
	private Grupo grupo;
	//private Linhaproducao linhaproducao;
	private Marca marca;
	private Modelo modelo;
	private Tributacao tributacao;
	private String mdlNom;
	private String mdlApe;
	private String mdlNn1;
	private String mdlNn2;
	private char mdlSit;
	private String mdlG01;
	private String mdlG02;
	private String mdlG03;
	private String mdlG04;
	private String mdlG05;
	private String mdlG06;
	private String mdlG07;
	private String mdlG08;
	private String mdlG09;
	private String mdlG10;
	private String mdlG11;
	private String mdlG12;
	private String mdlG13;
	private String mdlG14;
	private char mdlTer;
	private BigDecimal mdlIpi;
	private String mdlClf;
	private String mdlUnd;
	private Integer mdlSgr;
	private BigDecimal mdlIcm;
	private BigDecimal mdlFre;
	private BigDecimal mdlOut;
	private BigDecimal mdlCom;
	private BigDecimal mdlImp;
	private BigDecimal mdlOud;
	private BigDecimal mdlMlu;
	private Integer mdlDgc;
	private BigDecimal mdlIpc;
	private BigDecimal mdlPsb;
	private BigDecimal mdlPsl;
	private Integer mdlCpt;
	private String mdlObs;
	private Integer mdlEtc;
	private String mdlObf;
	private String mdlObm;
	private Integer mdlEtl;
	private char mdlCls;
	private char mdlOri;
	private BigDecimal mdlCmg;
	private String mdlNcm;
	private String mdlExt;
	private String mdlEan;
	private String mdlCcp;
	private Integer mdlMlt;
	private String mdlPst;
	private String mdlLgc;
	private String mdlBse;
	private Date mdlDtc;
	private BigDecimal mdlMin;
	private Integer mdlEtf;
	private String mdlObi;
	private String mdlNpt;
	private char mdlSts;
	private String mdlOpe;
	private String mdlFci;
	private Set<EmpresaPautaModeloArtigo> empresaPautaModeloArtigos = new HashSet<EmpresaPautaModeloArtigo>(0);
	private Set<Modelo> modelos = new HashSet<Modelo>(0);
	//private Set<Modelomaodeobra> modelomaodeobras = new HashSet<Modelomaodeobra>(0);
	//private Set<Empresapautamodelotamanho> empresapautamodelotamanhos = new HashSet<Empresapautamodelotamanho>(0);
	//private Set<Modelofichatecnica> modelofichatecnicas = new HashSet<Modelofichatecnica>(0);
	//private Set<Estoqueminimo> estoqueminimos = new HashSet<Estoqueminimo>(0);
	//private Set<Medida> medidas = new HashSet<Medida>(0);
	//private Set<Modeloartigo> modeloartigos = new HashSet<Modeloartigo>(0);
	//private Set<Operacaopautaproduto> operacaopautaprodutos = new HashSet<Operacaopautaproduto>(0);
	//private Set<Pedidoproducaoitens> pedidoproducaoitenses = new HashSet<Pedidoproducaoitens>(0);
	private Set<Produto> produtos = new HashSet<Produto>(0);

	public Modelo() {
	}

	/*public Modelo(ModeloId id, Empresa empresa, Fornecedor fornecedor,
			Linhaproducao linhaproducao, Modelo modelo, Tributacao tributacao,
			String mdlNom, char mdlSit, char mdlG01, char mdlG02, char mdlG03,
			char mdlG04, char mdlG05, char mdlG06, char mdlG07, char mdlG08,
			char mdlG09, char mdlG10, char mdlG11, char mdlG12, char mdlG13,
			char mdlG14, char mdlTer, BigDecimal mdlIpi, BigDecimal mdlIcm,
			BigDecimal mdlFre, BigDecimal mdlOut, BigDecimal mdlCom,
			BigDecimal mdlImp, BigDecimal mdlOud, BigDecimal mdlMlu,
			BigDecimal mdlIpc, BigDecimal mdlPsb, BigDecimal mdlPsl,
			char mdlCls, char mdlOri, BigDecimal mdlCmg, String mdlCcp,
			Date mdlDtc, BigDecimal mdlMin, char mdlSts) {
		this.id = id;
		this.empresa = empresa;
		this.fornecedor = fornecedor;
		this.linhaproducao = linhaproducao;
		this.modelo = modelo;
		this.tributacao = tributacao;
		this.mdlNom = mdlNom;
		this.mdlSit = mdlSit;
		this.mdlG01 = mdlG01;
		this.mdlG02 = mdlG02;
		this.mdlG03 = mdlG03;
		this.mdlG04 = mdlG04;
		this.mdlG05 = mdlG05;
		this.mdlG06 = mdlG06;
		this.mdlG07 = mdlG07;
		this.mdlG08 = mdlG08;
		this.mdlG09 = mdlG09;
		this.mdlG10 = mdlG10;
		this.mdlG11 = mdlG11;
		this.mdlG12 = mdlG12;
		this.mdlG13 = mdlG13;
		this.mdlG14 = mdlG14;
		this.mdlTer = mdlTer;
		this.mdlIpi = mdlIpi;
		this.mdlIcm = mdlIcm;
		this.mdlFre = mdlFre;
		this.mdlOut = mdlOut;
		this.mdlCom = mdlCom;
		this.mdlImp = mdlImp;
		this.mdlOud = mdlOud;
		this.mdlMlu = mdlMlu;
		this.mdlIpc = mdlIpc;
		this.mdlPsb = mdlPsb;
		this.mdlPsl = mdlPsl;
		this.mdlCls = mdlCls;
		this.mdlOri = mdlOri;
		this.mdlCmg = mdlCmg;
		this.mdlCcp = mdlCcp;
		this.mdlDtc = mdlDtc;
		this.mdlMin = mdlMin;
		this.mdlSts = mdlSts;
	}*/

	/* public Modelo(ModeloId id, Colecao colecao, Empresa empresa,
			Fornecedor fornecedor, Grade grade, Grupo grupo,
			Linhaproducao linhaproducao, Marca marca, Modelo modelo,
			Tributacao tributacao, String mdlNom, String mdlApe, String mdlNn1,
			String mdlNn2, char mdlSit, char mdlG01, char mdlG02, char mdlG03,
			char mdlG04, char mdlG05, char mdlG06, char mdlG07, char mdlG08,
			char mdlG09, char mdlG10, char mdlG11, char mdlG12, char mdlG13,
			char mdlG14, char mdlTer, BigDecimal mdlIpi, String mdlClf,
			String mdlUnd, Integer mdlSgr, BigDecimal mdlIcm,
			BigDecimal mdlFre, BigDecimal mdlOut, BigDecimal mdlCom,
			BigDecimal mdlImp, BigDecimal mdlOud, BigDecimal mdlMlu,
			Integer mdlDgc, BigDecimal mdlIpc, BigDecimal mdlPsb,
			BigDecimal mdlPsl, Integer mdlCpt, String mdlObs, Integer mdlEtc,
			String mdlObf, String mdlObm, Integer mdlEtl, char mdlCls,
			char mdlOri, BigDecimal mdlCmg, String mdlNcm, String mdlExt,
			String mdlEan, String mdlCcp, Integer mdlMlt, String mdlPst,
			String mdlLgc, String mdlBse, Date mdlDtc, BigDecimal mdlMin,
			Integer mdlEtf, String mdlObi, String mdlNpt, char mdlSts,
			String mdlOpe, String mdlFci,
			Set<EmpresaPautaModeloArtigo> empresaPautaModeloArtigos,
			Set<Modelo> modelos, Set<Modelomaodeobra> modelomaodeobras,
			Set<Empresapautamodelotamanho> empresapautamodelotamanhos,
			Set<Modelofichatecnica> modelofichatecnicas,
			Set<Estoqueminimo> estoqueminimos, Set<Medida> medidas,
			Set<Modeloartigo> modeloartigos,
			Set<Operacaopautaproduto> operacaopautaprodutos,
			Set<Pedidoproducaoitens> pedidoproducaoitenses,
			Set<Produto> produtos) {
		this.id = id;
		this.colecao = colecao;
		this.empresa = empresa;
		this.fornecedor = fornecedor;
		this.grade = grade;
		this.grupo = grupo;
		this.linhaproducao = linhaproducao;
		this.marca = marca;
		this.modelo = modelo;
		this.tributacao = tributacao;
		this.mdlNom = mdlNom;
		this.mdlApe = mdlApe;
		this.mdlNn1 = mdlNn1;
		this.mdlNn2 = mdlNn2;
		this.mdlSit = mdlSit;
		this.mdlG01 = mdlG01;
		this.mdlG02 = mdlG02;
		this.mdlG03 = mdlG03;
		this.mdlG04 = mdlG04;
		this.mdlG05 = mdlG05;
		this.mdlG06 = mdlG06;
		this.mdlG07 = mdlG07;
		this.mdlG08 = mdlG08;
		this.mdlG09 = mdlG09;
		this.mdlG10 = mdlG10;
		this.mdlG11 = mdlG11;
		this.mdlG12 = mdlG12;
		this.mdlG13 = mdlG13;
		this.mdlG14 = mdlG14;
		this.mdlTer = mdlTer;
		this.mdlIpi = mdlIpi;
		this.mdlClf = mdlClf;
		this.mdlUnd = mdlUnd;
		this.mdlSgr = mdlSgr;
		this.mdlIcm = mdlIcm;
		this.mdlFre = mdlFre;
		this.mdlOut = mdlOut;
		this.mdlCom = mdlCom;
		this.mdlImp = mdlImp;
		this.mdlOud = mdlOud;
		this.mdlMlu = mdlMlu;
		this.mdlDgc = mdlDgc;
		this.mdlIpc = mdlIpc;
		this.mdlPsb = mdlPsb;
		this.mdlPsl = mdlPsl;
		this.mdlCpt = mdlCpt;
		this.mdlObs = mdlObs;
		this.mdlEtc = mdlEtc;
		this.mdlObf = mdlObf;
		this.mdlObm = mdlObm;
		this.mdlEtl = mdlEtl;
		this.mdlCls = mdlCls;
		this.mdlOri = mdlOri;
		this.mdlCmg = mdlCmg;
		this.mdlNcm = mdlNcm;
		this.mdlExt = mdlExt;
		this.mdlEan = mdlEan;
		this.mdlCcp = mdlCcp;
		this.mdlMlt = mdlMlt;
		this.mdlPst = mdlPst;
		this.mdlLgc = mdlLgc;
		this.mdlBse = mdlBse;
		this.mdlDtc = mdlDtc;
		this.mdlMin = mdlMin;
		this.mdlEtf = mdlEtf;
		this.mdlObi = mdlObi;
		this.mdlNpt = mdlNpt;
		this.mdlSts = mdlSts;
		this.mdlOpe = mdlOpe;
		this.mdlFci = mdlFci;
		this.empresaPautaModeloArtigos = empresaPautaModeloArtigos;
		this.modelos = modelos;
		this.modelomaodeobras = modelomaodeobras;
		this.empresapautamodelotamanhos = empresapautamodelotamanhos;
		this.modelofichatecnicas = modelofichatecnicas;
		this.estoqueminimos = estoqueminimos;
		this.medidas = medidas;
		this.modeloartigos = modeloartigos;
		this.operacaopautaprodutos = operacaopautaprodutos;
		this.pedidoproducaoitenses = pedidoproducaoitenses;
		this.produtos = produtos;
	} */

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "mdlEmp", column = @Column(name = "MDL_EMP", nullable = false)),
			@AttributeOverride(name = "mdlCod", column = @Column(name = "MDL_COD", nullable = false)) })
	public ModeloId getId() {
		return this.id;
	}

	public void setId(ModeloId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MDL_CLO")
	public Colecao getColecao() {
		return this.colecao;
	}

	public void setColecao(Colecao colecao) {
		this.colecao = colecao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MDL_EMP", nullable = false, insertable = false, updatable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "MDL_EMP", referencedColumnName = "FOR_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "MDL_FOR", referencedColumnName = "FOR_COL", nullable = false, insertable = false, updatable = false) })
	public Fornecedor getFornecedor() {
		return this.fornecedor;
	}

	public void setFornecedor(Fornecedor fornecedor) {
		this.fornecedor = fornecedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MDL_GRD")
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MDL_GRU")
	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "MDL_EMP", referencedColumnName = "LNP_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "MDL_LNP", referencedColumnName = "LNP_COD", insertable = false, updatable = false) })
	public Linhaproducao getLinhaproducao() {
		return this.linhaproducao;
	}

	public void setLinhaproducao(Linhaproducao linhaproducao) {
		this.linhaproducao = linhaproducao;
	}*/

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MDL_MAR")
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "MDL_EMP", referencedColumnName = "MDL_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "MDL_MDL", referencedColumnName = "MDL_COD", nullable = false, insertable = false, updatable = false) })
	public Modelo getModelo() {
		return this.modelo;
	}

	public void setModelo(Modelo modelo) {
		this.modelo = modelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "MDL_EMP", referencedColumnName = "TRI_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "MDL_TRI", referencedColumnName = "TRI_COD", nullable = false, insertable = false, updatable = false) })
	public Tributacao getTributacao() {
		return this.tributacao;
	}

	public void setTributacao(Tributacao tributacao) {
		this.tributacao = tributacao;
	}

	@Column(name = "MDL_NOM", nullable = false, length = 40)
	public String getMdlNom() {
		return this.mdlNom;
	}

	public void setMdlNom(String mdlNom) {
		this.mdlNom = mdlNom;
	}

	@Column(name = "MDL_APE", length = 15)
	public String getMdlApe() {
		return this.mdlApe;
	}

	public void setMdlApe(String mdlApe) {
		this.mdlApe = mdlApe;
	}

	@Column(name = "MDL_NN1", length = 60)
	public String getMdlNn1() {
		return this.mdlNn1;
	}

	public void setMdlNn1(String mdlNn1) {
		this.mdlNn1 = mdlNn1;
	}

	@Column(name = "MDL_NN2", length = 60)
	public String getMdlNn2() {
		return this.mdlNn2;
	}

	public void setMdlNn2(String mdlNn2) {
		this.mdlNn2 = mdlNn2;
	}

	@Column(name = "MDL_SIT", nullable = false, length = 1)
	public char getMdlSit() {
		return this.mdlSit;
	}

	public void setMdlSit(char mdlSit) {
		this.mdlSit = mdlSit;
	}

	@Column(name = "MDL_G01", nullable = false, length = 1)
	public String getMdlG01() {
		return this.mdlG01;
	}

	public void setMdlG01(String mdlG01) {
		this.mdlG01 = mdlG01;
	}

	@Column(name = "MDL_G02", nullable = false, length = 1)
	public String getMdlG02() {
		return this.mdlG02;
	}

	public void setMdlG02(String mdlG02) {
		this.mdlG02 = mdlG02;
	}

	@Column(name = "MDL_G03", nullable = false, length = 1)
	public String getMdlG03() {
		return this.mdlG03;
	}

	public void setMdlG03(String mdlG03) {
		this.mdlG03 = mdlG03;
	}

	@Column(name = "MDL_G04", nullable = false, length = 1)
	public String getMdlG04() {
		return this.mdlG04;
	}

	public void setMdlG04(String mdlG04) {
		this.mdlG04 = mdlG04;
	}

	@Column(name = "MDL_G05", nullable = false, length = 1)
	public String getMdlG05() {
		return this.mdlG05;
	}

	public void setMdlG05(String mdlG05) {
		this.mdlG05 = mdlG05;
	}

	@Column(name = "MDL_G06", nullable = false, length = 1)
	public String getMdlG06() {
		return this.mdlG06;
	}

	public void setMdlG06(String mdlG06) {
		this.mdlG06 = mdlG06;
	}

	@Column(name = "MDL_G07", nullable = false, length = 1)
	public String getMdlG07() {
		return this.mdlG07;
	}

	public void setMdlG07(String mdlG07) {
		this.mdlG07 = mdlG07;
	}

	@Column(name = "MDL_G08", nullable = false, length = 1)
	public String getMdlG08() {
		return this.mdlG08;
	}

	public void setMdlG08(String mdlG08) {
		this.mdlG08 = mdlG08;
	}

	@Column(name = "MDL_G09", nullable = false, length = 1)
	public String getMdlG09() {
		return this.mdlG09;
	}

	public void setMdlG09(String mdlG09) {
		this.mdlG09 = mdlG09;
	}

	@Column(name = "MDL_G10", nullable = false, length = 1)
	public String getMdlG10() {
		return this.mdlG10;
	}

	public void setMdlG10(String mdlG10) {
		this.mdlG10 = mdlG10;
	}

	@Column(name = "MDL_G11", nullable = false, length = 1)
	public String getMdlG11() {
		return this.mdlG11;
	}

	public void setMdlG11(String mdlG11) {
		this.mdlG11 = mdlG11;
	}

	@Column(name = "MDL_G12", nullable = false, length = 1)
	public String getMdlG12() {
		return this.mdlG12;
	}

	public void setMdlG12(String mdlG12) {
		this.mdlG12 = mdlG12;
	}

	@Column(name = "MDL_G13", nullable = false, length = 1)
	public String getMdlG13() {
		return this.mdlG13;
	}

	public void setMdlG13(String mdlG13) {
		this.mdlG13 = mdlG13;
	}

	@Column(name = "MDL_G14", nullable = false, length = 1)
	public String getMdlG14() {
		return this.mdlG14;
	}

	public void setMdlG14(String mdlG14) {
		this.mdlG14 = mdlG14;
	}

	@Column(name = "MDL_TER", nullable = false, length = 1)
	public char getMdlTer() {
		return this.mdlTer;
	}

	public void setMdlTer(char mdlTer) {
		this.mdlTer = mdlTer;
	}

	@Column(name = "MDL_IPI", nullable = false, precision = 6)
	public BigDecimal getMdlIpi() {
		return this.mdlIpi;
	}

	public void setMdlIpi(BigDecimal mdlIpi) {
		this.mdlIpi = mdlIpi;
	}

	@Column(name = "MDL_CLF", length = 3)
	public String getMdlClf() {
		return this.mdlClf;
	}

	public void setMdlClf(String mdlClf) {
		this.mdlClf = mdlClf;
	}

	@Column(name = "MDL_UND", length = 3)
	public String getMdlUnd() {
		return this.mdlUnd;
	}

	public void setMdlUnd(String mdlUnd) {
		this.mdlUnd = mdlUnd;
	}

	@Column(name = "MDL_SGR")
	public Integer getMdlSgr() {
		return this.mdlSgr;
	}

	public void setMdlSgr(Integer mdlSgr) {
		this.mdlSgr = mdlSgr;
	}

	@Column(name = "MDL_ICM", nullable = false, precision = 6)
	public BigDecimal getMdlIcm() {
		return this.mdlIcm;
	}

	public void setMdlIcm(BigDecimal mdlIcm) {
		this.mdlIcm = mdlIcm;
	}

	@Column(name = "MDL_FRE", nullable = false, precision = 6)
	public BigDecimal getMdlFre() {
		return this.mdlFre;
	}

	public void setMdlFre(BigDecimal mdlFre) {
		this.mdlFre = mdlFre;
	}

	@Column(name = "MDL_OUT", nullable = false, precision = 6)
	public BigDecimal getMdlOut() {
		return this.mdlOut;
	}

	public void setMdlOut(BigDecimal mdlOut) {
		this.mdlOut = mdlOut;
	}

	@Column(name = "MDL_COM", nullable = false, precision = 6)
	public BigDecimal getMdlCom() {
		return this.mdlCom;
	}

	public void setMdlCom(BigDecimal mdlCom) {
		this.mdlCom = mdlCom;
	}

	@Column(name = "MDL_IMP", nullable = false, precision = 6)
	public BigDecimal getMdlImp() {
		return this.mdlImp;
	}

	public void setMdlImp(BigDecimal mdlImp) {
		this.mdlImp = mdlImp;
	}

	@Column(name = "MDL_OUD", nullable = false, precision = 6)
	public BigDecimal getMdlOud() {
		return this.mdlOud;
	}

	public void setMdlOud(BigDecimal mdlOud) {
		this.mdlOud = mdlOud;
	}

	@Column(name = "MDL_MLU", nullable = false, precision = 6)
	public BigDecimal getMdlMlu() {
		return this.mdlMlu;
	}

	public void setMdlMlu(BigDecimal mdlMlu) {
		this.mdlMlu = mdlMlu;
	}

	@Column(name = "MDL_DGC")
	public Integer getMdlDgc() {
		return this.mdlDgc;
	}

	public void setMdlDgc(Integer mdlDgc) {
		this.mdlDgc = mdlDgc;
	}

	@Column(name = "MDL_IPC", nullable = false, precision = 6)
	public BigDecimal getMdlIpc() {
		return this.mdlIpc;
	}

	public void setMdlIpc(BigDecimal mdlIpc) {
		this.mdlIpc = mdlIpc;
	}

	@Column(name = "MDL_PSB", nullable = false, precision = 8, scale = 3)
	public BigDecimal getMdlPsb() {
		return this.mdlPsb;
	}

	public void setMdlPsb(BigDecimal mdlPsb) {
		this.mdlPsb = mdlPsb;
	}

	@Column(name = "MDL_PSL", nullable = false, precision = 8, scale = 3)
	public BigDecimal getMdlPsl() {
		return this.mdlPsl;
	}

	public void setMdlPsl(BigDecimal mdlPsl) {
		this.mdlPsl = mdlPsl;
	}

	@Column(name = "MDL_CPT")
	public Integer getMdlCpt() {
		return this.mdlCpt;
	}

	public void setMdlCpt(Integer mdlCpt) {
		this.mdlCpt = mdlCpt;
	}

	@Column(name = "MDL_OBS", length = 0)
	public String getMdlObs() {
		return this.mdlObs;
	}

	public void setMdlObs(String mdlObs) {
		this.mdlObs = mdlObs;
	}

	@Column(name = "MDL_ETC")
	public Integer getMdlEtc() {
		return this.mdlEtc;
	}

	public void setMdlEtc(Integer mdlEtc) {
		this.mdlEtc = mdlEtc;
	}

	@Column(name = "MDL_OBF", length = 0)
	public String getMdlObf() {
		return this.mdlObf;
	}

	public void setMdlObf(String mdlObf) {
		this.mdlObf = mdlObf;
	}

	@Column(name = "MDL_OBM", length = 0)
	public String getMdlObm() {
		return this.mdlObm;
	}

	public void setMdlObm(String mdlObm) {
		this.mdlObm = mdlObm;
	}

	@Column(name = "MDL_ETL")
	public Integer getMdlEtl() {
		return this.mdlEtl;
	}

	public void setMdlEtl(Integer mdlEtl) {
		this.mdlEtl = mdlEtl;
	}

	@Column(name = "MDL_CLS", nullable = false, length = 1)
	public char getMdlCls() {
		return this.mdlCls;
	}

	public void setMdlCls(char mdlCls) {
		this.mdlCls = mdlCls;
	}

	@Column(name = "MDL_ORI", nullable = false, length = 1)
	public char getMdlOri() {
		return this.mdlOri;
	}

	public void setMdlOri(char mdlOri) {
		this.mdlOri = mdlOri;
	}

	@Column(name = "MDL_CMG", nullable = false, precision = 6)
	public BigDecimal getMdlCmg() {
		return this.mdlCmg;
	}

	public void setMdlCmg(BigDecimal mdlCmg) {
		this.mdlCmg = mdlCmg;
	}

	@Column(name = "MDL_NCM", length = 8)
	public String getMdlNcm() {
		return this.mdlNcm;
	}

	public void setMdlNcm(String mdlNcm) {
		this.mdlNcm = mdlNcm;
	}

	@Column(name = "MDL_EXT", length = 3)
	public String getMdlExt() {
		return this.mdlExt;
	}

	public void setMdlExt(String mdlExt) {
		this.mdlExt = mdlExt;
	}

	@Column(name = "MDL_EAN", length = 14)
	public String getMdlEan() {
		return this.mdlEan;
	}

	public void setMdlEan(String mdlEan) {
		this.mdlEan = mdlEan;
	}

	@Column(name = "MDL_CCP", nullable = false, length = 8)
	public String getMdlCcp() {
		return this.mdlCcp;
	}

	public void setMdlCcp(String mdlCcp) {
		this.mdlCcp = mdlCcp;
	}

	@Column(name = "MDL_MLT")
	public Integer getMdlMlt() {
		return this.mdlMlt;
	}

	public void setMdlMlt(Integer mdlMlt) {
		this.mdlMlt = mdlMlt;
	}

	@Column(name = "MDL_PST", length = 15)
	public String getMdlPst() {
		return this.mdlPst;
	}

	public void setMdlPst(String mdlPst) {
		this.mdlPst = mdlPst;
	}

	@Column(name = "MDL_LGC", length = 15)
	public String getMdlLgc() {
		return this.mdlLgc;
	}

	public void setMdlLgc(String mdlLgc) {
		this.mdlLgc = mdlLgc;
	}

	@Column(name = "MDL_BSE", length = 50)
	public String getMdlBse() {
		return this.mdlBse;
	}

	public void setMdlBse(String mdlBse) {
		this.mdlBse = mdlBse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MDL_DTC", nullable = false, length = 10)
	public Date getMdlDtc() {
		return this.mdlDtc;
	}

	public void setMdlDtc(Date mdlDtc) {
		this.mdlDtc = mdlDtc;
	}

	@Column(name = "MDL_MIN", nullable = false, precision = 18, scale = 5)
	public BigDecimal getMdlMin() {
		return this.mdlMin;
	}

	public void setMdlMin(BigDecimal mdlMin) {
		this.mdlMin = mdlMin;
	}

	@Column(name = "MDL_ETF")
	public Integer getMdlEtf() {
		return this.mdlEtf;
	}

	public void setMdlEtf(Integer mdlEtf) {
		this.mdlEtf = mdlEtf;
	}

	@Column(name = "MDL_OBI", length = 0)
	public String getMdlObi() {
		return this.mdlObi;
	}

	public void setMdlObi(String mdlObi) {
		this.mdlObi = mdlObi;
	}

	@Column(name = "MDL_NPT", length = 20)
	public String getMdlNpt() {
		return this.mdlNpt;
	}

	public void setMdlNpt(String mdlNpt) {
		this.mdlNpt = mdlNpt;
	}

	@Column(name = "MDL_STS", nullable = false, length = 1)
	public char getMdlSts() {
		return this.mdlSts;
	}

	public void setMdlSts(char mdlSts) {
		this.mdlSts = mdlSts;
	}

	@Column(name = "MDL_OPE", length = 60)
	public String getMdlOpe() {
		return this.mdlOpe;
	}

	public void setMdlOpe(String mdlOpe) {
		this.mdlOpe = mdlOpe;
	}

	@Column(name = "MDL_FCI", length = 36)
	public String getMdlFci() {
		return this.mdlFci;
	}

	public void setMdlFci(String mdlFci) {
		this.mdlFci = mdlFci;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<EmpresaPautaModeloArtigo> getEmpresaPautaModeloArtigos() {
		return this.empresaPautaModeloArtigos;
	}

	public void setEmpresaPautaModeloArtigos(Set<EmpresaPautaModeloArtigo> empresaPautaModeloArtigos) {
		this.empresaPautaModeloArtigos = empresaPautaModeloArtigos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Modelo> getModelos() {
		return this.modelos;
	}

	public void setModelos(Set<Modelo> modelos) {
		this.modelos = modelos;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Modelomaodeobra> getModelomaodeobras() {
		return this.modelomaodeobras;
	}

	public void setModelomaodeobras(Set<Modelomaodeobra> modelomaodeobras) {
		this.modelomaodeobras = modelomaodeobras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Empresapautamodelotamanho> getEmpresapautamodelotamanhos() {
		return this.empresapautamodelotamanhos;
	}

	public void setEmpresapautamodelotamanhos(
			Set<Empresapautamodelotamanho> empresapautamodelotamanhos) {
		this.empresapautamodelotamanhos = empresapautamodelotamanhos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Modelofichatecnica> getModelofichatecnicas() {
		return this.modelofichatecnicas;
	}

	public void setModelofichatecnicas(
			Set<Modelofichatecnica> modelofichatecnicas) {
		this.modelofichatecnicas = modelofichatecnicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Estoqueminimo> getEstoqueminimos() {
		return this.estoqueminimos;
	}

	public void setEstoqueminimos(Set<Estoqueminimo> estoqueminimos) {
		this.estoqueminimos = estoqueminimos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Medida> getMedidas() {
		return this.medidas;
	}

	public void setMedidas(Set<Medida> medidas) {
		this.medidas = medidas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Modeloartigo> getModeloartigos() {
		return this.modeloartigos;
	}

	public void setModeloartigos(Set<Modeloartigo> modeloartigos) {
		this.modeloartigos = modeloartigos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Operacaopautaproduto> getOperacaopautaprodutos() {
		return this.operacaopautaprodutos;
	}

	public void setOperacaopautaprodutos(
			Set<Operacaopautaproduto> operacaopautaprodutos) {
		this.operacaopautaprodutos = operacaopautaprodutos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Pedidoproducaoitens> getPedidoproducaoitenses() {
		return this.pedidoproducaoitenses;
	}

	public void setPedidoproducaoitenses(
			Set<Pedidoproducaoitens> pedidoproducaoitenses) {
		this.pedidoproducaoitenses = pedidoproducaoitenses;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

}
