
package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Movimento generated by hbm2java
 */
@Entity
@Table(name = "MOVIMENTO", uniqueConstraints = @UniqueConstraint(columnNames = {
		"MOV_EMP", "MOV_FIL", "MOV_MOT", "MOV_SEQ" }))
public class Movimento implements java.io.Serializable {

	
	
	private static final long serialVersionUID = 2123602078198207600L;
	
	private int movCod;
//	private ColaboradorEmpresa colaboradorEmpresaByFkMovCof;
	private ColaboradorEmpresa colaboradorEmpresaByFkMovCoe;
//	private Empresapauta empresapauta;	
	private Filial filial;
	private LocalDeposito localDepositoByFkMovLcd;
	private LocalDeposito localDepositoByFkMovLdd;
//	private Movimentocaixa movimentocaixa;
	private MovimentoTipo movimentoTipo;
//	private Notafiscal notafiscal;
//	private Operacaocomercial operacaocomercial;
//	private Planodecontas planodecontas;
	private int movSeq;
	private int movOri;
	private Integer movInt;
	private String movSit;
	private Integer movTco;
	private Integer movRep;
	private Integer movPrr;
	private Date movDte;
	private Date movDtf;
	private String movDoc;
	private BigDecimal movTop;
	private float movTot;
	private int movNrp;
	private char movCen;
	private Integer movCdp;
	private Integer movFpa;
	private String movCfo;
	private Integer movBco;
	private BigDecimal movPac;
	private BigDecimal movAcr;
	private BigDecimal movPou;
	private BigDecimal movOut;
	private BigDecimal movPde;
	private BigDecimal movDes;
	private char movSfr;
	private BigDecimal movPfr;
	private BigDecimal movVfr;
	private BigDecimal movPcf;
	private BigDecimal movVcf;
	private BigDecimal movPfn;
	private BigDecimal movVfn;
	private BigDecimal movPfs;
	private BigDecimal movVfs;
	private BigDecimal movPfc;
	private BigDecimal movVfc;
	private char movSff;
	private Date movDvf;
	private Integer movFpf;
	private BigDecimal movPft;
	private BigDecimal movVft;
	private BigDecimal movBcr;
	private BigDecimal movPcr;
	private Integer movTra;
	private String movClp;
	private String movMtr;
	private String movOb1;
	private String movOb2;
	private String movOb3;
	private String movOb4;
	private String movOb5;
	private int movUsu;
	private BigDecimal movPse;
	private BigDecimal movSer;
	private char movFnp;
	private Character movCgf;
	private Integer movFpc;
	private BigDecimal movToa;
	private BigDecimal movPoa;
	private BigDecimal movTod;
	private char movNfi;
	private char movCba;
	private Integer movCop;
	private String movCsm;
	private int movFpr;
	private BigDecimal movPda;
	private BigDecimal movDad;
	private BigDecimal movPds;
	private BigDecimal movDsp;
	private char movDpr;
	private Integer movGui;
	private Short movAdc;
	private Short movTct;
	private Character movSts;
	private Date movOfd;
	private Integer movOfp;
	private Integer movOfm;
	private String movVav;
	private char movReb;
	private char movCct;
	private Integer movCvc;
	private Date movDtp;
	private char movDag;
	private char movSma;
	private Date movDbg;
	private BigDecimal movPcg;
	private Integer movCpa;
	private String movDcf;
	private Date movRte;
	private Integer movPag;
	private char movRebf;
	private String movDca;
	private Integer movCar;
	private Integer movEcf;
	private char movCavd;
	private Integer movClo;
//	private Set<Empacotamento> empacotamentos = new HashSet<Empacotamento>(0);
//	private Movimentonfe movimentonfe;
	private Set<MovimentoItens> movimentoItens = new HashSet<MovimentoItens>(0);
//	private Set<Movimentoproducaoitens> movimentoproducaoitenses = new HashSet<Movimentoproducaoitens>(0);
//	private Set<Movimentoepc> movimentoepcs = new HashSet<Movimentoepc>(0);
//	private Set<Movimentocartao> movimentocartaos = new HashSet<Movimentocartao>(0);
//	private Set<Movimentoparcelas> movimentoparcelases = new HashSet<Movimentoparcelas>(0);
//	private Set<Notafiscal> notafiscals = new HashSet<Notafiscal>(0);	

	@Id
	@Column(name = "MOV_COD", unique = true, nullable = false)
	public int getMovCod() {
		return this.movCod;
	}

	public void setMovCod(int movCod) {
		this.movCod = movCod;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "MOV_EMP", referencedColumnName = "COE_EMP", nullable = false),
//			@JoinColumn(name = "MOV_COF", referencedColumnName = "COE_COL") })
//	public ColaboradorEmpresa getColaboradorEmpresaByFkMovCof() {
//		return this.colaboradorEmpresaByFkMovCof;
//	}
//
//	public void setColaboradorEmpresaByFkMovCof(
//			ColaboradorEmpresa colaboradorEmpresaByFkMovCof) {
//		this.colaboradorEmpresaByFkMovCof = colaboradorEmpresaByFkMovCof;
//	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "MOV_EMP", referencedColumnName = "COE_EMP", insertable = false, updatable = false),
			@JoinColumn(name = "MOV_COL", referencedColumnName = "COE_COL", insertable = false, updatable = false) })
	public ColaboradorEmpresa getColaboradorEmpresaByFkMovCoe() {
		return this.colaboradorEmpresaByFkMovCoe;
	}

	public void setColaboradorEmpresaByFkMovCoe(
			ColaboradorEmpresa colaboradorEmpresaByFkMovCoe) {
		this.colaboradorEmpresaByFkMovCoe = colaboradorEmpresaByFkMovCoe;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "MOV_EMP", referencedColumnName = "EPT_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "MOV_EPT", referencedColumnName = "EPT_PAT", insertable = false, updatable = false) })
//	public Empresapauta getEmpresapauta() {
//		return this.empresapauta;
//	}
//
//	public void setEmpresapauta(Empresapauta empresapauta) {
//		this.empresapauta = empresapauta;
//	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "MOV_EMP", referencedColumnName = "FIL_EMP", insertable = false, updatable = false),
//			@JoinColumn(name = "MOV_FID", referencedColumnName = "FIL_COD", insertable = false, updatable = false) })
//	public Filial getFilial() {
//		return this.filial;
//	}
//
//	public void setFilial(Filial filial) {
//		this.filial = filial;
//	}
	
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "MOV_EMP", referencedColumnName = "FIL_EMP", insertable = false, updatable = false),
			@JoinColumn(name = "MOV_FIL", referencedColumnName = "FIL_COD", insertable = false, updatable = false) })
	public Filial getFilial() {
		return this.filial;
	}

	public void setFilial(Filial filial) {
		this.filial = filial;
	}
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "MOV_EMP", referencedColumnName = "LCD_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "MOV_FIL", referencedColumnName = "LCD_FIL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "MOV_LCD", referencedColumnName = "LCD_COD", nullable = false, insertable = false, updatable = false) })
	public LocalDeposito getLocalDepositoByFkMovLcd() {
		return this.localDepositoByFkMovLcd;
	}

	public void setLocalDepositoByFkMovLcd(LocalDeposito localDepositoByFkMovLcd) {
		this.localDepositoByFkMovLcd = localDepositoByFkMovLcd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "MOV_EMP", referencedColumnName = "LCD_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "MOV_FID", referencedColumnName = "LCD_FIL", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "MOV_LDD", referencedColumnName = "LCD_COD", nullable = false, insertable = false, updatable = false) })
	public LocalDeposito getLocalDepositoByFkMovLdd() {
		return this.localDepositoByFkMovLdd;
	}

	public void setLocalDepositoByFkMovLdd(LocalDeposito localDepositoByFkMovLdd) {
		this.localDepositoByFkMovLdd = localDepositoByFkMovLdd;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "MOV_EMP", referencedColumnName = "MCX_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "MOV_FIL", referencedColumnName = "MCX_FIL", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "MOV_DTF", referencedColumnName = "MCX_DTA", insertable = false, updatable = false),
//			@JoinColumn(name = "MOV_PER", referencedColumnName = "MCX_PER", insertable = false, updatable = false),
//			@JoinColumn(name = "MOV_MCX", referencedColumnName = "MCX_COD", insertable = false, updatable = false) })
//	public Movimentocaixa getMovimentocaixa() {
//		return this.movimentocaixa;
//	}
//
//	public void setMovimentocaixa(Movimentocaixa movimentocaixa) {
//		this.movimentocaixa = movimentocaixa;
//	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOV_MOT", nullable = false)
	public MovimentoTipo getMovimentoTipo() {
		return this.movimentoTipo;
	}

	public void setMovimentoTipo(MovimentoTipo movimentoTipo) {
		this.movimentoTipo = movimentoTipo;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "MOV_NFS")
//	public Notafiscal getNotafiscal() {
//		return this.notafiscal;
//	}
//
//	public void setNotafiscal(Notafiscal notafiscal) {
//		this.notafiscal = notafiscal;
//	}
//
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "MOV_EMP", referencedColumnName = "OPC_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "MOV_FIL", referencedColumnName = "OPC_FIL", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "MOV_OPC", referencedColumnName = "OPC_COD", nullable = false, insertable = false, updatable = false) })
//	public Operacaocomercial getOperacaocomercial() {
//		return this.operacaocomercial;
//	}
//
//	public void setOperacaocomercial(Operacaocomercial operacaocomercial) {
//		this.operacaocomercial = operacaocomercial;
//	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumns({
//			@JoinColumn(name = "MOV_EMP", referencedColumnName = "PLA_EMP", nullable = false, insertable = false, updatable = false),
//			@JoinColumn(name = "MOV_FPP", referencedColumnName = "PLA_COD", insertable = false, updatable = false) })
//	public Planodecontas getPlanodecontas() {
//		return this.planodecontas;
//	}
//
//	public void setPlanodecontas(Planodecontas planodecontas) {
//		this.planodecontas = planodecontas;
//	}

	@Column(name = "MOV_SEQ", nullable = false)
	public int getMovSeq() {
		return this.movSeq;
	}

	public void setMovSeq(int movSeq) {
		this.movSeq = movSeq;
	}

	@Column(name = "MOV_ORI", nullable = false)
	public int getMovOri() {
		return this.movOri;
	}

	public void setMovOri(int movOri) {
		this.movOri = movOri;
	}

	@Column(name = "MOV_INT")
	public Integer getMovInt() {
		return this.movInt;
	}

	public void setMovInt(Integer movInt) {
		this.movInt = movInt;
	}

	@Column(name = "MOV_SIT", nullable = false, length = 1)
	public String getMovSit() {
		return this.movSit;
	}

	public void setMovSit(String movSit) {
		this.movSit = movSit;
	}

	@Column(name = "MOV_TCO")
	public Integer getMovTco() {
		return this.movTco;
	}

	public void setMovTco(Integer movTco) {
		this.movTco = movTco;
	}

	@Column(name = "MOV_REP")
	public Integer getMovRep() {
		return this.movRep;
	}

	public void setMovRep(Integer movRep) {
		this.movRep = movRep;
	}

	@Column(name = "MOV_PRR")
	public Integer getMovPrr() {
		return this.movPrr;
	}

	public void setMovPrr(Integer movPrr) {
		this.movPrr = movPrr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MOV_DTE", nullable = false, length = 10)
	public Date getMovDte() {
		return this.movDte;
	}

	public void setMovDte(Date movDte) {
		this.movDte = movDte;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "MOV_DTF", nullable = false, length = 10)
	public Date getMovDtf() {
		return this.movDtf;
	}

	public void setMovDtf(Date movDte) {
		this.movDte = movDte;
	}

	@Column(name = "MOV_DOC", length = 10)
	public String getMovDoc() {
		return this.movDoc;
	}

	public void setMovDoc(String movDoc) {
		this.movDoc = movDoc;
	}

	@Column(name = "MOV_TOP", nullable = false, precision = 14)
	public BigDecimal getMovTop() {
		return this.movTop;
	}

	public void setMovTop(BigDecimal movTop) {
		this.movTop = movTop;
	}

	@Column(name = "MOV_TOT", nullable = false, precision = 14)
	public float getMovTot() {
		return this.movTot;
	}

	public void setMovTot(float movTot) {
		this.movTot = movTot;
	}

	@Column(name = "MOV_NRP", nullable = false)
	public int getMovNrp() {
		return this.movNrp;
	}

	public void setMovNrp(int movNrp) {
		this.movNrp = movNrp;
	}

	@Column(name = "MOV_CEN", nullable = false, length = 1)
	public char getMovCen() {
		return this.movCen;
	}

	public void setMovCen(char movCen) {
		this.movCen = movCen;
	}

	@Column(name = "MOV_CDP")
	public Integer getMovCdp() {
		return this.movCdp;
	}

	public void setMovCdp(Integer movCdp) {
		this.movCdp = movCdp;
	}

	@Column(name = "MOV_FPA")
	public Integer getMovFpa() {
		return this.movFpa;
	}

	public void setMovFpa(Integer movFpa) {
		this.movFpa = movFpa;
	}

	@Column(name = "MOV_CFO", length = 4)
	public String getMovCfo() {
		return this.movCfo;
	}

	public void setMovCfo(String movCfo) {
		this.movCfo = movCfo;
	}

	@Column(name = "MOV_BCO")
	public Integer getMovBco() {
		return this.movBco;
	}

	public void setMovBco(Integer movBco) {
		this.movBco = movBco;
	}

	@Column(name = "MOV_PAC", nullable = false, precision = 8, scale = 4)
	public BigDecimal getMovPac() {
		return this.movPac;
	}

	public void setMovPac(BigDecimal movPac) {
		this.movPac = movPac;
	}

	@Column(name = "MOV_ACR", nullable = false, precision = 14)
	public BigDecimal getMovAcr() {
		return this.movAcr;
	}

	public void setMovAcr(BigDecimal movAcr) {
		this.movAcr = movAcr;
	}

	@Column(name = "MOV_POU", nullable = false, precision = 8, scale = 4)
	public BigDecimal getMovPou() {
		return this.movPou;
	}

	public void setMovPou(BigDecimal movPou) {
		this.movPou = movPou;
	}

	@Column(name = "MOV_OUT", nullable = false, precision = 14)
	public BigDecimal getMovOut() {
		return this.movOut;
	}

	public void setMovOut(BigDecimal movOut) {
		this.movOut = movOut;
	}

	@Column(name = "MOV_PDE", nullable = false, precision = 8, scale = 4)
	public BigDecimal getMovPde() {
		return this.movPde;
	}

	public void setMovPde(BigDecimal movPde) {
		this.movPde = movPde;
	}

	@Column(name = "MOV_DES", nullable = false, precision = 14)
	public BigDecimal getMovDes() {
		return this.movDes;
	}

	public void setMovDes(BigDecimal movDes) {
		this.movDes = movDes;
	}

	@Column(name = "MOV_SFR", nullable = false, length = 1)
	public char getMovSfr() {
		return this.movSfr;
	}

	public void setMovSfr(char movSfr) {
		this.movSfr = movSfr;
	}

	@Column(name = "MOV_PFR", nullable = false, precision = 6)
	public BigDecimal getMovPfr() {
		return this.movPfr;
	}

	public void setMovPfr(BigDecimal movPfr) {
		this.movPfr = movPfr;
	}

	@Column(name = "MOV_VFR", nullable = false, precision = 14)
	public BigDecimal getMovVfr() {
		return this.movVfr;
	}

	public void setMovVfr(BigDecimal movVfr) {
		this.movVfr = movVfr;
	}

	@Column(name = "MOV_PCF", nullable = false, precision = 6)
	public BigDecimal getMovPcf() {
		return this.movPcf;
	}

	public void setMovPcf(BigDecimal movPcf) {
		this.movPcf = movPcf;
	}

	@Column(name = "MOV_VCF", nullable = false, precision = 14)
	public BigDecimal getMovVcf() {
		return this.movVcf;
	}

	public void setMovVcf(BigDecimal movVcf) {
		this.movVcf = movVcf;
	}

	@Column(name = "MOV_PFN", nullable = false, precision = 6)
	public BigDecimal getMovPfn() {
		return this.movPfn;
	}

	public void setMovPfn(BigDecimal movPfn) {
		this.movPfn = movPfn;
	}

	@Column(name = "MOV_VFN", nullable = false, precision = 14)
	public BigDecimal getMovVfn() {
		return this.movVfn;
	}

	public void setMovVfn(BigDecimal movVfn) {
		this.movVfn = movVfn;
	}

	@Column(name = "MOV_PFS", nullable = false, precision = 6)
	public BigDecimal getMovPfs() {
		return this.movPfs;
	}

	public void setMovPfs(BigDecimal movPfs) {
		this.movPfs = movPfs;
	}

	@Column(name = "MOV_VFS", nullable = false, precision = 14)
	public BigDecimal getMovVfs() {
		return this.movVfs;
	}

	public void setMovVfs(BigDecimal movVfs) {
		this.movVfs = movVfs;
	}

	@Column(name = "MOV_PFC", nullable = false, precision = 6)
	public BigDecimal getMovPfc() {
		return this.movPfc;
	}

	public void setMovPfc(BigDecimal movPfc) {
		this.movPfc = movPfc;
	}

	@Column(name = "MOV_VFC", nullable = false, precision = 14)
	public BigDecimal getMovVfc() {
		return this.movVfc;
	}

	public void setMovVfc(BigDecimal movVfc) {
		this.movVfc = movVfc;
	}

	@Column(name = "MOV_SFF", nullable = false, length = 1)
	public char getMovSff() {
		return this.movSff;
	}

	public void setMovSff(char movSff) {
		this.movSff = movSff;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MOV_DVF", length = 10)
	public Date getMovDvf() {
		return this.movDvf;
	}

	public void setMovDvf(Date movDvf) {
		this.movDvf = movDvf;
	}

	@Column(name = "MOV_FPF")
	public Integer getMovFpf() {
		return this.movFpf;
	}

	public void setMovFpf(Integer movFpf) {
		this.movFpf = movFpf;
	}

	@Column(name = "MOV_PFT", nullable = false, precision = 6)
	public BigDecimal getMovPft() {
		return this.movPft;
	}

	public void setMovPft(BigDecimal movPft) {
		this.movPft = movPft;
	}

	@Column(name = "MOV_VFT", nullable = false, precision = 14)
	public BigDecimal getMovVft() {
		return this.movVft;
	}

	public void setMovVft(BigDecimal movVft) {
		this.movVft = movVft;
	}

	@Column(name = "MOV_BCR", nullable = false, precision = 14)
	public BigDecimal getMovBcr() {
		return this.movBcr;
	}

	public void setMovBcr(BigDecimal movBcr) {
		this.movBcr = movBcr;
	}

	@Column(name = "MOV_PCR", nullable = false, precision = 6)
	public BigDecimal getMovPcr() {
		return this.movPcr;
	}

	public void setMovPcr(BigDecimal movPcr) {
		this.movPcr = movPcr;
	}

	@Column(name = "MOV_TRA")
	public Integer getMovTra() {
		return this.movTra;
	}

	public void setMovTra(Integer movTra) {
		this.movTra = movTra;
	}

	@Column(name = "MOV_CLP", length = 10)
	public String getMovClp() {
		return this.movClp;
	}

	public void setMovClp(String movClp) {
		this.movClp = movClp;
	}

	@Column(name = "MOV_MTR", length = 50)
	public String getMovMtr() {
		return this.movMtr;
	}

	public void setMovMtr(String movMtr) {
		this.movMtr = movMtr;
	}

	@Column(name = "MOV_OB1", length = 40)
	public String getMovOb1() {
		return this.movOb1;
	}

	public void setMovOb1(String movOb1) {
		this.movOb1 = movOb1;
	}

	@Column(name = "MOV_OB2", length = 40)
	public String getMovOb2() {
		return this.movOb2;
	}

	public void setMovOb2(String movOb2) {
		this.movOb2 = movOb2;
	}

	@Column(name = "MOV_OB3", length = 40)
	public String getMovOb3() {
		return this.movOb3;
	}

	public void setMovOb3(String movOb3) {
		this.movOb3 = movOb3;
	}

	@Column(name = "MOV_OB4", length = 40)
	public String getMovOb4() {
		return this.movOb4;
	}

	public void setMovOb4(String movOb4) {
		this.movOb4 = movOb4;
	}

	@Column(name = "MOV_OB5", length = 40)
	public String getMovOb5() {
		return this.movOb5;
	}

	public void setMovOb5(String movOb5) {
		this.movOb5 = movOb5;
	}

	@Column(name = "MOV_USU", nullable = false)
	public int getMovUsu() {
		return this.movUsu;
	}

	public void setMovUsu(int movUsu) {
		this.movUsu = movUsu;
	}

	@Column(name = "MOV_PSE", nullable = false, precision = 8, scale = 4)
	public BigDecimal getMovPse() {
		return this.movPse;
	}

	public void setMovPse(BigDecimal movPse) {
		this.movPse = movPse;
	}

	@Column(name = "MOV_SER", nullable = false, precision = 14)
	public BigDecimal getMovSer() {
		return this.movSer;
	}

	public void setMovSer(BigDecimal movSer) {
		this.movSer = movSer;
	}

	@Column(name = "MOV_FNP", nullable = false, length = 1)
	public char getMovFnp() {
		return this.movFnp;
	}

	public void setMovFnp(char movFnp) {
		this.movFnp = movFnp;
	}

	@Column(name = "MOV_CGF", length = 1)
	public Character getMovCgf() {
		return this.movCgf;
	}

	public void setMovCgf(Character movCgf) {
		this.movCgf = movCgf;
	}

	@Column(name = "MOV_FPC")
	public Integer getMovFpc() {
		return this.movFpc;
	}

	public void setMovFpc(Integer movFpc) {
		this.movFpc = movFpc;
	}

	@Column(name = "MOV_TOA", nullable = false, precision = 14)
	public BigDecimal getMovToa() {
		return this.movToa;
	}

	public void setMovToa(BigDecimal movToa) {
		this.movToa = movToa;
	}

	@Column(name = "MOV_POA", nullable = false, precision = 6)
	public BigDecimal getMovPoa() {
		return this.movPoa;
	}

	public void setMovPoa(BigDecimal movPoa) {
		this.movPoa = movPoa;
	}

	@Column(name = "MOV_TOD", nullable = false, precision = 14)
	public BigDecimal getMovTod() {
		return this.movTod;
	}

	public void setMovTod(BigDecimal movTod) {
		this.movTod = movTod;
	}

	@Column(name = "MOV_NFI", nullable = false, length = 1)
	public char getMovNfi() {
		return this.movNfi;
	}

	public void setMovNfi(char movNfi) {
		this.movNfi = movNfi;
	}

	@Column(name = "MOV_CBA", nullable = false, length = 1)
	public char getMovCba() {
		return this.movCba;
	}

	public void setMovCba(char movCba) {
		this.movCba = movCba;
	}

	@Column(name = "MOV_COP")
	public Integer getMovCop() {
		return this.movCop;
	}

	public void setMovCop(Integer movCop) {
		this.movCop = movCop;
	}

	@Column(name = "MOV_CSM", length = 50)
	public String getMovCsm() {
		return this.movCsm;
	}

	public void setMovCsm(String movCsm) {
		this.movCsm = movCsm;
	}

	@Column(name = "MOV_FPR", nullable = false)
	public int getMovFpr() {
		return this.movFpr;
	}

	public void setMovFpr(int movFpr) {
		this.movFpr = movFpr;
	}

	@Column(name = "MOV_PDA", nullable = false, precision = 8, scale = 4)
	public BigDecimal getMovPda() {
		return this.movPda;
	}

	public void setMovPda(BigDecimal movPda) {
		this.movPda = movPda;
	}

	@Column(name = "MOV_DAD", nullable = false, precision = 14)
	public BigDecimal getMovDad() {
		return this.movDad;
	}

	public void setMovDad(BigDecimal movDad) {
		this.movDad = movDad;
	}

	@Column(name = "MOV_PDS", nullable = false, precision = 8, scale = 4)
	public BigDecimal getMovPds() {
		return this.movPds;
	}

	public void setMovPds(BigDecimal movPds) {
		this.movPds = movPds;
	}

	@Column(name = "MOV_DSP", nullable = false, precision = 14)
	public BigDecimal getMovDsp() {
		return this.movDsp;
	}

	public void setMovDsp(BigDecimal movDsp) {
		this.movDsp = movDsp;
	}

	@Column(name = "MOV_DPR", nullable = false, length = 1)
	public char getMovDpr() {
		return this.movDpr;
	}

	public void setMovDpr(char movDpr) {
		this.movDpr = movDpr;
	}

	@Column(name = "MOV_GUI")
	public Integer getMovGui() {
		return this.movGui;
	}

	public void setMovGui(Integer movGui) {
		this.movGui = movGui;
	}

	@Column(name = "MOV_ADC")
	public Short getMovAdc() {
		return this.movAdc;
	}

	public void setMovAdc(Short movAdc) {
		this.movAdc = movAdc;
	}

	@Column(name = "MOV_TCT")
	public Short getMovTct() {
		return this.movTct;
	}

	public void setMovTct(Short movTct) {
		this.movTct = movTct;
	}

	@Column(name = "MOV_STS", length = 1)
	public Character getMovSts() {
		return this.movSts;
	}

	public void setMovSts(Character movSts) {
		this.movSts = movSts;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MOV_OFD", length = 10)
	public Date getMovOfd() {
		return this.movOfd;
	}

	public void setMovOfd(Date movOfd) {
		this.movOfd = movOfd;
	}

	@Column(name = "MOV_OFP")
	public Integer getMovOfp() {
		return this.movOfp;
	}

	public void setMovOfp(Integer movOfp) {
		this.movOfp = movOfp;
	}

	@Column(name = "MOV_OFM")
	public Integer getMovOfm() {
		return this.movOfm;
	}

	public void setMovOfm(Integer movOfm) {
		this.movOfm = movOfm;
	}

	@Column(name = "MOV_VAV", length = 1)
	public String getMovVav() {
		return this.movVav;
	}

	public void setMovVav(String movVav) {
		this.movVav = movVav;
	}

	@Column(name = "MOV_REB", nullable = false, length = 1)
	public char getMovReb() {
		return this.movReb;
	}

	public void setMovReb(char movReb) {
		this.movReb = movReb;
	}

	@Column(name = "MOV_CCT", nullable = false, length = 1)
	public char getMovCct() {
		return this.movCct;
	}

	public void setMovCct(char movCct) {
		this.movCct = movCct;
	}

	@Column(name = "MOV_CVC")
	public Integer getMovCvc() {
		return this.movCvc;
	}

	public void setMovCvc(Integer movCvc) {
		this.movCvc = movCvc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MOV_DTP", length = 10)
	public Date getMovDtp() {
		return this.movDtp;
	}

	public void setMovDtp(Date movDtp) {
		this.movDtp = movDtp;
	}

	@Column(name = "MOV_DAG", nullable = false, length = 1)
	public char getMovDag() {
		return this.movDag;
	}

	public void setMovDag(char movDag) {
		this.movDag = movDag;
	}

	@Column(name = "MOV_SMA", nullable = false, length = 1)
	public char getMovSma() {
		return this.movSma;
	}

	public void setMovSma(char movSma) {
		this.movSma = movSma;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MOV_DBG", length = 10)
	public Date getMovDbg() {
		return this.movDbg;
	}

	public void setMovDbg(Date movDbg) {
		this.movDbg = movDbg;
	}

	@Column(name = "MOV_PCG", nullable = false, precision = 6)
	public BigDecimal getMovPcg() {
		return this.movPcg;
	}

	public void setMovPcg(BigDecimal movPcg) {
		this.movPcg = movPcg;
	}

	@Column(name = "MOV_CPA")
	public Integer getMovCpa() {
		return this.movCpa;
	}

	public void setMovCpa(Integer movCpa) {
		this.movCpa = movCpa;
	}

	@Column(name = "MOV_DCF", length = 10)
	public String getMovDcf() {
		return this.movDcf;
	}

	public void setMovDcf(String movDcf) {
		this.movDcf = movDcf;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MOV_RTE", length = 19)
	public Date getMovRte() {
		return this.movRte;
	}

	public void setMovRte(Date movRte) {
		this.movRte = movRte;
	}

	@Column(name = "MOV_PAG")
	public Integer getMovPag() {
		return this.movPag;
	}

	public void setMovPag(Integer movPag) {
		this.movPag = movPag;
	}

	@Column(name = "MOV_REBF", nullable = false, length = 1)
	public char getMovRebf() {
		return this.movRebf;
	}

	public void setMovRebf(char movRebf) {
		this.movRebf = movRebf;
	}

	@Column(name = "MOV_DCA", length = 10)
	public String getMovDca() {
		return this.movDca;
	}

	public void setMovDca(String movDca) {
		this.movDca = movDca;
	}

	@Column(name = "MOV_CAR")
	public Integer getMovCar() {
		return this.movCar;
	}

	public void setMovCar(Integer movCar) {
		this.movCar = movCar;
	}

	@Column(name = "MOV_ECF")
	public Integer getMovEcf() {
		return this.movEcf;
	}

	public void setMovEcf(Integer movEcf) {
		this.movEcf = movEcf;
	}

	@Column(name = "MOV_CAVD", nullable = false, length = 1)
	public char getMovCavd() {
		return this.movCavd;
	}

	public void setMovCavd(char movCavd) {
		this.movCavd = movCavd;
	}

	@Column(name = "MOV_CLO")
	public Integer getMovClo() {
		return this.movClo;
	}

	public void setMovClo(Integer movClo) {
		this.movClo = movClo;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimento")
//	public Set<Empacotamento> getEmpacotamentos() {
//		return this.empacotamentos;
//	}
//
//	public void setEmpacotamentos(Set<Empacotamento> empacotamentos) {
//		this.empacotamentos = empacotamentos;
//	}
//
//	@OneToOne(fetch = FetchType.LAZY, mappedBy = "movimento")
//	public Movimentonfe getMovimentonfe() {
//		return this.movimentonfe;
//	}
//
//	public void setMovimentonfe(Movimentonfe movimentonfe) {
//		this.movimentonfe = movimentonfe;
//	}
//
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimento")
	public Set<MovimentoItens> getMovimentoItens() {
		return this.movimentoItens;
	}

	public void setMovimentoItens(Set<MovimentoItens> movimentoItens) {
		this.movimentoItens = movimentoItens;
	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimento")
//	public Set<Movimentoproducaoitens> getMovimentoproducaoitenses() {
//		return this.movimentoproducaoitenses;
//	}
//
//	public void setMovimentoproducaoitenses(
//			Set<Movimentoproducaoitens> movimentoproducaoitenses) {
//		this.movimentoproducaoitenses = movimentoproducaoitenses;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimento")
//	public Set<Movimentoepc> getMovimentoepcs() {
//		return this.movimentoepcs;
//	}
//
//	public void setMovimentoepcs(Set<Movimentoepc> movimentoepcs) {
//		this.movimentoepcs = movimentoepcs;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimento")
//	public Set<Movimentocartao> getMovimentocartaos() {
//		return this.movimentocartaos;
//	}
//
//	public void setMovimentocartaos(Set<Movimentocartao> movimentocartaos) {
//		this.movimentocartaos = movimentocartaos;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimento")
//	public Set<Movimentoparcelas> getMovimentoparcelases() {
//		return this.movimentoparcelases;
//	}
//
//	public void setMovimentoparcelases(
//			Set<Movimentoparcelas> movimentoparcelases) {
//		this.movimentoparcelases = movimentoparcelases;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimento")
//	public Set<Notafiscal> getNotafiscals() {
//		return this.notafiscals;
//	}
//
//	public void setNotafiscals(Set<Notafiscal> notafiscals) {
//		this.notafiscals = notafiscals;
//	}

}
