package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.JoinColumns;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovimentoItens generated by hbm2java
 */
@Entity
@Table(name = "MOVIMENTOITENS")
public class MovimentoItens implements java.io.Serializable {

	
	private static final long serialVersionUID = 4465255214593016116L;
	private Integer moiCod;
	private Movimento movimento;
	private PedidoItens pedidoItens;
	private ProdutoLocal produtoLocal;
	private Date moiDte;
	private Integer moiGrd;
	private Integer moiQ01;
	private Integer moiQ02;
	private Integer moiQ03;
	private Integer moiQ04;
	private Integer moiQ05;
	private Integer moiQ06;
	private Integer moiQ07;
	private Integer moiQ08;
	private Integer moiQ09;
	private Integer moiQ10;
	private Integer moiQ11;
	private Integer moiQ12;
	private Integer moiQ13;
	private Integer moiQ14;
	private BigDecimal moiQtd;
	private BigDecimal moiPru;
	private BigDecimal moiPrc;
	private String moiOb1;
	private String moiOb2;
	private String moiOb3;
	private char moiTip;
	private String moiSit;
	private char moiEtq;
	private Integer moiOri;
	private Integer moiCer;
	private BigDecimal moiIpp;
	private BigDecimal moiIpv;
	private BigDecimal moiPnf;
	private BigDecimal moiIcp;
	private BigDecimal moiRed;
	private Integer moiPag;
	private Integer moiMpi;
	private Short moiIte;
	private String moiCst;
	private BigDecimal moiBas;
	private BigDecimal moiIcv;
	private Integer moiMoi;
//	private Set<Notafiscalitens> notafiscalitenses = new HashSet<Notafiscalitens>(0);
//	private Set<Comprapedidocompraitens> comprapedidocompraitenses = new HashSet<Comprapedidocompraitens>(0);


	@Id
	@Column(name = "MOI_COD", unique = true, nullable = false)
	public Integer getMoiCod() {
		return this.moiCod;
	}

	public void setMoiCod(Integer moiCod) {
		this.moiCod = moiCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOI_MOV", nullable = false)
	public Movimento getMovimento() {
		return this.movimento;
	}

	public void setMovimento(Movimento movimento) {
		this.movimento = movimento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MOI_PEI")
	public PedidoItens getPedidoItens() {
		return this.pedidoItens;
	}

	public void setPedidoItens(PedidoItens pedidoItens) {
		this.pedidoItens = pedidoItens;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "MOI_EMP", referencedColumnName = "PRL_EMP", nullable = false),
			@JoinColumn(name = "MOI_PRO", referencedColumnName = "PRL_PRO", nullable = false),
			@JoinColumn(name = "MOI_FIL", referencedColumnName = "PRL_FIL", nullable = false),
			@JoinColumn(name = "MOI_LCD", referencedColumnName = "PRL_LCD", nullable = false) })
	public ProdutoLocal getProdutoLocal() {
		return this.produtoLocal;
	}

	public void setProdutoLocal(ProdutoLocal produtoLocal) {
		this.produtoLocal = produtoLocal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MOI_DTE", length = 10)
	public Date getMoiDte() {
		return this.moiDte;
	}

	public void setMoiDte(Date moiDte) {
		this.moiDte = moiDte;
	}

	@Column(name = "MOI_GRD")
	public Integer getMoiGrd() {
		return this.moiGrd;
	}

	public void setMoiGrd(Integer moiGrd) {
		this.moiGrd = moiGrd;
	}

	@Column(name = "MOI_Q01", nullable = false)
	public Integer getMoiQ01() {
		return this.moiQ01;
	}

	public void setMoiQ01(Integer moiQ01) {
		this.moiQ01 = moiQ01;
	}

	@Column(name = "MOI_Q02", nullable = false)
	public Integer getMoiQ02() {
		return this.moiQ02;
	}

	public void setMoiQ02(Integer moiQ02) {
		this.moiQ02 = moiQ02;
	}

	@Column(name = "MOI_Q03", nullable = false)
	public Integer getMoiQ03() {
		return this.moiQ03;
	}

	public void setMoiQ03(Integer moiQ03) {
		this.moiQ03 = moiQ03;
	}

	@Column(name = "MOI_Q04", nullable = false)
	public Integer getMoiQ04() {
		return this.moiQ04;
	}

	public void setMoiQ04(Integer moiQ04) {
		this.moiQ04 = moiQ04;
	}

	@Column(name = "MOI_Q05", nullable = false)
	public Integer getMoiQ05() {
		return this.moiQ05;
	}

	public void setMoiQ05(Integer moiQ05) {
		this.moiQ05 = moiQ05;
	}

	@Column(name = "MOI_Q06", nullable = false)
	public Integer getMoiQ06() {
		return this.moiQ06;
	}

	public void setMoiQ06(Integer moiQ06) {
		this.moiQ06 = moiQ06;
	}

	@Column(name = "MOI_Q07", nullable = false)
	public Integer getMoiQ07() {
		return this.moiQ07;
	}

	public void setMoiQ07(Integer moiQ07) {
		this.moiQ07 = moiQ07;
	}

	@Column(name = "MOI_Q08", nullable = false)
	public Integer getMoiQ08() {
		return this.moiQ08;
	}

	public void setMoiQ08(Integer moiQ08) {
		this.moiQ08 = moiQ08;
	}

	@Column(name = "MOI_Q09", nullable = false)
	public Integer getMoiQ09() {
		return this.moiQ09;
	}

	public void setMoiQ09(Integer moiQ09) {
		this.moiQ09 = moiQ09;
	}

	@Column(name = "MOI_Q10", nullable = false)
	public Integer getMoiQ10() {
		return this.moiQ10;
	}

	public void setMoiQ10(Integer moiQ10) {
		this.moiQ10 = moiQ10;
	}

	@Column(name = "MOI_Q11", nullable = false)
	public Integer getMoiQ11() {
		return this.moiQ11;
	}

	public void setMoiQ11(Integer moiQ11) {
		this.moiQ11 = moiQ11;
	}

	@Column(name = "MOI_Q12", nullable = false)
	public Integer getMoiQ12() {
		return this.moiQ12;
	}

	public void setMoiQ12(Integer moiQ12) {
		this.moiQ12 = moiQ12;
	}

	@Column(name = "MOI_Q13", nullable = false)
	public Integer getMoiQ13() {
		return this.moiQ13;
	}

	public void setMoiQ13(Integer moiQ13) {
		this.moiQ13 = moiQ13;
	}

	@Column(name = "MOI_Q14", nullable = false)
	public Integer getMoiQ14() {
		return this.moiQ14;
	}

	public void setMoiQ14(Integer moiQ14) {
		this.moiQ14 = moiQ14;
	}

	@Column(name = "MOI_QTD", nullable = false, precision = 18, scale = 5)
	public BigDecimal getMoiQtd() {
		return this.moiQtd;
	}

	public void setMoiQtd(BigDecimal moiQtd) {
		this.moiQtd = moiQtd;
	}

	@Column(name = "MOI_PRU", nullable = false, precision = 18, scale = 5)
	public BigDecimal getMoiPru() {
		return this.moiPru;
	}

	public void setMoiPru(BigDecimal moiPru) {
		this.moiPru = moiPru;
	}

	@Column(name = "MOI_PRC", nullable = false, precision = 18, scale = 5)
	public BigDecimal getMoiPrc() {
		return this.moiPrc;
	}

	public void setMoiPrc(BigDecimal moiPrc) {
		this.moiPrc = moiPrc;
	}

	@Column(name = "MOI_OB1", length = 40)
	public String getMoiOb1() {
		return this.moiOb1;
	}

	public void setMoiOb1(String moiOb1) {
		this.moiOb1 = moiOb1;
	}

	@Column(name = "MOI_OB2", length = 40)
	public String getMoiOb2() {
		return this.moiOb2;
	}

	public void setMoiOb2(String moiOb2) {
		this.moiOb2 = moiOb2;
	}

	@Column(name = "MOI_OB3", length = 40)
	public String getMoiOb3() {
		return this.moiOb3;
	}

	public void setMoiOb3(String moiOb3) {
		this.moiOb3 = moiOb3;
	}

	@Column(name = "MOI_TIP", nullable = false, length = 1)
	public char getMoiTip() {
		return this.moiTip;
	}

	public void setMoiTip(char moiTip) {
		this.moiTip = moiTip;
	}

	@Column(name = "MOI_SIT", nullable = false, length = 1)
	public String getMoiSit() {
		return this.moiSit;
	}

	public void setMoiSit(String moiSit) {
		this.moiSit = moiSit;
	}

	@Column(name = "MOI_ETQ", nullable = false, length = 1)
	public char getMoiEtq() {
		return this.moiEtq;
	}

	public void setMoiEtq(char moiEtq) {
		this.moiEtq = moiEtq;
	}

	@Column(name = "MOI_ORI")
	public Integer getMoiOri() {
		return this.moiOri;
	}

	public void setMoiOri(Integer moiOri) {
		this.moiOri = moiOri;
	}

	@Column(name = "MOI_CER")
	public Integer getMoiCer() {
		return this.moiCer;
	}

	public void setMoiCer(Integer moiCer) {
		this.moiCer = moiCer;
	}

	@Column(name = "MOI_IPP", nullable = false, precision = 6)
	public BigDecimal getMoiIpp() {
		return this.moiIpp;
	}

	public void setMoiIpp(BigDecimal moiIpp) {
		this.moiIpp = moiIpp;
	}

	@Column(name = "MOI_IPV", nullable = false, precision = 14)
	public BigDecimal getMoiIpv() {
		return this.moiIpv;
	}

	public void setMoiIpv(BigDecimal moiIpv) {
		this.moiIpv = moiIpv;
	}

	@Column(name = "MOI_PNF", nullable = false, precision = 18, scale = 5)
	public BigDecimal getMoiPnf() {
		return this.moiPnf;
	}

	public void setMoiPnf(BigDecimal moiPnf) {
		this.moiPnf = moiPnf;
	}

	@Column(name = "MOI_ICP", precision = 6)
	public BigDecimal getMoiIcp() {
		return this.moiIcp;
	}

	public void setMoiIcp(BigDecimal moiIcp) {
		this.moiIcp = moiIcp;
	}

	@Column(name = "MOI_RED", precision = 6)
	public BigDecimal getMoiRed() {
		return this.moiRed;
	}

	public void setMoiRed(BigDecimal moiRed) {
		this.moiRed = moiRed;
	}

	@Column(name = "MOI_PAG")
	public Integer getMoiPag() {
		return this.moiPag;
	}

	public void setMoiPag(Integer moiPag) {
		this.moiPag = moiPag;
	}

	@Column(name = "MOI_MPI")
	public Integer getMoiMpi() {
		return this.moiMpi;
	}

	public void setMoiMpi(Integer moiMpi) {
		this.moiMpi = moiMpi;
	}

	@Column(name = "MOI_ITE")
	public Short getMoiIte() {
		return this.moiIte;
	}

	public void setMoiIte(Short moiIte) {
		this.moiIte = moiIte;
	}

	@Column(name = "MOI_CST", length = 4)
	public String getMoiCst() {
		return this.moiCst;
	}

	public void setMoiCst(String moiCst) {
		this.moiCst = moiCst;
	}

	@Column(name = "MOI_BAS", precision = 14)
	public BigDecimal getMoiBas() {
		return this.moiBas;
	}

	public void setMoiBas(BigDecimal moiBas) {
		this.moiBas = moiBas;
	}

	@Column(name = "MOI_ICV", precision = 14)
	public BigDecimal getMoiIcv() {
		return this.moiIcv;
	}

	public void setMoiIcv(BigDecimal moiIcv) {
		this.moiIcv = moiIcv;
	}

	@Column(name = "MOI_MOI")
	public Integer getMoiMoi() {
		return this.moiMoi;
	}

	public void setMoiMoi(Integer moiMoi) {
		this.moiMoi = moiMoi;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimentoitens")
//	public Set<Notafiscalitens> getNotafiscalitenses() {
//		return this.notafiscalitenses;
//	}
//
//	public void setNotafiscalitenses(Set<Notafiscalitens> notafiscalitenses) {
//		this.notafiscalitenses = notafiscalitenses;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movimentoitens")
//	public Set<Comprapedidocompraitens> getComprapedidocompraitenses() {
//		return this.comprapedidocompraitenses;
//	}
//
//	public void setComprapedidocompraitenses(
//			Set<Comprapedidocompraitens> comprapedidocompraitenses) {
//		this.comprapedidocompraitenses = comprapedidocompraitenses;
//	}

}
