package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PedidoItens generated by hbm2java
 */
@Entity
@Table(name = "PEDIDOITENS")
public class PedidoItens implements java.io.Serializable {

	private static final long serialVersionUID = -1162764981018428932L;
	private Integer peiCod;
	private Pedido pedido;
	private Produto produto;
	private Integer peiGrd;
	private Integer peiQ01;
	private Integer peiQ02;
	private Integer peiQ03;
	private Integer peiQ04;
	private Integer peiQ05;
	private Integer peiQ06;
	private Integer peiQ07;
	private Integer peiQ08;
	private Integer peiQ09;
	private Integer peiQ10;
	private Integer peiQ11;
	private Integer peiQ12;
	private Integer peiQ13;
	private Integer peiQ14;
	private BigDecimal peiQtd;
	private BigDecimal peiPru;
	private BigDecimal peiPnf;
	private Integer peiP01;
	private Integer peiP02;
	private Integer peiP03;
	private Integer peiP04;
	private Integer peiP05;
	private Integer peiP06;
	private Integer peiP07;
	private Integer peiP08;
	private Integer peiP09;
	private Integer peiP10;
	private Integer peiP11;
	private Integer peiP12;
	private Integer peiP13;
	private Integer peiP14;
	private BigDecimal peiQtp;
	private Integer peiR01;
	private Integer peiR02;
	private Integer peiR03;
	private Integer peiR04;
	private Integer peiR05;
	private Integer peiR06;
	private Integer peiR07;
	private Integer peiR08;
	private Integer peiR09;
	private Integer peiR10;
	private Integer peiR11;
	private Integer peiR12;
	private Integer peiR13;
	private Integer peiR14;
	private BigDecimal peiQtr;
	private BigDecimal peiTot;
	private BigDecimal peiTod;
	private Integer peiC01;
	private Integer peiC02;
	private Integer peiC03;
	private Integer peiC04;
	private Integer peiC05;
	private Integer peiC06;
	private Integer peiC07;
	private Integer peiC08;
	private Integer peiC09;
	private Integer peiC10;
	private Integer peiC11;
	private Integer peiC12;
	private Integer peiC13;
	private Integer peiC14;
	private BigDecimal peiQtc;
	private Integer peiE01;
	private Integer peiE02;
	private Integer peiE03;
	private Integer peiE04;
	private Integer peiE05;
	private Integer peiE06;
	private Integer peiE07;
	private Integer peiE08;
	private Integer peiE09;
	private Integer peiE10;
	private Integer peiE11;
	private Integer peiE12;
	private Integer peiE13;
	private Integer peiE14;
	private BigDecimal peiQte;
	private String peiObs;
	//private Set<MovimentoItens> movimentoItenses = new HashSet<MovimentoItens>(0);
	/*private Set<Pedidoreserva> pedidoreservas = new HashSet<Pedidoreserva>(0);
	private Set<Ordemproducao> ordemproducaos = new HashSet<Ordemproducao>(0);
	private Set<Pedidocancelaitens> pedidocancelaitenses = new HashSet<Pedidocancelaitens>(0);*/

	public PedidoItens() {
	}

	/*public PedidoItens(Integer peiCod, Pedido pedido, Produto produto, Integer peiQ01,
			Integer peiQ02, Integer peiQ03, Integer peiQ04, Integer peiQ05, Integer peiQ06,
			Integer peiQ07, Integer peiQ08, Integer peiQ09, Integer peiQ10, Integer peiQ11,
			Integer peiQ12, Integer peiQ13, Integer peiQ14, BigDecimal peiQtd,
			BigDecimal peiPru, BigDecimal peiPnf, Integer peiP01, Integer peiP02,
			Integer peiP03, Integer peiP04, Integer peiP05, Integer peiP06, Integer peiP07,
			Integer peiP08, Integer peiP09, Integer peiP10, Integer peiP11, Integer peiP12,
			Integer peiP13, Integer peiP14, BigDecimal peiQtp, Integer peiR01, Integer peiR02,
			Integer peiR03, Integer peiR04, Integer peiR05, Integer peiR06, Integer peiR07,
			Integer peiR08, Integer peiR09, Integer peiR10, Integer peiR11, Integer peiR12,
			Integer peiR13, Integer peiR14, BigDecimal peiQtr, BigDecimal peiTot,
			BigDecimal peiTod, Integer peiC01, Integer peiC02, Integer peiC03, Integer peiC04,
			Integer peiC05, Integer peiC06, Integer peiC07, Integer peiC08, Integer peiC09,
			Integer peiC10, Integer peiC11, Integer peiC12, Integer peiC13, Integer peiC14,
			BigDecimal peiQtc, Integer peiE01, Integer peiE02, Integer peiE03, Integer peiE04,
			Integer peiE05, Integer peiE06, Integer peiE07, Integer peiE08, Integer peiE09,
			Integer peiE10, Integer peiE11, Integer peiE12, Integer peiE13, Integer peiE14,
			BigDecimal peiQte) {
		this.peiCod = peiCod;
		this.pedido = pedido;
		this.produto = produto;
		this.peiQ01 = peiQ01;
		this.peiQ02 = peiQ02;
		this.peiQ03 = peiQ03;
		this.peiQ04 = peiQ04;
		this.peiQ05 = peiQ05;
		this.peiQ06 = peiQ06;
		this.peiQ07 = peiQ07;
		this.peiQ08 = peiQ08;
		this.peiQ09 = peiQ09;
		this.peiQ10 = peiQ10;
		this.peiQ11 = peiQ11;
		this.peiQ12 = peiQ12;
		this.peiQ13 = peiQ13;
		this.peiQ14 = peiQ14;
		this.peiQtd = peiQtd;
		this.peiPru = peiPru;
		this.peiPnf = peiPnf;
		this.peiP01 = peiP01;
		this.peiP02 = peiP02;
		this.peiP03 = peiP03;
		this.peiP04 = peiP04;
		this.peiP05 = peiP05;
		this.peiP06 = peiP06;
		this.peiP07 = peiP07;
		this.peiP08 = peiP08;
		this.peiP09 = peiP09;
		this.peiP10 = peiP10;
		this.peiP11 = peiP11;
		this.peiP12 = peiP12;
		this.peiP13 = peiP13;
		this.peiP14 = peiP14;
		this.peiQtp = peiQtp;
		this.peiR01 = peiR01;
		this.peiR02 = peiR02;
		this.peiR03 = peiR03;
		this.peiR04 = peiR04;
		this.peiR05 = peiR05;
		this.peiR06 = peiR06;
		this.peiR07 = peiR07;
		this.peiR08 = peiR08;
		this.peiR09 = peiR09;
		this.peiR10 = peiR10;
		this.peiR11 = peiR11;
		this.peiR12 = peiR12;
		this.peiR13 = peiR13;
		this.peiR14 = peiR14;
		this.peiQtr = peiQtr;
		this.peiTot = peiTot;
		this.peiTod = peiTod;
		this.peiC01 = peiC01;
		this.peiC02 = peiC02;
		this.peiC03 = peiC03;
		this.peiC04 = peiC04;
		this.peiC05 = peiC05;
		this.peiC06 = peiC06;
		this.peiC07 = peiC07;
		this.peiC08 = peiC08;
		this.peiC09 = peiC09;
		this.peiC10 = peiC10;
		this.peiC11 = peiC11;
		this.peiC12 = peiC12;
		this.peiC13 = peiC13;
		this.peiC14 = peiC14;
		this.peiQtc = peiQtc;
		this.peiE01 = peiE01;
		this.peiE02 = peiE02;
		this.peiE03 = peiE03;
		this.peiE04 = peiE04;
		this.peiE05 = peiE05;
		this.peiE06 = peiE06;
		this.peiE07 = peiE07;
		this.peiE08 = peiE08;
		this.peiE09 = peiE09;
		this.peiE10 = peiE10;
		this.peiE11 = peiE11;
		this.peiE12 = peiE12;
		this.peiE13 = peiE13;
		this.peiE14 = peiE14;
		this.peiQte = peiQte;
	}
*/
/*	public PedidoItens(Integer peiCod, Pedido pedido, Produto produto,
			Integer peiGrd, Integer peiQ01, Integer peiQ02, Integer peiQ03, Integer peiQ04,
			Integer peiQ05, Integer peiQ06, Integer peiQ07, Integer peiQ08, Integer peiQ09,
			Integer peiQ10, Integer peiQ11, Integer peiQ12, Integer peiQ13, Integer peiQ14,
			BigDecimal peiQtd, BigDecimal peiPru, BigDecimal peiPnf,
			Integer peiP01, Integer peiP02, Integer peiP03, Integer peiP04, Integer peiP05,
			Integer peiP06, Integer peiP07, Integer peiP08, Integer peiP09, Integer peiP10,
			Integer peiP11, Integer peiP12, Integer peiP13, Integer peiP14, BigDecimal peiQtp,
			Integer peiR01, Integer peiR02, Integer peiR03, Integer peiR04, Integer peiR05,
			Integer peiR06, Integer peiR07, Integer peiR08, Integer peiR09, Integer peiR10,
			Integer peiR11, Integer peiR12, Integer peiR13, Integer peiR14, BigDecimal peiQtr,
			BigDecimal peiTot, BigDecimal peiTod, Integer peiC01, Integer peiC02,
			Integer peiC03, Integer peiC04, Integer peiC05, Integer peiC06, Integer peiC07,
			Integer peiC08, Integer peiC09, Integer peiC10, Integer peiC11, Integer peiC12,
			Integer peiC13, Integer peiC14, BigDecimal peiQtc, Integer peiE01, Integer peiE02,
			Integer peiE03, Integer peiE04, Integer peiE05, Integer peiE06, Integer peiE07,
			Integer peiE08, Integer peiE09, Integer peiE10, Integer peiE11, Integer peiE12,
			Integer peiE13, Integer peiE14, BigDecimal peiQte, String peiObs,
			Set<MovimentoItens> movimentoItenses,
			Set<Pedidoreserva> pedidoreservas,
			Set<Ordemproducao> ordemproducaos,
			Set<Pedidocancelaitens> pedidocancelaitenses) {
		this.peiCod = peiCod;
		this.pedido = pedido;
		this.produto = produto;
		this.peiGrd = peiGrd;
		this.peiQ01 = peiQ01;
		this.peiQ02 = peiQ02;
		this.peiQ03 = peiQ03;
		this.peiQ04 = peiQ04;
		this.peiQ05 = peiQ05;
		this.peiQ06 = peiQ06;
		this.peiQ07 = peiQ07;
		this.peiQ08 = peiQ08;
		this.peiQ09 = peiQ09;
		this.peiQ10 = peiQ10;
		this.peiQ11 = peiQ11;
		this.peiQ12 = peiQ12;
		this.peiQ13 = peiQ13;
		this.peiQ14 = peiQ14;
		this.peiQtd = peiQtd;
		this.peiPru = peiPru;
		this.peiPnf = peiPnf;
		this.peiP01 = peiP01;
		this.peiP02 = peiP02;
		this.peiP03 = peiP03;
		this.peiP04 = peiP04;
		this.peiP05 = peiP05;
		this.peiP06 = peiP06;
		this.peiP07 = peiP07;
		this.peiP08 = peiP08;
		this.peiP09 = peiP09;
		this.peiP10 = peiP10;
		this.peiP11 = peiP11;
		this.peiP12 = peiP12;
		this.peiP13 = peiP13;
		this.peiP14 = peiP14;
		this.peiQtp = peiQtp;
		this.peiR01 = peiR01;
		this.peiR02 = peiR02;
		this.peiR03 = peiR03;
		this.peiR04 = peiR04;
		this.peiR05 = peiR05;
		this.peiR06 = peiR06;
		this.peiR07 = peiR07;
		this.peiR08 = peiR08;
		this.peiR09 = peiR09;
		this.peiR10 = peiR10;
		this.peiR11 = peiR11;
		this.peiR12 = peiR12;
		this.peiR13 = peiR13;
		this.peiR14 = peiR14;
		this.peiQtr = peiQtr;
		this.peiTot = peiTot;
		this.peiTod = peiTod;
		this.peiC01 = peiC01;
		this.peiC02 = peiC02;
		this.peiC03 = peiC03;
		this.peiC04 = peiC04;
		this.peiC05 = peiC05;
		this.peiC06 = peiC06;
		this.peiC07 = peiC07;
		this.peiC08 = peiC08;
		this.peiC09 = peiC09;
		this.peiC10 = peiC10;
		this.peiC11 = peiC11;
		this.peiC12 = peiC12;
		this.peiC13 = peiC13;
		this.peiC14 = peiC14;
		this.peiQtc = peiQtc;
		this.peiE01 = peiE01;
		this.peiE02 = peiE02;
		this.peiE03 = peiE03;
		this.peiE04 = peiE04;
		this.peiE05 = peiE05;
		this.peiE06 = peiE06;
		this.peiE07 = peiE07;
		this.peiE08 = peiE08;
		this.peiE09 = peiE09;
		this.peiE10 = peiE10;
		this.peiE11 = peiE11;
		this.peiE12 = peiE12;
		this.peiE13 = peiE13;
		this.peiE14 = peiE14;
		this.peiQte = peiQte;
		this.peiObs = peiObs;
		this.movimentoItenses = movimentoItenses;
		this.pedidoreservas = pedidoreservas;
		this.ordemproducaos = ordemproducaos;
		this.pedidocancelaitenses = pedidocancelaitenses;
	}*/

	@Id
	@Column(name = "PEI_COD", unique = true, nullable = false)
	public Integer getPeiCod() {
		return this.peiCod;
	}

	public void setPeiCod(Integer peiCod) {
		this.peiCod = peiCod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PEI_PED", nullable = false)
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PEI_EMP", referencedColumnName = "PRO_EMP", nullable = false),
			@JoinColumn(name = "PEI_PRO", referencedColumnName = "PRO_COD", nullable = false) })
	public Produto getProduto() {
		return this.produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	@Column(name = "PEI_GRD")
	public Integer getPeiGrd() {
		return this.peiGrd;
	}

	public void setPeiGrd(Integer peiGrd) {
		this.peiGrd = peiGrd;
	}

	@Column(name = "PEI_Q01", nullable = false)
	public Integer getPeiQ01() {
		return this.peiQ01;
	}

	public void setPeiQ01(Integer peiQ01) {
		this.peiQ01 = peiQ01;
	}

	@Column(name = "PEI_Q02", nullable = false)
	public Integer getPeiQ02() {
		return this.peiQ02;
	}

	public void setPeiQ02(Integer peiQ02) {
		this.peiQ02 = peiQ02;
	}

	@Column(name = "PEI_Q03", nullable = false)
	public Integer getPeiQ03() {
		return this.peiQ03;
	}

	public void setPeiQ03(Integer peiQ03) {
		this.peiQ03 = peiQ03;
	}

	@Column(name = "PEI_Q04", nullable = false)
	public Integer getPeiQ04() {
		return this.peiQ04;
	}

	public void setPeiQ04(Integer peiQ04) {
		this.peiQ04 = peiQ04;
	}

	@Column(name = "PEI_Q05", nullable = false)
	public Integer getPeiQ05() {
		return this.peiQ05;
	}

	public void setPeiQ05(Integer peiQ05) {
		this.peiQ05 = peiQ05;
	}

	@Column(name = "PEI_Q06", nullable = false)
	public Integer getPeiQ06() {
		return this.peiQ06;
	}

	public void setPeiQ06(Integer peiQ06) {
		this.peiQ06 = peiQ06;
	}

	@Column(name = "PEI_Q07", nullable = false)
	public Integer getPeiQ07() {
		return this.peiQ07;
	}

	public void setPeiQ07(Integer peiQ07) {
		this.peiQ07 = peiQ07;
	}

	@Column(name = "PEI_Q08", nullable = false)
	public Integer getPeiQ08() {
		return this.peiQ08;
	}

	public void setPeiQ08(Integer peiQ08) {
		this.peiQ08 = peiQ08;
	}

	@Column(name = "PEI_Q09", nullable = false)
	public Integer getPeiQ09() {
		return this.peiQ09;
	}

	public void setPeiQ09(Integer peiQ09) {
		this.peiQ09 = peiQ09;
	}

	@Column(name = "PEI_Q10", nullable = false)
	public Integer getPeiQ10() {
		return this.peiQ10;
	}

	public void setPeiQ10(Integer peiQ10) {
		this.peiQ10 = peiQ10;
	}

	@Column(name = "PEI_Q11", nullable = false)
	public Integer getPeiQ11() {
		return this.peiQ11;
	}

	public void setPeiQ11(Integer peiQ11) {
		this.peiQ11 = peiQ11;
	}

	@Column(name = "PEI_Q12", nullable = false)
	public Integer getPeiQ12() {
		return this.peiQ12;
	}

	public void setPeiQ12(Integer peiQ12) {
		this.peiQ12 = peiQ12;
	}

	@Column(name = "PEI_Q13", nullable = false)
	public Integer getPeiQ13() {
		return this.peiQ13;
	}

	public void setPeiQ13(Integer peiQ13) {
		this.peiQ13 = peiQ13;
	}

	@Column(name = "PEI_Q14", nullable = false)
	public Integer getPeiQ14() {
		return this.peiQ14;
	}

	public void setPeiQ14(Integer peiQ14) {
		this.peiQ14 = peiQ14;
	}

	@Column(name = "PEI_QTD", nullable = false, precision = 18, scale = 5)
	public BigDecimal getPeiQtd() {
		return this.peiQtd;
	}

	public void setPeiQtd(BigDecimal peiQtd) {
		this.peiQtd = peiQtd;
	}

	@Column(name = "PEI_PRU", nullable = false, precision = 18, scale = 5)
	public BigDecimal getPeiPru() {
		return this.peiPru;
	}

	public void setPeiPru(BigDecimal peiPru) {
		this.peiPru = peiPru;
	}

	@Column(name = "PEI_PNF", nullable = false, precision = 18, scale = 5)
	public BigDecimal getPeiPnf() {
		return this.peiPnf;
	}

	public void setPeiPnf(BigDecimal peiPnf) {
		this.peiPnf = peiPnf;
	}

	@Column(name = "PEI_P01", nullable = false)
	public Integer getPeiP01() {
		return this.peiP01;
	}

	public void setPeiP01(Integer peiP01) {
		this.peiP01 = peiP01;
	}

	@Column(name = "PEI_P02", nullable = false)
	public Integer getPeiP02() {
		return this.peiP02;
	}

	public void setPeiP02(Integer peiP02) {
		this.peiP02 = peiP02;
	}

	@Column(name = "PEI_P03", nullable = false)
	public Integer getPeiP03() {
		return this.peiP03;
	}

	public void setPeiP03(Integer peiP03) {
		this.peiP03 = peiP03;
	}

	@Column(name = "PEI_P04", nullable = false)
	public Integer getPeiP04() {
		return this.peiP04;
	}

	public void setPeiP04(Integer peiP04) {
		this.peiP04 = peiP04;
	}

	@Column(name = "PEI_P05", nullable = false)
	public Integer getPeiP05() {
		return this.peiP05;
	}

	public void setPeiP05(Integer peiP05) {
		this.peiP05 = peiP05;
	}

	@Column(name = "PEI_P06", nullable = false)
	public Integer getPeiP06() {
		return this.peiP06;
	}

	public void setPeiP06(Integer peiP06) {
		this.peiP06 = peiP06;
	}

	@Column(name = "PEI_P07", nullable = false)
	public Integer getPeiP07() {
		return this.peiP07;
	}

	public void setPeiP07(Integer peiP07) {
		this.peiP07 = peiP07;
	}

	@Column(name = "PEI_P08", nullable = false)
	public Integer getPeiP08() {
		return this.peiP08;
	}

	public void setPeiP08(Integer peiP08) {
		this.peiP08 = peiP08;
	}

	@Column(name = "PEI_P09", nullable = false)
	public Integer getPeiP09() {
		return this.peiP09;
	}

	public void setPeiP09(Integer peiP09) {
		this.peiP09 = peiP09;
	}

	@Column(name = "PEI_P10", nullable = false)
	public Integer getPeiP10() {
		return this.peiP10;
	}

	public void setPeiP10(Integer peiP10) {
		this.peiP10 = peiP10;
	}

	@Column(name = "PEI_P11", nullable = false)
	public Integer getPeiP11() {
		return this.peiP11;
	}

	public void setPeiP11(Integer peiP11) {
		this.peiP11 = peiP11;
	}

	@Column(name = "PEI_P12", nullable = false)
	public Integer getPeiP12() {
		return this.peiP12;
	}

	public void setPeiP12(Integer peiP12) {
		this.peiP12 = peiP12;
	}

	@Column(name = "PEI_P13", nullable = false)
	public Integer getPeiP13() {
		return this.peiP13;
	}

	public void setPeiP13(Integer peiP13) {
		this.peiP13 = peiP13;
	}

	@Column(name = "PEI_P14", nullable = false)
	public Integer getPeiP14() {
		return this.peiP14;
	}

	public void setPeiP14(Integer peiP14) {
		this.peiP14 = peiP14;
	}

	@Column(name = "PEI_QTP", nullable = false, precision = 18, scale = 5)
	public BigDecimal getPeiQtp() {
		return this.peiQtp;
	}

	public void setPeiQtp(BigDecimal peiQtp) {
		this.peiQtp = peiQtp;
	}

	@Column(name = "PEI_R01", nullable = false)
	public Integer getPeiR01() {
		return this.peiR01;
	}

	public void setPeiR01(Integer peiR01) {
		this.peiR01 = peiR01;
	}

	@Column(name = "PEI_R02", nullable = false)
	public Integer getPeiR02() {
		return this.peiR02;
	}

	public void setPeiR02(Integer peiR02) {
		this.peiR02 = peiR02;
	}

	@Column(name = "PEI_R03", nullable = false)
	public Integer getPeiR03() {
		return this.peiR03;
	}

	public void setPeiR03(Integer peiR03) {
		this.peiR03 = peiR03;
	}

	@Column(name = "PEI_R04", nullable = false)
	public Integer getPeiR04() {
		return this.peiR04;
	}

	public void setPeiR04(Integer peiR04) {
		this.peiR04 = peiR04;
	}

	@Column(name = "PEI_R05", nullable = false)
	public Integer getPeiR05() {
		return this.peiR05;
	}

	public void setPeiR05(Integer peiR05) {
		this.peiR05 = peiR05;
	}

	@Column(name = "PEI_R06", nullable = false)
	public Integer getPeiR06() {
		return this.peiR06;
	}

	public void setPeiR06(Integer peiR06) {
		this.peiR06 = peiR06;
	}

	@Column(name = "PEI_R07", nullable = false)
	public Integer getPeiR07() {
		return this.peiR07;
	}

	public void setPeiR07(Integer peiR07) {
		this.peiR07 = peiR07;
	}

	@Column(name = "PEI_R08", nullable = false)
	public Integer getPeiR08() {
		return this.peiR08;
	}

	public void setPeiR08(Integer peiR08) {
		this.peiR08 = peiR08;
	}

	@Column(name = "PEI_R09", nullable = false)
	public Integer getPeiR09() {
		return this.peiR09;
	}

	public void setPeiR09(Integer peiR09) {
		this.peiR09 = peiR09;
	}

	@Column(name = "PEI_R10", nullable = false)
	public Integer getPeiR10() {
		return this.peiR10;
	}

	public void setPeiR10(Integer peiR10) {
		this.peiR10 = peiR10;
	}

	@Column(name = "PEI_R11", nullable = false)
	public Integer getPeiR11() {
		return this.peiR11;
	}

	public void setPeiR11(Integer peiR11) {
		this.peiR11 = peiR11;
	}

	@Column(name = "PEI_R12", nullable = false)
	public Integer getPeiR12() {
		return this.peiR12;
	}

	public void setPeiR12(Integer peiR12) {
		this.peiR12 = peiR12;
	}

	@Column(name = "PEI_R13", nullable = false)
	public Integer getPeiR13() {
		return this.peiR13;
	}

	public void setPeiR13(Integer peiR13) {
		this.peiR13 = peiR13;
	}

	@Column(name = "PEI_R14", nullable = false)
	public Integer getPeiR14() {
		return this.peiR14;
	}

	public void setPeiR14(Integer peiR14) {
		this.peiR14 = peiR14;
	}

	@Column(name = "PEI_QTR", nullable = false, precision = 18, scale = 5)
	public BigDecimal getPeiQtr() {
		return this.peiQtr;
	}

	public void setPeiQtr(BigDecimal peiQtr) {
		this.peiQtr = peiQtr;
	}

	@Column(name = "PEI_TOT", nullable = false, precision = 15)
	public BigDecimal getPeiTot() {
		return this.peiTot;
	}

	public void setPeiTot(BigDecimal peiTot) {
		this.peiTot = peiTot;
	}

	@Column(name = "PEI_TOD", nullable = false, precision = 15)
	public BigDecimal getPeiTod() {
		return this.peiTod;
	}

	public void setPeiTod(BigDecimal peiTod) {
		this.peiTod = peiTod;
	}

	@Column(name = "PEI_C01", nullable = false)
	public Integer getPeiC01() {
		return this.peiC01;
	}

	public void setPeiC01(Integer peiC01) {
		this.peiC01 = peiC01;
	}

	@Column(name = "PEI_C02", nullable = false)
	public Integer getPeiC02() {
		return this.peiC02;
	}

	public void setPeiC02(Integer peiC02) {
		this.peiC02 = peiC02;
	}

	@Column(name = "PEI_C03", nullable = false)
	public Integer getPeiC03() {
		return this.peiC03;
	}

	public void setPeiC03(Integer peiC03) {
		this.peiC03 = peiC03;
	}

	@Column(name = "PEI_C04", nullable = false)
	public Integer getPeiC04() {
		return this.peiC04;
	}

	public void setPeiC04(Integer peiC04) {
		this.peiC04 = peiC04;
	}

	@Column(name = "PEI_C05", nullable = false)
	public Integer getPeiC05() {
		return this.peiC05;
	}

	public void setPeiC05(Integer peiC05) {
		this.peiC05 = peiC05;
	}

	@Column(name = "PEI_C06", nullable = false)
	public Integer getPeiC06() {
		return this.peiC06;
	}

	public void setPeiC06(Integer peiC06) {
		this.peiC06 = peiC06;
	}

	@Column(name = "PEI_C07", nullable = false)
	public Integer getPeiC07() {
		return this.peiC07;
	}

	public void setPeiC07(Integer peiC07) {
		this.peiC07 = peiC07;
	}

	@Column(name = "PEI_C08", nullable = false)
	public Integer getPeiC08() {
		return this.peiC08;
	}

	public void setPeiC08(Integer peiC08) {
		this.peiC08 = peiC08;
	}

	@Column(name = "PEI_C09", nullable = false)
	public Integer getPeiC09() {
		return this.peiC09;
	}

	public void setPeiC09(Integer peiC09) {
		this.peiC09 = peiC09;
	}

	@Column(name = "PEI_C10", nullable = false)
	public Integer getPeiC10() {
		return this.peiC10;
	}

	public void setPeiC10(Integer peiC10) {
		this.peiC10 = peiC10;
	}

	@Column(name = "PEI_C11", nullable = false)
	public Integer getPeiC11() {
		return this.peiC11;
	}

	public void setPeiC11(Integer peiC11) {
		this.peiC11 = peiC11;
	}

	@Column(name = "PEI_C12", nullable = false)
	public Integer getPeiC12() {
		return this.peiC12;
	}

	public void setPeiC12(Integer peiC12) {
		this.peiC12 = peiC12;
	}

	@Column(name = "PEI_C13", nullable = false)
	public Integer getPeiC13() {
		return this.peiC13;
	}

	public void setPeiC13(Integer peiC13) {
		this.peiC13 = peiC13;
	}

	@Column(name = "PEI_C14", nullable = false)
	public Integer getPeiC14() {
		return this.peiC14;
	}

	public void setPeiC14(Integer peiC14) {
		this.peiC14 = peiC14;
	}

	@Column(name = "PEI_QTC", nullable = false, precision = 18, scale = 5)
	public BigDecimal getPeiQtc() {
		return this.peiQtc;
	}

	public void setPeiQtc(BigDecimal peiQtc) {
		this.peiQtc = peiQtc;
	}

	@Column(name = "PEI_E01", nullable = false)
	public Integer getPeiE01() {
		return this.peiE01;
	}

	public void setPeiE01(Integer peiE01) {
		this.peiE01 = peiE01;
	}

	@Column(name = "PEI_E02", nullable = false)
	public Integer getPeiE02() {
		return this.peiE02;
	}

	public void setPeiE02(Integer peiE02) {
		this.peiE02 = peiE02;
	}

	@Column(name = "PEI_E03", nullable = false)
	public Integer getPeiE03() {
		return this.peiE03;
	}

	public void setPeiE03(Integer peiE03) {
		this.peiE03 = peiE03;
	}

	@Column(name = "PEI_E04", nullable = false)
	public Integer getPeiE04() {
		return this.peiE04;
	}

	public void setPeiE04(Integer peiE04) {
		this.peiE04 = peiE04;
	}

	@Column(name = "PEI_E05", nullable = false)
	public Integer getPeiE05() {
		return this.peiE05;
	}

	public void setPeiE05(Integer peiE05) {
		this.peiE05 = peiE05;
	}

	@Column(name = "PEI_E06", nullable = false)
	public Integer getPeiE06() {
		return this.peiE06;
	}

	public void setPeiE06(Integer peiE06) {
		this.peiE06 = peiE06;
	}

	@Column(name = "PEI_E07", nullable = false)
	public Integer getPeiE07() {
		return this.peiE07;
	}

	public void setPeiE07(Integer peiE07) {
		this.peiE07 = peiE07;
	}

	@Column(name = "PEI_E08", nullable = false)
	public Integer getPeiE08() {
		return this.peiE08;
	}

	public void setPeiE08(Integer peiE08) {
		this.peiE08 = peiE08;
	}

	@Column(name = "PEI_E09", nullable = false)
	public Integer getPeiE09() {
		return this.peiE09;
	}

	public void setPeiE09(Integer peiE09) {
		this.peiE09 = peiE09;
	}

	@Column(name = "PEI_E10", nullable = false)
	public Integer getPeiE10() {
		return this.peiE10;
	}

	public void setPeiE10(Integer peiE10) {
		this.peiE10 = peiE10;
	}

	@Column(name = "PEI_E11", nullable = false)
	public Integer getPeiE11() {
		return this.peiE11;
	}

	public void setPeiE11(Integer peiE11) {
		this.peiE11 = peiE11;
	}

	@Column(name = "PEI_E12", nullable = false)
	public Integer getPeiE12() {
		return this.peiE12;
	}

	public void setPeiE12(Integer peiE12) {
		this.peiE12 = peiE12;
	}

	@Column(name = "PEI_E13", nullable = false)
	public Integer getPeiE13() {
		return this.peiE13;
	}

	public void setPeiE13(Integer peiE13) {
		this.peiE13 = peiE13;
	}

	@Column(name = "PEI_E14", nullable = false)
	public Integer getPeiE14() {
		return this.peiE14;
	}

	public void setPeiE14(Integer peiE14) {
		this.peiE14 = peiE14;
	}

	@Column(name = "PEI_QTE", nullable = false, precision = 18, scale = 5)
	public BigDecimal getPeiQte() {
		return this.peiQte;
	}

	public void setPeiQte(BigDecimal peiQte) {
		this.peiQte = peiQte;
	}

	@Column(name = "PEI_OBS", length = 60)
	public String getPeiObs() {
		return this.peiObs;
	}

	public void setPeiObs(String peiObs) {
		this.peiObs = peiObs;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedidoItens")
	public Set<MovimentoItens> getMovimentoItenses() {
		return this.movimentoItenses;
	}

	public void setMovimentoItenses(Set<MovimentoItens> movimentoItenses) {
		this.movimentoItenses = movimentoItenses;
	}*/

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedidoItens")
	public Set<Pedidoreserva> getPedidoreservas() {
		return this.pedidoreservas;
	}

	public void setPedidoreservas(Set<Pedidoreserva> pedidoreservas) {
		this.pedidoreservas = pedidoreservas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedidoItens")
	public Set<Ordemproducao> getOrdemproducaos() {
		return this.ordemproducaos;
	}

	public void setOrdemproducaos(Set<Ordemproducao> ordemproducaos) {
		this.ordemproducaos = ordemproducaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedidoItens")
	public Set<Pedidocancelaitens> getPedidocancelaitenses() {
		return this.pedidocancelaitenses;
	}

	public void setPedidocancelaitenses(
			Set<Pedidocancelaitens> pedidocancelaitenses) {
		this.pedidocancelaitenses = pedidocancelaitenses;
	}
*/
}
