package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Placa generated by hbm2java
 */
@Entity
@Table(name = "PLACA")
public class Placa implements java.io.Serializable {
	
	private static final long serialVersionUID = 8822694171366263556L;
	
	private String plcCod;
	private char plcTip;
	private String plcMun;
	private String plcEst;
	private String plcNom;
	private String plcRen;
	private Short plcAnf;
	private Short plcAnm;
	private String plcCor;
	private String plcCom;
	private String plcMod;
	private String plcCha;
	private String plcPro;
	private String plcOb1;
	private String plcOb2;
	private Veiculo veiculoByPlcCod;
	private Set<Veiculo> veiculosForVeiPld = new HashSet<Veiculo>(0);
	private Set<Veiculo> veiculosForVeiPlb = new HashSet<Veiculo>(0);
	private Set<Veiculo> veiculosForVeiPlr = new HashSet<Veiculo>(0);

	@Id
	@Column(name = "PLC_COD", unique = true, nullable = false, length = 10)
	public String getPlcCod() {
		return this.plcCod;
	}

	public void setPlcCod(String plcCod) {
		this.plcCod = plcCod;
	}

	@Column(name = "PLC_TIP", nullable = false, length = 1)
	public char getPlcTip() {
		return this.plcTip;
	}

	public void setPlcTip(char plcTip) {
		this.plcTip = plcTip;
	}

	@Column(name = "PLC_MUN", length = 20)
	public String getPlcMun() {
		return this.plcMun;
	}

	public void setPlcMun(String plcMun) {
		this.plcMun = plcMun;
	}

	@Column(name = "PLC_EST", length = 2)
	public String getPlcEst() {
		return this.plcEst;
	}

	public void setPlcEst(String plcEst) {
		this.plcEst = plcEst;
	}

	@Column(name = "PLC_NOM", length = 40)
	public String getPlcNom() {
		return this.plcNom;
	}

	public void setPlcNom(String plcNom) {
		this.plcNom = plcNom;
	}

	@Column(name = "PLC_REN", length = 10)
	public String getPlcRen() {
		return this.plcRen;
	}

	public void setPlcRen(String plcRen) {
		this.plcRen = plcRen;
	}

	@Column(name = "PLC_ANF")
	public Short getPlcAnf() {
		return this.plcAnf;
	}

	public void setPlcAnf(Short plcAnf) {
		this.plcAnf = plcAnf;
	}

	@Column(name = "PLC_ANM")
	public Short getPlcAnm() {
		return this.plcAnm;
	}

	public void setPlcAnm(Short plcAnm) {
		this.plcAnm = plcAnm;
	}

	@Column(name = "PLC_COR", length = 20)
	public String getPlcCor() {
		return this.plcCor;
	}

	public void setPlcCor(String plcCor) {
		this.plcCor = plcCor;
	}

	@Column(name = "PLC_COM", length = 20)
	public String getPlcCom() {
		return this.plcCom;
	}

	public void setPlcCom(String plcCom) {
		this.plcCom = plcCom;
	}

	@Column(name = "PLC_MOD", length = 20)
	public String getPlcMod() {
		return this.plcMod;
	}

	public void setPlcMod(String plcMod) {
		this.plcMod = plcMod;
	}

	@Column(name = "PLC_CHA", length = 20)
	public String getPlcCha() {
		return this.plcCha;
	}

	public void setPlcCha(String plcCha) {
		this.plcCha = plcCha;
	}

	@Column(name = "PLC_PRO", length = 40)
	public String getPlcPro() {
		return this.plcPro;
	}

	public void setPlcPro(String plcPro) {
		this.plcPro = plcPro;
	}

	@Column(name = "PLC_OB1", length = 40)
	public String getPlcOb1() {
		return this.plcOb1;
	}

	public void setPlcOb1(String plcOb1) {
		this.plcOb1 = plcOb1;
	}

	@Column(name = "PLC_OB2", length = 40)
	public String getPlcOb2() {
		return this.plcOb2;
	}

	public void setPlcOb2(String plcOb2) {
		this.plcOb2 = plcOb2;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "placaByPlcCod")
	public Veiculo getVeiculoByPlcCod() {
		return this.veiculoByPlcCod;
	}

	public void setVeiculoByPlcCod(Veiculo veiculoByPlcCod) {
		this.veiculoByPlcCod = veiculoByPlcCod;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "placaByVeiPld")
	public Set<Veiculo> getVeiculosForVeiPld() {
		return this.veiculosForVeiPld;
	}

	public void setVeiculosForVeiPld(Set<Veiculo> veiculosForVeiPld) {
		this.veiculosForVeiPld = veiculosForVeiPld;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "placaByVeiPlb")
	public Set<Veiculo> getVeiculosForVeiPlb() {
		return this.veiculosForVeiPlb;
	}

	public void setVeiculosForVeiPlb(Set<Veiculo> veiculosForVeiPlb) {
		this.veiculosForVeiPlb = veiculosForVeiPlb;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "placaByVeiPlr")
	public Set<Veiculo> getVeiculosForVeiPlr() {
		return this.veiculosForVeiPlr;
	}

	public void setVeiculosForVeiPlr(Set<Veiculo> veiculosForVeiPlr) {
		this.veiculosForVeiPlr = veiculosForVeiPlr;
	}

}
