package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PlanoDeContas generated by hbm2java
 */
@Entity
@Table(name = "PLANODECONTAS")
public class PlanoDeContas implements java.io.Serializable {

	
	private static final long serialVersionUID = -5736963974794397581L;
	private PlanoDeContasId id;
	private Empresa empresa;
	private String plaTip;
	private String plaCtb;
	private String plaNom;
	private Integer plaDie;
	private char plaZer;
	private Integer plaDre;
	private Integer plaDoa;
	private char plaLoj;
	private char plaSit;
	/*private Set<Operacaocomercial> operacaocomercialsForFkOpcPla = new HashSet<Operacaocomercial>(0);
	private Set<Contratocartao> contratocartaosForFkCtcPlv = new HashSet<Contratocartao>(0);
	private Set<Contratocartao> contratocartaosForFkCtcPlt = new HashSet<Contratocartao>(0);
	private Set<Receber> recebers = new HashSet<Receber>(0);*/
	private Set<Movimento> movimentos = new HashSet<Movimento>(0);
	/*private Set<Contratoservico> contratoservicos = new HashSet<Contratoservico>(0);
	private Set<Operacao> operacaos = new HashSet<Operacao>(0);
	private Set<Contratocartao> contratocartaosForFkCtcPlp = new HashSet<Contratocartao>(0);
	private Set<Custofixo> custofixos = new HashSet<Custofixo>(0);
	private Set<Operacaocomercial> operacaocomercialsForFkOpcPlaf = new HashSet<Operacaocomercial>(0);*/

	public PlanoDeContas() {
	}

	public PlanoDeContas(PlanoDeContasId id, Empresa empresa, String plaTip,
			String plaCtb, String plaNom, char plaZer, char plaLoj, char plaSit) {
		this.id = id;
		this.empresa = empresa;
		this.plaTip = plaTip;
		this.plaCtb = plaCtb;
		this.plaNom = plaNom;
		this.plaZer = plaZer;
		this.plaLoj = plaLoj;
		this.plaSit = plaSit;
	}

	/*public PlanoDeContas(PlanoDeContasId id, Empresa empresa, String plaTip,
			String plaCtb, String plaNom, Integer plaDie, char plaZer,
			Integer plaDre, Integer plaDoa, char plaLoj, char plaSit,
			Set<Operacaocomercial> operacaocomercialsForFkOpcPla,
			Set<Contratocartao> contratocartaosForFkCtcPlv,
			Set<Contratocartao> contratocartaosForFkCtcPlt,
			Set<Receber> recebers, Set<Movimento> movimentos,
			Set<Contratoservico> contratoservicos, Set<Operacao> operacaos,
			Set<Contratocartao> contratocartaosForFkCtcPlp,
			Set<Custofixo> custofixos,
			Set<Operacaocomercial> operacaocomercialsForFkOpcPlaf) {
		this.id = id;
		this.empresa = empresa;
		this.plaTip = plaTip;
		this.plaCtb = plaCtb;
		this.plaNom = plaNom;
		this.plaDie = plaDie;
		this.plaZer = plaZer;
		this.plaDre = plaDre;
		this.plaDoa = plaDoa;
		this.plaLoj = plaLoj;
		this.plaSit = plaSit;
		this.operacaocomercialsForFkOpcPla = operacaocomercialsForFkOpcPla;
		this.contratocartaosForFkCtcPlv = contratocartaosForFkCtcPlv;
		this.contratocartaosForFkCtcPlt = contratocartaosForFkCtcPlt;
		this.recebers = recebers;
		this.movimentos = movimentos;
		this.contratoservicos = contratoservicos;
		this.operacaos = operacaos;
		this.contratocartaosForFkCtcPlp = contratocartaosForFkCtcPlp;
		this.custofixos = custofixos;
		this.operacaocomercialsForFkOpcPlaf = operacaocomercialsForFkOpcPlaf;
	}*/

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "plaEmp", column = @Column(name = "PLA_EMP", nullable = false)),
			@AttributeOverride(name = "plaCod", column = @Column(name = "PLA_COD", nullable = false)) })
	public PlanoDeContasId getId() {
		return this.id;
	}

	public void setId(PlanoDeContasId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PLA_EMP", nullable = false, insertable = false, updatable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "PLA_TIP", nullable = false, length = 1)
	public String getPlaTip() {
		return this.plaTip;
	}

	public void setPlaTip(String plaTip) {
		this.plaTip = plaTip;
	}

	@Column(name = "PLA_CTB", nullable = false, length = 20)
	public String getPlaCtb() {
		return this.plaCtb;
	}

	public void setPlaCtb(String plaCtb) {
		this.plaCtb = plaCtb;
	}

	@Column(name = "PLA_NOM", nullable = false, length = 60)
	public String getPlaNom() {
		return this.plaNom;
	}

	public void setPlaNom(String plaNom) {
		this.plaNom = plaNom;
	}

	@Column(name = "PLA_DIE")
	public Integer getPlaDie() {
		return this.plaDie;
	}

	public void setPlaDie(Integer plaDie) {
		this.plaDie = plaDie;
	}

	@Column(name = "PLA_ZER", nullable = false, length = 1)
	public char getPlaZer() {
		return this.plaZer;
	}

	public void setPlaZer(char plaZer) {
		this.plaZer = plaZer;
	}

	@Column(name = "PLA_DRE")
	public Integer getPlaDre() {
		return this.plaDre;
	}

	public void setPlaDre(Integer plaDre) {
		this.plaDre = plaDre;
	}

	@Column(name = "PLA_DOA")
	public Integer getPlaDoa() {
		return this.plaDoa;
	}

	public void setPlaDoa(Integer plaDoa) {
		this.plaDoa = plaDoa;
	}

	@Column(name = "PLA_LOJ", nullable = false, length = 1)
	public char getPlaLoj() {
		return this.plaLoj;
	}

	public void setPlaLoj(char plaLoj) {
		this.plaLoj = plaLoj;
	}

	@Column(name = "PLA_SIT", nullable = false, length = 1)
	public char getPlaSit() {
		return this.plaSit;
	}

	public void setPlaSit(char plaSit) {
		this.plaSit = plaSit;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planodecontasByFkOpcPla")
	public Set<Operacaocomercial> getOperacaocomercialsForFkOpcPla() {
		return this.operacaocomercialsForFkOpcPla;
	}

	public void setOperacaocomercialsForFkOpcPla(
			Set<Operacaocomercial> operacaocomercialsForFkOpcPla) {
		this.operacaocomercialsForFkOpcPla = operacaocomercialsForFkOpcPla;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planodecontasByFkCtcPlv")
	public Set<Contratocartao> getContratocartaosForFkCtcPlv() {
		return this.contratocartaosForFkCtcPlv;
	}

	public void setContratocartaosForFkCtcPlv(
			Set<Contratocartao> contratocartaosForFkCtcPlv) {
		this.contratocartaosForFkCtcPlv = contratocartaosForFkCtcPlv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planodecontasByFkCtcPlt")
	public Set<Contratocartao> getContratocartaosForFkCtcPlt() {
		return this.contratocartaosForFkCtcPlt;
	}

	public void setContratocartaosForFkCtcPlt(
			Set<Contratocartao> contratocartaosForFkCtcPlt) {
		this.contratocartaosForFkCtcPlt = contratocartaosForFkCtcPlt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planodecontas")
	public Set<Receber> getRecebers() {
		return this.recebers;
	}

	public void setRecebers(Set<Receber> recebers) {
		this.recebers = recebers;
	}*/

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planodecontas")
	public Set<Movimento> getMovimentos() {
		return this.movimentos;
	}

	public void setMovimentos(Set<Movimento> movimentos) {
		this.movimentos = movimentos;
	}

/*	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planodecontas")
	public Set<Contratoservico> getContratoservicos() {
		return this.contratoservicos;
	}

	public void setContratoservicos(Set<Contratoservico> contratoservicos) {
		this.contratoservicos = contratoservicos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planodecontas")
	public Set<Operacao> getOperacaos() {
		return this.operacaos;
	}

	public void setOperacaos(Set<Operacao> operacaos) {
		this.operacaos = operacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planodecontasByFkCtcPlp")
	public Set<Contratocartao> getContratocartaosForFkCtcPlp() {
		return this.contratocartaosForFkCtcPlp;
	}

	public void setContratocartaosForFkCtcPlp(
			Set<Contratocartao> contratocartaosForFkCtcPlp) {
		this.contratocartaosForFkCtcPlp = contratocartaosForFkCtcPlp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planodecontas")
	public Set<Custofixo> getCustofixos() {
		return this.custofixos;
	}

	public void setCustofixos(Set<Custofixo> custofixos) {
		this.custofixos = custofixos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planodecontasByFkOpcPlaf")
	public Set<Operacaocomercial> getOperacaocomercialsForFkOpcPlaf() {
		return this.operacaocomercialsForFkOpcPlaf;
	}

	public void setOperacaocomercialsForFkOpcPlaf(
			Set<Operacaocomercial> operacaocomercialsForFkOpcPlaf) {
		this.operacaocomercialsForFkOpcPlaf = operacaocomercialsForFkOpcPlaf;
	}*/

}
