package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name = "PRODUTO", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PRO_EMP", "PRO_CCP" }))
public class Produto implements java.io.Serializable {

	private static final long serialVersionUID = -2210669785892587969L;
	private ProdutoId id;
	private Artigo artigo;
	private Colecao colecao;
	private Cor cor;
	private Empresa empresa;
	private Fornecedor fornecedor;
	private Grade grade;
	private Grupo grupo;
	//private Linhaproducao linhaproducao;
	private Marca marca;
	//private Medidalavacao medidalavacao;
	private Modelo modelo;
	private Tributacao tributacao;
	private String proCcp;
	private String proEan;
	private String proTip;
	private String proNom;
	private String proApe;
	private String proNn1;
	private String proNn2;
	private String proEsp;
	private String proNat;
	private String proUnd;
	private BigDecimal proPsb;
	private BigDecimal proPsl;
	private Integer proCla;
	private String proClf;
	private BigDecimal proIpi;
	private String proEtq;
	private String proCom;
	private String proTer;
	private String proSit;
	private String proG01;
	private String proG02;
	private String proG03;
	private String proG04;
	private String proG05;
	private String proG06;
	private String proG07;
	private String proG08;
	private String proG09;
	private String proG10;
	private String proG11;
	private String proG12;
	private String proG13;
	private String proG14;
	private Integer proSgr;
	private Integer proVra;
	private Integer proDgc;
	private String proCps;
	private Integer proUat;
	private String proImg;
	private String proTpp;
	private String proObs;
	private BigDecimal proLar;
	private Date proDtc;
	private Integer proEtl;
	private String proCls;
	private String proIft;
	private String proOri;
	private String proNcm;
	private String proExt;
	private BigDecimal proPma;
	private Integer proEtc;
	private BigDecimal proFgt;
	private BigDecimal proFrd;
	private String proFcr;
	private String proFob;
	private String proCds;
	private String proTpi;
	private BigDecimal proPrv;
	private Integer proMlt;
	private String proFcr1;
	private String proFcr2;
	private BigDecimal proPcf;
	private String proNom1;
	private Integer proEtf;
	private String proIma;
	private String proSts;
	private String proOpe;
	private String proFci;
	private BigDecimal proAm1;
	private BigDecimal proAm2;
	private BigDecimal proAm3;
	private BigDecimal proPam;
	private BigDecimal proAre;
	private BigDecimal proPsi;
	private BigDecimal proPsf;
	private BigDecimal proTaj;
	private BigDecimal proCsm;
	private BigDecimal proCld;
	/*private Set<Estoqueminimo> estoqueminimos = new HashSet<Estoqueminimo>(0);
	private Set<Produtomateriaprima> produtomateriaprimasForFkPrmMtp = new HashSet<Produtomateriaprima>(0);
	private Set<Codigobarras> codigobarrases = new HashSet<Codigobarras>(0);
	private Set<Pcpordemproducao> pcpordemproducaos = new HashSet<Pcpordemproducao>(0);
	private Set<Produtomateriaprima> produtomateriaprimasForFkPrmPro = new HashSet<Produtomateriaprima>(0);
	private Set<Produtosilk> produtosilks = new HashSet<Produtosilk>(0);
	private Set<Balancoproduto> balancoprodutos = new HashSet<Balancoproduto>(0);
	private Set<Grupomateriaprima> grupomateriaprimas = new HashSet<Grupomateriaprima>(0);
	private Set<Empresapautaproduto> empresapautaprodutos = new HashSet<Empresapautaproduto>(0);
	private Set<Pedidoitens> pedidoitenses = new HashSet<Pedidoitens>(0);
	private Set<Produtofilial> produtofilials = new HashSet<Produtofilial>(0);
	private Set<Produtofornecedor> produtofornecedors = new HashSet<Produtofornecedor>(0);
	private Set<Produtolocal> produtolocals = new HashSet<Produtolocal>(0);
	private Set<Bloqueioconsignado> bloqueioconsignados = new HashSet<Bloqueioconsignado>(0);
	private Set<Operacaooperadormovimento> operacaooperadormovimentos = new HashSet<Operacaooperadormovimento>(0);
	private Set<Operacaopautaproduto> operacaopautaprodutos = new HashSet<Operacaopautaproduto>(0);
	private Set<Codigoepc> codigoepcs = new HashSet<Codigoepc>(0);
	private Set<Pedidocompraitens> pedidocompraitenses = new HashSet<Pedidocompraitens>(0);
	private Set<Empresapautaprodutotamanho> empresapautaprodutotamanhos = new HashSet<Empresapautaprodutotamanho>(0);
	private Set<Remessaproducaosimulacaoitens> remessaproducaosimulacaoitenses = new HashSet<Remessaproducaosimulacaoitens>(0);
	private Set<Mapacorte> mapacortes = new HashSet<Mapacorte>(0);*/
	private Set<ProdutoLocal> produtoLocal = new HashSet<ProdutoLocal>(0);

	public Produto() {
	}

	/*public Produto(ProdutoId id, Empresa empresa, Fornecedor fornecedor,
			Linhaproducao linhaproducao, Modelo modelo, Tributacao tributacao,
			String proCcp, String proTip, String proNom, BigDecimal proPsb,
			BigDecimal proPsl, BigDecimal proIpi, String proEtq, String proCom,
			String proTer, String proSit, String proG01, String proG02, String proG03,
			String proG04, String proG05, String proG06, String proG07, String proG08,
			String proG09, String proG10, String proG11, String proG12, String proG13,
			String proG14, Integer proVra, Integer proUat, BigDecimal proLar,
			Date proDtc, String proCls, String proIft, String proOri,
			BigDecimal proPma, BigDecimal proFgt, BigDecimal proFrd,
			String proCds, String proTpi, BigDecimal proPrv, BigDecimal proPcf,
			String proSts, BigDecimal proAm1, BigDecimal proAm2,
			BigDecimal proAm3, BigDecimal proPam, BigDecimal proAre,
			BigDecimal proPsi, BigDecimal proPsf, BigDecimal proTaj,
			BigDecimal proCsm, BigDecimal proCld) {
		this.id = id;
		this.empresa = empresa;
		this.fornecedor = fornecedor;
		this.linhaproducao = linhaproducao;
		this.modelo = modelo;
		this.tributacao = tributacao;
		this.proCcp = proCcp;
		this.proTip = proTip;
		this.proNom = proNom;
		this.proPsb = proPsb;
		this.proPsl = proPsl;
		this.proIpi = proIpi;
		this.proEtq = proEtq;
		this.proCom = proCom;
		this.proTer = proTer;
		this.proSit = proSit;
		this.proG01 = proG01;
		this.proG02 = proG02;
		this.proG03 = proG03;
		this.proG04 = proG04;
		this.proG05 = proG05;
		this.proG06 = proG06;
		this.proG07 = proG07;
		this.proG08 = proG08;
		this.proG09 = proG09;
		this.proG10 = proG10;
		this.proG11 = proG11;
		this.proG12 = proG12;
		this.proG13 = proG13;
		this.proG14 = proG14;
		this.proVra = proVra;
		this.proUat = proUat;
		this.proLar = proLar;
		this.proDtc = proDtc;
		this.proCls = proCls;
		this.proIft = proIft;
		this.proOri = proOri;
		this.proPma = proPma;
		this.proFgt = proFgt;
		this.proFrd = proFrd;
		this.proCds = proCds;
		this.proTpi = proTpi;
		this.proPrv = proPrv;
		this.proPcf = proPcf;
		this.proSts = proSts;
		this.proAm1 = proAm1;
		this.proAm2 = proAm2;
		this.proAm3 = proAm3;
		this.proPam = proPam;
		this.proAre = proAre;
		this.proPsi = proPsi;
		this.proPsf = proPsf;
		this.proTaj = proTaj;
		this.proCsm = proCsm;
		this.proCld = proCld;
	}

	public Produto(ProdutoId id, Artigo artigo, Colecao colecao, Cor cor,
			Empresa empresa, Fornecedor fornecedor, Grade grade, Grupo grupo,
			Linhaproducao linhaproducao, Marca marca,
			Medidalavacao medidalavacao, Modelo modelo, Tributacao tributacao,
			String proCcp, String proEan, String proTip, String proNom,
			String proApe, String proNn1, String proNn2, String proEsp,
			String proNat, String proUnd, BigDecimal proPsb, BigDecimal proPsl,
			Integer proCla, String proClf, BigDecimal proIpi, String proEtq,
			String proCom, String proTer, String proSit, String proG01, String proG02,
			String proG03, String proG04, String proG05, String proG06, String proG07,
			String proG08, String proG09, String proG10, String proG11, String proG12,
			String proG13, String proG14, Integer proSgr, Integer proVra,
			Integer proDgc, String proCps, Integer proUat, String proImg,
			String proTpp, String proObs, BigDecimal proLar, Date proDtc,
			Integer proEtl, String proCls, String proIft, String proOri,
			String proNcm, String proExt, BigDecimal proPma, Integer proEtc,
			BigDecimal proFgt, BigDecimal proFrd, String proFcr, String proFob,
			String proCds, String proTpi, BigDecimal proPrv, Integer proMlt,
			String proFcr1, String proFcr2, BigDecimal proPcf, String proNom1,
			Integer proEtf, String proIma, String proSts, String proOpe,
			String proFci, BigDecimal proAm1, BigDecimal proAm2,
			BigDecimal proAm3, BigDecimal proPam, BigDecimal proAre,
			BigDecimal proPsi, BigDecimal proPsf, BigDecimal proTaj,
			BigDecimal proCsm, BigDecimal proCld,
			Set<Estoqueminimo> estoqueminimos,
			Set<Produtomateriaprima> produtomateriaprimasForFkPrmMtp,
			Set<Codigobarras> codigobarrases,
			Set<Pcpordemproducao> pcpordemproducaos,
			Set<Produtomateriaprima> produtomateriaprimasForFkPrmPro,
			Set<Produtosilk> produtosilks, Set<Balancoproduto> balancoprodutos,
			Set<Grupomateriaprima> grupomateriaprimas,
			Set<Empresapautaproduto> empresapautaprodutos,
			Set<Pedidoitens> pedidoitenses, Set<Produtofilial> produtofilials,
			Set<Produtofornecedor> produtofornecedors,
			Set<Produtolocal> produtolocals,
			Set<Bloqueioconsignado> bloqueioconsignados,
			Set<Operacaooperadormovimento> operacaooperadormovimentos,
			Set<Operacaopautaproduto> operacaopautaprodutos,
			Set<Codigoepc> codigoepcs,
			Set<Pedidocompraitens> pedidocompraitenses,
			Set<Empresapautaprodutotamanho> empresapautaprodutotamanhos,
			Set<Remessaproducaosimulacaoitens> remessaproducaosimulacaoitenses,
			Set<Mapacorte> mapacortes) {
		this.id = id;
		this.artigo = artigo;
		this.colecao = colecao;
		this.cor = cor;
		this.empresa = empresa;
		this.fornecedor = fornecedor;
		this.grade = grade;
		this.grupo = grupo;
		this.linhaproducao = linhaproducao;
		this.marca = marca;
		this.medidalavacao = medidalavacao;
		this.modelo = modelo;
		this.tributacao = tributacao;
		this.proCcp = proCcp;
		this.proEan = proEan;
		this.proTip = proTip;
		this.proNom = proNom;
		this.proApe = proApe;
		this.proNn1 = proNn1;
		this.proNn2 = proNn2;
		this.proEsp = proEsp;
		this.proNat = proNat;
		this.proUnd = proUnd;
		this.proPsb = proPsb;
		this.proPsl = proPsl;
		this.proCla = proCla;
		this.proClf = proClf;
		this.proIpi = proIpi;
		this.proEtq = proEtq;
		this.proCom = proCom;
		this.proTer = proTer;
		this.proSit = proSit;
		this.proG01 = proG01;
		this.proG02 = proG02;
		this.proG03 = proG03;
		this.proG04 = proG04;
		this.proG05 = proG05;
		this.proG06 = proG06;
		this.proG07 = proG07;
		this.proG08 = proG08;
		this.proG09 = proG09;
		this.proG10 = proG10;
		this.proG11 = proG11;
		this.proG12 = proG12;
		this.proG13 = proG13;
		this.proG14 = proG14;
		this.proSgr = proSgr;
		this.proVra = proVra;
		this.proDgc = proDgc;
		this.proCps = proCps;
		this.proUat = proUat;
		this.proImg = proImg;
		this.proTpp = proTpp;
		this.proObs = proObs;
		this.proLar = proLar;
		this.proDtc = proDtc;
		this.proEtl = proEtl;
		this.proCls = proCls;
		this.proIft = proIft;
		this.proOri = proOri;
		this.proNcm = proNcm;
		this.proExt = proExt;
		this.proPma = proPma;
		this.proEtc = proEtc;
		this.proFgt = proFgt;
		this.proFrd = proFrd;
		this.proFcr = proFcr;
		this.proFob = proFob;
		this.proCds = proCds;
		this.proTpi = proTpi;
		this.proPrv = proPrv;
		this.proMlt = proMlt;
		this.proFcr1 = proFcr1;
		this.proFcr2 = proFcr2;
		this.proPcf = proPcf;
		this.proNom1 = proNom1;
		this.proEtf = proEtf;
		this.proIma = proIma;
		this.proSts = proSts;
		this.proOpe = proOpe;
		this.proFci = proFci;
		this.proAm1 = proAm1;
		this.proAm2 = proAm2;
		this.proAm3 = proAm3;
		this.proPam = proPam;
		this.proAre = proAre;
		this.proPsi = proPsi;
		this.proPsf = proPsf;
		this.proTaj = proTaj;
		this.proCsm = proCsm;
		this.proCld = proCld;
		this.estoqueminimos = estoqueminimos;
		this.produtomateriaprimasForFkPrmMtp = produtomateriaprimasForFkPrmMtp;
		this.codigobarrases = codigobarrases;
		this.pcpordemproducaos = pcpordemproducaos;
		this.produtomateriaprimasForFkPrmPro = produtomateriaprimasForFkPrmPro;
		this.produtosilks = produtosilks;
		this.balancoprodutos = balancoprodutos;
		this.grupomateriaprimas = grupomateriaprimas;
		this.empresapautaprodutos = empresapautaprodutos;
		this.pedidoitenses = pedidoitenses;
		this.produtofilials = produtofilials;
		this.produtofornecedors = produtofornecedors;
		this.produtolocals = produtolocals;
		this.bloqueioconsignados = bloqueioconsignados;
		this.operacaooperadormovimentos = operacaooperadormovimentos;
		this.operacaopautaprodutos = operacaopautaprodutos;
		this.codigoepcs = codigoepcs;
		this.pedidocompraitenses = pedidocompraitenses;
		this.empresapautaprodutotamanhos = empresapautaprodutotamanhos;
		this.remessaproducaosimulacaoitenses = remessaproducaosimulacaoitenses;
		this.mapacortes = mapacortes;
	}*/

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "proEmp", column = @Column(name = "PRO_EMP", nullable = false)),
			@AttributeOverride(name = "proCod", column = @Column(name = "PRO_COD", nullable = false)) })
	public ProdutoId getId() {
		return this.id;
	}

	public void setId(ProdutoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRO_ATG")
	public Artigo getArtigo() {
		return this.artigo;
	}

	public void setArtigo(Artigo artigo) {
		this.artigo = artigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRO_CLO")
	public Colecao getColecao() {
		return this.colecao;
	}

	public void setColecao(Colecao colecao) {
		this.colecao = colecao;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PRO_COR")
	public Cor getCor() {
		return this.cor;
	}

	public void setCor(Cor cor) {
		this.cor = cor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRO_EMP", nullable = false, insertable = false, updatable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PRO_EMP", referencedColumnName = "FOR_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PRO_FOR", referencedColumnName = "FOR_COL", nullable = false, insertable = false, updatable = false) })
	public Fornecedor getFornecedor() {
		return this.fornecedor;
	}

	public void setFornecedor(Fornecedor fornecedor) {
		this.fornecedor = fornecedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRO_GRD")
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRO_GRU")
	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}
/*
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PRO_EMP", referencedColumnName = "LNP_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PRO_LNP", referencedColumnName = "LNP_COD", insertable = false, updatable = false) })
	public Linhaproducao getLinhaproducao() {
		return this.linhaproducao;
	}

	public void setLinhaproducao(Linhaproducao linhaproducao) {
		this.linhaproducao = linhaproducao;
	}*/

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRO_MAR")
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRO_MEL")
	public Medidalavacao getMedidalavacao() {
		return this.medidalavacao;
	}

	public void setMedidalavacao(Medidalavacao medidalavacao) {
		this.medidalavacao = medidalavacao;
	}*/

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PRO_EMP", referencedColumnName = "MDL_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PRO_MDL", referencedColumnName = "MDL_COD", nullable = false, insertable = false, updatable = false) })
	public Modelo getModelo() {
		return this.modelo;
	}

	public void setModelo(Modelo modelo) {
		this.modelo = modelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PRO_EMP", referencedColumnName = "TRI_EMP", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PRO_TRI", referencedColumnName = "TRI_COD", nullable = false, insertable = false, updatable = false) })
	public Tributacao getTributacao() {
		return this.tributacao;
	}

	public void setTributacao(Tributacao tributacao) {
		this.tributacao = tributacao;
	}

	@Column(name = "PRO_CCP", nullable = false, length = 14)
	public String getProCcp() {
		return this.proCcp;
	}

	public void setProCcp(String proCcp) {
		this.proCcp = proCcp;
	}

	@Column(name = "PRO_EAN", length = 14)
	public String getProEan() {
		return this.proEan;
	}

	public void setProEan(String proEan) {
		this.proEan = proEan;
	}

	@Column(name = "PRO_TIP", nullable = false, length = 1)
	public String getProTip() {
		return this.proTip;
	}

	public void setProTip(String proTip) {
		this.proTip = proTip;
	}

	@Column(name = "PRO_NOM", nullable = false, length = 40)
	public String getProNom() {
		return this.proNom;
	}

	public void setProNom(String proNom) {
		this.proNom = proNom;
	}

	@Column(name = "PRO_APE", length = 15)
	public String getProApe() {
		return this.proApe;
	}

	public void setProApe(String proApe) {
		this.proApe = proApe;
	}

	@Column(name = "PRO_NN1", length = 60)
	public String getProNn1() {
		return this.proNn1;
	}

	public void setProNn1(String proNn1) {
		this.proNn1 = proNn1;
	}

	@Column(name = "PRO_NN2", length = 60)
	public String getProNn2() {
		return this.proNn2;
	}

	public void setProNn2(String proNn2) {
		this.proNn2 = proNn2;
	}

	@Column(name = "PRO_ESP", length = 10)
	public String getProEsp() {
		return this.proEsp;
	}

	public void setProEsp(String proEsp) {
		this.proEsp = proEsp;
	}

	@Column(name = "PRO_NAT", length = 15)
	public String getProNat() {
		return this.proNat;
	}

	public void setProNat(String proNat) {
		this.proNat = proNat;
	}

	@Column(name = "PRO_UND", length = 3)
	public String getProUnd() {
		return this.proUnd;
	}

	public void setProUnd(String proUnd) {
		this.proUnd = proUnd;
	}

	@Column(name = "PRO_PSB", nullable = false, precision = 8, scale = 3)
	public BigDecimal getProPsb() {
		return this.proPsb;
	}

	public void setProPsb(BigDecimal proPsb) {
		this.proPsb = proPsb;
	}

	@Column(name = "PRO_PSL", nullable = false, precision = 8, scale = 3)
	public BigDecimal getProPsl() {
		return this.proPsl;
	}

	public void setProPsl(BigDecimal proPsl) {
		this.proPsl = proPsl;
	}

	@Column(name = "PRO_CLA")
	public Integer getProCla() {
		return this.proCla;
	}

	public void setProCla(Integer proCla) {
		this.proCla = proCla;
	}

	@Column(name = "PRO_CLF", length = 3)
	public String getProClf() {
		return this.proClf;
	}

	public void setProClf(String proClf) {
		this.proClf = proClf;
	}

	@Column(name = "PRO_IPI", nullable = false, precision = 6)
	public BigDecimal getProIpi() {
		return this.proIpi;
	}

	public void setProIpi(BigDecimal proIpi) {
		this.proIpi = proIpi;
	}

	@Column(name = "PRO_ETQ", nullable = false, length = 1)
	public String getProEtq() {
		return this.proEtq;
	}

	public void setProEtq(String proEtq) {
		this.proEtq = proEtq;
	}

	@Column(name = "PRO_COM", nullable = false, length = 1)
	public String getProCom() {
		return this.proCom;
	}

	public void setProCom(String proCom) {
		this.proCom = proCom;
	}

	@Column(name = "PRO_TER", nullable = false, length = 1)
	public String getProTer() {
		return this.proTer;
	}

	public void setProTer(String proTer) {
		this.proTer = proTer;
	}

	@Column(name = "PRO_SIT", nullable = false, length = 1)
	public String getProSit() {
		return this.proSit;
	}

	public void setProSit(String proSit) {
		this.proSit = proSit;
	}

	@Column(name = "PRO_G01", nullable = false, length = 1)
	public String getProG01() {
		return this.proG01;
	}

	public void setProG01(String proG01) {
		this.proG01 = proG01;
	}

	@Column(name = "PRO_G02", nullable = false, length = 1)
	public String getProG02() {
		return this.proG02;
	}

	public void setProG02(String proG02) {
		this.proG02 = proG02;
	}

	@Column(name = "PRO_G03", nullable = false, length = 1)
	public String getProG03() {
		return this.proG03;
	}

	public void setProG03(String proG03) {
		this.proG03 = proG03;
	}

	@Column(name = "PRO_G04", nullable = false, length = 1)
	public String getProG04() {
		return this.proG04;
	}

	public void setProG04(String proG04) {
		this.proG04 = proG04;
	}

	@Column(name = "PRO_G05", nullable = false, length = 1)
	public String getProG05() {
		return this.proG05;
	}

	public void setProG05(String proG05) {
		this.proG05 = proG05;
	}

	@Column(name = "PRO_G06", nullable = false, length = 1)
	public String getProG06() {
		return this.proG06;
	}

	public void setProG06(String proG06) {
		this.proG06 = proG06;
	}

	@Column(name = "PRO_G07", nullable = false, length = 1)
	public String getProG07() {
		return this.proG07;
	}

	public void setProG07(String proG07) {
		this.proG07 = proG07;
	}

	@Column(name = "PRO_G08", nullable = false, length = 1)
	public String getProG08() {
		return this.proG08;
	}

	public void setProG08(String proG08) {
		this.proG08 = proG08;
	}

	@Column(name = "PRO_G09", nullable = false, length = 1)
	public String getProG09() {
		return this.proG09;
	}

	public void setProG09(String proG09) {
		this.proG09 = proG09;
	}

	@Column(name = "PRO_G10", nullable = false, length = 1)
	public String getProG10() {
		return this.proG10;
	}

	public void setProG10(String proG10) {
		this.proG10 = proG10;
	}

	@Column(name = "PRO_G11", nullable = false, length = 1)
	public String getProG11() {
		return this.proG11;
	}

	public void setProG11(String proG11) {
		this.proG11 = proG11;
	}

	@Column(name = "PRO_G12", nullable = false, length = 1)
	public String getProG12() {
		return this.proG12;
	}

	public void setProG12(String proG12) {
		this.proG12 = proG12;
	}

	@Column(name = "PRO_G13", nullable = false, length = 1)
	public String getProG13() {
		return this.proG13;
	}

	public void setProG13(String proG13) {
		this.proG13 = proG13;
	}

	@Column(name = "PRO_G14", nullable = false, length = 1)
	public String getProG14() {
		return this.proG14;
	}

	public void setProG14(String proG14) {
		this.proG14 = proG14;
	}

	@Column(name = "PRO_SGR")
	public Integer getProSgr() {
		return this.proSgr;
	}

	public void setProSgr(Integer proSgr) {
		this.proSgr = proSgr;
	}

	@Column(name = "PRO_VRA", nullable = false)
	public Integer getProVra() {
		return this.proVra;
	}

	public void setProVra(Integer proVra) {
		this.proVra = proVra;
	}

	@Column(name = "PRO_DGC")
	public Integer getProDgc() {
		return this.proDgc;
	}

	public void setProDgc(Integer proDgc) {
		this.proDgc = proDgc;
	}

	@Column(name = "PRO_CPS", length = 40)
	public String getProCps() {
		return this.proCps;
	}

	public void setProCps(String proCps) {
		this.proCps = proCps;
	}

	@Column(name = "PRO_UAT", nullable = false)
	public Integer getProUat() {
		return this.proUat;
	}

	public void setProUat(Integer proUat) {
		this.proUat = proUat;
	}

	@Column(name = "PRO_IMG", length = 5)
	public String getProImg() {
		return this.proImg;
	}

	public void setProImg(String proImg) {
		this.proImg = proImg;
	}

	@Column(name = "PRO_TPP", length = 3)
	public String getProTpp() {
		return this.proTpp;
	}

	public void setProTpp(String proTpp) {
		this.proTpp = proTpp;
	}

	@Column(name = "PRO_OBS", length = 0)
	public String getProObs() {
		return this.proObs;
	}

	public void setProObs(String proObs) {
		this.proObs = proObs;
	}

	@Column(name = "PRO_LAR", nullable = false, precision = 6)
	public BigDecimal getProLar() {
		return this.proLar;
	}

	public void setProLar(BigDecimal proLar) {
		this.proLar = proLar;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PRO_DTC", nullable = false, length = 10)
	public Date getProDtc() {
		return this.proDtc;
	}

	public void setProDtc(Date proDtc) {
		this.proDtc = proDtc;
	}

	@Column(name = "PRO_ETL")
	public Integer getProEtl() {
		return this.proEtl;
	}

	public void setProEtl(Integer proEtl) {
		this.proEtl = proEtl;
	}

	@Column(name = "PRO_CLS", nullable = false, length = 1)
	public String getProCls() {
		return this.proCls;
	}

	public void setProCls(String proCls) {
		this.proCls = proCls;
	}

	@Column(name = "PRO_IFT", nullable = false, length = 1)
	public String getProIft() {
		return this.proIft;
	}

	public void setProIft(String proIft) {
		this.proIft = proIft;
	}

	@Column(name = "PRO_ORI", nullable = false, length = 1)
	public String getProOri() {
		return this.proOri;
	}

	public void setProOri(String proOri) {
		this.proOri = proOri;
	}

	@Column(name = "PRO_NCM", length = 8)
	public String getProNcm() {
		return this.proNcm;
	}

	public void setProNcm(String proNcm) {
		this.proNcm = proNcm;
	}

	@Column(name = "PRO_EXT", length = 3)
	public String getProExt() {
		return this.proExt;
	}

	public void setProExt(String proExt) {
		this.proExt = proExt;
	}

	@Column(name = "PRO_PMA", nullable = false, precision = 6)
	public BigDecimal getProPma() {
		return this.proPma;
	}

	public void setProPma(BigDecimal proPma) {
		this.proPma = proPma;
	}

	@Column(name = "PRO_ETC")
	public Integer getProEtc() {
		return this.proEtc;
	}

	public void setProEtc(Integer proEtc) {
		this.proEtc = proEtc;
	}

	@Column(name = "PRO_FGT", nullable = false, precision = 18, scale = 5)
	public BigDecimal getProFgt() {
		return this.proFgt;
	}

	public void setProFgt(BigDecimal proFgt) {
		this.proFgt = proFgt;
	}

	@Column(name = "PRO_FRD", nullable = false, precision = 18, scale = 5)
	public BigDecimal getProFrd() {
		return this.proFrd;
	}

	public void setProFrd(BigDecimal proFrd) {
		this.proFrd = proFrd;
	}

	@Column(name = "PRO_FCR", length = 60)
	public String getProFcr() {
		return this.proFcr;
	}

	public void setProFcr(String proFcr) {
		this.proFcr = proFcr;
	}

	@Column(name = "PRO_FOB", length = 60)
	public String getProFob() {
		return this.proFob;
	}

	public void setProFob(String proFob) {
		this.proFob = proFob;
	}

	@Column(name = "PRO_CDS", nullable = false, length = 4)
	public String getProCds() {
		return this.proCds;
	}

	public void setProCds(String proCds) {
		this.proCds = proCds;
	}

	@Column(name = "PRO_TPI", nullable = false, length = 2)
	public String getProTpi() {
		return this.proTpi;
	}

	public void setProTpi(String proTpi) {
		this.proTpi = proTpi;
	}

	@Column(name = "PRO_PRV", nullable = false, precision = 18, scale = 5)
	public BigDecimal getProPrv() {
		return this.proPrv;
	}

	public void setProPrv(BigDecimal proPrv) {
		this.proPrv = proPrv;
	}

	@Column(name = "PRO_MLT")
	public Integer getProMlt() {
		return this.proMlt;
	}

	public void setProMlt(Integer proMlt) {
		this.proMlt = proMlt;
	}

	@Column(name = "PRO_FCR1", length = 60)
	public String getProFcr1() {
		return this.proFcr1;
	}

	public void setProFcr1(String proFcr1) {
		this.proFcr1 = proFcr1;
	}

	@Column(name = "PRO_FCR2", length = 60)
	public String getProFcr2() {
		return this.proFcr2;
	}

	public void setProFcr2(String proFcr2) {
		this.proFcr2 = proFcr2;
	}

	@Column(name = "PRO_PCF", nullable = false, precision = 6)
	public BigDecimal getProPcf() {
		return this.proPcf;
	}

	public void setProPcf(BigDecimal proPcf) {
		this.proPcf = proPcf;
	}

	@Column(name = "PRO_NOM1", length = 10)
	public String getProNom1() {
		return this.proNom1;
	}

	public void setProNom1(String proNom1) {
		this.proNom1 = proNom1;
	}

	@Column(name = "PRO_ETF")
	public Integer getProEtf() {
		return this.proEtf;
	}

	public void setProEtf(Integer proEtf) {
		this.proEtf = proEtf;
	}

	@Column(name = "PRO_IMA", length = 5)
	public String getProIma() {
		return this.proIma;
	}

	public void setProIma(String proIma) {
		this.proIma = proIma;
	}

	@Column(name = "PRO_STS", nullable = false, length = 1)
	public String getProSts() {
		return this.proSts;
	}

	public void setProSts(String proSts) {
		this.proSts = proSts;
	}

	@Column(name = "PRO_OPE", length = 60)
	public String getProOpe() {
		return this.proOpe;
	}

	public void setProOpe(String proOpe) {
		this.proOpe = proOpe;
	}

	@Column(name = "PRO_FCI", length = 36)
	public String getProFci() {
		return this.proFci;
	}

	public void setProFci(String proFci) {
		this.proFci = proFci;
	}

	@Column(name = "PRO_AM1", nullable = false, precision = 15, scale = 3)
	public BigDecimal getProAm1() {
		return this.proAm1;
	}

	public void setProAm1(BigDecimal proAm1) {
		this.proAm1 = proAm1;
	}

	@Column(name = "PRO_AM2", nullable = false, precision = 15, scale = 3)
	public BigDecimal getProAm2() {
		return this.proAm2;
	}

	public void setProAm2(BigDecimal proAm2) {
		this.proAm2 = proAm2;
	}

	@Column(name = "PRO_AM3", nullable = false, precision = 15, scale = 3)
	public BigDecimal getProAm3() {
		return this.proAm3;
	}

	public void setProAm3(BigDecimal proAm3) {
		this.proAm3 = proAm3;
	}

	@Column(name = "PRO_PAM", nullable = false, precision = 15, scale = 3)
	public BigDecimal getProPam() {
		return this.proPam;
	}

	public void setProPam(BigDecimal proPam) {
		this.proPam = proPam;
	}

	@Column(name = "PRO_ARE", nullable = false, precision = 15, scale = 4)
	public BigDecimal getProAre() {
		return this.proAre;
	}

	public void setProAre(BigDecimal proAre) {
		this.proAre = proAre;
	}

	@Column(name = "PRO_PSI", nullable = false, precision = 15, scale = 3)
	public BigDecimal getProPsi() {
		return this.proPsi;
	}

	public void setProPsi(BigDecimal proPsi) {
		this.proPsi = proPsi;
	}

	@Column(name = "PRO_PSF", nullable = false, precision = 15, scale = 3)
	public BigDecimal getProPsf() {
		return this.proPsf;
	}

	public void setProPsf(BigDecimal proPsf) {
		this.proPsf = proPsf;
	}

	@Column(name = "PRO_TAJ", nullable = false, precision = 15)
	public BigDecimal getProTaj() {
		return this.proTaj;
	}

	public void setProTaj(BigDecimal proTaj) {
		this.proTaj = proTaj;
	}

	@Column(name = "PRO_CSM", nullable = false, precision = 15)
	public BigDecimal getProCsm() {
		return this.proCsm;
	}

	public void setProCsm(BigDecimal proCsm) {
		this.proCsm = proCsm;
	}

	@Column(name = "PRO_CLD", nullable = false, precision = 15, scale = 3)
	public BigDecimal getProCld() {
		return this.proCld;
	}

	public void setProCld(BigDecimal proCld) {
		this.proCld = proCld;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Estoqueminimo> getEstoqueminimos() {
		return this.estoqueminimos;
	}

	public void setEstoqueminimos(Set<Estoqueminimo> estoqueminimos) {
		this.estoqueminimos = estoqueminimos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produtoByFkPrmMtp")
	public Set<Produtomateriaprima> getProdutomateriaprimasForFkPrmMtp() {
		return this.produtomateriaprimasForFkPrmMtp;
	}

	public void setProdutomateriaprimasForFkPrmMtp(
			Set<Produtomateriaprima> produtomateriaprimasForFkPrmMtp) {
		this.produtomateriaprimasForFkPrmMtp = produtomateriaprimasForFkPrmMtp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Codigobarras> getCodigobarrases() {
		return this.codigobarrases;
	}

	public void setCodigobarrases(Set<Codigobarras> codigobarrases) {
		this.codigobarrases = codigobarrases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Pcpordemproducao> getPcpordemproducaos() {
		return this.pcpordemproducaos;
	}

	public void setPcpordemproducaos(Set<Pcpordemproducao> pcpordemproducaos) {
		this.pcpordemproducaos = pcpordemproducaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produtoByFkPrmPro")
	public Set<Produtomateriaprima> getProdutomateriaprimasForFkPrmPro() {
		return this.produtomateriaprimasForFkPrmPro;
	}

	public void setProdutomateriaprimasForFkPrmPro(
			Set<Produtomateriaprima> produtomateriaprimasForFkPrmPro) {
		this.produtomateriaprimasForFkPrmPro = produtomateriaprimasForFkPrmPro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Produtosilk> getProdutosilks() {
		return this.produtosilks;
	}

	public void setProdutosilks(Set<Produtosilk> produtosilks) {
		this.produtosilks = produtosilks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Balancoproduto> getBalancoprodutos() {
		return this.balancoprodutos;
	}

	public void setBalancoprodutos(Set<Balancoproduto> balancoprodutos) {
		this.balancoprodutos = balancoprodutos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Grupomateriaprima> getGrupomateriaprimas() {
		return this.grupomateriaprimas;
	}

	public void setGrupomateriaprimas(Set<Grupomateriaprima> grupomateriaprimas) {
		this.grupomateriaprimas = grupomateriaprimas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Empresapautaproduto> getEmpresapautaprodutos() {
		return this.empresapautaprodutos;
	}

	public void setEmpresapautaprodutos(
			Set<Empresapautaproduto> empresapautaprodutos) {
		this.empresapautaprodutos = empresapautaprodutos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Pedidoitens> getPedidoitenses() {
		return this.pedidoitenses;
	}

	public void setPedidoitenses(Set<Pedidoitens> pedidoitenses) {
		this.pedidoitenses = pedidoitenses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Produtofilial> getProdutofilials() {
		return this.produtofilials;
	}

	public void setProdutofilials(Set<Produtofilial> produtofilials) {
		this.produtofilials = produtofilials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Produtofornecedor> getProdutofornecedors() {
		return this.produtofornecedors;
	}

	public void setProdutofornecedors(Set<Produtofornecedor> produtofornecedors) {
		this.produtofornecedors = produtofornecedors;
	}



	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Bloqueioconsignado> getBloqueioconsignados() {
		return this.bloqueioconsignados;
	}

	public void setBloqueioconsignados(
			Set<Bloqueioconsignado> bloqueioconsignados) {
		this.bloqueioconsignados = bloqueioconsignados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Operacaooperadormovimento> getOperacaooperadormovimentos() {
		return this.operacaooperadormovimentos;
	}

	public void setOperacaooperadormovimentos(
			Set<Operacaooperadormovimento> operacaooperadormovimentos) {
		this.operacaooperadormovimentos = operacaooperadormovimentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Operacaopautaproduto> getOperacaopautaprodutos() {
		return this.operacaopautaprodutos;
	}

	public void setOperacaopautaprodutos(
			Set<Operacaopautaproduto> operacaopautaprodutos) {
		this.operacaopautaprodutos = operacaopautaprodutos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Codigoepc> getCodigoepcs() {
		return this.codigoepcs;
	}

	public void setCodigoepcs(Set<Codigoepc> codigoepcs) {
		this.codigoepcs = codigoepcs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Pedidocompraitens> getPedidocompraitenses() {
		return this.pedidocompraitenses;
	}

	public void setPedidocompraitenses(
			Set<Pedidocompraitens> pedidocompraitenses) {
		this.pedidocompraitenses = pedidocompraitenses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Empresapautaprodutotamanho> getEmpresapautaprodutotamanhos() {
		return this.empresapautaprodutotamanhos;
	}

	public void setEmpresapautaprodutotamanhos(
			Set<Empresapautaprodutotamanho> empresapautaprodutotamanhos) {
		this.empresapautaprodutotamanhos = empresapautaprodutotamanhos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Remessaproducaosimulacaoitens> getRemessaproducaosimulacaoitenses() {
		return this.remessaproducaosimulacaoitenses;
	}

	public void setRemessaproducaosimulacaoitenses(
			Set<Remessaproducaosimulacaoitens> remessaproducaosimulacaoitenses) {
		this.remessaproducaosimulacaoitenses = remessaproducaosimulacaoitenses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<Mapacorte> getMapacortes() {
		return this.mapacortes;
	}

	public void setMapacortes(Set<Mapacorte> mapacortes) {
		this.mapacortes = mapacortes;
	}*/
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produto")
	public Set<ProdutoLocal> getProdutoLocal() {
		return this.produtoLocal;
	}

	public void setProdutoLocal(Set<ProdutoLocal> produtoLocal) {
		this.produtoLocal = produtoLocal;
	}

}
