package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProdutoId generated by hbm2java
 */
@Embeddable
public class ProdutoId implements java.io.Serializable {

	private static final long serialVersionUID = -1584268264833014269L;
	private Integer proEmp;
	private Integer proCod;

	public ProdutoId() {
	}

	public ProdutoId(Integer proEmp, Integer proCod) {
		this.proEmp = proEmp;
		this.proCod = proCod;
	}

	@Column(name = "PRO_EMP", nullable = false)
	public Integer getProEmp() {
		return this.proEmp;
	}

	public void setProEmp(Integer proEmp) {
		this.proEmp = proEmp;
	}

	@Column(name = "PRO_COD", nullable = false)
	public Integer getProCod() {
		return this.proCod;
	}

	public void setProCod(Integer proCod) {
		this.proCod = proCod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProdutoId))
			return false;
		ProdutoId castOther = (ProdutoId) other;

		return (this.getProEmp() == castOther.getProEmp())
				&& (this.getProCod() == castOther.getProCod());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getProEmp();
		result = 37 * result + this.getProCod();
		return result;
	}

}
