package br.ufsc.creche.model;

// Generated 19/03/2015 10:22:22 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TelaWebId generated by hbm2java
 */
@Embeddable
public class TelaWebId implements java.io.Serializable {

	private static final long serialVersionUID = -7937221372338681856L;
	private String tlwFrm;
	private String tlwCpo;

	public TelaWebId() {
	}

	public TelaWebId(String tlwFrm, String tlwCpo) {
		this.tlwFrm = tlwFrm;
		this.tlwCpo = tlwCpo;
	}

	@Column(name = "TLW_FRM", nullable = false, length = 40)
	public String getTlwFrm() {
		return this.tlwFrm;
	}

	public void setTlwFrm(String tlwFrm) {
		this.tlwFrm = tlwFrm;
	}

	@Column(name = "TLW_CPO", nullable = false, length = 20)
	public String getTlwCpo() {
		return this.tlwCpo;
	}

	public void setTlwCpo(String tlwCpo) {
		this.tlwCpo = tlwCpo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TelaWebId))
			return false;
		TelaWebId castOther = (TelaWebId) other;

		return ((this.getTlwFrm() == castOther.getTlwFrm()) || (this
				.getTlwFrm() != null && castOther.getTlwFrm() != null && this
				.getTlwFrm().equals(castOther.getTlwFrm())))
				&& ((this.getTlwCpo() == castOther.getTlwCpo()) || (this
						.getTlwCpo() != null && castOther.getTlwCpo() != null && this
						.getTlwCpo().equals(castOther.getTlwCpo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTlwFrm() == null ? 0 : this.getTlwFrm().hashCode());
		result = 37 * result
				+ (getTlwCpo() == null ? 0 : this.getTlwCpo().hashCode());
		return result;
	}

}
