package br.ufsc.creche.model;

// Generated 22/12/2014 15:06:02 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tributacao generated by hbm2java
 */
@Entity
@Table(name = "TRIBUTACAO")
public class Tributacao implements java.io.Serializable {

	private static final long serialVersionUID = 3624366906492433948L;
	private TributacaoId id;
	private Empresa empresa;
	private String triDes;
	private String triSti;
	private BigDecimal triIps;
	private BigDecimal triIpv;
	private String triStp;
	private BigDecimal triPis;
	private BigDecimal triPvs;
	private String triStc;
	private BigDecimal triCfs;
	private BigDecimal triCvs;
	private String triEtp;
	private BigDecimal triPie;
	private BigDecimal triPve;
	private String triEtc;
	private BigDecimal triCfe;
	private BigDecimal triCve;
	private String triEti;
	private BigDecimal triIpe;
	private BigDecimal triIve;
	private Set<Modelo> modelos = new HashSet<Modelo>(0);
	private Set<Produto> produtos = new HashSet<Produto>(0);
//	private Set<Tributacaouf> tributacaoufs = new HashSet<Tributacaouf>(0);

	public Tributacao() {
	}

	public Tributacao(TributacaoId id, Empresa empresa, String triDes,
			BigDecimal triIps, BigDecimal triIpv, String triStp,
			BigDecimal triPis, BigDecimal triPvs, String triStc,
			BigDecimal triCfs, BigDecimal triCvs, String triEtp,
			BigDecimal triPie, BigDecimal triPve, String triEtc,
			BigDecimal triCfe, BigDecimal triCve, BigDecimal triIpe,
			BigDecimal triIve) {
		this.id = id;
		this.empresa = empresa;
		this.triDes = triDes;
		this.triIps = triIps;
		this.triIpv = triIpv;
		this.triStp = triStp;
		this.triPis = triPis;
		this.triPvs = triPvs;
		this.triStc = triStc;
		this.triCfs = triCfs;
		this.triCvs = triCvs;
		this.triEtp = triEtp;
		this.triPie = triPie;
		this.triPve = triPve;
		this.triEtc = triEtc;
		this.triCfe = triCfe;
		this.triCve = triCve;
		this.triIpe = triIpe;
		this.triIve = triIve;
	}

	/* public Tributacao(TributacaoId id, Empresa empresa, String triDes,
			String triSti, BigDecimal triIps, BigDecimal triIpv, String triStp,
			BigDecimal triPis, BigDecimal triPvs, String triStc,
			BigDecimal triCfs, BigDecimal triCvs, String triEtp,
			BigDecimal triPie, BigDecimal triPve, String triEtc,
			BigDecimal triCfe, BigDecimal triCve, String triEti,
			BigDecimal triIpe, BigDecimal triIve, Set<Modelo> modelos,
			Set<Produto> produtos, Set<Tributacaouf> tributacaoufs) {
		this.id = id;
		this.empresa = empresa;
		this.triDes = triDes;
		this.triSti = triSti;
		this.triIps = triIps;
		this.triIpv = triIpv;
		this.triStp = triStp;
		this.triPis = triPis;
		this.triPvs = triPvs;
		this.triStc = triStc;
		this.triCfs = triCfs;
		this.triCvs = triCvs;
		this.triEtp = triEtp;
		this.triPie = triPie;
		this.triPve = triPve;
		this.triEtc = triEtc;
		this.triCfe = triCfe;
		this.triCve = triCve;
		this.triEti = triEti;
		this.triIpe = triIpe;
		this.triIve = triIve;
		this.modelos = modelos;
		this.produtos = produtos;
		this.tributacaoufs = tributacaoufs;
	} */

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "triEmp", column = @Column(name = "TRI_EMP", nullable = false)),
			@AttributeOverride(name = "triCod", column = @Column(name = "TRI_COD", nullable = false)) })
	public TributacaoId getId() {
		return this.id;
	}

	public void setId(TributacaoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRI_EMP", nullable = false, insertable = false, updatable = false)
	public Empresa getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(Empresa empresa) {
		this.empresa = empresa;
	}

	@Column(name = "TRI_DES", nullable = false, length = 30)
	public String getTriDes() {
		return this.triDes;
	}

	public void setTriDes(String triDes) {
		this.triDes = triDes;
	}

	@Column(name = "TRI_STI", length = 2)
	public String getTriSti() {
		return this.triSti;
	}

	public void setTriSti(String triSti) {
		this.triSti = triSti;
	}

	@Column(name = "TRI_IPS", nullable = false, precision = 6)
	public BigDecimal getTriIps() {
		return this.triIps;
	}

	public void setTriIps(BigDecimal triIps) {
		this.triIps = triIps;
	}

	@Column(name = "TRI_IPV", nullable = false, precision = 15, scale = 4)
	public BigDecimal getTriIpv() {
		return this.triIpv;
	}

	public void setTriIpv(BigDecimal triIpv) {
		this.triIpv = triIpv;
	}

	@Column(name = "TRI_STP", nullable = false, length = 2)
	public String getTriStp() {
		return this.triStp;
	}

	public void setTriStp(String triStp) {
		this.triStp = triStp;
	}

	@Column(name = "TRI_PIS", nullable = false, precision = 6)
	public BigDecimal getTriPis() {
		return this.triPis;
	}

	public void setTriPis(BigDecimal triPis) {
		this.triPis = triPis;
	}

	@Column(name = "TRI_PVS", nullable = false, precision = 15, scale = 4)
	public BigDecimal getTriPvs() {
		return this.triPvs;
	}

	public void setTriPvs(BigDecimal triPvs) {
		this.triPvs = triPvs;
	}

	@Column(name = "TRI_STC", nullable = false, length = 2)
	public String getTriStc() {
		return this.triStc;
	}

	public void setTriStc(String triStc) {
		this.triStc = triStc;
	}

	@Column(name = "TRI_CFS", nullable = false, precision = 6)
	public BigDecimal getTriCfs() {
		return this.triCfs;
	}

	public void setTriCfs(BigDecimal triCfs) {
		this.triCfs = triCfs;
	}

	@Column(name = "TRI_CVS", nullable = false, precision = 15, scale = 4)
	public BigDecimal getTriCvs() {
		return this.triCvs;
	}

	public void setTriCvs(BigDecimal triCvs) {
		this.triCvs = triCvs;
	}

	@Column(name = "TRI_ETP", nullable = false, length = 2)
	public String getTriEtp() {
		return this.triEtp;
	}

	public void setTriEtp(String triEtp) {
		this.triEtp = triEtp;
	}

	@Column(name = "TRI_PIE", nullable = false, precision = 6)
	public BigDecimal getTriPie() {
		return this.triPie;
	}

	public void setTriPie(BigDecimal triPie) {
		this.triPie = triPie;
	}

	@Column(name = "TRI_PVE", nullable = false, precision = 15, scale = 4)
	public BigDecimal getTriPve() {
		return this.triPve;
	}

	public void setTriPve(BigDecimal triPve) {
		this.triPve = triPve;
	}

	@Column(name = "TRI_ETC", nullable = false, length = 2)
	public String getTriEtc() {
		return this.triEtc;
	}

	public void setTriEtc(String triEtc) {
		this.triEtc = triEtc;
	}

	@Column(name = "TRI_CFE", nullable = false, precision = 6)
	public BigDecimal getTriCfe() {
		return this.triCfe;
	}

	public void setTriCfe(BigDecimal triCfe) {
		this.triCfe = triCfe;
	}

	@Column(name = "TRI_CVE", nullable = false, precision = 15, scale = 4)
	public BigDecimal getTriCve() {
		return this.triCve;
	}

	public void setTriCve(BigDecimal triCve) {
		this.triCve = triCve;
	}

	@Column(name = "TRI_ETI", length = 2)
	public String getTriEti() {
		return this.triEti;
	}

	public void setTriEti(String triEti) {
		this.triEti = triEti;
	}

	@Column(name = "TRI_IPE", nullable = false, precision = 6)
	public BigDecimal getTriIpe() {
		return this.triIpe;
	}

	public void setTriIpe(BigDecimal triIpe) {
		this.triIpe = triIpe;
	}

	@Column(name = "TRI_IVE", nullable = false, precision = 15, scale = 4)
	public BigDecimal getTriIve() {
		return this.triIve;
	}

	public void setTriIve(BigDecimal triIve) {
		this.triIve = triIve;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tributacao")
	public Set<Modelo> getModelos() {
		return this.modelos;
	}

	public void setModelos(Set<Modelo> modelos) {
		this.modelos = modelos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tributacao")
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "tributacao")
	public Set<Tributacaouf> getTributacaoufs() {
		return this.tributacaoufs;
	}

	public void setTributacaoufs(Set<Tributacaouf> tributacaoufs) {
		this.tributacaoufs = tributacaoufs;
	}*/

}
